### ISSUE TITLE
Edge / IE11 browsers not supported

### ISSUE THREAD

**Issue by pityuh112** [doccano/doccano#1001]
I've got an issue with frontend. As I see the IE11/Edge is not supported. Unfortunately I've to use it with this browsers but I am not a JS/(vue maybe) expert. 
<img width="1629" alt="Screenshot 2020-09-25 at 15 58 28" src="https://user-images.githubusercontent.com/22007813/94298793-03483680-ff67-11ea-9067-b1a38afbb565.png">

According to browser console, the .js files went wrong. Like demo_text_classification.js
------------------------

### System information
- Windows OS
- Browser: IE11, Edge

**Comment by Hironsan** [comment]
Please use docker-compose version.

**Comment by pityuh112** [comment]
Issue still occurs with docker-compose.

<img width="1412" alt="Screenshot 2020-09-26 at 08 56 26" src="https://user-images.githubusercontent.com/22007813/94332530-5e654200-ffd6-11ea-9d97-011364e5b488.png">
