### ISSUE TITLE
Please use docker-compose version.

### ISSUE THREAD

**Issue by pityuh112** [doccano/doccano#1003]
Please use docker-compose version.

_Originally posted by @Hironsan in https://github.com/doccano/doccano/issues/1001#issuecomment-699211216_

Thank you for the feedback.

unfortunately the issue occurs with any possible versions (compose, docker image)

**Comment by Hironsan** [comment]
Thanks for your comment.
Did you try `docker-compose.prod.yml`?

```bash
$ git clone https://github.com/doccano/doccano.git --config core.autocrlf=input
$ docker-compose -f docker-compose.prod.yml up
```

If non-zero code: 127 or 128 occurred, please see https://github.com/doccano/doccano/issues/998.

**Comment by pityuh112** [comment]
Yes, I did so.

**Comment by Hironsan** [comment]
Hmm, but it seems to me that the image is the previous version.

The current version is the following:
![image](https://user-images.githubusercontent.com/6737785/94336527-d5bec400-001e-11eb-9521-2059d6723009.png)
