### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by seal-git** [doccano/doccano#1008]
How to reproduce the behaviour
---------

When I run Doccano and create a new project, the button "Create" doesn't work and no project can be created. The button clicked, the firefox console shows the following error:
 ```
TypeError: this.$t is not a function
    create http://192.168.99.100:8000/static/bundle/projects.js:8
    click http://192.168.99.100:8000/static/bundle/projects.js:8
    Ve http://192.168.99.100:8000/static/bundle/projects.js:14
    n http://192.168.99.100:8000/static/bundle/projects.js:14
    _wrapper http://192.168.99.100:8000/static/bundle/projects.js:14
    Je http://192.168.99.100:8000/static/bundle/projects.js:14
    Ke http://192.168.99.100:8000/static/bundle/projects.js:14
    ze http://192.168.99.100:8000/static/bundle/projects.js:14
    Ve http://192.168.99.100:8000/static/bundle/projects.js:14
    n http://192.168.99.100:8000/static/bundle/projects.js:14
    _wrapper http://192.168.99.100:8000/static/bundle/projects.js:14
```
I use win10 home, so Docker works on Docker Tool Box. I installed and launched Doccano by typing following command on 2020/09/30 11:00, then accessed http://192.168.99.100:8000. 
```
> docker pull doccano/doccano
> docker run -d --rm --name doccano -e "ADMIN_USERNAME=admin" -e "ADMIN_EMAIL=admin@example.com"  -e "ADMIN_PASSWORD=password" -p 8000:8000 doccano/doccano
```
I tried to change the browser, but nothing changed. Also, `docker pull chakkiworks/doccano` reproduced the same situation. 

Your Environment
---------

*   Operating System: Windows 10 home, version 1903
*   Docker   :19.03.1
*   image "doccano/doccano" : created on "2020-09-29T06:40:21.924764145Z"
*   Virtual Box:  6.1.10 r138449 (Qt5.6.2)
*   Linux in Virtual Box: Boot2Docker 19.03.5
*   Browser: Firefox 80.0.1 (64bit), Chrome 85.0.4183.121 Official Build(64bit)
*   When you install doccano: 2020/09/30 11:00
*   How did you install doccano (Heroku button etc): Docker pull doccano/doccano

**Comment by avidale** [comment]
A similar error happens when I run doccano on Heroku: when clicking "create", a JS error occurs and nothing happens.

```
projects.js:14 TypeError: this.$t is not a function
    at a.create (projects.js:8)
    at click (projects.js:8)
    at Ve (projects.js:14)
    at HTMLButtonElement.n (projects.js:14)
    at HTMLButtonElement.Yr.o._wrapper (projects.js:14)
Je @ projects.js:14
Ke @ projects.js:14
ze @ projects.js:14
Ve @ projects.js:14
n @ projects.js:14
Yr.o._wrapper @ projects.js:14
```

**Comment by letnotimitateothers** [comment]
Hello !
Same error for me when I do :

> docker pull chakkiworks/doccano
> docker run -d --rm --name doccano   -e "ADMIN_USERNAME=admin"   -e "ADMIN_EMAIL=admin@example.com"   -e "ADMIN_PASSWORD=password"   -p 8000:8000 chakkiworks/doccano


`
TypeError: this.$t is not a function
    at a.create (projects.js:8)
    at click (projects.js:8
    at Ve (projects.js:14)
    at HTMLButtonElement.n (projects.js:14)
    at HTMLButtonElement.Yr.o._wrapper (projects.js:14)
Je @ projects.js:14
Ke @ projects.js:14
ze @ projects.js:14
Ve @ projects.js:14
n @ projects.js:14
Yr.o._wrapper @ projects.js:14
`

**Comment by seal-git** [comment]
@letnotimitateothers 
Hello! I find this error with DockerToolbox that works on Windows10 home. What's your environment? Same as me?

**Comment by pjbull** [comment]
To work around this, I rolled back to the tagged `v1.0.5` release and then picked up this change, and that version worked for me: https://github.com/doccano/doccano/commit/8a350c7cdcd60da5648c493d507688a2ca8a940c

**Comment by markuspoerschke** [comment]
@pjbull Solution worked for me. I pushed the image to Docker Hub so changing `doccano/doccano` to `markuspoerschke/doccano:1.0.5` will temporarily fix the issue.

https://hub.docker.com/layers/markuspoerschke/doccano/1.0.5/images/sha256-917ce1a61b7c508546d5700ff88e79e07b4542e5eb492d5ad85541070bfff8fa?context=repo

**Comment by seal-git** [comment]
@markuspoerschke 
It worked on my environment!
`docker pull markuspoerschke/doccano:1.0.5`
`docker run -d --rm --name doccano105 -e "ADMIN_USERNAME=admin" -e "ADMIN_EMAIL=admin@example.com"  -e "ADMIN_PASSWORD=password" -p 8000:8000 markuspoerschke/doccano:1.0.5`
I accessed http://192.168.99.100:8000 then create button worked. 
How did you get the old image of Doccano?

**Comment by PATELS2R** [comment]
@markuspoerschke  Could you please elaborate the process of building an image and pushing it to Docker Hub.

I am in a deep complicated mess and would really appreciate some help. I am behind corporate proxy on RHEL. The routes to *.debian.org are blocked. So I cannot use the docker-compose up (gettiing DNS lookup error as it tried to download alpine and other images)

The only thing working for me is `docker container create --name doccano  -p 80:8000 doccano/doccano`. However this image has the older interface. But I am interested in the new interface.

Hypothetical solution - Build the image (new interface) on local PC and upload to Docker Hub. Followed up by docker pull on my secured server.

**Comment by markuspoerschke** [comment]
@PATELS2R I checked out the old tag using Git and then ran `docker build . -t markuspoerschke/doccano:1.0.5` manually. I had to adjust two files according the suggestion from here: https://github.com/doccano/doccano/issues/1008#issuecomment-705986779.

> Hypothetical solution - Build the image (new interface) on local PC and upload to Docker Hub. Followed up by docker pull on my secured server.

That’s more or less what I’ve done.

**Comment by PATELS2R** [comment]
@markuspoerschke  Yes you're right. That was possible because of the Dockerfile in the github repo. However the image build by you has the older interface. I am looking for the new interface. It has much better features.

**Comment by Hironsan** [comment]
Hello guys. Sorry for the late reply. I worked hard on another project in two weeks.

I recommend you should use the docker-compose version.

By the way, I investigate the problem and found the cause.
In #976, the file `app/server/static/components/projects.vue` was accidently edited.
I rolled back the file and pushed the image in #1024. Now you are able to create a project.

Regards,
