### ISSUE TITLE
Can't create a new project (deployed by Heroku button)

### ISSUE THREAD

**Issue by grace6029** [doccano/doccano#1009]
How to reproduce the behaviour
---------
Hello! I use Heroku button to deploy doccano and I can get into the webpage. However, when I click "Create" button to create project, nothing happen and the application log doesn't change anything. So I couldn't create any project now.
By the way, I also try to upload not by Heroku button but by myself using docker-compose, but the problem still remain. 

![擷取](https://user-images.githubusercontent.com/30849777/94986690-4754c000-0593-11eb-8b4b-9c0032eeec37.JPG)
![app log](https://user-images.githubusercontent.com/30849777/94986710-62273480-0593-11eb-997c-4c55ed46f426.JPG)

How to solve the problem?

Your Environment
---------
*   Operating System: Windows 10
*   Python Version Used: Python 3.6.2
*   When you install doccano: 2020/10/2
*   How did you install doccano (Heroku button etc): Heroku button

**Comment by xman14** [comment]
same issue for me, interested in the solution

**Comment by bitmman** [comment]
Same problem here.

**Comment by MESSALTI** [comment]
Same problem

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/issues/1008#issuecomment-713348075
