### ISSUE TITLE
Create Project Button not working (Used Docker to install Doccano)

### ISSUE THREAD

**Issue by osamahameedX** [doccano/doccano#1010]
How to reproduce the behaviour
---------

---------

*   Operating System: window 10 pro
*   Python Version Used: Python 3.7.3
*   When you install doccano: 2020/10/06 11:00
*   How did you install doccano (Heroku button etc): docker pull doccano/doccano

**Comment by osamahameedX** [comment]
[First Error Image](https://drive.google.com/file/d/1HMgsmdg87e0CiBhvyDHmBDWiPldJQgFe/view?usp=sharing)

[Second Error Image](https://drive.google.com/file/d/1I5ORYOTNd4FB6LSOfOSM8Llmnk4cE7ET/view?usp=sharing)

**Comment by icoxfog417** [comment]
Does your doccano behind to proxy?

**Comment by osamahameedX** [comment]
I didn't get your question. I didn't know much about proxy. Tell me what I have to do step by step.

**Comment by PATELS2R** [comment]
@icoxfog417 I can confirm with behavior. I'm using the latest version and yes I'm behind corporate proxy.

**Comment by osamahameedX** [comment]
What is the solution  @PATELS2R? do you find anything useful?
