### ISSUE TITLE
Backend updation of Doccano

### ISSUE THREAD

**Issue by munivinayk** [doccano/doccano#1011]
Feature description (Look at the bold ones below - Step 2 and 4)
---------
I am trying to build an MLOPs platform end to end. 
Trying invoice processing example -For the training the documents.
step 1:  Data extraction: Where by i am extracting the cleaned text from the user uploaded PDF's using streamlit. 
**Step 2: Push the data for annotation (Feature request) - Is it possible to connect to the doccano project using credentials and upload the data from the backend instead of frontend UI**
Step 3: Annotate the data manually using front end.
**Step 4: Train the data from docanno json file (Feature request): Pull the json file from the docanno project (using back end, not the UI) to train a transformer or spacy model.**
Step 5: Save the output of the training file and auto deploy it to the production (using heroku APP)

**Comment by icoxfog417** [comment]
You can use API for your Steps.

https://github.com/doccano/doccano-client
