### ISSUE TITLE
User data cannot be preserved on importing an exported dataset

### ISSUE THREAD

**Issue by carsondwilber** [doccano/doccano#1015]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04.4 LTS
- **Python version**: 2.7.17

### Describe the problem
You cannot re-import an exported dataset with user IDs attached.

### Source code / logs
No particular source code, but as noted in #217 there is an export option for "text labels" (in the format [start_offset, end_offset, "label"]). However, since this is the only format which can be imported, user data is not preserved.

Here's my team's issue: what we did is we changed our label spec based on some revisions in our annotating guidelines. When we uploaded our new spec, of course our old files' annotations broke as the new labels had different IDs. I wrote a handy script for mapping the old spec to the new spec, converted the labels in the old files to use the new IDs, and went to upload --

But you can't do that and keep the user IDs. You MUST convert to the "text label" format to reupload, and upon doing so, it seems the "user" value is always set to 1. When not in collaborative mode, you cannot access these annotations without being signed in to the user with ID 1. This is not optimal as we like to use collaborative mode when doing cross-annotator analysis.

You also can't do this because the importer will reject any file which has overlapping annotations. Because the user is the same for all of the annotations, and a user cannot label any portion of the document with multiple annotations, you will receive the generic "failed to upload" notification on the import dialog.

It seems like the two possible solutions are:

1. Revise the "text label" format to allow (if not require) a fourth value in each tuple which is the user ID, and remove checks for overlapping annotations.
2. Revise the importer to allow the original JSON format (not the "text label" format) and ascribe annotations to each user by the user ID included in each annotation, thus avoiding checks for overlapping annotations.

I'm pressed for time or I would implement this and PR myself, so I figured it would be best to at least make an issue for it.

**Comment by kuraga** [comment]
See also: #826l

**Comment by fjen** [comment]
Should be related to #482 which would be fixed by #958. It would allow importing an exported csv while preserving user information.

**Comment by nihiluis** [comment]
how can we preserve user data now?
