### ISSUE TITLE
Can not create a project in doccano

### ISSUE THREAD

**Issue by Wabbina** [doccano/doccano#1019]
-----------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 professional 64 bits
- **Python version**:  3.6

###
I am working on labelling classification dataset using doccano. I installed a docker desktop for windows and followed instructions provided [here](https://doccano.github.io/doccano/getting-started/):
- create a docker container for doccano :
`docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano`

Then , I start Doccano by running the container : 
`docker container start doccano`.
After these steps, when I try to create a project, nothing happen when I click on "create" button. How can I resolve this problem ?
Thanks

**Comment by markuspoerschke** [comment]
I can confirm this issue. The error message shows:

```
TypeError: this.$t is not a function
    create http://127.0.0.1:8001/static/bundle/projects.js:8
    click http://127.0.0.1:8001/static/bundle/projects.js:8
    Ve http://127.0.0.1:8001/static/bundle/projects.js:14
    n http://127.0.0.1:8001/static/bundle/projects.js:14
    _wrapper http://127.0.0.1:8001/static/bundle/projects.js:14
```

**Comment by markuspoerschke** [comment]
I think this issue is the same as the following tickets:

* https://github.com/doccano/doccano/issues/1010
* https://github.com/doccano/doccano/issues/1009
* https://github.com/doccano/doccano/issues/1008

**Comment by Wabbina** [comment]
I've seen in the ticket 1008 your suggestion :

> @pjbull Solution worked for me. I pushed the image to Docker Hub so changing doccano/doccano to markuspoerschke/doccano:1.0.5 will temporarily fix the issue.
So you suggest to change "doccano\doccano". But where ?

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/issues/1008#issuecomment-713348075

**Comment by Wabbina** [comment]
Great! thanks you 👍

**Comment by kuraga** [comment]
> Another question please: what is the main difference between doccano development, production and deployment. In other word, when I create a project in development mode, can I deploy that project in AWS (for example) ?

@Wabbina , related: #733.

**Comment by Wabbina** [comment]
Thanks @kuraga. I understand that there is difference between developement and production modes. But suppose that I create projects in development mode, can I deploy these projects on Heroku ?? If yes, how can I proceed ?

**Comment by Wabbina** [comment]
Finally I've built an app on Heroku (based on doccano). Then I get rid of the problem mentioned above. Thanks you
