### ISSUE TITLE
docker-compose fails on prod, cannot resolve nhn/raphael

### ISSUE THREAD

**Issue by breznak** [doccano/doccano#1020]
Hello, I'm beginning with your SW, currently on master, building with docker-compose, the prod.yml config fails on some unrosolved URLs. 

How to reproduce the behaviour
---------
`doccano$ docker-compose -f docker-compose.prod.yml up` 

Your Environment
---------

*   Operating System: Ubuntu 20.04
*   Python Version Used: 3.8.5
*   When you install doccano: ea0590ad0bb32d2
*   How did you install doccano (Heroku button etc): git clone and docker-compose following the readme. 

Err output: 
------------------
```
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["squire-rte@github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-squire-rte-1.9.0/node_modules/squire-rte" as pattern ["squire-rte@github:seonim-ryu/Squire#10a470c9dfd07cfb37b06dedc581526b061975e1"]. This could result in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://github.com/nhn/raphael.git /usr/local/share/.cache/yarn/v6/.tmp/60cb5dac1cfafc1829af48c5dc5fdf3f
Directory: /app
Output:
Cloning into '/usr/local/share/.cache/yarn/v6/.tmp/60cb5dac1cfafc1829af48c5dc5fdf3f'...
fatal: unable to access 'https://github.com/nhn/raphael.git/': Could not resolve host: github.com
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c apk add -U --no-cache git python3 make g++   && yarn install   && yarn build   && apk del --no-cache git make g++' returned a non-zero code: 128
```

Thank you for any help

PS: devel config runs OK.

**Comment by Hironsan** [comment]
Please set the proxy setting.

**Comment by breznak** [comment]
> Please set the proxy setting. 

I don't use any proxy and internet otherwise works on the machine. Is there a readme on what needs to be done, please?

**Comment by kernelbare** [comment]
I have the same problem 
`
warning Pattern ["squire-rte@github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-squire-rte-1.9.0/node_modules/squire-rte" as pattern ["squire-rte@github:seonim-ryu/Squire#10a470c9dfd07cfb37b06dedc581526b061975e1"]. This could result in non-deterministic behavior, skipping.
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").

`
Operating System: Ubuntu 20.04

**Comment by PepijnBoers** [comment]
Adding the following line to my Docker Engine fixed it for me:
```
"dns": ["8.8.8.8"]
```

My full configuration file looks like this:
```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "features": {
    "buildkit": true
  },
  "dns": ["8.8.8.8"],
  "experimental": false
}
```
