### ISSUE TITLE
Bad Request: when importing dataset

### ISSUE THREAD

**Issue by krzynio** [doccano/doccano#1025]
I am trying to import dataset for sequence labelling task. It is always failing. Both dev and prod.

Backend is giving me:

backend_1   | Bad Request: /v1/projects/2/docs/upload

---------

Your Environment
---------

*   Operating System: mac / linux
*   Python Version Used: 
*   When you install doccano:
*   How did you install doccano (Heroku button etc): docker-compose

**Comment by icoxfog417** [comment]
Could you please provide the your data and your environment information?
