### ISSUE TITLE
Duplication of the data occurs at the bottom of paging

### ISSUE THREAD

**Issue by lsy641** [doccano/doccano#1026]
How to reproduce the behaviour
---------
The data at bottom of every page is same, that also make reduplicate document when doing annotation.

![image](https://user-images.githubusercontent.com/26696711/97519948-21c1a780-19d5-11eb-9243-35a5534738c9.png)
![image](https://user-images.githubusercontent.com/26696711/97520098-69483380-19d5-11eb-8861-33e7415c4fca.png)
![image](https://user-images.githubusercontent.com/26696711/97520119-75cc8c00-19d5-11eb-868f-74e703cca7e4.png)

Your Environment
---------
*   Operating System: ubuntu 16
*   Python Version Used: python3.6
*   When you install doccano: 2020-10-26
*   How did you install doccano (Heroku button etc): github

**Comment by lsy641** [comment]
@buriy @ramok @vinayaugustine @clarus

**Comment by TissueC** [comment]
Same issue

**Comment by icoxfog417** [comment]
related #933
