### ISSUE TITLE
Error running manager.py django

### ISSUE THREAD

**Issue by mlussati** [doccano/doccano#1029]
Add users
---------

I want to add more annotator user to doccano but I can't run manager.py I get this error:

installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

You have 33 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, api, auth, authtoken, contenttypes, sessions, social_django.
Run 'python manage.py migrate' to apply them.

django.db.utils.OperationalError: no such table: auth_user

**Comment by icoxfog417** [comment]
You seem not to install doccano properly, Please read the "Getting started".

https://doccano.github.io/doccano/getting-started/
