### ISSUE TITLE
Status 500

### ISSUE THREAD

**Issue by mlussati** [doccano/doccano#1031]
`backend_1   | Internal Server Error: /v1/projects
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_1   |     response = get_response(request)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
backend_1   |     response = self.process_exception_by_middleware(e, request)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
backend_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
backend_1   |     return view_func(*args, **kwargs)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
backend_1   |     return self.dispatch(request, *args, **kwargs)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 497, in dispatch
backend_1   |     response = self.handle_exception(exc)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 457, in handle_exception
backend_1   |     self.raise_uncaught_exception(exc)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
backend_1   |     raise exc
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
backend_1   |     response = handler(request, *args, **kwargs)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/generics.py", line 239, in get
backend_1   |     return self.list(request, *args, **kwargs)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/mixins.py", line 46, in list
backend_1   |     return Response(serializer.data)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 757, in data
backend_1   |     ret = super().data
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 261, in data
backend_1   |     self._data = self.to_representation(self.instance)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 675, in to_representation
backend_1   |     self.child.to_representation(item) for item in iterable
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 675, in <listcomp>
backend_1   |     self.child.to_representation(item) for item in iterable
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_polymorphic/serializers.py", line 59, in to_representation
backend_1   |     ret = serializer.to_representation(instance)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/serializers.py", line 526, in to_representation
backend_1   |     ret[field.field_name] = field.to_representation(attribute)
backend_1   |   File "/usr/lib/python3.6/site-packages/rest_framework/fields.py", line 1873, in to_representation
backend_1   |     return method(value)
backend_1   |   File "/app/api/serializers.py", line 106, in get_current_users_role
backend_1   |     queryset, project=instance.id, user=self.context.get("request").user.id
backend_1   |   File "/usr/lib/python3.6/site-packages/django/shortcuts.py", line 93, in get_object_or_404
backend_1   |     return queryset.get(*args, **kwargs)
backend_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
backend_1   |     (self.model._meta.object_name, num)
backend_1   | api.models.RoleMapping.MultipleObjectsReturned: get() returned more than one RoleMapping -- it returned 2!
`

Your Environment
---------

*   Operating System: Ubuntu
*   Python Version Used: python 3.7
*   When you install doccano: doccano-1.0.5
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by mlussati** [comment]
nginx_1     | 177.63.235.12 - - [30/Oct/2020:22:17:05 +0000] "GET /v1/projects HTTP/1.1" 500 27 "http://34.67.31.21/projects" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36" "-"

**Comment by icoxfog417** [comment]
merge to #713
