### ISSUE TITLE
login problem from remote machine

### ISSUE THREAD

**Issue by biteNi** [doccano/doccano#1034]
I install doccano using "$ docker-compose -f docker-compose.dev.yml up" command and work well on my own machine A. But when I login in doccano in another machine B, it reminds me “Incorrect username or password or something went wrong.” 

Your Environment
---------

*   Operating System: mac
*   Python Version Used: python 3.7
*   When you install doccano: 2020/10/30
*   How did you install doccano (Heroku button etc): docker-compose -f docker-compose.dev.yml up

**Comment by icoxfog417** [comment]
The username and password don't differ by network location. Would you please confirm the username and password is correct and you certainly access doccano on machine A ?

**Comment by biteNi** [comment]
> The username and password don't differ by network location. Would you please confirm the username and password is correct and you certainly access doccano on machine A ?

yeah，I'm sure the username and password is right. And can access doccano on machine A.

I try to login in doccano on my own machine with ip:3000, it reminds me “Incorrect username or password or something went wrong.” But when I login in with http://127.0.0.1:3000/ , it works well.

**Comment by kuraga** [comment]
Possible related: #713, #1031, #968, #836.

Possible solutions: https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-change-users-or-admins-password, https://github.com/doccano/doccano/issues/836#issuecomment-648844105, https://github.com/doccano/doccano/issues/713#issuecomment-696881479.
