### ISSUE TITLE
Tags not shown at top of window

### ISSUE THREAD

**Issue by david-waterworth** [doccano/doccano#1035]
I'm evaluating docanno against a number of other tools, I looked at the live demo (https://doccano.herokuapp.com/demo/named-entity-recognition/) and then installed locally. It's working but the UI is different, the live demo has the list of available tags on the top of the page above the document - when I run locally this isn't shown? Is the lice demo an older version - I'm running the latest commit from github? I'm specifically interested in named-entity-recognition.

I can select tags by highlighting a region and sometimes a context menu appears with my tags (but sometimes it doesn't). I can also press one of the keys I bound to each tag - again sometimes it highlights a tag and sometimes it doesn't.

**Comment by kuraga** [comment]
See #635 (merged in _non-equivalent_ #834).

**Comment by kuraga** [comment]
Related: #635 (merged in _non-equivalent_ #834), #627, #991.

**Comment by david-waterworth** [comment]
Thanks, the linked issues explain why the tags aren't displayed. I don't see any mention of the context menu not displaying and/or the keys not working though.

What I experienced periodically (and frequently, about 20% of the time) was aftering selecting a span the menu would not appear. I also though maybe right clicking on the span may display it but no luck. When this happens the keyboard shortcuts also don't work.

I'm using Ubuntu 20.04 with Chrome
