### ISSUE TITLE
500 Error at the url root of backend (for accessing Swagger doc)

### ISSUE THREAD

**Issue by jbkoh** [doccano/doccano#1038]
How to reproduce the behaviour
---------

I wanted to access swagger doc, so I went to `localhost:8000` to login as described [here](https://github.com/doccano/doccano/pull/647#issuecomment-617778961), but it only showed the below message:
```
Request Method: | GET
-- | --
http://localhost:8000/
2.2.13
OSError
Error reading /src/app/server/static/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
/src/venv/lib/python3.6/site-packages/webpack_loader/loader.py in _load_assets, line 32
/src/app/tools/../../venv/bin/python
3.6.12
['/src/app',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/src/venv/lib/python3.6/site-packages',  '../api']
Thu, 5 Nov 2020 05:32:51 +0000
```

The same thing happen even when I put basic auth info in the URL as `admin_id:admin_password@localhost:8000`. 

Then, I try to use the auth info directly for the swagger url as `admin_id:admin_password@localhost:8000/swagger`, which showed 403 error.

What's the proper way of accessing the API doc?

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: I used docker-compose, so whatever the container uses.
*   When you install doccano: 11/4/2020
*   How did you install doccano (Heroku button etc): docker compose local deployment.

**Comment by Hironsan** [comment]
Please use `docker-compose.dev.yml` or `docker-compose.prod.yml`.

By the way, nginx config need to be updated for `docker-compose.prod.yml`:

```bash
location /swagger/ {
    proxy_pass http://backend:8000/swagger/;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_redirect off;
}

location = /swagger {
    absolute_redirect off;
    return 301 /swagger/;
}
```
