### ISSUE TITLE
How to recover labeled data if i delete a label and then add it as same name again?

### ISSUE THREAD

**Issue by lsy641** [doccano/doccano#1041]
How to reproduce the behaviour
---------
I want to add some label using label file but there exists some overlapped labels. So I have to delete all overlappd labels and import the label file.
And!! Then I find the labels of data that I originally gave are all not displayed!! Even if my imported labels have same name with them.
So, is there any way to recover my labels? it costs a lot

our Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by lsy641** [comment]
@buriy @ramok @vinayaugustine @clarus

**Comment by buriy** [comment]
@lsy641 why are you writing to me??? :(

**Comment by icoxfog417** [comment]
Please import the label file without overlapped labels.

**Comment by kuraga** [comment]
Related: #826.

**Comment by kuraga** [comment]
Related: #826, #913, #961, #1015.
