### ISSUE TITLE
Unable to approve annotations

### ISSUE THREAD

**Issue by jonhilgart22** [doccano/doccano#1043]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System: MacOS Catalina
*   Python Version Used: 3.7
*   When you install doccano: pulled from master 11/13/2020
*   How did you install doccano (Heroku button etc): docker-compose up

I'm unable to approve annotations locally.

Running Docanno locally via docker-compose

![image](https://user-images.githubusercontent.com/8621935/99121835-ff718180-25b1-11eb-8459-72be12203500.png)

**Comment by jonhilgart22** [comment]
@Hironsan Is this something you've seen before?

**Comment by Hironsan** [comment]
I recommend you should use docker-compose.prod.yml.

By the way, I investigated the problem and found the issue:
https://github.com/doccano/doccano/blob/afc599a56ecb007861c4b6dcbdc05fb9a719bbff/app/server/static/components/annotationMixin.js#L240-L243

This line discards the text information so the following line raises the exception:
https://github.com/doccano/doccano/blob/afc599a56ecb007861c4b6dcbdc05fb9a719bbff/app/server/static/components/annotation.pug#L80
