### ISSUE TITLE
Support tagging to distinguish multiple projects

### ISSUE THREAD

**Issue by keaxu-exp** [doccano/doccano#1044]
Hi,

As title described. I think this feature will be helpful when:

- managing projects programmatically
- integrating doccano with other jobs/services. 

Here are my thoughts:

**UI:** 
<img width="1000" alt="Screen Shot 2020-11-13 at 5 00 04 PM" src="https://user-images.githubusercontent.com/37673226/99134715-cea24400-25d3-11eb-9452-1ce6b848e33c.png">

**DB Models:**
add one more table `api_tag`, with following columns:
```
id (PK)
text
created_at
project_id (FK)
text_color
background_color
```

**APIs:**
GET /projects/{project_id}/tags

response body may look like:
```
[
  {
    "id": 1,
    "text": "In Progress"
  },
  {
    "id": 2,
    "text": "Completed"
  }
]
```

POST /projects/{project_id}/tags
GET /projects/{project_id}/tags/{tag_id}
PUT /projects/{project_id}/tags/{tag_id}
PATCH /projects/{project_id}/tags/{tag_id}
DELETE /projects/{project_id}/tags/{tag_id}

## Usecases & Scenarios:
We want to integrate doccano with our interval jobs/services. As providing an automated platform, we want annotators explicitly mark a project as 'completed', so that certain downstream jobs can be triggered.

As we serving doccano for multiple internal teams, we also want to attach business-related information to the project, like model names, stakeholder teams, etc.

**Comment by Hironsan** [comment]
Solved https://github.com/doccano/doccano/pull/1301.
