### ISSUE TITLE
Label annotations aren't visible by other users after importing a dataset.

### ISSUE THREAD

**Issue by dimidd** [doccano/doccano#1045]
Hi,
First of all, thank you for this great project. I think I'm missing something very basic, here's my usecase:

How to reproduce the behaviour
---------
Admin imports a JSONL dataset for sequence labeling, that contains texts and spans. E.g.
`{text: "lazy brown fox", labels: [[0, 3, "trait"], [5, 9, "color"]]}`

When annotating the user who imported the file is able to see the text and its labels "trait" and "color", however other users such as annotation-approvers can only see the text.

*   Operating System: Linux
*   Python Version Used: 3.8
*   When you install doccano: at SHA1 c0b4eb768498ce85950baeef2f7d1917e603e514
*   How did you install doccano (Heroku button etc): docker

**Comment by kuraga** [comment]
Is "Share annotations" on for the project?

**Comment by dimidd** [comment]
Thanks! That was the issue.
