### ISSUE TITLE
[Bug report] Shortkeys don't work

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#1049]
How to reproduce the behaviour
---------
Shortkeys of the labels are: `d`, `n`, `z`, `p`.

But nothing happens on clicking them on Annotation page. No console errors.

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: d3f6e66259063e9d9316473f5ac058955547d0f7
*   How did you install doccano (Heroku button etc): Docker Compose (production)

**Comment by Hironsan** [comment]
Hmm, I don't have a problem. Are you using some browser extention?

**Comment by kuraga** [comment]
Aha, see. `d` doesn't work. Change `d` to `2`. Works. `u` doesn't  work. `3` works. Letters vs digits?!

**Comment by Hironsan** [comment]
Try the browser's secret mode. It disables extentions.

**Comment by Hironsan** [comment]
There is no problem for me:

![](https://i.gyazo.com/fb83f488b53e98a301b9af159884e5f4.gif)

Maybe due to your browser or some browser extensions.

**Comment by kuraga** [comment]
Ok, will debug. Will reopen.

P.S. Appreciate you point a handler's code.

**Comment by kuraga** [comment]
@Hironsan , that's what I thought! Good intition! But I really don't understand how it could be....

![image](https://user-images.githubusercontent.com/1063219/100499339-d0ded380-3179-11eb-9b93-f0cdbfc6b27c.png)

`e.key == "т"`. But I pressed `n` key en `en` layout! (Well, in Russian layout it would be exactly `т`, yes. But layout is English!)

Didn't you have a such issue? Vue's, maybe? Vue plugins'?

**Comment by kuraga** [comment]
@Hironsan , that's what I thought! Good intition! But I really don't understand how it could be....

![image](https://user-images.githubusercontent.com/1063219/100499339-d0ded380-3179-11eb-9b93-f0cdbfc6b27c.png)

`e.key == "т"`. But I pressed `n` key en `en` layout! (Well, in Russian layout it would be exactly `т`, yes. But layout is English!)

Didn't you have a such issue? Vue's, maybe? Vue plugins'?

**Comment by kuraga** [comment]
Ok, my collegues don't confirm the issue.
