### ISSUE TITLE
Support Comments when Annotating

### ISSUE THREAD

**Issue by keaxu-exp** [doccano/doccano#1050]
Hi,

As the title described. I think this feature will improve the cooperation experience. 

**Usecase**
- As an annotator, when classification is ambiguous, we want to leave relative information and the thought process instead of letting the utterance unlabeled.
- As an annotator, I want to provide more information why I think `label-A` is more appropriate than `label-B`.

### Thoughts:

**UI**
<img width="1436" alt="Screen Shot 2020-11-16 at 4 51 55 PM" src="https://user-images.githubusercontent.com/37673226/99326346-022bdb00-282d-11eb-8a0c-890f1356b14e.png">

**DB Models**
add one more table `api_documentcomment`, with the following columns:

```
id (PK)
text
created_at
document_id (FK)
user_id (FK)
```

**Comment by kuraga** [comment]
See also: https://github.com/doccano/doccano/issues/966#issuecomment-685565644, #966.
