### ISSUE TITLE
pip install carla - ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by ccm24** [doccano/doccano#1057]
I try to use pip install carla and I get this error : 

Collecting carla
  Using cached carla-0.9.5.tar.gz (3.9 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\f67886\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\F67886\\AppData\\Local\\Temp\\pip-install-9x5wm3pa\\carla\\setup.py'"'"'; __file__='"'"'C:\\Users\\F67886\\AppData\\Local\\Temp\\pip-install-9x5wm3pa\\carla\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\F67886\AppData\Local\Temp\pip-pip-egg-info-6e19xs3q'
         cwd: C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\setup.py", line 114, in <module>
        ext_modules=get_libcarla_extensions(),
      File "C:\Users\F67886\AppData\Local\Temp\pip-install-9x5wm3pa\carla\setup.py", line 75, in get_libcarla_extensions
        libs = [x for x in os.listdir('dependencies/lib') if any(d in x for d in required_libs)]
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dependencies/lib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I'm trying to do this because there is no "carla" folder in "\ Python \ Python37 \ Lib \ site-packages" and I think that's why when I run a matlab script it can't connect to the carla server and I get this error: "Unable to resolve the name py.carla.Client. "

There is someone who has encountered this problem ?

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: Python 3.7.9

**Comment by icoxfog417** [comment]
Here is doccano repository, we can't help carla issue.
