### ISSUE TITLE
Doccano AWS deployment error

### ISSUE THREAD

**Issue by sploitfun** [doccano/doccano#1061]
Hi All,

I have successfully got doccano to run on my local machine. However when I follow the same procedure on a EC2 instance, I am unable to. Below are the steps I followed in EC2:

1. Created a EC2 instance with default hardware config of t2.micro, 8 GB HDD and operating system is Ubuntu Server 20.04 LTS 
2. Executed the below commands in terminal
   
>  #sudo apt-get update
>  #sudo apt-get install docker.io
>  #sudo apt-get install docker-compose 
>  #git clone https://github.com/doccano/doccano.git
>  #cd doccano
>  #sudo docker-compose -f docker-compose.dev.yml up

3. Yes I am trying to run the development version of Doccano. When I execute the above docker-compose command I get below logs (snippet below) and then EC2 instance lags for sometime, eventually it does come back to its normal state but doccano_frontend_1 fails to start. 

> #sudo docker-compose -f docker-compose.dev.yml up
> ...
> backend_1   | Role created successfully "annotation_approver"
> frontend_1  | Done in 132.49s.
> frontend_1  | Starting frontend server
> frontend_1  | yarn run v1.21.1
> frontend_1  | $ eslint --fix --ext .js,.vue --ignore-path .gitignore .
> backend_1   | Setting password for User admin.
> backend_1   | Superuser created successfully.
> backend_1   | Starting django
> backend_1   | Watching for file changes with StatReloader
> frontend_1  | Done in 12.74s.
> frontend_1  | yarn run v1.21.1
> frontend_1  | $ nuxt
> frontend_1  | ℹ Listening on: http://172.19.0.3:3000/
> frontend_1  | ℹ Preparing project for development
> frontend_1  | ℹ Initial build may take a while
> frontend_1  | ✔ Builder initialized
> frontend_1  | ✔ Nuxt files generated
> frontend_1  | ℹ Compiling Client
> frontend_1  |
> frontend_1  |  ERROR  (node:283) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
> frontend_1  |
>

After a very long delay I get the below logs

>postgres_1  | 2020-11-20 13:33:40.976 UTC [45] WARNING:  worker took too long to start; canceled
> postgres_1  | 2020-11-20 13:34:07.764 UTC [58] WARNING:  autovacuum worker started without a worker entry
> postgres_1  | 2020-11-20 13:38:23.718 UTC [45] WARNING:  worker took too long to start; canceled
> postgres_1  | 2020-11-20 13:38:54.267 UTC [59] WARNING:  autovacuum worker started without a worker entry
> postgres_1  | 2020-11-20 13:43:36.699 UTC [45] WARNING:  worker took too long to start; canceled
> frontend_1  | Killed
> frontend_1  | error Command failed with exit code 137.
> frontend_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> doccano_frontend_1 exited with code 137

Any help here, please? Thanks!!

**Comment by sploitfun** [comment]
Ok it did eventually start after I explicitly restarted frontend docker. Its my bad, I was planning to run doccano with t2.micro, however I believe the minimum requirement is t2.small. So moving to t2.small...

**Comment by GHonem21** [comment]
after installing doccano on aws ubuntu server using docker compose, I got this:

Then how to access doccano, I tried to used public DNS but I dot nothing

![image](https://user-images.githubusercontent.com/108152831/176272816-b703c53f-baef-4b19-8e1b-a17af882de3f.png)
