### ISSUE TITLE
Maybe invalid format (eng+kor mixup)

### ISSUE THREAD

**Issue by hmkim** [doccano/doccano#1062]
How to reproduce the behaviour
---------

![스크린샷 2020-11-21 오전 12 24 25](https://user-images.githubusercontent.com/4966343/99817288-14d94380-2b90-11eb-83ae-b0b969b4f277.png)

With this data,
[message_info_mix.txt](https://github.com/doccano/doccano/files/5574418/message_info_mix.txt)

Your Environment
---------

$ git clone https://github.com/doccano/doccano.git (docker-compose.prod.yml)
$ cd doccano
$ docker-compose -f docker-compose.prod.yml up

**Comment by Hironsan** [comment]
Plain text format assumes you store a document in a line. So if you want to import multiline documents, please use JSONL format.
