### ISSUE TITLE
Cannot import data because of blank screen in frontend

### ISSUE THREAD

**Issue by heyalistair** [doccano/doccano#1074]
How to reproduce the behavior.
---------
On a newly running instance of Doccano:
 
1) Create a sequence labelling project
2) Click on Import Data

The problem is that I see a blank screen, and it is impossible to load data.

When I open up the console log of the browser, I see:
```
Uncaught TypeError: i.a.registerLanguage is not a function
    at upload_sequence_labeling.de2d39ec4ff4.js:8
    at Array.forEach (<anonymous>)
    at Object.42 (upload_sequence_labeling.de2d39ec4ff4.js:8)
    at n (upload_sequence_labeling.de2d39ec4ff4.js:1)
    at Module.278 (upload_sequence_labeling.de2d39ec4ff4.js:8)
    at n (upload_sequence_labeling.de2d39ec4ff4.js:1)
    at upload_sequence_labeling.de2d39ec4ff4.js:1
    at upload_sequence_labeling.de2d39ec4ff4.js:1
```
Your Environment
---------
*   Operating System: macOS 10.15.7
*   Python Version Used: N/A
*   When you install doccano: `2020-11-26T16:43:45.127Z INFO  - Pulling image from Docker hub: doccano/doccano:latest`
*   How did you install doccano: Azure 1-click deployment

**Comment by martinezhermes** [comment]
Same exact issue with current build. `Uncaught TypeError: i.a.registerLanguage is not a function`

**Comment by Hironsan** [comment]
Maybe due to the following commit:
https://github.com/doccano/doccano/commit/65d758873b7329b57948bf2cb2c9d4392c80512d

**Comment by Hironsan** [comment]
OK. I was able to reproduce the problem. Now I reverted the commit.
