### ISSUE TITLE
Can't access the admin user

### ISSUE THREAD

**Issue by ofersabo** [doccano/doccano#1084]
After installing doccano and running it successfully a few times, I tried to change the password to an empty password.
This did not work, and even when I reset it to the default value it still doesn't work. 

Another thing that may harm the correct flow of my doccano is that I downloaded another repo of doccano which I accidentally run on different ports simultaneously, this might have harmed the common databases.

Unfortunately, looking up all the existing similar issues in the repo issues pages did not solve my problem.

I think that full removal of the doccano files could help, but I'm not sure which files should be removed, except for the obvious project files.

When the server fires up i get this error msg:
postgres_1  | 2020-11-29 11:10:57.015 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.1.

and once I try to insert the correct default credentials, the console outputs

frontend_1  |  ERROR  [HPM] Error occurred while trying to proxy request /v1/auth-token from 127.0.0.1:3000 to http://backend:8000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
frontend_1  |

Another error appears as the server starts:
postgres_1  | 2020-11-29 11:45:24.606 UTC [1] FATAL:  database files are incompatible with server
postgres_1  | 2020-11-29 11:45:24.606 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.1.

When the servers is done loading I get this error:
backend_1   | Database unavailable on attempt 60/60: could not translate host name "postgres" to address: Name or service not known

My Environment
Mac os 10.15.5
Python 3.6.12 :: Anaconda, Inc.
Doccano was installed two weeks ago, but I did git pull today. 

The UI error msg I get is:
![Screen Shot 2020-11-26 at 15 48 22](https://user-images.githubusercontent.com/31179968/100541185-bb85aa00-324a-11eb-8492-c3605f9e53b3.png)

**Comment by shnuhw** [comment]
I login through `docker-compose -f docker-compose.prod.yml restart`, but it will occure after using /admin to add users

**Comment by i4never** [comment]
In my case, things go smoothly after ADMIN_EMAIL is set.

**Comment by oreoft** [comment]
If you can't access whit showing username or password error, might your project of backend starting fail.
In my case, keepping restart project of backend, until it  running with no error
