### ISSUE TITLE
How to generate tags automatically

### ISSUE THREAD

**Issue by niutyut** [doccano/doccano#1087]
How to generate tags automatically, e.g. add a tag and then the same word is automatically added to that tag.

**Comment by icoxfog417** [comment]
doccano does not have this feature. But the auto-labeling is in progress now.
https://github.com/doccano/auto-labeling-pipeline

**Comment by niutyut** [comment]
doccano does not have this feature. But the auto-labeling is in progress now.
https://github.com/doccano/auto-labeling-pipeline
my question:
I would like to know how auto-labeling-pipeline is implemented? How do I use doccano after installation? Is there an example of this in action?

**Comment by niutyut** [comment]
For example, if my sentence is "My favorite novel is Jane Eyre, my favorite novel is Jane Eyre, Jane Eyre is my favorite novel, Jane Eyre is very good", then after manually marking Jane Eyre as a book, can other Jane Eyres be marked automatically? How about this?
