### ISSUE TITLE
Does Doccano have Auto Labeling/Active Learning?

### ISSUE THREAD

**Issue by kuatroka** [doccano/doccano#1089]
Hi, I feel a bit confused about whether there is or not Active Learning / Auto Labeling functionality in doccano. The tutorial doesn't say anything about it, but the doccano [heroju website](https://doccano.herokuapp.com/) says that there is.

There is also another [repo  ](https://github.com/doccano/auto-labeling-pipeline)that seems to be about Auto Labeling, but no tutorial. 

Thanks

![image](https://user-images.githubusercontent.com/9093546/100950033-632d0180-3503-11eb-89df-0c9753c3916d.png)

**Comment by Hironsan** [comment]
Now you can annotate text automatically by using doccano's REST API.
In the near future, I will implement the feature on the web app by using [auto-labeling-pipeline](https://github.com/doccano/auto-labeling-pipeline).

**Comment by kuatroka** [comment]
Thanks, maybe I'm missing something. I've installed the code from doccano repo and ran the container but I don't see any Automated Labeling feature. Maybe you can direct me tutorial or something that explains how to use it? Thanks.

**Comment by niutyut** [comment]
how to finish Auto labeling？
