### ISSUE TITLE
How does label ID while exporting keeps on increasing?

### ISSUE THREAD

**Issue by shadylpstan** [doccano/doccano#1096]
How to reproduce the behaviour
---------
I created a dummy project, added 2 labels to it and tagged my document.
While exporting the JSON annotations were like :
[{"label": 3, "start_offset": 0, "end_offset": 5, "user": 1, "created_at": "2020-12-07T12:21:22.865178Z", "updated_at": "2020-12-07T12:21:22.865178Z"}, {"label": 4, "start_offset": 10, "end_offset": 15, "user": 1, "created_at": "2020-12-07T12:21:32.592122Z", "updated_at": "2020-12-07T12:21:32.592122Z"}, {"label": 5, "start_offset": 15, "end_offset": 19, "user": 1, "created_at": "2020-12-07T12:25:09.214959Z", "updated_at": "2020-12-07T12:25:09.214959Z"}]
So in label: 3 and 4.

After deleting all the labels, deleting projects and every try, whenever I export any document after tagging, the "label" keeps on increasing.

Question is:
Why the label id keeps on increasing even after deleting labels and projects?
Also, how to get the label name which I created, after all I need the labels to be attached with my annotation. 

Please help. And thanks for the wonderful library. This is wonderful.

Your Environment
---------

*   Operating System: Windows
*   Python Version Used: 3.6.12
*   When you install doccano: 7th Dec, 2020
*   How did you install doccano (Heroku button etc): pip

**Comment by icoxfog417** [comment]
We try to implement exporting labels by name (not  id). 
Please upvote this issue if you want this feature!

#295
