### ISSUE TITLE
How to get the real label name instead of the label id after exporting the dataset? (Document classification project)

### ISSUE THREAD

**Issue by arthurthlee** [doccano/doccano#1102]
This PR: https://github.com/doccano/doccano/pull/217
Incorrectly states that it added "Enhancement/Alignment for import data format and export data format". The PR only added this functionality to sequence labelling projects, but there is still no json1 export option for Document Classification projects.

This functionality should be added for other project types

**Comment by icoxfog417** [comment]
We try to implement exporting labels by name (not  id). 
Please upvote this issue if you want this feature!

#295
