### ISSUE TITLE
Doccano is duplicating the words displayed for some unknown reason

### ISSUE THREAD

**Issue by milos-cuculovic** [doccano/doccano#1105]
I have imported a pre-labeled dataset to doccano and asked some colleagues to check and fix the annotations. In some cases, the sentences displayed in doccano have one annotated word duplicated, see the following screenshots:

1. I open doccano, the word should is duplicated:
https://ibb.co/3WKKd2m

2. I remove both duplicate annotations, should is shown only once
https://ibb.co/SJnV1mL

3. When I try to annotate should, the label selection window is not popping up

4. When I annotate something before the word should:
https://ibb.co/nzB28bx

5. The annotation is placed on a wrong position:
https://ibb.co/7QpWvjR

If I remove all annotations and redo them again, all looks ok.

Your Environment
---------

*   Operating System: Ubuntu 20.04
*   Python Version Used: 3.8.5
*   When you install doccano: 4 weeks ago
*   How did you install doccano (Heroku button etc): Docker

**Comment by Hironsan** [comment]
Could you please show me an example of pre-labeled data? It helps me a lot to investigate the problem.

**Comment by milos-cuculovic** [comment]
Hi @Hironsan,  sure, here you go:

{ "text": "2, The main text under the \u2018results and discussion\u2019 is unnecessarily wordy. Shorten the text and minimize the discussion and reference to literature in this section as the \u2018results and discussion\u2019 should focus on the results obtained by the authors. In some cases it is difficult to understand whether the findings are original, or already reported in the literature.", "labels": [[12,16,"LOCATION"], [197,203,"MODAL"]]}

**Comment by Hironsan** [comment]
Thank you for your response.

I uploaded the data but I couldn't find the duplication:

![](https://i.gyazo.com/011547575a9080d3fff768813bf4b74f.png)

Do you have a pre-labeled data which has word duplicated? Thanks.

**Comment by milos-cuculovic** [comment]
This one is when I imported the pre-labelled text into doccano. After labelling, somehow it had duplicates.
Here is another one I just exported from doccano, that has duplicates:

{"id": 6111, "text": "10. The“Adsorption (2018) 24:691” article should be acknowledged , it discussed the same material and separation but from a different approach. Similarly,“Chem. Mater., 2018, 30 (2), 447-455” also discussed the same material for a novel application, which should be briefly incorporated  into the introduction about the target materials.", "meta": {}, "annotation_approver": "gajic@mdpi.com", "labels": [[7, 33, "LOCATION"], [51, 64, "ACTION"], [42, 48, "MODAL"], [113, 116, "TRIGGER"], [42, 48, "MODAL"], [52, 64, "ACTION"], [4, 41, "CONTENT"], [154, 191, "CONTENT"], [256, 262, "MODAL"], [274, 286, "ACTION"], [297, 309, "LOCATION"]]}
{"id": 6115, "text": "The excessive information from the introduction is not needed – Authors should rather present more results of their study.", "meta": {}, "annotation_approver": "gajic@mdpi.com", "labels": [[35, 47, "LOCATION"], [72, 78, "MODAL"], [35, 47, "LOCATION"], [51, 61, "ACTION"], [0, 25, "CONTENT"], [72, 78, "MODAL"], [86, 93, "ACTION"], [94, 121, "CONTENT"]]}

**Comment by milos-cuculovic** [comment]
https://ibb.co/BN9Fzyj

**Comment by Hironsan** [comment]
Thank you.

I looked at the data and found `[42, 48, "MODAL"]` is duplicated.

I have a hypothesis. Did you check the `share annotation` option when you create the project?

**Comment by milos-cuculovic** [comment]
Collaborative annotation is now checked, but I do not remember if I checked it when I created the project and imported the dataset, or afterwards. Shall I disable it and try to export again?

**Comment by milos-cuculovic** [comment]
Ok, the good news is that once I disable the "Collaborative annotation", I do not see the duplicates in doccano any longer, however, when I export them from doccano, there are duplicates in the json file.

**Comment by Hironsan** [comment]
## The way to reproduce the problem

- There are two annotators: annotator A and B.
- The share annotation option is on.
- The annotator A annotate a word should:

![image](https://user-images.githubusercontent.com/6737785/101776228-f41f6080-3b33-11eb-9870-9431d5a49b8d.png)

- The annotator B also annotate a word should:

![image](https://user-images.githubusercontent.com/6737785/101776228-f41f6080-3b33-11eb-9870-9431d5a49b8d.png)

- Once we refresh the app, we can see the duplication.

![image](https://user-images.githubusercontent.com/6737785/101776413-39439280-3b34-11eb-8c2b-2d527abddf2b.png)

## Problem

- The `SequenceAnnotation` model has a unique constraint.
- It includes `user`, so different users can annotate the same offset, label, and document.
- This is not preferable if `share annotation` is enabled.

```python
class SequenceAnnotation(Annotation):
    ...
    class Meta:
        unique_together = ('document', 'user', 'label', 'start_offset', 'end_offset')
```

## Solution idea

I can't come up with anything right now. I will think the solution.

**Comment by milos-cuculovic** [comment]
Thanks @Hironsan  ! The main issue I have now is that even after disabling the share annotation option, the view is fixed for the user B, however while exporting the annotations in JSON, the two are still shown. To bypass the problem, I am querying directly the PostgreSQL db with a WHERE cause user_id = user B. Looking forward to a cleaner solution.
