### ISSUE TITLE
Invalid syntax error when running the newly installed doccano

### ISSUE THREAD

**Issue by IsVeneti** [doccano/doccano#1107]
### System information
- **OS Platform and Distribution**: Fedora 32
- **Python version**: Python 3.8.6

### The problem
When opening using the docker-compose, the backend shows an error code about invalid syntax:
```
File "/src/app/app/settings.py", line 283
 if (spec := importlib.util.find_spec(name)) is not None:
          ^
SyntaxError: invalid syntax
```
this results in `doccano_backend_1 exited with code 1`

I also tried downloading it through pip in my windows pc, and it had the same result. 

When using the prod file on docker-compose, it also shows the following error
```
nginx_1     | 2020/12/10 20:27:46 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/conf.d/nginx.conf:15
nginx_1     | nginx: [emerg] host not found in upstream "backend" in /etc/nginx/conf.d/nginx.conf:15
doccano_nginx_1 exited with code 1
```
It's my first time using doccano and I may did something wrong, but I'm certain i followed the instructions correctly. 
Thank you for the help in advance!

**Comment by Hironsan** [comment]
Fixed in #1008 . Please rebuild images and run containers.
