### ISSUE TITLE
Annotated data lost

### ISSUE THREAD

**Issue by JillinJia** [doccano/doccano#1111]
My Macbook has been shut down because of the low battery level when I was annotating my data using doccano. After I restarted my pc and logged in doccano, there was a totally new display of this app and the data I have finished annotating has completely disappeared. I lost all my works.
What should I do to find my lost works? Plz help me:(

**Comment by icoxfog417** [comment]
That's very tragic.  But we can't help you because it depends on your pc (not doccano).
