### ISSUE TITLE
Bases of Docker containers

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#1112]
@Hironsan , IMHO every part of doccano should be Alpine-, Debian **or** Ubuntu-based.

* Nginx's Docker base [is Alpine](https://github.com/doccano/doccano/blob/master/nginx/Dockerfile#L1),
* Node's Docker base ~was Ubuntu~ [is Alpine](https://github.com/doccano/doccano/blob/master/frontend/Dockerfile#L1),
* Python's Docker base ~was Ubuntu~ ~was Alpine~ [is Debian](https://github.com/doccano/doccano/blob/master/app/Dockerfile#L1).

Thoughts?

**Comment by Hironsan** [comment]
Alpine is useful for smaller images. But in Python, it can take quiet time to build images. So I changed the image from Alpine to slim-buster.

- [Using Alpine can make Python Docker builds 50× slower](https://pythonspeed.com/articles/alpine-docker-python/)

Are there any concerns?

**Comment by kuraga** [comment]
Alpine, Debian and Ubuntu even use different standard C libraries. Feel free to close but IMHO to have same bases is better even than (size-optimized) Alpine. And

> But in Python, it can take quiet time

IMHO is not an issue. We build once only.

**Comment by ricjhill** [comment]
Alpine, Debian and Ubuntu even use different standard C libraries. Feel free to close but IMHO to have same bases is better even than (size-optimized) Alpine. And

Agreed.

**Comment by kuraga** [comment]
By another side using a precompiled versions (i.e. "wheels" i.e. non-Alpine) could be better...

But even that IMHO the base have to be the same.
