### ISSUE TITLE
Mark project as done

### ISSUE THREAD

**Issue by dimidd** [doccano/doccano#1114]
Feature description
---------

Hi, is there a way for an annotator/project-admin to mark a project as done?
We could add a boolean field to the schema, and a checkbox in the front-end.

**Comment by Hironsan** [comment]
There is no way for now.
It is necessary to change:

- Add a project status field to the ProjectModel
- Add a checkbox somewhere in the frontend

We should be able to use `ProjectDetail` API to change the state:
https://github.com/doccano/doccano/blob/1e40005f35c65a98f5ec2cd48443646cd7741237/app/api/views.py#L71-L75

**Comment by fjen** [comment]
Could by solved by adding tags to projects #1044
