### ISSUE TITLE
File size should be less than 1MB in the last update ?

### ISSUE THREAD

**Issue by MESSALTI** [doccano/doccano#1124]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by fjen** [comment]
You've already asked about that 3 days ago #1119

**Comment by icoxfog417** [comment]
Thank you @fjen ! @MESSALTI please refer the pointed issue.

**Comment by MESSALTI** [comment]
Unfortunately, the previous solutions don't work, even though I updated nginx.conf and front-end / rules / index.js
