### ISSUE TITLE
Issues deploying doccano with context root

### ISSUE THREAD

**Issue by aabid0193** [doccano/doccano#1129]
Related Issues:
#380
#775
#967

Having issues deploying doccano at a base uri with a context root '/doccano', with SSL such as: https://XYZ.com/doccano/. I have tried the suggested methods in the related issues with no success & they seem like incomplete answers.

Anyone aware of how this can be done? Not sure if any of the other related Issues were actually resolved.

**Comment by Hironsan** [comment]
Maybe `API_URL` needs to be changed:

https://github.com/doccano/doccano/blob/507f11e0717d9d378a526dcf53b352c4d0191a25/docker-compose.prod.yml#L27-L28

**Comment by icoxfog417** [comment]
@aabid0193 Please let us know if the advice from Hirosan works.
