### ISSUE TITLE
I cant't login in the doccano ,when i have installed , i use differernt account and password , and no one can  login succeed. even，i can't  open the ip:8000/admin,or any  other  website ,only the  ip:8000,why you must set the  default password? it's very  unconvenient

### ISSUE THREAD

**Issue by vencent-love-python** [doccano/doccano#1133]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by Hironsan** [comment]
I don't understand what you are saying.
I don't understand what is your situation.
I don't understand what is your environment.

Please tell us about your situation correctly.

**Comment by vencent-love-python** [comment]
my system is window 10 , python 3.7 ,i use pip to install the doccano. when&nbsp; installed ,i use&nbsp; command : doccano &nbsp; to start .&nbsp; the default user and password i dont' know ,so i look for the doccano.py to&nbsp; find.&nbsp; i find the file&nbsp; in the path&nbsp; :C:\ProgramData\Anaconda3\Lib\site-packages\app\doccano, and the default user and password is&nbsp; admin and password . But&nbsp; when i user the default user and password &nbsp; to&nbsp; login ,i always&nbsp; fail . i follow the &nbsp;guide to change the password ,so i visit &nbsp;http://127.0.0.1:8000/admin, but i&nbsp; even&nbsp; can't&nbsp; open the&nbsp; page .i dont know&nbsp; why? &nbsp; can you&nbsp; help me?











------------------ 原始邮件 ------------------
发件人:                                                                                                                        "doccano/doccano"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月26日(星期六) 上午10:38
收件人:&nbsp;"doccano/doccano"<doccano@noreply.github.com&gt;;
抄送:&nbsp;"时空守望者@"<1042370669@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [doccano/doccano] I cant't login in the doccano ,when i have installed , i use differernt account and password , and no one can  login succeed. even，i can't  open the ip:8000/admin,or any  other  website ,only the  ip:8000,why you must set the  default password? it's very  unconvenient (#1133)





 
I don't understand what you are saying.
 I don't understand what is your situation.
 I don't understand what is your environment.
 
Please tell us about your situation correctly.
