### ISSUE TITLE
webpack_loader is missing when log in localhost:8000

### ISSUE THREAD

**Issue by frederic89** [doccano/doccano#1134]
When I log in localhost:8000 in Chrome ， webpack_loader cannot be load with Django. I can't set up user as before with backend.
It is said 500 Fault in docker log.

I check the source file setting.py of Django, INSTAlLL_APP webpack_loader becomes # webpack_loader since someday.

Your Environment
---------

*   Operating System: Centos 7
*   Python Version Used: Python 3.8.6 in docker-compose yml file
*   When you install doccano: Now
*   How did you install doccano (Heroku button etc): Docker compose

**Comment by Hironsan** [comment]
If you used `docker-compose.dev.yml`, please use `localhost:3000` instead of `localhost:8000`.
