### ISSUE TITLE
'webpack_loader' is not a registered tag library.

### ISSUE THREAD

**Issue by doraemonlei** [doccano/doccano#1135]
win10
py3.6

http://127.0.0.1:8000/
2.2.13
TemplateSyntaxError
'webpack_loader' is not a registered tag library. 
Must be one of: admin_list admin_modify admin_static admin_urls analytics cache i18n l10n log polymorphic_admin_tags polymorphic_formset_tags rest_framework static staticfiles tz utils_templating

**Comment by Hironsan** [comment]
If you used `docker-compose.dev.yml`, please use `localhost:3000` instead of `localhost:8000`.
