### ISSUE TITLE
deployment problem

### ISSUE THREAD

**Issue by zhentaoCoding** [doccano/doccano#1136]
i deploy the doccano with docker-compose.prod.yml, but i can't visit the system with http://0.0.0.0:8000

![image](https://user-images.githubusercontent.com/5669444/103507896-1ee2a780-4e9b-11eb-9bd8-bb09bcea44fd.png)

Your Environment

*   Operating System: win10
*   Python Version Used: 3.8
*   When you install doccano:2021/1/4
*   How did you install doccano (Heroku button etc):docker-compose.prod.yml

**Comment by zhentaoCoding** [comment]
and i found "doccano_frontend_1 exited with code 0"

**Comment by Hironsan** [comment]
Could you please try `localhost:80` or `127.0.0.1:80`?
