### ISSUE TITLE
Can't reset doccano environment

### ISSUE THREAD

**Issue by wbqtac** [doccano/doccano#1137]
I installed doccano on linux machine, but due to some mis-operation, I stopped the server before first login.

Since then, I cannot login to the system correctly. I used "admin" and "password", but cannot log in.
After I started the server from commandline, I get the following error:
-----------------------------------
No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

-----------------------------------

I uninstall and reinstall the package, but the problem remains the same, it looks that some settings are kept there, not a really fresh install. 

My question:
(1) any way to fix this to login to it?
(2) any way to really fresh install everything?
Thank you for your help in advance.

Best

**Comment by SwiftPredator** [comment]
@wbqtac Have you tried to run `python app/manage.py makemigrations` and then `python3 app/manage.py migrate` in the doccano directory? Maybe this could fix your issue.

**Comment by wbqtac** [comment]
Hi Paul,

Thank you for your reply.
(1) I pulled the code, tried to run the command, but doesn't work. Not sure what actually cause the problem.
(2) I used docker, it works.

Best

Bingqing

**Comment by icoxfog417** [comment]
That sounds tough.
Could you please try the procedure of "I want to update to the latest doccano image"?

https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-update-to-the-latest-doccano-image

**Comment by icoxfog417** [comment]
Close this issue because of docker works.
