### ISSUE TITLE
how can i link externel postgresql to docker backend??

### ISSUE THREAD

**Issue by choiseulong** [doccano/doccano#1141]
i tried, but most of google answer said to getting out data postgresql in docker to outside space

i want separate postgresql to docker 

external space   //   in docker
postgresql        //    back + front 

just using python ?
-> import psycopg2 && test.connect() ? ?

or 
In setting.py 
using DATABASES ={} ??

help me plz and have a nice day :)

*   Operating System: windows10 ?
*   Python Version Used: 3.8.9
*   When you install doccano: 1 day ago
*   How did you install doccano (Heroku button etc): searching google

**Comment by icoxfog417** [comment]
Thank you for using the doccano. Your question is hard to solve because it depends on your situation and the docker feature (not doccano).
