### ISSUE TITLE
I need output label numbers to be consistent cross-project!!

### ISSUE THREAD

**Issue by CatOfTheCannals** [doccano/doccano#1142]
I'm using doccano for text classification.
I'm tagging different datasets and I do so by creating a new project every time.
I'm loading the same label json for every project. However, every time I export an annotated dataset, I get different numbers corresponding to the same labels.

I'm using the docker version of doccano in osx Catalina 10.15.7

Do you know of a way I can keep adding new datasets without having to map the output labels every time?

Thanks!!!

**Comment by icoxfog417** [comment]
We discuss this feature at #901 . Please upvote this issue and it is reflected to #882
