### ISSUE TITLE
TemplateDoesNotExist at / when I run "python manage.py runserver"

### ISSUE THREAD

**Issue by YeZiyi1998** [doccano/doccano#1146]
How to reproduce the problem
---------

python manage.py runserver
open 127.0.0.1:8000
I see:

Request Method: | GET
-- | --
http://127.0.0.1:8000/
3.1.5
TemplateDoesNotExist
index.html
/usr/local/anaconda3/envs/docc/lib/python3.6/site-packages/django/template/loader.py, line 47, in select_template
/usr/local/anaconda3/envs/docc/bin/python3
3.6.12
['/Users/yeziyi/Desktop/gitRepository/docc/doccano/app',  '/usr/local/anaconda3/envs/docc/lib/python36.zip',  '/usr/local/anaconda3/envs/docc/lib/python3.6',  '/usr/local/anaconda3/envs/docc/lib/python3.6/lib-dynload',  '/usr/local/anaconda3/envs/docc/lib/python3.6/site-packages']
Mon, 11 Jan 2021 14:14:40 +0000

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):
mac
I use npm install，npm run build, python manage.py migrate, python manage.py create_roles, python manage.py create_admin --noinput --username admin --email admin@example.com --password password, python manage.py runserver

**Comment by Hironsan** [comment]
If you want to develop some features, I recommend you should use `docker-compose.dev.yml`.

By the way, I think you need to:

- run frontend server(`yarn dev` in the frontend directory)
- access `127.0.0.1:3000`. Because the port `8000` just provides backend API, not frontend.
