### ISSUE TITLE
Can't login to Doccano using any other user than admin while loggin into the user portal 

### ISSUE THREAD

**Issue by skshahidur** [doccano/doccano#1148]
How to reproduce the behaviour
---------

I open two tabs on a browser. On first browser I Login using admin credentials on the Django Administration portal. Now I created a new user. Using this new user credentials if I login to doccano portal while already logged in to the Admin portal, it fails to login. 

I'm required to logout from the Django Administration portal and then only I can login using the new credentials.

Your Environment
---------
*   Operating System: Mac and Chrome
*   Python Version Used: 3.7
*   When you install doccano: 1 month ago
*   How did you install doccano (Heroku button etc): Our own ec2

Django Administration portal:
![Screenshot 2021-01-13 at 16 05 33](https://user-images.githubusercontent.com/11743805/104442799-98754680-55bb-11eb-9fd9-3d2eb8e9051e.jpg)

At the same time, doccano portal,
![Screenshot 2021-01-13 at 16 05 16](https://user-images.githubusercontent.com/11743805/104442830-a2974500-55bb-11eb-8cff-d880a610119c.jpg)

**Comment by Hironsan** [comment]
Related to https://github.com/doccano/doccano/issues/1098#issuecomment-742492683
