### ISSUE TITLE
Can annotate while logged in administration protal

### ISSUE THREAD

**Issue by skshahidur** [doccano/doccano#1149]
How to reproduce the behaviour
---------

1.  Login to a user other than admin
2. Login to administration portal using admin
3. Go to previous user and try annotating

Your Environment
---------
*   Operating System: Mac and Chrome
*   Python Version Used: 3.7
*   When you install doccano: 1 month ago
*   How did you install doccano (Heroku button etc): AWS ec2

Admin portal,
![Screenshot 2021-01-13 at 16 28 01](https://user-images.githubusercontent.com/11743805/104447859-63b8bd80-55c2-11eb-8d7a-e82439afc427.jpg)

Error in another user (other than admin) portal,
![Screenshot 2021-01-13 at 16 27 50](https://user-images.githubusercontent.com/11743805/104447934-7fbc5f00-55c2-11eb-83a6-aa94cc7a7e96.jpg)

**Comment by Hironsan** [comment]
Related to https://github.com/doccano/doccano/issues/1098#issuecomment-742492683
