### ISSUE TITLE
Azure one click deployment: container was not able to startup

### ISSUE THREAD

**Issue by creeston** [doccano/doccano#1153]
I tried one-click deployment to deploy doccano in Azure. I had a problem with creating new SendGrid account (because I already had one) so I modified template a little bit: I removed "send grid creation" step from template and replaced send-grid related parameters with existing value (smpt, api key and etc).

But application not starting. Logs says that container was not able to startup because of following error:

2021-01-14T14:55:13.515214058Z Making staticfiles
2021-01-14T14:55:13.515247858Z Executing collectstatic
2021-01-14T14:55:13.657481952Z python: can't open file 'manage.py': [Errno 2] No such file or directory

Any idea how this can be fixed?

**Comment by Hironsan** [comment]
I'm not familiar with Azure. But I think we need to update the following file:

- https://github.com/doccano/doccano/blob/master/azure-pipelines.yaml

The docker build specifies `builder` as a target, but it's now missing in Dockerfile.

**Comment by creeston** [comment]
By the way, I was able to resolve the issue by pulling older version of container. I don't remember the exact hash of it, but I found something 2 weeks older then the day I reported that issue and it started to work. Well, it was not exactly "working" it still required some fixes to be done from my side, but eventually I was able to run it in Azure.
