### ISSUE TITLE
sh: 0: Can't open tools/heroku.sh

### ISSUE THREAD

**Issue by MESSALTI** [doccano/doccano#1157]
sh: 0: Can't open tools/heroku.sh

**Comment by ogabrielluiz** [comment]
Can this be related to [this commit](https://github.com/doccano/doccano/commit/7350f4eb9010e82ea01adc589ce45dc955939436)?

Considering WORKDIR is inside the app directory `tools/heroku.sh` would not be found, would it?

**Comment by Hironsan** [comment]
I investigated the problem. We need to change three things:

- Update `postdeploy` in app.json to `sh /doccano/tools/heroku.sh`
- Update `heroku.sh` to `python /doccano/app/manage.py`
- Update Dockerfile to install `psycopg2-binary` and `django-heroku`
