### ISSUE TITLE
TemplateDoesNotExist at / index.html

### ISSUE THREAD

**Issue by DylanDenali** [doccano/doccano#1159]
Request Method: | GET
-- | --
http://127.0.0.1:8000/
3.1.5
TemplateDoesNotExist
index.html
D:\Anaconda\envs\doccano\lib\site-packages\django\template\loader.py, line 47, in select_template
D:\Anaconda\envs\doccano\python.exe
3.7.9
['D:\\ScholarMethods\\doccano\\app',  'D:\\Anaconda\\envs\\doccano\\python37.zip',  'D:\\Anaconda\\envs\\doccano\\DLLs',  'D:\\Anaconda\\envs\\doccano\\lib',  'D:\\Anaconda\\envs\\doccano',  'C:\\Users\\adminxyj1\\AppData\\Roaming\\Python\\Python37\\site-packages',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\doccano-1.0.6.dev217+gd5e757b-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\whitenoise-5.2.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\social_auth_app_django-4.0.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\seqeval-1.2.2-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\python_jose-3.2.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pyexcel_xlsx-0.6.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pyexcel-0.6.6-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\furl-2.1.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\environs-9.3.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\drf_yasg-1.20.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\djangorestframework_xml-2.0.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\djangorestframework_csv-2.1.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\django_rest_polymorphic-0.1.9-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\django_filter-2.4.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\django_cors_headers-3.6.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\dj_database_url-0.5.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\conllu-4.2.2-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\colour-0.1.5-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\apache_libcloud-3.3.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\social_auth_core-4.0.3-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\six-1.15.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\scikit_learn-0.24.0-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\numpy-1.20.0rc2-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\rsa-4.7-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pyasn1-0.4.8-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\ecdsa-0.14.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pyexcel_io-0.6.4-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\openpyxl-3.0.6-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\texttable-1.6.3-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\lml-0.1.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\orderedmultidict-1.0.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\python_dotenv-0.15.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\marshmallow-3.10.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\uritemplate-3.0.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\ruamel.yaml-0.16.12-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\packaging-20.8-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\inflection-0.5.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\djangorestframework-3.12.2-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\coreschema-0.0.4-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\coreapi-2.3.3-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\defusedxml-0.7.0rc2-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\unicodecsv-0.14.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\django_polymorphic-3.0.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\requests-2.25.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\requests_oauthlib-1.3.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\python3_openid-3.2.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\oauthlib-3.1.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\cryptography-3.3.1-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pyjwt-2.0.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\threadpoolctl-2.1.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\scipy-1.6.0-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\joblib-1.0.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\jdcal-1.4.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\et_xmlfile-1.0.1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\ruamel.yaml.clib-0.2.2-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pyparsing-3.0.0b2-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\jinja2-3.0.0a1-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\itypes-1.2.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\urllib3-1.26.2-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\idna-2.10-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\chardet-4.0.0-py3.7.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\cffi-1.14.4-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\markupsafe-2.0.0a1-py3.7-win-amd64.egg',  'D:\\Anaconda\\envs\\doccano\\lib\\site-packages\\pycparser-2.20-py3.7.egg']
Sat, 16 Jan 2021 03:09:13 +0000

**Comment by Hironsan** [comment]
How did you install doccano? Pip, Docker, or Docker Compose(dev/prod)?

**Comment by DylanDenali** [comment]
Pip



---Original---

**Comment by Hironsan** [comment]
I updated the package v1.1.1. Please try it.

**Comment by Hironsan** [comment]
Move to https://github.com/doccano/doccano/issues/1159 and close.
