### ISSUE TITLE
size of upoad file

### ISSUE THREAD

**Issue by MESSALTI** [doccano/doccano#1166]
Thank you for this great job. The only thing missing is an increased upload file size. I think 1MB is too small. Hope you get to this point in future updates.

**Comment by fjen** [comment]
see #708.

**Comment by MESSALTI** [comment]
Unfortunately, the previous solutions don't work, even though I updated nginx.conf and front-end / rules / index.js

**Comment by xhw205** [comment]
> Unfortunately, the previous solutions don't work, even though I updated nginx.conf and front-end / rules / index.js

Same as you, have you solved it?
