### ISSUE TITLE
Couldn't Access to Django Admin Page

### ISSUE THREAD

**Issue by SimZhou** [doccano/doccano#1170]
How to reproduce the problem
---------

I installed using docker method. 
I want to create users for annotators.
I followed [https://djangobook.com/mdj2-django-admin/](https://djangobook.com/mdj2-django-admin/) and created a superuser `python manage.py createsuperuser`
I still could not access to admin page by `XXXX:8000/admin`
![image](https://user-images.githubusercontent.com/11748629/105440458-8c674400-5ca1-11eb-8440-18a8f7ab0825.png)

I wonder if I should restart the doccano app. 
But I did not find a way. 
(btw, restarting the docker container does not work!)

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System: Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017
*   Python Version Used: -
*   When you install doccano: 2021.01.16
*   How did you install doccano (Heroku button etc): 
```
docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano
docker container start doccano
```

**Comment by Hironsan** [comment]
Please Access  `/admin/` instead of `/admin`
