### ISSUE TITLE
display shortcut keys for annotators

### ISSUE THREAD

**Issue by MESSALTI** [doccano/doccano#1173]
Can you display  shortcuts keys for commentators?

**Comment by MESSALTI** [comment]
Can you provide keyboard shortcuts for commentators?

**Comment by Hironsan** [comment]
We need to know what you expect in detail.

Do your words mean you want to popup comment window after pressing some shortcuts keys for commentators?
![image](https://user-images.githubusercontent.com/6737785/105666112-e3784d80-5f1b-11eb-8190-c81f957216c1.png)

**Comment by MESSALTI** [comment]
In previous versions of Doccanon, there were a few icons in the annotation interface for the labels to short it, but now there is a drop-down menu that hides these labels, so it's best to display these labels as they were before.
thank you in advance

**Comment by MESSALTI** [comment]
In previous versions of Doccano, in the annotator interface there were icons for the labels with their shortcut, but now there is a drop-down menu that hides these labels so it's best to display these labels as they were before.
thank you in advance

**Comment by rbagd** [comment]
I think what @MESSALTI meant is bringing back the available label overview on top of the text card along with the shortcut keys as it used to be.

![doccano](https://user-images.githubusercontent.com/1479558/105897003-dfc9f100-6017-11eb-9682-0e991eea456e.png)

Currently, shortcut keys are no longer visually indicated, so it's much harder to train oneself to do (much faster) keyboard-driven labelling. I also think that having a label overview is pretty nice instead of them being in a dropdown.

**Comment by Hironsan** [comment]
I understood what you are saying.

OK. I'll consider it.

**Comment by nbroad1881** [comment]
Here are 2 more suggestions related to keyboard shortcuts.

1. Give each user their own preference for which shortcut corresponds to each label. For example: User 1 likes to use the key 'a' for label 1, 's' for label 2, but User 2 likes to use '1' for label 1 and '2' for label 2.
2. Give the option for users to choose a keyboard shortcut for non-labeling actions like next example, previous, and approve. (also make these displayable from the annotation screen). For example, set next to the 'f' key and approve to the 'w' key.

**Comment by Hironsan** [comment]
I'm now working on the auto labeling feature. So after that, I'll consider something.

**Comment by Hironsan** [comment]
![](https://i.gyazo.com/9a6153e294dad7785d5b0064001e3fc5.gif)
