### ISSUE TITLE
Spaces in text get lost during import

### ISSUE THREAD

**Issue by tjernic** [doccano/doccano#1176]
How to reproduce the behaviour
---------

I imported plain text into doccano for Sequence Labelling. When looking at the text in Doccano (under Dataset or Annotate) there are some spaces missing. They are also missing when exporting the data. Here is an example:

_This is what it looks like in the .txt file:_
```
This OPC UA ObjectType represents an optical reader device (1D or 2D codes). It defines additional methods and properties required for managing optical code readers or to get additional information on their scan events. Figure 8 shows an overview for the OpticalReaderDeviceType with its Methods and related ObjectType. It is formally defined in Table 11.  Figure 8 – OpticalReaderDeviceType overview  
```

_This is what it looks like in Doccano:_
```
This OPC UAObjectTyperepresents an optical reader device (1D or 2D codes).It defines additional methods and properties required for managing optical code readers or to get additional information on their scan events.Figure 8shows an overview for theOpticalReaderDeviceTypewith itsMethodsand relatedObjectType. It is formally defined inTable 11.Figure 8– OpticalReaderDeviceType overview
```

Any idea why these get lost in the process? 

Your Environment
---------

*   Operating System: W10
*   Python Version Used: 3.9
*   When you install doccano: Beginning of Dec 2020
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by Hironsan** [comment]
Hi @tjernic 

Could you please give me a part of the file?
It seems to me that the problem is caused by character encoding. So the file is useful to investigate the problem.

**Comment by tjernic** [comment]
Hey @Hironsan, 

thanks for your message, here is the file. I pull the text from this website https://reference.opcfoundation.org/v104/AutoID/v101/docs/6.3.1/

[OPCUACS_AutoID_6.3.1.txt](https://github.com/doccano/doccano/files/5864777/OPCUACS_AutoID_6.3.1.txt)

**Comment by Hironsan** [comment]
Hmm, I uploaded your data but I can't reproduce the problem:

![image](https://user-images.githubusercontent.com/6737785/105952537-0be77f80-60b5-11eb-972d-d62b7772986b.png)

Hmm, it's a mystery.

**Comment by tjernic** [comment]
Reinstalling and creating a new project helped. Thanks @Hironsan
