### ISSUE TITLE
No Admin url to add user

### ISSUE THREAD

**Issue by abneetwats24** [doccano/doccano#1186]
How to reproduce the behaviour
---------

Your Environment
---------

*   How did you install doccano (Heroku button etc): Heroku button
*   Config ALLOW_SIGNUP = true 

<s> As per [FAQ docs](https://doccano.github.io/doccano/faq/#i-want-to-add-annotators-annotatorsannotation-approvers) I visit /admin for adding users but got 404 </s>

And In Login /auth page I do not see any signup button.
How do I sign up?

#################################
I am able to get the admin page at /admin/

but still do not find any signup page URL

**Comment by abneetwats24** [comment]
I am able to get the admin page at /admin/ 

but still do not find any signup page URL

**Comment by Hironsan** [comment]
If you want to add a user, please use the admin page.
The signup page has not supported yet in v1.x.x.
