### ISSUE TITLE
Few issues encountered

### ISSUE THREAD

**Issue by LisaBanana** [doccano/doccano#1187]
Hi,
I encountered some errors when trying to use the docanno application.
1 : When adding a collaborator for annotation task, I gave him the "annotator" rôle but he couldn't see the datas, I had to give him administrator privilege to make him able to see and anotate the data. I couldn't find a way to fix it myself in the doc.
his screen whith anotator rôle was :  
![image](https://user-images.githubusercontent.com/48214320/106487953-7d5b6f80-64b3-11eb-8b16-cbfb78de88e4.png)

2 : I created labels for a project and downloaded the json whith those labels informations. I wanted to reuse it in another project, so I tried to upload it but it couldn't work. I had this screen : 
![image](https://user-images.githubusercontent.com/48214320/106487783-5309b200-64b3-11eb-9d4a-99fc36b3f242.png)

3 : When trying to upload jsonline datas, i had to select the .txt format to make it work as it was'nt whith the JSONL one selected

Don't hesitate if you have any more questions on the issues I encountered and thanks in advance for your answers :)

**Comment by Hironsan** [comment]
Answers:

1. Did you assign a role to the user on the admin page? If so, you should do it on the member's page.
2. https://github.com/doccano/doccano/pull/1163 might have affected.
3. What task did you select? sequence labeling? and what errors did you have?

**Comment by Hironsan** [comment]
The second problem was solved by https://github.com/doccano/doccano/pull/1193.

**Comment by LisaBanana** [comment]
Hello,

For the first issue, the user had the annotator rôle and I had to change it
to give him the administrator rôle for him to be able to annotate the datas.
The task was sentence labelling. I'll check with the developper whom work
on the hosting of the app and the rôle managing to see if it doesn't come
from there.

Thanks for your answers,

Lisa

Le mer. 3 févr. 2021 à 14:20, Hiroki Nakayama <notifications@github.com> a
écrit :
