### ISSUE TITLE
Unable to upload labels into server

### ISSUE THREAD

**Issue by vetbabble** [doccano/doccano#1188]
How to reproduce the behaviour

When trying to import labels in a heroku server.  It says 'file required' no matter what format the file is in.   I've matched the format, but it doesn't seem to even try to import the file.  The button is greyed out.

![image](https://user-images.githubusercontent.com/63191678/106558052-36cf4900-6577-11eb-97eb-1901f3dd5282.png)

Your Environment
---------

*   Operating System: Ubuntu 18.04 and Windows 10
*   Python Version Used: 3.6
*   When you install doccano: Jan-21st
*   How did you install doccano (Heroku button etc):
Heroku button

**Comment by martinezhermes** [comment]
Sadly this is broken.

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/pull/1163 might have affected.
