### ISSUE TITLE
How to pip install from a cloned repo? (pip install -e .)

### ISSUE THREAD

**Issue by johann-petrak** [doccano/doccano#1192]
Is there a way to do a "development install" using pip, so the instead of downloading from pypi, the cloned repository is directly installed?

I tried to do `pip install -e .` from within the doccano directory, but that does not work. Apparently some steps are needed before this cloned repository can be used. 
I also did run the following steps from within the ./app subdirectory:
``` 
python manage.py collectstatic --noinput
python manage.py wait_for_db
python manage.py migrate
python manage.py create_roles
python manage.py create_admin --username admin --password admin --email me@somewhere.com --noinput
```
But after this, running doccan still produces just a Server error.

Is there a way to install from the cloned directory? 

This would perhaps make it much easier to work around the issue #1191 because one could make some local changes first and then run from the modified repo?

**Comment by johann-petrak** [comment]
I also followed the instructions under "Python" and "Node.js" on this page: https://doccano.github.io/doccano/getting-started/ 
With this I can login, create a project, import data, create labels on the  http://127.0.0.1:3000/ URL, but when I click   "Start Annotation" I get a 404 error for the URL http://127.0.0.1:3000/projects/1/text-classification?page=1 and the console of the Python server shows the following:
```
[02/Feb/2021 19:57:40] "GET /v1/projects/1/labels HTTP/1.1" 200 433
[02/Feb/2021 19:57:40] "GET /v1/projects/1/docs?limit=10&offset=0&q=&doc_annotations__isnull= HTTP/1.1" 200 879
```

**Comment by Hironsan** [comment]
The following workflow will be useful for you. It publishes doccano as a Python package.
https://github.com/doccano/doccano/blob/master/.github/workflows/pypi-publish.yml

If you want to `pip install`, you need to build the frontend and move the result to `app/client/`

**Comment by johann-petrak** [comment]
Thank you for that. I start completely fresh (new cloned repo) on Ubuntu 18.04 using a fresh conda environment with Python 3.8.5 and carried out these commands
```
cd doccano
mkdir app/client
nvm install 8.1
nvm use 8.1
npm install --global yarn
yarn install
yarn build
```
This gave me the error 
```
yarn run v1.22.10
error Command "build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I also tried to use node version 12.1 instead of 8.1 but with that the `yarn install` command gives me this error message:
```
error @: The engine "node" is incompatible with this module. Expected version "8.x". Got "12.1.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by johann-petrak** [comment]
So far for me the steps above seem to do everything I need. 
Maybe put them into the docs somewhere for others or put them into a file to be run if needed?
Otherwise and if nobody finds a flaw in those steps I think this issue can be closed.
