### ISSUE TITLE
RROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by magic202009** [doccano/doccano#1194]
pip3 install -r requirements.txt                                   1 ⨯
Collecting Scrapy==1.1.0rc3
  Using cached Scrapy-1.1.0rc3-py2.py3-none-any.whl (292 kB)
Collecting pybloom==1.1
  Using cached pybloom-1.1.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dwvhygh4/pybloom/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dwvhygh4/pybloom/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ml4o2gdc                                        
         cwd: /tmp/pip-install-dwvhygh4/pybloom/                           
    Complete output (8 lines):                                             
    Traceback (most recent call last):                                     
      File "<string>", line 1, in <module>                                 
      File "/tmp/pip-install-dwvhygh4/pybloom/setup.py", line 2, in <module>                                                                          
        from ez_setup import use_setuptools                                
      File "/tmp/pip-install-dwvhygh4/pybloom/ez_setup.py", line 98        
        except pkg_resources.VersionConflict, e:                           
                                            ^                              
    SyntaxError: invalid syntax                                            
    ----------------------------------------                               
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 

Your Environment
---------

*   Operating System: kali linux
*   Python Version Used: Python 3.9.1+

**Comment by Hironsan** [comment]
It seems to me that this is not related to doccano.
