### ISSUE TITLE
python: can't open file '/src/app/manage.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yangxueping** [doccano/doccano#1199]
I ran docker-compose.prod.yml according to the official tutorial and reported the following error：

> CN-MAC-458-1909:doccano klook$ docker-compose -f docker-compose.prod.yml up 
> Creating network "doccano_network-backend" with the default driver 
> Creating network "doccano_network-frontend" with the default driver 
> Creating doccano_postgres_1 ... done
> Creating doccano_backend_1  ... done
> Creating doccano_nginx_1    ... done
> Attaching to doccano_postgres_1, doccano_backend_1, doccano_nginx_1
> postgres_1  | 
> postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
> postgres_1  | 
> postgres_1  | 2021-02-09 10:47:01.145 UTC [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
> postgres_1  | 2021-02-09 10:47:01.146 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> postgres_1  | 2021-02-09 10:47:01.146 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> postgres_1  | 2021-02-09 10:47:01.151 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> postgres_1  | 2021-02-09 10:47:01.156 UTC [20] LOG:  database system was shut down at 2021-02-09 10:46:39 UTC
> postgres_1  | 2021-02-09 10:47:01.164 UTC [1] LOG:  database system is ready to accept connections
> backend_1   | No virtualenv has been created for this project(/src) yet!
> backend_1   | Aborted!
> backend_1   | Creating a virtualenv for this project...
> backend_1   | Pipfile: /src/Pipfile
> backend_1   | Using /usr/local/bin/python3 (3.8.6) to create virtualenv...
> ⠧ Creating virtual environment...created virtual environment CPython3.8.6.final.0-64 in 521ms
> backend_1   |   creator CPython3Posix(dest=/root/.local/share/virtualenvs/src-NVTF7jWz, clear=False, no_vcs_ignore=False, global=False)
> backend_1   |   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
> backend_1   |     added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
> backend_1   |   activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
> backend_1   | 
> backend_1   |✔ Successfully created virtual environment! 
> backend_1   | Virtualenv location: /root/.local/share/virtualenvs/src-NVTF7jWz
> backend_1   | Creating a Pipfile for this project...
> backend_1   | Installing dependencies from Pipfile...
> backend_1   | To activate this project's virtualenv, run pipenv shell.
> backend_1   | Alternatively, run a command inside the virtualenv with pipenv run.
> backend_1   | Initializing database
> backend_1   | python: can't open file '/src/app/manage.py': [Errno 2] No such file or directory
> doccano_backend_1 exited with code 2

Environment:
on MackBook

The code downloaded  today, by:
`git clone https://github.com/doccano/doccano.git`

The above is the error reported by running docker-compose.prod.yml, but I tried to run docker-compose.dev.yml without any problems！！！

How can i solve it？thanks

**Comment by yangxueping** [comment]
I followed the **Docker Compose** tutorial under [https://github.com/doccano/doccano](https://github.com/doccano/doccano)

**Comment by snailkn** [comment]
same issue

**Comment by Hironsan** [comment]
In my guess, you run `docker-compose -f docker-compose.dev.yaml up` before `docker-compose -f docker-compose.prod.yaml up`. It causes the problem.

Once you run the `docker-compose.dev.yaml`, run `docker-compose -f docker-compose.dev.yaml down` before `docker-compose -f docker-compose.prod up`. We need build and up.
