### ISSUE TITLE
ALLOW_SIGNUP env issue. Register not operational

### ISSUE THREAD

**Issue by hakan280** [doccano/doccano#1200]
ALLOW_SIGNUP default value is true, I also set related env value explicitly true but still I can not see any signup page/button or anything else.

<img width="715" alt="Screen Shot 2021-02-09 at 14 30 50" src="https://user-images.githubusercontent.com/4259575/107357874-b44d0900-6ae3-11eb-86bf-be1c80f2a0c8.png">

**Comment by icoxfog417** [comment]
@hakan280 Could you please tell us your setup instruction of doccano?

* Operating System:
* Python Version Used:
* When you install doccano:
* How did you install doccano (Heroku button etc):
* Environmental variable you set: 
* How did you set Eevironmental variable:
