### ISSUE TITLE
admin area shows 404, no login

### ISSUE THREAD

**Issue by tgruenert** [doccano/doccano#1205]
How to reproduce the behaviour
---------
* start docker container as described in [documentation](https://doccano.github.io/doccano/getting-started/)
* open http://localhost:8000/admin as described in [FAQ](https://doccano.github.io/doccano/faq/)
* you get 404 page

Your Environment
---------
docker from dockerhub
doccano app version v1.1.1

Work around
----------
* open http://localhost:8000/admin/login/
* you can login and get redirect to admin area

**Comment by abneetwats24** [comment]
Admin is working on http://localhost:8000/admin/, not on http://localhost:8000/admin 
see #1186

**Comment by tgruenert** [comment]
checked this. you are right @abneetwats24 . thank you!
