### ISSUE TITLE
[Proposal / Feature Req] Zero Shot Labelling

### ISSUE THREAD

**Issue by rakesh4real** [doccano/doccano#1207]
Hey!

I am planning to integrate zero-shot entity recognition to help automating labelling process to some margin. Is there any implementation under progress so that I don't have to build from scratch

cheers!
Rakesh

**Comment by Hironsan** [comment]
I have no idea about zero-shot labeling, but I think it's possible to label text automatically by using [auto-labeling](https://github.com/doccano/doccano/pull/1206).
