### ISSUE TITLE
Is there a possibility to remove the limit of 30 characters for text labels?

### ISSUE THREAD

**Issue by merionum** [doccano/doccano#1210]
Doccano doesn't allow to have labels of length >= 30. Can it be removed or changed somehow? I tried to change the rule in frontend/rules/index.js

```javascript
export const labelNameRules = (msg) => {
  return [
    v => !!v || msg.labelRequired,
    v => (v && v.length <= 30) || msg.labelLessThan30Chars
  ]
}

```
It didn't affect anything though

**Comment by Hironsan** [comment]
The length of the label name is restricted by

https://github.com/doccano/doccano/blob/02f0c08892d47687c291e9e6abb1dbc043e2b09f/frontend/components/label/FormCreate.vue#L85
