### ISSUE TITLE
Uploading txt file in Heroku app does not work

### ISSUE THREAD

**Issue by DB-Python** [doccano/doccano#1211]
How to reproduce the behaviour
---------
I am starting with an NLP project on case law and want to use doccanos for annotation. I am using doccanos with the heroku app and trying to upload txt files (UTF-8) of case law (11 kB). The text is in one line and contains 1643 words. Doccanos gives the following error: "The file could not be uploaded. Maybe invalid format. Please check available formats carefully.". I've tried multiple times, also with less text, and sometimes it works, but most of the time not. How to resolve this?

For clarity sake, I added the text file I wanted to upload to doccanos for annotation.

[Test file.txt](https://github.com/doccano/doccano/files/6009858/Test.file.txt)

Your Environment
---------

*   Operating System: 
*   Python Version Used: 
*   When you install doccano: January 22, 2021
*   How did you install doccano (Heroku button etc): Heroku

**Comment by Hironsan** [comment]
When I removed the additional new line, I can successfully upload the file.
