### ISSUE TITLE
There is no requirements.txt in the downloaded file 

### ISSUE THREAD

**Issue by uRENu** [doccano/doccano#1214]
How to reproduce the problem
---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by uRENu** [comment]
pip install -r requirements.txt
ERROR:could not open requirements file: [error2] no such file or directory:'requirements.txt'

**Comment by SwiftPredator** [comment]
@uRENu I dont know why you want to install the dependencies manually but as far as I know you have to use pipenv if you want to install the dependencies manually. As you can see the projects uses a pipfile.

Try to install pipenv and run:

`pipenv install`

inside the doccano directory.
