### ISSUE TITLE
You do not have permission to perform auto labeling.Please ask the project administrators to add you.

### ISSUE THREAD

**Issue by greathour** [doccano/doccano#1218]
OS:Centos7.6
doccano version:1.2.1
docker-compose install 
git clone https://github.com/doccano/doccano.git
cd doccano
docker-compose -f docker-compose.prod.yml up
click auto-labeling in setting  with admin ,show this:

![image](https://user-images.githubusercontent.com/38709366/109244547-da7be400-7819-11eb-8aab-e8292ef840b6.png)

with annotator,show this:
![image](https://user-images.githubusercontent.com/38709366/109245298-27ac8580-781b-11eb-8a75-e0b25501c98a.png)

**Comment by dotafreshman** [comment]
I also have the same problem

**Comment by sloth2012** [comment]
same

**Comment by Hironsan** [comment]
Please write the procedure and your environment to reproduce the problem.
