### ISSUE TITLE
Admin panel : CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by flavienbwk** [doccano/doccano#1220]
How to reproduce the behaviour
---------

Hi,

I've run the following command : 

```
git checkout v1.2.1
docker-compose -f docker-compose.prod.yml up
```

Everything seem smooth and running but I get the following error on `/admin` when logging in : 

![image](https://user-images.githubusercontent.com/14158127/109241108-0dea4e80-77d9-11eb-9f9a-7b94088538cf.png)

What is the problem and how to fix it ?

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Doccano version : Docker / v1.2.1

Thanks

**Comment by chameleonTK** [comment]
It seems that it has a CSRF conflict between admin site and client site so you need to logout before using another site.

**Comment by flavienbwk** [comment]
I were both logged out and removed cookies.
