### ISSUE TITLE
Active Directory login with the one click deployment 

### ISSUE THREAD

**Issue by f-nicolai** [doccano/doccano#1226]
Hi,

I'm deploying Doccano via the one click deployment on Azure for my organisation but I'd like to connect it to Active Directory.
I know this [PR 75](https://github.com/doccano/doccano/pull/75) added it but I can't figure how making it work.
Is it compatible with the one click deployment or do I have to do it manually by pulling the project and building a customized Docker image with some environmentvariables ?

**Comment by nlorenzen1** [comment]
I too am trying to figure out the 1 click deployment to azure with Azure AD. If it can't be 1-click is there a series of steps we could follow to define the environment vars for Azure AD and deploy the container?

**Comment by f-nicolai** [comment]
Correct me if I'm wrong but it seems that login from a thrid party is no longer supported.
It's still referenced within the code on the backend part  in app/app/settings.py, but it doesn't seem to be referenced by anything within the front end code, thus even if you setup the environment variables you won't be able to see the button to log in with AD.

The only solution I found was to use an old Docker image : chakkiworks/doccano:v1.0.0 (roughtly 2 years old)
