### ISSUE TITLE
how to setup doccano with sqlite persistence?

### ISSUE THREAD

**Issue by vanangamudi** [doccano/doccano#1229]
How to reproduce the behaviour
---------
I just pip installed doccano and started running to test it out. but the imported samples and projects disappear when I restart doccano. I understand that there needs to be a database setup for persistence. where can I find the config to do that. 

I do not have any experience setting up postgres database. 

Thanks in advance.

*   Operating System: Ubuntu 20.04
*   Python Version Used: 3.6
*   When you install doccano: 
*   How did you install doccano (Heroku button etc): pip install doccano

**Comment by Hironsan** [comment]
doccano provides SQLite persistence. Once you start the doccano, it set up the SQLite DB as `doccano.db`.

```bash
> doccano
...
KeyboardInterrupt
> ls
doccano.db
```
