### ISSUE TITLE
[Bug report] Django admin is unavailable on pip installation

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#1245]
How to reproduce the behaviour
---------
`http://site.com/admin` is 404  error'd on pip installation.

Your Environment
---------

*   Operating System: CentOS 8.3
*   Python Version Used: 3.8.8
*   When you install doccano: v1.2.1
*   How did you install doccano (Heroku button etc): pip

**Comment by Hironsan** [comment]
Did you try to access `/admin/`?
Or you want to say we should be able to redirect `/admin` to `/admin/`?

**Comment by kuraga** [comment]
Ahaha, really, works! Haven't noticed for 1.5 years.
Ok, 'll reopen as a feature request.
