### ISSUE TITLE
Click annotation comment will get an error

### ISSUE THREAD

**Issue by xhw205** [doccano/doccano#1246]
![image](https://user-images.githubusercontent.com/32640956/110765974-a8de3080-828f-11eb-8500-7fca2b1b9ca6.png)

---------

*   Operating System: win10
*   Python Version Used:3.6
*   When you install doccano: 2021/2/26
*   How did you install doccano (Heroku button etc): source code

**Comment by Hironsan** [comment]
Maybe fixed in v1.2.2.
