### ISSUE TITLE
Text field missing / Costum Rest Api for Auto-Labelling

### ISSUE THREAD

**Issue by lrwagner** [doccano/doccano#1248]
How to reproduce the behaviour
---------
When sending (Testing) the Post request inside the creation of a costum rest api service for auto-labelling the request payload (which goes to doccano/django) looks like this:
```
{
  "id": 99999,
  "model_name": "CustomRESTRequestModel",
  "model_attrs": {
    "url": "http://0.0.0.0:5001/process-single/",
    "method": "POST",
    "params": {},
    "headers": {},
    "body": { "model": "models/model-best" }
  },
  "template": "",
  "label_mapping": {},
  "text": "Example Text"
}
```
My Problem/Question
---
I suppose this is the request which is being send to Django to create a model instance which is used to communicate with my costum rest api.
Somehow, when calling my api using doccano, the received json does only inlcude `{ "model": "models/model-best" }`. Shouldn't `"text": "Example Text"` also be in there? What am I missing?

*   Operating System: Ubuntu
*   Python Version Used: 3.8
*   How did you install doccano (Heroku button etc): Docker

**Comment by jreypy** [comment]
I am doing my first steps with doccano, I would like to use auto-labeling too, but when I create a record.

My curl body is like this

    {"id":99999,"model_name":"**Custom REST Request"**,"model_attrs":{"url":"http://0.0.0.0:5001/process- 
   single/","method":"POST","params":{},"headers":{},"body":{"model":"models/model- 
    best"}},"template":"","label_mapping":{},"text":"Example Test"}

I compare my json body and my model_name is  REST Request and your json body is CustomRESTRequestModel, I have this error in my server 


raise NameError(f'{model_name} is not found.')
NameError: Custom REST Request is not found.

what is wrong with my auto labeling register ?

I move to the previous version and still I have the same error, I dont know if I forget a step.

**Comment by pranavpawar3** [comment]
@jreypy Hi, I am facing the same issue, i.e. NameError. Have you found any solution to this?

Thanks

**Comment by jreypy** [comment]
Hi @pranavpawar3 , I really need my document auto labeled after the import and when the document has been checked... then My solution is create a Proxy (NINGX) and catch 2 requests (import and approve-labels) and overwrite services (another application) to import with labels and get all labels from the documents.

**Comment by gika815** [comment]
sulution https://github.com/doccano/doccano/issues/1307#issuecomment-824738905
