### ISSUE TITLE
Cannot build nginx container using docker-compose (v1.2.2)

### ISSUE THREAD

**Issue by neurotroph** [doccano/doccano#1254]
How to reproduce the behaviour
---------
When trying to build the nginx container using `docker-compose -f docker-compose.prod.yml build nginx` the installation fails without any verbose error message (only last section pasted here):

```
...

[4/4] Building fresh packages...
Done in 166.92s.
yarn run v1.21.1
$ nuxt build
ℹ Production build
ℹ Bundling only for client side
ℹ Target: static
✔ Builder initialized
✔ Nuxt files generated

 WARN  Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

ℹ Compiling Client

 ERROR  (node:246) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGKILL".
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c apk add -U --no-cache git python3 make g++   && yarn install   && yarn build   && apk del --no-cache git make g++' returned a non-zero code: 1
```

Might be related to #1213 , but changing the nginx Dockerfile to use the `node:15.9-alpine3.13` has the same result.

Your Environment
---------

*   Operating System: Ubuntu 20.04, Docker 19.03
*   Python Version Used: --
*   When you install doccano: v1.2.2
*   How did you install doccano (Heroku button etc): git clone, cd doccano, docker-compose -f docker-compose.prod.yml up

**Comment by Hironsan** [comment]
Hmm, what is the cause? I tried the following environment and it succeeded.

- Ubuntu 20.04
- Docker 20.10.5
- Docker Compose 1.28.5

and

- macOS mojave 10.14.1
- Docker 19.03.13
- Docker Compose 1.27.4

```
[4/4] Building fresh packages...
Done in 54.84s.
yarn run v1.21.1
$ nuxt build
ℹ Production build
ℹ Bundling only for client side
ℹ Target: static
✔ Builder initialized
✔ Nuxt files generated

 WARN  Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

ℹ Compiling Client

 ERROR  (node:251) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time

✔ Client: Compiled successfully in 1.17m
```

**Comment by neurotroph** [comment]
Sorry for the late follow-up: The problem turned out to be a memory issue. After resizing the machine to have at least 8 GB RAM, building went fine. Error message just wasn't informative enough, so it was more trial and error until it turned out to be the memory.
