### ISSUE TITLE
Okta OIDC social login is not available

### ISSUE THREAD

**Issue by yoshiya8** [doccano/doccano#1255]
# Problem

The [documentation for activating Okta OIDC social authentication](https://doccano.github.io/doccano/advanced/oauth2_settings/#openidconnect) indicates that when I set the three following environment variables, the login screen will have an option to authenticate using Okta OIDC:
1. `OAUTH_OKTA_OPENIDCONNECT_KEY`
2. `OAUTH_OKTA_OPENIDCONNECT_SECRET`
3. `OAUTH_OKTA_OPENIDCONNECT_API_URL`

This is not happening.

# How to reproduce the behaviour
1. Run `doccano:1.2.1` image with the following command:
```bash
docker run --rm --interactive --tty
    --env SECRET_KEY=REDACTED \
    --env ADMIN_EMAIL=noreply@example.com \
    --env ADMIN_PASSWORD=REDACTED \
    --env ADMIN_USERNAME=admin \
    --env OAUTH_OKTA_OPENIDCONNECT_KEY=REDACTED \
    --env OAUTH_OKTA_OPENIDCONNECT_SECRET=REDACTED \
    --env OAUTH_OKTA_OPENIDCONNECT_API_URL=https://my-identity.okta.com/api \
    --publish 8000:8000 \
    doccano/doccano:1.2.1
```
2. Navigate to `doccano` in your browser at: http://locahost:8000
3. Select the "login" button at the top-right of the page

# Expected behavior
I expect to see the "Login with Okta" option as depicted in [this image](https://doccano.github.io/doccano/images/oauth/okta_oauth_login_page.png)

# Actual behavior
I end up seeing the same login screen/options that I get when I do not configure Okta OIDC social authentication.

# My environment
* I am running the `doccano/doccano:1.2.1` Docker image
* I am running behind a enterprise firewall with a SSL packet inspection and enterprise certificate authority. Other applications can perform Okta OIDC SSO in this environment, but app eventually needs to recognize system installed trusted CA chain. I do not expect this to be the source of this problem _before we actually submit login credentials_, however - there is a possibility.
* `docker-desktop` v20.10.5 on Windows 10
* Above command issued from WSL version 1, running WSL (version 1 with Ubuntu 18.04 LTS) bash:
```bash
$ uname -a
Linux MY-PC 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yoshiya8** [comment]
@setu4993 - am I missing something obvious, or is this a bug?
Thanks

**Comment by setu4993** [comment]
@yoshiya8 : Thanks for flagging. I don't think this is a problem at your end, I can reproduce it.

The backend correctly identifies and sets flags for the Okta / other social auth, but unfortunately, it cannot be used with the current version of the Doccano frontend.

What I had built was an integration with the previously used Doccano frontend (that is still under `app/server`). I can see that since https://github.com/doccano/doccano/commit/362df6373af833bb16ee02a4708db5a811f03d5c the frontend is being pointed to the new Nuxt.JS frontend. That version doesn't appear to have the ability to use the social auth and doesn't thus have all of the features that the old UI did. I am not familiar with Nuxt / Vue enough to be able to contribute the changes that'd be required, but if someone can point me to the file(s) that'd need to be touched, I'm happy to take a stab (cc @Hironsan, @icoxfog417).

Additionally, a workaround right now might be to build the Docker container from source, while checking out to an older commit. I tried building the container for 6e76b9586b9c95f27e9432a456f4213d2febef53 and got it to work. (One other change is required in `requirements.txt` there for it to build and run successfully: pin the max version of `pyjwt` as `pyjwt>=1.7.1,<2.0`).

**Comment by setu4993** [comment]
The best I can tell, we need to port the login contained in lines 59-85 from [here](https://github.com/doccano/doccano/blob/ea0590ad0bb32d2c91f9f27afd154829e13dcac4/app/server/templates/login.html#L59) to [here](https://github.com/doccano/doccano/blob/master/frontend/components/auth/FormLogin.vue).

**Comment by ljades** [comment]
+1 to this. Would love to be able to use OIDC on the new login.

The project since that older commit has a lot of improvements that I'd rather keep, and I'm also not familiar enough with Nuxt / Vue. If I have the bandwidth maybe I'll try to work on it in the future if it's not resolved by then.

**Comment by ljades** [comment]
Other important information for whoever works on this: while debugging it a bit myself, I noticed the templates in the Django app settings will also need modification: https://github.com/doccano/doccano/blob/master/app/app/settings.py#L90

Right now, it still redirects to old templates that require webpack installation and building.

**Comment by Vydruth** [comment]
+1, I'm facing this issue as well when trying to configure `OAuth Okta OpenID Connect`. 

@ljades 
> Other important information for whoever works on this: while debugging it a bit myself, I noticed the templates in the Django app settings will also need modification: https://github.com/doccano/doccano/blob/master/app/app/settings.py#L90
> Right now, it still redirects to old templates that require webpack installation and building.

I am guessing the issue this can be resolved by just changing [this line](https://github.com/doccano/doccano/blob/master/app/app/settings.py#L93) to: 

`'DIRS': [path.join(BASE_DIR, '../../frontend/dist')],`

Not sure if there are additional places that will get affected by this change. 🤷

**Comment by sunyinge** [comment]
Same here. I am also not to configure OIDC with Okta with v1.0.0 or v1.3.1 can someone help with that? Appreciate that!!

**Comment by Vydruth** [comment]
Hi @setu4993, I am having some trouble getting login with Okta working with version 1.0.0 or even with the version where you made the change and merged to master (commit message `Batch user save calls`).  I followed the process outlined in this [document](https://doccano.github.io/doccano/advanced/oauth2_settings/) step by step but it did not seem to work. I might be missing something but I am not sure what it is.

Could you point me to a version of the project or commit where login with Okta is working for you (even if it is the old UI)? Appreciate your help in this regard.

Error details:
I am able to see the `Login with Okta` button when on the Old UI, when I click on it, I am being redirected to Okta once I enter my username and password correctly it gives me the following page:

<img width="1680" alt="LogInWithOkta Failure" src="https://user-images.githubusercontent.com/10277192/116837201-3f3b1e00-ab7e-11eb-8668-faffe4f642e2.png">


Error stack trace
```
Environment:

Request Method: GET
Request URL: http://{doccano-url}/social/complete/okta-openidconnect/?code=xxxxxxxxxxxx&state=xxxxxxxxxxxxxxxxxxx

Django Version: 2.1.11
Python Version: 3.6.13

Installed Applications:
['whitenoise.runserver_nostatic',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'server.apps.ServerConfig',
 'api.apps.ApiConfig',
 'widget_tweaks',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'social_django',
 'polymorphic',
 'webpack_loader',
 'corsheaders',
 'drf_yasg']

Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'applicationinsights.django.ApplicationInsightsMiddleware',
 'corsheaders.middleware.CorsMiddleware')
Traceback:
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  124.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/social_django/utils.py" in wrapper
  49.             return func(request, backend, *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/social_django/views.py" in complete
  33.                        *args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/social_core/actions.py" in do_complete
  73.                                          social_user.provider)
  
Exception Type: AttributeError at /social/complete/okta-openidconnect/
Exception Value: 'NoneType' object has no attribute 'provider'

```

I did do some research `'NoneType' object has no attribute 'provider'` and found that it could be the order of calls in the [settings.py#SOCIAL_AUTH_PIPELINE](https://github.com/doccano/doccano/blob/v1.0.5/app/app/settings.py#L176-L190). I am not very familiar with Django and social auth to be honest, so not sure what the right order is, it seemed correct to me when I looked at the documentation. Any suggestions?

PS: I would rather prefer someone getting the login with okta working on the latest Doccano code version. But its painful as it is not working in the older version as well. :(

**Comment by Vydruth** [comment]
Trying to tag/reach @setu4993 again (as he contributed the initial version of code) to see if he has seen this issue before/knows how to fix it.

**Comment by setu4993** [comment]
@Vydruth : Hey, sorry,  I haven't had a lot of time to look at this over the last few days. The last version that works for me (and I have set up for) is 6d5bff4bd03c63babe2c7164579d77ff4f0597d1.

I haven't seen that error before, but from the truncated traceback my guess is it's likely a configuration / permissions issue. Happy to help you through this if you can share a more detailed traceback.

I'd recommend reaching out over email (see my GitHub profile) to avoid the issue going off-topic.

**Comment by setu4993** [comment]
Just an update. The below process works for me in case someone wants to use Okta OAuth with the old UI once you have cloned the repo (I just validated it):
1. `git clone https://github.com/doccano/doccano.git`
2. `cd doccano`
2. `git checkout 6e76b9586b9c95f27e9432a456f4213d2febef53`
3. Update [line 33 in the requirements.txt at the root of the repo](https://github.com/doccano/doccano/blob/6e76b9586b9c95f27e9432a456f4213d2febef53/requirements.txt#L33) from to: `pyjwt>=1.7.1,<2.0`
4. `docker build -t doccano-local .`
5. Depending on if you have OAuth2 or OIDC:
OAuth2:
```shell
docker run --interactive --tty \
    --env "SECRET_KEY=<SECRET_KEY" \
    --env "ADMIN_EMAIL=noreply@example.com" \
    --env "ADMIN_PASSWORD=password" \
    --env "ADMIN_USERNAME=admin" \
    --env "OAUTH_OKTA_OAUTH2_KEY=<OAUTH_KEY>" \
    --env "OAUTH_OKTA_OAUTH2_SECRET=<OAUTH_SECRET>" \
    --env "OAUTH_OKTA_OAUTH2_API_URL=<OAUTH_URL>" \
    --publish 8000:8000 \
    doccano-local
```

OIDC:
```shell
docker run --interactive --tty \
    --env "SECRET_KEY=<SECRET_KEY>" \
    --env "ADMIN_EMAIL=noreply@example.com" \
    --env "ADMIN_PASSWORD=password" \
    --env "ADMIN_USERNAME=admin" \
    --env "OAUTH_OKTA_OPENIDCONNECT_KEY=<OAUTH_KEY> \
    --env "OAUTH_OKTA_OPENIDCONNECT_SECRET=<OAUTH_SECRET>" \
    --env "OAUTH_OKTA_OPENIDCONNECT_API_URL=<OAUTH_URL>" \
    --publish 8000:8000 \
    doccano-local
```

Of course, this is not to say that the new UI should not support OAuth (it should!), but a detailed workaround for those that need it right now and are fine with the old UI.

**Comment by temal-** [comment]
Thanks for your work on this!

I think it is more or less obvious, but just to mention it: The “Login with Active Directory” button is also missing. Our workaround is to use the endpoint `/social/login/azuread-tenant-oauth2/` directly. I don’t know if this will work for Octa or Google though.

Related: https://github.com/doccano/doccano/issues/989

**Comment by dnssh** [comment]
Hi @setu4993,
I followed the exact steps you mentioned above, but was still unable to get the okta openid connect working for the older version as mentioned.
The okta signin button redirects to a 404 page displaying following

`{"errorCode":"E0000022","errorSummary":"The endpoint does not support the provided HTTP method","errorLink":"E0000022","errorId":"oaeWFArFw3gRLuzWlbrEStC0w","errorCauses":[]}`

Just wanted to ask if you have ever run into this issue before.
Thanks!

**Comment by setu4993** [comment]
Hi @dnssh, I'm not sure. I haven't seen that one before. Looking at the message in the error, it does appear to be a configuration issue, but can't say for sure.

**Comment by dnssh** [comment]
Hi @setu4993,
No worries I was able to resolve the issue by adding the missing scope -'groups' in the okta admin dashboard

1. In the Admin Console, go to Security > API.
2. On the Authorization Servers tab, select the name of the Authorization Server, and then select Scopes.
3. Select Scopes and then Add Scope.
4. Enter a Name, Display phrase, and Description
<img width="1045" alt="Screen Shot 2021-06-20 at 12 59 47 PM" src="https://user-images.githubusercontent.com/16509414/122857843-05f57380-d2ce-11eb-8033-bdc6cfcf8e96.png">

**Comment by setu4993** [comment]
@Hironsan : Not seeing an existing commit / PR that implements this... Was the point of closing this to indicate that this is unlikely to be ported over to the new version?

**Comment by setu4993** [comment]
I tried pulling from the latest image on Docker Hub, but that doesn't support OAuth.

**Comment by elvisphilipn** [comment]
@setu4993 @Hironsan I too can't get OAuth to work with doccano:latest, from Docker Hub

**Comment by danquack** [comment]
Please reopen this issue.

Tried running this with latest....
```
docker run --interactive --tty \
    --env "ADMIN_EMAIL=noreply@example.com" \
    --env "ADMIN_PASSWORD=password" \
    --env "ADMIN_USERNAME=admin" \
    --env "OAUTH_OKTA_OPENIDCONNECT_KEY=redacted" \
    --env "OAUTH_OKTA_OPENIDCONNECT_SECRET=redacted" \
    --env "OAUTH_OKTA_OPENIDCONNECT_API_URL=x.okta.com" \
    --publish 8000:8000 \
    doccano/doccano
 ```

When speaking directly to the backend I get a 500 server error, when speaking to the frontend I get a 404 at `social/complete/okta-openidconnect/ `

**Comment by lhr0909** [comment]
Our team has put together a PR that adds Okta Login to Doccano (#2079). Currently the login button is hard-coded due to the fact that the Django system and Nuxt.js frontend are separated. But it is working fine on our end so we would like to work with the contributors to get this merged if it helps other people.

This should also help with other social logins as well.

Cheers!
