### ISSUE TITLE
export data as jsonl ,but the result is json.

### ISSUE THREAD

**Issue by 13360806188** [doccano/doccano#1257]
in the datasets,I export data,when I choose jsonl and export ,the result is still json.I find the request url is 
v1/projects/2/docs/download?q=json&onlyApproved=false

not 
v1/projects/2/docs/download?q=jsonl&onlyApproved=false

**Comment by abneetwats24** [comment]
Any fix for this?

**Comment by abneetwats24** [comment]
Workaround 
using curl or postman, you can use following curl request for token 
```
curl --location --request POST 'http://172.16.10.6/v1/auth-token' \
--header 'Content-Type: application/json' \
--data-raw '{"username":"admin","password":"Admin123$"}'
```
then use this to get the jsonl response
```
curl --location --request GET 'http://172.16.10.6/v1/projects/1/docs/download?q=jsonl&onlyApproved=false' \
--header 'Authorization: Token <token from above api>' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json'
```
to download response in file use:
```
curl  -O data.jsonl --location --request GET 'http://172.16.10.6/v1/projects/1/docs/download?q=jsonl&onlyApproved=false' \
--header 'Authorization: Token <token from above api>' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json'
```

**Comment by 13360806188** [comment]
thanks.But it is a bug.I think it must be changed in the code .

**Comment by abneetwats24** [comment]
Yes, it should be fixed.

**Comment by MateusMarcuzzo** [comment]
thanks @abneetwats24, that may be a temporary solution for now.

I also need the fix
