### ISSUE TITLE
[Bug report] Shortcut keys not working for text classification

### ISSUE THREAD

**Issue by perjonasam** [doccano/doccano#1258]
First of all, thanks for a great product!

I can't get the shortcut keys for project type DocumentClassification to work. It works fine however for a SequenceLabeling project. I've tried several sets of numbers and letters, marking different things in UI -- no response. From what I can tell, there are no console messages (Chrome). I've tried multiple browsers (listed below), and a colleague has reproduced the problem on a different OS (listed below).

To reproduce the problem
--------------------------
Create a standard DocumentClassification project, upload a minimal dataset, create two arbitrary labels with shortcuts. Start annotation and watch the shortcuts fail.

Environment
------------
The following combinations have been tested:
*    macOS Catalina (10.15.7) + Chrome (89.0.4389.90)
*    macOS Catalina (10.15.7) + Firefox (86.0.1 (64-bit))
*    macOS Catalina (10.15.7) + Safari (14.0)
*    Ubuntu 18.04 + Firefox (86.0 (64-bit))

- Python Version Used: 3.8.6 (container), 3.8.2 (macOS)
- When you install doccano: current master: 979f8720444bf8a933d2450e60874bd15aafd4b0 (v1.2.2)
- How did you install doccano (Heroku button etc): docker-compose (README.md instructions)
- Using dev container

**Comment by Hironsan** [comment]
Hello

This is due to the recent PR https://github.com/doccano/doccano/pull/1251.
It seems to me that I accidentally removed `v-shortkey` from text classification component.

**Comment by perjonasam** [comment]
Thanks @Hironsan for super quick bug fix.
