### ISSUE TITLE
Cannot import labels

### ISSUE THREAD

**Issue by gailmargolis76** [doccano/doccano#1259]
Could not import labels in json format. When I select the json file, doccano keeps insisting that 'File is required', even though a file has clearly been selected. Tried all sorts of things in changing the json format, nothing worked. I then tried an experiment: I created labels manually in doccano then exported them. Then tried to re-import them. Did not work. Doccano literally cannot import the SAME labels it exported!!! I even tried copying the example json format given in the upload panel into a file, and importing that. Still didn't work. Why put an "import label" function when it clearly doesn't work? Would also be nice if it gave some useful errors, rather than just insisting that "File is Required" when you've clearly loaded a file.

**Comment by cakiki** [comment]
I'm not sure what version you're running, but the one I'm running requires JSONL, i.e. JSON Lines and that seems to work for me.

**Comment by Hironsan** [comment]
@gailmargolis76 You should follow the ISSUE Template. We can't understand your situation.

I can upload the file successfully.

![](https://i.gyazo.com/b461ee14d0fef0b529dce357fd85054a.gif)

```bash
[
  {
    "id": 109,
    "text": "Dog",
    "prefix_key": null,
    "suffix_key": "0",
    "background_color": "#2196F3",
    "text_color": "#ffffff"
  },
  {
    "id": 110,
    "text": "Shepherd",
    "prefix_key": null,
    "suffix_key": "1",
    "background_color": "#3F51B5",
    "text_color": "#ffffff"
  },
  {
    "id": 111,
    "text": "aasdf",
    "prefix_key": null,
    "suffix_key": "2",
    "background_color": "#FFEB3B",
    "text_color": "#ffffff"
  },
  {
    "id": 112,
    "text": "sdaf",
    "prefix_key": null,
    "suffix_key": "3",
    "background_color": "#F44336",
    "text_color": "#ffffff"
  }
]
```
