### ISSUE TITLE
使用pip安装doccano后，如何修改前端？

### ISSUE THREAD

**Issue by zxbzxb180** [doccano/doccano#1264]
您好，我想请问一下，使用pip安装doccano后，如何修改前端？
---------

Your Environment
---------
*   Python Version Used:python3.8
*   When you install doccano:2021-03-23
*   How did you install doccano (Heroku button etc):pip install doccano

**Comment by Hironsan** [comment]
If you want to change the frontend, I recommend you should use `docker-compose.dev.yaml`.
