### ISSUE TITLE
Auto Labeling how to Write a mapping template to extract labels from API responses

### ISSUE THREAD

**Issue by GuilongZh** [doccano/doccano#1281]
doccano Auto Labeling how to Write a mapping template to extract labels from API responses
![image](https://user-images.githubusercontent.com/24869034/113107320-5d87c400-9236-11eb-86b3-28fcd69ac0fd.png)

who can give a demo, how to use jinja write a mapping template, it's hard!

**Comment by armsp** [comment]
This is not very well documented. I think it would be great if we can get more information on how to go about doing this...also when the API response is exactly the way doccano expects then how to use the mapping? https://github.com/doccano/doccano/issues/1417
