### ISSUE TITLE
Dataset export only exports numbers and not named text.

### ISSUE THREAD

**Issue by natescrape** [doccano/doccano#1286]
When i export my labelled dataset, the output only contains numbers and not the text names of the labels. I have used both export options and the outputs are the same. I have tried on mac and PC - the same. I have installed fresh and up-to-date and still the same issue. What am i missing here? I have seen this was a previous issue, but no answer apart from this has been solved. I am using windows 10 and python 3.9.0

thanks

**Comment by AshutoshUpadhya** [comment]
Facing same issue on Windows10

**Comment by LisaBanana** [comment]
Hi, I have the same issue with label extraction (detailed here : #1267 ).
This issue is also encountered by other users : https://github.com/doccano/doccano/issues/1291 & https://github.com/doccano/doccano/issues/1288
