### ISSUE TITLE
Export format jsonl (text label) dosen't work.

### ISSUE THREAD

**Issue by walsripe** [doccano/doccano#1291]
Hello,

Recently, I deployed the Doccano on Microsoft Azure by clicking the button Deploy on Microsoft Azure. But when I export the data set, the JSONL(text label) function doesn't work.

What I want is:

{"id": 1, "text": "EU rejects ...", "labels": [[0,2,"ORG"], [11,17, "MISC"], [34,41,"ORG"]]}
{"id": 2, "text": "Peter Blackburn", "labels": [[0, 15, "PERSON"]]}
{"id": 3, "text": "President Obama", "labels": [[10, 15, "PERSON"]]}

But, the output format is the same as the JSONL:

{"id": 1, "text": "EU rejects ...", "annotations": [{"id": 1, "label": 2, "start_offset": 0, "end_offset": 2, "user": 1}]}
{"id": 2, "text": "Peter Blackburn", "annotations": [{"id": 2, "label": 1, "start_offset": 0, "end_offset": 15, "user": 1}]}
{"id": 3, "text": "President Obama", "annotations": [{"id": 3, "label": 1, "start_offset": 10, "end_offset": 15, "user": 1}]}

I think this might be a bug, thus hoping to get a solution.

Best

**Comment by SwiftPredator** [comment]
Look at my pull request for a quick fix. @walsripe 
Maybe it gets merged in the next time.

**Comment by walsripe** [comment]
Hello, do you know how to fix it on Microsoft Azure? I am not sure when this issue will be solved on the master branch.

> Look at my pull request( #1287) for a quick fix. @walsripe
> Maybe it gets merged in time.

**Comment by walsripe** [comment]
> Look at my pull request( #1287) for a quick fix. @walsripe
> Maybe it gets merged in time.

Hello, I installed the Doccano on myself Ubuntu by using Docker and modified the file you mentioned in the commit. But, it seems that the problem also remains. Thus, I would like to know whether you could give me a brief description of how you did?

**Comment by SwiftPredator** [comment]
I have tested the output on a sequence labeling project. After I changed the format.ts the jsonl text label output isn't anymore the same as the jsonl output. 
I got the following outputs on example data:

Jsonl with text label:
`{"id": 4, "text": "example", "meta": {"wikiPageID": 1}, "annotation_approver": null, "comment_count": 0, "labels": [[0, 1, "LOC"], [0, 2, "ORG"]]}
{"id": 5, "text": "example", "meta": {"wikiPageID": 2}, "annotation_approver": null, "comment_count": 0, "labels": [[0, 1, "LOC"]]}
{"id": 6, "text": "example", "meta": {"wikiPageID": 3}, "annotation_approver": null, "comment_count": 0, "labels": [[0, 1, "PER"]]}`

Jsonl without text label:
`{"id": 4, "text": "example", "annotations": [{"label": 3, "start_offset": 0, "end_offset": 1, "user": 1, "created_at": "2021-04-03T19:54:42.369772Z", "updated_at": "2021-04-03T19:54:42.369797Z"}, {"label": 4, "start_offset": 0, "end_offset": 2, "user": 1, "created_at": "2021-04-03T19:54:42.374564Z", "updated_at": "2021-04-03T19:54:42.374586Z"}], "meta": {"wikiPageID": 1}, "annotation_approver": null, "comment_count": 0}
{"id": 5, "text": "example", "annotations": [{"label": 3, "start_offset": 0, "end_offset": 1, "user": 1, "created_at": "2021-04-03T19:54:42.376095Z", "updated_at": "2021-04-03T19:54:42.376114Z"}], "meta": {"wikiPageID": 2}, "annotation_approver": null, "comment_count": 0}
{"id": 6, "text": "example", "annotations": [{"label": 5, "start_offset": 0, "end_offset": 1, "user": 1, "created_at": "2021-04-03T19:54:42.377344Z", "updated_at": "2021-04-03T19:54:42.377363Z"}], "meta": {"wikiPageID": 3}, "annotation_approver": null, "comment_count": 0}`

Is the output format above the one you look for? What type of project do you use?

**Comment by walsripe** [comment]
Many thanks. I also tested on sequence labelling project. The outputs are as below.

The project looks like:

![project](https://user-images.githubusercontent.com/26459647/113631310-2c0d5f00-9661-11eb-8465-5e9dfe3c17d9.png)

The config I modified looks like:

![config](https://user-images.githubusercontent.com/26459647/113631377-48a99700-9661-11eb-9d60-bdbc9ca2a64b.png)

The output without text label:

![withouttext](https://user-images.githubusercontent.com/26459647/113631432-60811b00-9661-11eb-9526-3ca11c256c73.png)

The output with text label:

![withtext](https://user-images.githubusercontent.com/26459647/113631465-6c6cdd00-9661-11eb-9106-cca69400e661.png)

I am not sure why the modified config didn't work, or maybe I missed some key points?

**Comment by JamesDConley** [comment]
I ran into this problem today as well!
I believe it worked for one export or something like that, and then hasn't worked since. Would be very happy to get a fix

**Comment by SwiftPredator** [comment]
Thanks for the quick reply. I can't really tell why its not working for you, but you could check if the right format arrives at the TextDownloadView.
You can print the format in the import_export.py after line 133. If it doesn't print jsonl in your terminal( where you start the server) then the wrong format parameter arrives at the view. Line 146 shows the check for the type parameter where the labels are painted. Would be interesting if that's the case. 
Sry, but that's my only suggestion for the problem rn. I have time in some days to test it further.

**Comment by walsripe** [comment]
Thanks for your step by step help. I found a strange thing:

The docker log are like:

Starting django
[2021-04-05 23:46:57 +0000] [40] [INFO] Starting gunicorn 20.1.0
[2021-04-05 23:46:57 +0000] [40] [INFO] Listening at: http://0.0.0.0:8000 (40)
[2021-04-05 23:46:57 +0000] [40] [INFO] Using worker: sync
[2021-04-05 23:46:57 +0000] [42] [INFO] Booting worker with pid: 42
[2021-04-05 23:46:57 +0000] [43] [INFO] Booting worker with pid: 43
Forbidden: /v1/me
Forbidden: /v1/me

And actually, after the initialisation of TextDownloadAPI, it seems that the class function get(self, request, *args, **kwargs) has not been called at all. Since I am not familiar with this, I hope my test results could be helpful to your analysis, and this issue could be resolved soon.

**Comment by LisaBanana** [comment]
Hi, I have the same issue with label extraction (detailed here : https://github.com/doccano/doccano/issues/1267 ).

**Comment by walsripe** [comment]
BTW. A in-normal quick fix of export text label is:

Just use hard coding, change the below line:
#format = request.query_params.get('q')
to
format = "jsonl"

It can work if you want to export text label format, but the jsonl format export won't work anymore. Thus, we should change manually.


> Hi, I have the same issue with label extraction (detailed here : #1267 ).



> I ran into this problem today as well!
> I believe it worked for one export or something like that, and then hasn't worked since. Would be very happy to get a fix
> 
> Edit : This is for doing the text extraction task (NER) btw
