### ISSUE TITLE
Some stale documentation needs to be updated

### ISSUE THREAD

**Issue by Vydruth** [doccano/doccano#1302]
- Readme and About page have stale information!
Please see the screenshots attached:

<img width="500" alt="Screen Shot 2021-04-13 at 7 26 32 PM" src="https://user-images.githubusercontent.com/10277192/114646362-f8998880-9c8f-11eb-9693-5716a8815753.png"><img width="500" alt="Screen Shot 2021-04-13 at 7 31 10 PM" src="https://user-images.githubusercontent.com/10277192/114646372-fc2d0f80-9c8f-11eb-832d-9fb43b3fb38b.png">

It might be a good idea to have a document or contributing.md reflect:
- The technologies and design patterns that your project is using in every version of doccano release. 
- I see that you have changed the UI completely in the recent past, for a person not very familiar with the front end it might be a little difficult to understand what changes were made and why they were made. Maybe having information related to why the change was made and what changes were made could be really helpful :)

**Comment by Vydruth** [comment]
The environment is not relevant here.

**Comment by Hironsan** [comment]
The following is done:

- Update the site
- Update the tags
