### ISSUE TITLE
Deployment with single click on Google Cloud fails

### ISSUE THREAD

**Issue by nehakapila94** [doccano/doccano#1305]
When I try to deploy doccano using One-click Deployment on Cloud Run, it fails with below error

"Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable"
 When I checked the config, the Container Port was set to 8080, I updated it to 8000, but the deployment still fails with above error.

**Comment by erol-apiday** [comment]
I am having this issue too. Did you have to enter a Database URL during the set up process? I left it as "" which may have contributed to the failure based on a quick skim of the logs. 

@doccano do you guys have any suggestions on what to use for the DATABASE_URL variable to avoid this?
