### ISSUE TITLE
After Quick Deploy on Heroku, App crash due to sqlalchemy

### ISSUE THREAD

**Issue by vtmoreau** [doccano/doccano#1327]
How to reproduce the behaviour
---------
Start the quick deploy to heroku
Wait for successful build and deploy
Open app and wait for crash.

**Logs** 
`sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres`
 `celery crashed`
`Process exited with status 12021-04-23T17:02:29.297622+00:00 heroku[web.1]: State changed from up to crashed`

Apparently versions of SQLAlchemy 1.4+ require postgresql:// and do not accept postgre:// anymore.

The DATABASE_URL start with postgres:// after deployment on heroku

Your Environment
---------
Installed with the deploy to heroku from doccano's home page, built from Dockerfile.
SQLAlchemy was 1.4.7

**Comment by vtmoreau** [comment]
After forking and updating Pipfiles with SQLAlchemy==1.3.24, app is up and running on heroku.
SQLAlchemy related errors disappeared from logs.

**Comment by Hironsan** [comment]
Related:
- [Why is SQLAlchemy 1.4.x not connecting to Heroku Postgres?](https://help.heroku.com/ZKNTJQSK/why-is-sqlalchemy-1-4-x-not-connecting-to-heroku-postgres)
