### ISSUE TITLE
Query regarding custom ner with docanno and deployment of same on cloud platform

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [doccano/doccano#1329]
Hi,

I want to build custom ner with docanno and deploy the same on cloud platform .
Also after deployment I want to use the application using rest api to get respective response.

Please guide me through this.

**Comment by shubhamgajbhiye1994** [comment]
currently I am using linux but later on I need to be switched to window , but currently I am going with linux

**Comment by Hironsan** [comment]
1. Upload your dataset to doccano.
2. Annotate the dataset.
3. Export the dataset.
4. Train your model with the dataset.
5. Deploy the model.

**Comment by shubhamgajbhiye1994** [comment]
ok,Thanks!
