### ISSUE TITLE
export to JSON(Text-Labels / was eliminated?

### ISSUE THREAD

**Issue by jp-geoAI** [doccano/doccano#1330]
Please could you help me, I want to export to JSON(Text-Labels), but the software does not give me the option.

Was this export option removed?

I want to do something similar to this Arcgis tutorial, they recommend Doccano, but they indicate to export in that format. I exported my data in JSONL but the ArcGIS example code does not recognise the data.

https://developers.arcgis.com/python/guide/labeling-text-using-doccano/

https://developers.arcgis.com/python/sample-notebooks/information-extraction-from-madison-city-crime-incident-reports-using-deep-learning/#Publishing-the-results-as-feature-layer

 

My input data are txt files of crime reports in Brazil.

**Comment by jp-geoAI** [comment]
Win10

**Comment by Hironsan** [comment]
You can export JSON(Text-Labels) by selecting `JSONL`.

![image](https://user-images.githubusercontent.com/6737785/116013327-a03c9080-a66a-11eb-8f09-c2f2e1a47275.png)

**Comment by jp-geoAI** [comment]
but the output file does not have this structure... 

as was previously the output with the JSON(Text-Labels) option.


Ex: 

{"id": 2311, "text": "Officers were dispatched to a robbery of the Associated Bank in the 1500 block of W Broadway. A M/W described as 5'04\" – 5'05\" and 130 lbs., wearing a gray hooded sweatshirt, dark sunglasses, and a blue bandana around his mouth area demanded money from a teller. No weapon was mentioned or displayed. A K-9 track was attempted. The track ended at a nearby apartment complex. Released 08/09/2018 at 6:17 PM by Sgt. Jennifer Kane", "meta": {}, "annotation_approver": null, "labels": [[30, 38, "Crime"], [45, 92, "Address"], [233, 248, "Crime"], [263, 272, "Weapon"], [409, 427, "Reporting_officer"], [384, 394, "Reported_date"], [398, 405, "Reported_time"]]}

**Comment by Hironsan** [comment]
If you want the same structure, I recommend you use v1.2.x.

**Comment by jp-geoAI** [comment]
I installed and tested all versions v1.2.x. and 1.1.0, and none of them allow me to import txt files. It gives me an error message in the format. With the latest version it does accept txt files, but I don't have the option to export to JSON(Text-Labels). Please do you have any other recommendations?

**Comment by Hironsan** [comment]
As you say, v1.2.x does not allow you to import text files. The feature is implemented in v1.3.0.

What do you want? I can add `annotation_approver` field and will probably be able to make the field names configurable(e.g. data->text, label->labels). But `meta` field is removed in v1.3.0 so you cannot use it.

**Comment by jp-geoAI** [comment]
Dear Hironsan,

I want to create a dataset, in order to be able to use the functionalities of this example: 
(https://developers.arcgis.com/python/guide/labeling-text-using-doccano/)
My data is in txt format, I want to be able to import, tag and export it in JSON(Text- Labels) format, as indicated in the ESRI documentation and as in the examples in the Doccano documentation videos. Is this possible?

**Comment by yradsmikham** [comment]
I am currently running into this issue. @jp-geoAI - were you ever able to resolve your issue?

Why was this issue closed? It was never resolved?
