### ISSUE TITLE
Cant import any data

### ISSUE THREAD

**Issue by gika815** [doccano/doccano#1336]
Hello
I cant import any data with last version of Doccano. Last week there was no problem with it
Project: SequenceLabeling
file format: text line

Environment
---------

*   Python Version Used: 3.9
*   When you install doccano: today (28.04.2021)
*   git clone + docker compose prod

**Comment by wisdomikezogwo** [comment]
I had this error while importing data to dev

`Task api.tasks.injest_data[1234567-YYYY-XXXX-blah-blahblahblah] raised unexpected: DataError('value too long for type character varying(100)\n')` from celery.

Environment

Python Version Used: 3.9
When you install doccano: today (28.04.2021)
git clone + docker compose dev

But I was able to injest the data after renaming the text file to a short name (10 chars), idk maybe this might help out.

**Comment by hsnprsd** [comment]
I think we should increase length of filename here. So I reopen the issue.

**Comment by asehmi** [comment]
> But I was able to injest the data after renaming the text file to a short name (10 chars), idk maybe this might help out.

What an annoying error... I have spent many hours formatting and reformatting my import (with labels) to overcome this issue! Thanks for the tip.

**Comment by heinrichreimer** [comment]
With 31 characters in the filename it works for me, with 32 characters fails.
