### ISSUE TITLE
Is it possible to highlight labels in partially annotated data for Sequence Labeling?

### ISSUE THREAD

**Issue by kumudchauhan** [doccano/doccano#1337]
I am using doccano dev env locally on my Mac using Docker.
I have a partially annotated text data. I want to annotate some extra labels in this partially labeled text data using UI. Is there a way through which I can highlight the already labeled words when I import this data with so that it would be easy for humans to highlight new labels. 
For example, I have text labeled like following
My name is Kumud|**B-PER**  Chauhan|**I-PER**. I works at XYZ  in USA. 
Now, I want to highlight **|B-PER**  and **|I-PER** in Doccano UI so that humans can label remaining entities as  'XYZ' -> **ORG** and 'USA' -> **GEO**.

**Comment by SurajDonthi** [comment]
@kumudchauhan You can easily do this. Upload your data either in JSONL or CONLL formats. Once you upload, you should see all the labels highlighted in the annotation page.

JSONL FORMAT
------------------
```
{"text": "EU rejects German call to boycott British lamb.", "label": [ [0, 2, "ORG"], [11, 17, "MISC"], ... ]}
{"text": "Peter Blackburn", "label": [ [0, 15, "PERSON"] ]}
{"text": "President Obama", "label": [ [10, 15, "PERSON"] ]}
```

CONLL FORMAT (BIO FORMAT)
------------------
```
EU  B-ORG
rejects O
German  B-MISC
call  O
to  O
boycott O
British B-MISC
lamb  O
. O

Peter B-PER
Blackburn I-PER
```
