### ISSUE TITLE
Wrong variable used in the Gcloud One-click Deployment Script

### ISSUE THREAD

**Issue by fabong** [doccano/doccano#1345]
How to reproduce the behaviour
---------

Hello, 

I tried to use the Gcloud One-click Deployment script. The deployment worked correctly but I couldn't login with the admin account set in the environment variable. I checked in the database and saw that were not created user.
I restarted with DEBUG mode and saw this error: 
```
Creating admin`.
CommandError: Enter a valid email address.
```

Thus, I searched in the repository code and found no mention of environment variable `ADMIN_CONTACT_EMAIL` (defined in the Google Cloud Run parameters) except in 2 specific Heroku files. 
So, I tried by renaming `ADMIN_CONTACT_EMAIL` to `ADMIN_EMAIL` directly in the Google Cloud Run parameters.

I restarted with DEBUG mode and saw this in the logs: 
```
Creating admin`.
Superuser created successfully.
```

Finally, I tried to login and everything was working correctly.

This issue is probably linked with the same problem that I had: https://github.com/doccano/doccano/issues/1140.

Possible correction to do
-------
- Change in the Gcloud One-click Deployment Script from `ADMIN_CONTACT_EMAIL` to `ADMIN_EMAIL` (but I don't know where this environment variable is defined in this repository)

Your Environment
---------

*   Operating System: /
*   Python Version Used: /
*   When you install doccano: 4th of May 2021
*   How did you install doccano (Heroku button etc): Gcloud One-Click Deployment

**Comment by ricjhill** [comment]
I also have this issue with the Gcloud One-click Deployment scrip

**Comment by ricjhill** [comment]
The environment variable is defined in the app.json file as described here:   https://github.com/GoogleCloudPlatform/cloud-run-button

> Customizing deployment parameters
> 
> If you include an app.json at the root of your repository, it allows you customize the experience such as defining an alternative service name, or prompting for additional environment variables.
>
