### ISSUE TITLE
Unable to deploy Doccano on Azure platform

### ISSUE THREAD

**Issue by shrijithtb** [doccano/doccano#1346]
How to reproduce the problem
---------
Deploy Doccano using the one-click deployment found in this link - https://doccano.github.io/doccano/

I had Doccano deployed on Azure and was using it. 
I met with an export error where the format didn't include the text labels and had only label ids and offsets. (Despite changing the export format)
So I brought down the deployed to re-deploy but couldn't find the option that was previously available on the Github page. 
So I used the Azure one-click deployment on the documentation page. It gets deployed but the site is unresponsive or doesn't load at all. 
Also, the instructions mention to pull it using Docker and then deploy but it seems that whether or not I pull using Docker, the deployment is successful. 

I'm new to these processes. Can someone please help me? 
```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System: Windows 10 
*   Python Version Used: Didn't use Python. Used Docker. 
*   When you install doccano: It's unresponsive, too slow and failing to load.  
*   How did you install doccano (Heroku button etc): Azure one-click deployment in the documentation page. 
* Is the image that I pull into the Docker related to the Doccano I deploy in Azure because whether or not I use DOcker, I'm able to deploy using one-click deployment. If it's not related, how to deploy using Docker?

**Comment by jeffkayne** [comment]
I have also encountered this problem with the deployment of Doccano on Azure. I am unable to login to the tool, nor am I able to login to the django admin configuration. The page is unresponsive.
