### ISSUE TITLE
Import labels does not import backgroundColor

### ISSUE THREAD

**Issue by afcruzs** [doccano/doccano#1348]
How to reproduce the behaviour
---------

Create any set of labels, make sure to add background Color. Export it as json, import it in a new project. When imported, the background color defaults to "#209cee" for all labels, irrespective of what is set on the json file. Example json file:

```
[
  {
    "id": 6,
    "text": "ID",
    "prefixKey": null,
    "suffixKey": null,
    "backgroundColor": "#FFC107",
    "textColor": "#ffffff"
  },
  {
    "id": 7,
    "text": "Name",
    "prefixKey": null,
    "suffixKey": null,
    "backgroundColor": "#795548",
    "textColor": "#ffffff"
  },
  {
    "id": 8,
    "text": "Content",
    "prefixKey": null,
    "suffixKey": null,
    "backgroundColor": "#BF360C",
    "textColor": "#ffffff"
  }
]
```

A quick search shows this is the default value: https://github.com/doccano/doccano/blob/f6a3dbabc22b413959d359652c5241af1e8755a6/backend/api/models.py#L107 

WSL2 in windows
---------

*   Operating System: WSL2 (Ubuntu)
*   Python Version Used: 3.8.5
*   When you install doccano: 5/7
*   How did you install doccano (Heroku button etc): pip install

**Comment by janhenrikbern** [comment]
I am running into the same issue. Any updates on this?

Environment setup through docker image.

**Comment by dimidloc** [comment]
FWIW, it looks like a validation issue
The colors appear in `initial_data`, but not in `validated_data`:
```
labels = json.load(request.data['file'])
serializer = LabelSerializer(data=labels, many=True)
serializer.is_valid(raise_exception=True)
print("initial_data:")
print(serializer.initial_data)
print("validated_data:")
print(serializer.validated_data)
serializer.save(project=project)
```
Source `class LabelUploadAPI(APIView)`

**Comment by dimidloc** [comment]
Ah, the ModelSerializer is expecting `background_color`, while the labels are exported as `backgroundColor`.

**Comment by dimidloc** [comment]
Here's a quick fix:
`sed  's/backgroundColor/background_color/g; s/textColor/text_color/g; s/prefixKey/prefix_key/g; s/suffixKey/suffix_key/g' ~/Downloads/label_config.json > ~/Downloads/label_config2.json`

**Comment by dkarty** [comment]
I'm facing the same issue in v1.4.1. 
Environment setup: docker image.
Any updates on this please?
Thank you!
