### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by MESSALTI** [doccano/doccano#1350]
Hello dear friends,
first of all I want to thank you for this wonderful doccano, I only have a small remark concerning the export model I think that some fields are missing in the new export model of this version compared to the previous version (annotation_approver , created_at, updated_at, user) please keep us the model which includes all the information of the annotation task.
thanks in advance

**Comment by Hironsan** [comment]
OK. I will add the fields(approver, created_at, updated_at).

**Comment by MESSALTI** [comment]
Thank you very much hirosan, do not forget the user field and thank you for putting the username itself because in the previous version we only find the id
