### ISSUE TITLE
Can not import data

### ISSUE THREAD

**Issue by qu123xxx** [doccano/doccano#1353]
How to reproduce the behaviour
---------
I use the doccano 1.3.1 from [here](https://github.com/doccano/doccano/releases/tag/v1.3.1) and setup with Python and Node.js.

When I create a project and injest data, whatever format I select, it show the rings keep spinning
![image](https://user-images.githubusercontent.com/16397369/117673374-5365c780-b1dd-11eb-9059-ef9b812df303.png)

The data is from the tutorial and save as `json ` format.

and the log of backend is keeping repeat the last line of following sample log:
```
[10/May/2021 22:10:39] "POST /v1/projects/2/upload HTTP/1.1" 200 50
[10/May/2021 22:10:42] "GET /v1/tasks/status/e881360a-1a17-436b-ba7b-aa0d8c9845c3 HTTP/1.1" 200 42
[10/May/2021 22:10:45] "GET /v1/tasks/status/e881360a-1a17-436b-ba7b-aa0d8c9845c3 HTTP/1.1" 200 42
[10/May/2021 22:10:48] "GET /v1/tasks/status/e881360a-1a17-436b-ba7b-aa0d8c9845c3 HTTP/1.1" 200 42
[10/May/2021 22:10:51] "GET /v1/tasks/status/e881360a-1a17-436b-ba7b-aa0d8c9845c3 HTTP/1.1" 200 42
```

---------

*   Operating System: Win10 x64
*   Python Version Used: 3.9.5
*   When you install doccano: today
*   How did you install doccano (Heroku button etc): python+node.js 14.16.1

**Comment by EnzoNclt** [comment]
I have actually the same issue, tried out all different formats and none of them is working. I have exactly the same log as above. only bug for Dataset, i tried to import label and it worked.

- OS: macOS Darwin 19.6.0
- installed doccano on May 10th 2020
- Using directly docker-compose, modifying the docker-compose.dev.yml for dev purpose

**Comment by qu123xxx** [comment]
What is   

> import label

I try to import data like this
```
 {"text": "This dissertation examines the relationship between local scientific cultures, the construction of scientific disciplines, and the bounds of scientific creativity through a detailed study of the early research career of American chemist Linus Pauling (1901-1992).", "label": [[220, 228, "NORP"], [237, 250, "PERSON"], [252, 261, "DATE"]]}
{"text": "In the years between Linus Pauling's introduction to quantum mechanics in 1927 and his move to defense related research in the wake of World War Two, Pauling and his collaborators at the California Institute of Technology pursued a series of researches that intertwined to form the epochal article series and monograph", "label": [[3, 12, "DATE"], [21, 36, "PERSON"], [74, 78, "DATE"], [135, 148, "EVENT"], [150, 157, "PERSON"], [183, 221, "ORG"]]}
```

But it can't work……

**Comment by Hironsan** [comment]
It seems to me that the task queue is not running.
I updated the documentation. Please try it:

- [Running a task queue](https://github.com/doccano/doccano/blob/master/docs/getting-started.md#python)

**Comment by Hironsan** [comment]
Hmm, this may be related to Windows:

- https://github.com/celery/celery/issues/4081

Unfortunately, I don't have a windows PC.

**Comment by wisdomikezogwo** [comment]
Have the same issue, started after uploading and ingesting a large file of about >240MB which took forever and now small file injestion of <1MB take the same time it feels.

and this is on Ubuntu 20.04 LTS and not on Windows

**Comment by mtluczek** [comment]
I've got the same problem on MacOS - why did you close the issue if it's not fixed!!!?

**Comment by mennthor** [comment]
Same problem on Windows 10, Python 3.9, doccano 1.8.
Tried multiple data formats in different sizes (only a few lines up to a hundred) but the spinner keeps on spinning.
Is there maybe a workaround, where I can manually place the data in the DB or in some folder so doccano recognises it from the start without explicit import?

**Comment by oleksandr-khryplyvenko** [comment]
same problem
Python 3.10.5 (main, Jul 18 2022, 14:30:54) [GCC 11.3.0] on linux

Linux 5.15.52-gentoo x86_64 11th Gen Intel(R) Core(TM) i7-1165G7

**Comment by elm-daiki** [comment]
run doccano task in another terminal and the problem got fixed thanks to @RalphChobok

**Comment by onlyabhilash** [comment]
(doc) C:\Users\65361>doccano task
Traceback (most recent call last):
  File "C:\Users\65361\Anaconda3\envs\doc\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\65361\Anaconda3\envs\doc\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\65361\Anaconda3\envs\doc\Scripts\doccano.exe\__main__.py", line 7, in <module>
  File "C:\Users\65361\AppData\Roaming\Python\Python39\site-packages\backend\cli.py", line 174, in main
    env.read_env(args.env_file, recurse=False, override=True)
  File "C:\Users\65361\AppData\Roaming\Python\Python39\site-packages\environs\__init__.py", line 409, in read_env
    raise ValueError("path must be a filename, not a directory.")
ValueError: path must be a filename, not a directory.

Facing above issue, not able to run doccano task 
envi is python - 3.9 and doccano is 1.8.1

**Comment by JAYANTHNITW** [comment]
I tying to upload <1mb text line file, but it was always spinning. Pls help me to fix this problem on windows 11

**Comment by JAYANTHNITW** [comment]
> I tying to upload <1mb text line file, but it was always spinning. Pls help me to fix this problem on windows 11

problem solved
