### ISSUE TITLE
Cannot see annotated data for sequence labelling

### ISSUE THREAD

**Issue by shivarajmulimani** [doccano/doccano#1359]
In the statistics tab, I see annotator wise how many labels have been annotated but don't see changes in the donut chart.
Also, I can't see any annotations in the datasets.

**Comment by shivarajmulimani** [comment]
Os - Linux Ubuntu 18.04.5 LTS

Python version - 3.6

When did you install - Nov 23

How did you install - 
```
Docker Compose
You need to clone the repository:

git clone https://github.com/doccano/doccano.git
cd doccano
Note for Windows developers: Be sure to configure git to correctly handle line endings or you may encounter status code 127 errors while running the services in future steps. Running with the git config options below will ensure your git directory correctly handles line endings.

git clone https://github.com/doccano/doccano.git --config core.autocrlf=input
Production
Set the superuser account credentials in the docker-compose.prod.yml file:

ADMIN_USERNAME: "admin"
ADMIN_PASSWORD: "password"
If you use Google Analytics, set the tracking:

GOOGLE_TRACKING_ID: "UA-12345678-1"
Run doccano:

$ docker-compose -f docker-compose.prod.yml up
Go to http://0.0.0.0/.

```

**Comment by wisdomikezogwo** [comment]
> Os - Linux Ubuntu 18.04.5 LTS
> 
> Python version - 3.6
> 
> When did you install - Nov 23
> 
> How did you install -
> 
> ```
> Docker Compose
> You need to clone the repository:
> 
> git clone https://github.com/doccano/doccano.git
> cd doccano
> Note for Windows developers: Be sure to configure git to correctly handle line endings or you may encounter status code 127 errors while running the services in future steps. Running with the git config options below will ensure your git directory correctly handles line endings.
> 
> git clone https://github.com/doccano/doccano.git --config core.autocrlf=input
> Production
> Set the superuser account credentials in the docker-compose.prod.yml file:
> 
> ADMIN_USERNAME: "admin"
> ADMIN_PASSWORD: "password"
> If you use Google Analytics, set the tracking:
> 
> GOOGLE_TRACKING_ID: "UA-12345678-1"
> Run doccano:
> 
> $ docker-compose -f docker-compose.prod.yml up
> Go to http://0.0.0.0/.
> ```

Have the same issue, started after uploading and ingesting a large file of about >240MB which took forever and now small file injestion of <1MB take the same time it feels.
