### ISSUE TITLE
http://127.0.0.1:3000/admin/ page doesn't load

### ISSUE THREAD

**Issue by abercher** [doccano/doccano#1362]
I'm new to doccano and I'm trying to test it. But I can't manage to add a new annotators while following the FAQ instructions

Following the instructions docs, I cloned today the repo with

`git clone https://github.com/doccano/doccano.git`

Then I created a python virtual environment with python 3.7, activated it, and installed docker-compose in it with
`pip install docker-compose`

Then I ran the container with
`docker-compose -f docker-compose.dev.yml up`

Then I went to my browser at the address

[http://127.0.0.1:3000/](http://127.0.0.1:3000/)

And everything seemed to be working. I could login with the username "admin" and password "password", create a task, annotate some text and download it.

But when I tried to follow the [FAQ](https://doccano.github.io/doccano/faq/) instructions for adding a new user and try to enter this page via my browser:

[http://127.0.0.1:3000/admin/](http://127.0.0.1:3000/admin/)

I only get a blank page...

My Environment:
Ubuntu 20.04

Any suggestion would be very appreciated as this tool looks great for what I need to do.

**Comment by Clockcai** [comment]
Go to http://127.0.0.1:8000/admin/   admin page run on backend

**Comment by abercher** [comment]
Thanks a lot! Indeed it was the source of the issue!
