### ISSUE TITLE
unable to use production docker image

### ISSUE THREAD

**Issue by abercher** [doccano/doccano#1363]
I'm new to doccano and I can't start the application with the **production docker-compose file**, when I follow the guideline in the README.md file.

Following the instructions docs, I cloned today the repo with

`git clone https://github.com/doccano/doccano.git`

Then I created a python virtual environment with python 3.7, activated it, and installed docker-compose in it with
`pip install docker-compose`

Then I ran the container with
`docker-compose -f docker-compose.prod.yml up`

I get no error but then if I follow the guideline of the README.md and go to
[http://0.0.0.0/](http://0.0.0.0/)
(I click on the link in the README.md) then it directs me to
[https://0.0.0.0/](https://0.0.0.0/)
and Firefox displays this message:

> Unable to connect
> Firefox can’t establish a connection to the server at 0.0.0.0.

If I enter in the terminal
`docker ps`
the output is

> CONTAINER ID   IMAGE                  COMMAND                  CREATED      STATUS         PORTS                                                                    NAMES
> 85f0e8659386   rabbitmq:3.8           "docker-entrypoint.s…"   2 days ago   Up 3 minutes   4369/tcp, 5671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:5672->5672/tcp   doccano_rabbitmq_1
> 051623d73c12   postgres:13.1-alpine   "docker-entrypoint.s…"   2 days ago   Up 3 minutes   5432/tcp                                                                 doccano_postgres_1

and if I run in the terminal

`docker exec doccano_backend_1 pipenv run app/manage.py test api`
The output is

> Error response from daemon: Container 6beea5b4a14ff5c073545764c24dbcb13524be19b15867e474d82d3ffdb0b9d1 is not running

Note that if I go to this address (the one recommended in the dev case):
[http://127.0.0.1:3000/](http://127.0.0.1:3000/)
I get the same message from Firefox:

> Unable to connect
> Firefox can’t establish a connection to the server at 127.0.0.1:3000.

Finally here is the (long) output in the terminal when I enter
`docker-compose -f docker-compose.prod.yml up`

(there seems to be some python file not found and I wonder if there is some implicit step that wasn't in the explanation that I didn't do out of ignorance)

> WARNING: Found orphan containers (doccano_frontend_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
> Starting doccano_postgres_1 ... done
> Starting doccano_rabbitmq_1 ... done
> Recreating doccano_backend_1 ... done
> Recreating doccano_celery_1  ... done
> Recreating doccano_nginx_1   ... done
> Attaching to doccano_rabbitmq_1, doccano_postgres_1, doccano_celery_1, doccano_backend_1, doccano_nginx_1
> celery_1    | Waiting for database
> backend_1   | Initializing database
> backend_1   | python: can't open file '/src/backend/manage.py': [Errno 2] No such file or directory
> postgres_1  | 
> postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
> postgres_1  | 
> celery_1    | python: can't open file 'manage.py': [Errno 2] No such file or directory
> postgres_1  | 2021-05-12 16:42:52.051 UTC [1] LOG:  starting PostgreSQL 13.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
> doccano_backend_1 exited with code 2
> postgres_1  | 2021-05-12 16:42:52.052 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> postgres_1  | 2021-05-12 16:42:52.052 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> doccano_celery_1 exited with code 2
> postgres_1  | 2021-05-12 16:42:52.055 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> postgres_1  | 2021-05-12 16:42:52.059 UTC [21] LOG:  database system was shut down at 2021-05-12 16:40:50 UTC
> postgres_1  | 2021-05-12 16:42:52.062 UTC [1] LOG:  database system is ready to accept connections
> rabbitmq_1  | Configuring logger redirection
> rabbitmq_1  | 2021-05-12 16:42:57.929 [debug] <0.288.0> Lager installed handler error_logger_lager_h into error_logger
> rabbitmq_1  | 2021-05-12 16:42:57.939 [debug] <0.291.0> Lager installed handler lager_forwarder_backend into error_logger_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.939 [debug] <0.300.0> Lager installed handler lager_forwarder_backend into rabbit_log_connection_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.939 [debug] <0.297.0> Lager installed handler lager_forwarder_backend into rabbit_log_channel_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.939 [debug] <0.294.0> Lager installed handler lager_forwarder_backend into rabbit_log_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.940 [debug] <0.303.0> Lager installed handler lager_forwarder_backend into rabbit_log_feature_flags_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.942 [debug] <0.306.0> Lager installed handler lager_forwarder_backend into rabbit_log_federation_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.945 [debug] <0.309.0> Lager installed handler lager_forwarder_backend into rabbit_log_ldap_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.948 [debug] <0.312.0> Lager installed handler lager_forwarder_backend into rabbit_log_mirroring_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.949 [debug] <0.315.0> Lager installed handler lager_forwarder_backend into rabbit_log_prelaunch_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.954 [debug] <0.318.0> Lager installed handler lager_forwarder_backend into rabbit_log_queue_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.957 [debug] <0.321.0> Lager installed handler lager_forwarder_backend into rabbit_log_ra_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.960 [debug] <0.324.0> Lager installed handler lager_forwarder_backend into rabbit_log_shovel_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.963 [debug] <0.327.0> Lager installed handler lager_forwarder_backend into rabbit_log_upgrade_lager_event
> rabbitmq_1  | 2021-05-12 16:42:57.999 [info] <0.44.0> Application lager started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:42:58.428 [debug] <0.284.0> Lager installed handler lager_backend_throttle into lager_event
> nginx_1     | 2021/05/12 16:42:54 [emerg] 1#1: host not found in upstream "backend" in /etc/nginx/conf.d/nginx.conf:15
> nginx_1     | nginx: [emerg] host not found in upstream "backend" in /etc/nginx/conf.d/nginx.conf:15
> doccano_nginx_1 exited with code 1
> rabbitmq_1  | 2021-05-12 16:43:00.186 [info] <0.44.0> Application mnesia started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.187 [info] <0.273.0> 
> rabbitmq_1  |  Starting RabbitMQ 3.8.16 on Erlang 23.3.3
> rabbitmq_1  |  Copyright (c) 2007-2021 VMware, Inc. or its affiliates.
> rabbitmq_1  |  Licensed under the MPL 2.0. Website: https://rabbitmq.com
> rabbitmq_1  | 
> rabbitmq_1  |   ##  ##      RabbitMQ 3.8.16
> rabbitmq_1  |   ##  ##
> rabbitmq_1  |   ##########  Copyright (c) 2007-2021 VMware, Inc. or its affiliates.
> rabbitmq_1  |   ######  ##
> rabbitmq_1  |   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
> rabbitmq_1  | 
> rabbitmq_1  |   Doc guides: https://rabbitmq.com/documentation.html
> rabbitmq_1  |   Support:    https://rabbitmq.com/contact.html
> rabbitmq_1  |   Tutorials:  https://rabbitmq.com/getstarted.html
> rabbitmq_1  |   Monitoring: https://rabbitmq.com/monitoring.html
> rabbitmq_1  | 
> rabbitmq_1  |   Logs: <stdout>
> rabbitmq_1  | 
> rabbitmq_1  |   Config file(s): /etc/rabbitmq/rabbitmq.conf
> rabbitmq_1  |                   /etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf
> rabbitmq_1  | 
> rabbitmq_1  |   Starting broker...2021-05-12 16:43:00.188 [info] <0.273.0> 
> rabbitmq_1  |  node           : rabbit@85f0e8659386
> rabbitmq_1  |  home dir       : /var/lib/rabbitmq
> rabbitmq_1  |  config file(s) : /etc/rabbitmq/rabbitmq.conf
> rabbitmq_1  |                 : /etc/rabbitmq/conf.d/management_agent.disable_metrics_collector.conf
> rabbitmq_1  |  cookie hash    : cGEvhpU62Kty7Nm38Dt1LA==
> rabbitmq_1  |  log(s)         : <stdout>
> rabbitmq_1  |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags: list of feature flags found:
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] drop_unroutable_metric
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] empty_basic_get_metric
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] implicit_default_bindings
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] maintenance_mode_status
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] quorum_queue
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] user_limits
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags:   [x] virtual_host_metadata
> rabbitmq_1  | 2021-05-12 16:43:00.440 [info] <0.273.0> Feature flags: feature flag states written to disk: yes
> rabbitmq_1  | 2021-05-12 16:43:00.668 [info] <0.273.0> Running boot step pre_boot defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.668 [info] <0.273.0> Running boot step rabbit_core_metrics defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.669 [info] <0.273.0> Running boot step rabbit_alarm defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.672 [info] <0.421.0> Memory high watermark set to 6362 MiB (6671414067 bytes) of 15905 MiB (16678535168 bytes) total
> rabbitmq_1  | 2021-05-12 16:43:00.676 [info] <0.423.0> Enabling free disk space monitoring
> rabbitmq_1  | 2021-05-12 16:43:00.676 [info] <0.423.0> Disk free limit set to 50MB
> rabbitmq_1  | 2021-05-12 16:43:00.679 [info] <0.273.0> Running boot step code_server_cache defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.679 [info] <0.273.0> Running boot step file_handle_cache defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.679 [info] <0.426.0> Limiting to approx 1048479 file handles (943629 sockets)
> rabbitmq_1  | 2021-05-12 16:43:00.680 [info] <0.427.0> FHC read buffering:  OFF
> rabbitmq_1  | 2021-05-12 16:43:00.680 [info] <0.427.0> FHC write buffering: ON
> rabbitmq_1  | 2021-05-12 16:43:00.680 [info] <0.273.0> Running boot step worker_pool defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.680 [info] <0.374.0> Will use 8 processes for default worker pool
> rabbitmq_1  | 2021-05-12 16:43:00.680 [info] <0.374.0> Starting worker pool 'worker_pool' with 8 processes in it
> rabbitmq_1  | 2021-05-12 16:43:00.681 [info] <0.273.0> Running boot step database defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.683 [info] <0.273.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
> rabbitmq_1  | 2021-05-12 16:43:00.684 [info] <0.273.0> Successfully synced tables from a peer
> rabbitmq_1  | 2021-05-12 16:43:00.684 [info] <0.273.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
> rabbitmq_1  | 2021-05-12 16:43:00.684 [info] <0.273.0> Successfully synced tables from a peer
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Successfully synced tables from a peer
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Running boot step database_sync defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Running boot step feature_flags defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Running boot step codec_correctness_check defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Running boot step external_infrastructure defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Running boot step rabbit_registry defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.710 [info] <0.273.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.711 [info] <0.273.0> Running boot step rabbit_queue_location_random defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.711 [info] <0.273.0> Running boot step rabbit_event defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.711 [info] <0.273.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.711 [info] <0.273.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.711 [info] <0.273.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.712 [info] <0.273.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.712 [info] <0.273.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.712 [info] <0.273.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.712 [info] <0.273.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.712 [info] <0.273.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Running boot step rabbit_priority_queue defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Priority queues enabled, real BQ is rabbit_variable_queue
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Running boot step kernel_ready defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.713 [info] <0.273.0> Running boot step rabbit_sysmon_minder defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.714 [info] <0.273.0> Running boot step rabbit_epmd_monitor defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.714 [info] <0.453.0> epmd monitor knows us, inter-node communication (distribution) port: 25672
> rabbitmq_1  | 2021-05-12 16:43:00.714 [info] <0.273.0> Running boot step guid_generator defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.716 [info] <0.273.0> Running boot step rabbit_node_monitor defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.716 [info] <0.457.0> Starting rabbit_node_monitor
> rabbitmq_1  | 2021-05-12 16:43:00.716 [info] <0.273.0> Running boot step delegate_sup defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.718 [info] <0.273.0> Running boot step rabbit_memory_monitor defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.718 [info] <0.273.0> Running boot step core_initialized defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.718 [info] <0.273.0> Running boot step upgrade_queues defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.738 [info] <0.273.0> Running boot step channel_tracking defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.739 [info] <0.273.0> Setting up a table for channel tracking on this node: tracked_channel_on_node_rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.739 [info] <0.273.0> Setting up a table for channel tracking on this node: tracked_channel_table_per_user_on_node_rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.739 [info] <0.273.0> Running boot step rabbit_channel_tracking_handler defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.739 [info] <0.273.0> Running boot step connection_tracking defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.739 [info] <0.273.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.740 [info] <0.273.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.740 [info] <0.273.0> Setting up a table for per-user connection counting on this node: tracked_connection_table_per_user_on_node_rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.740 [info] <0.273.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.740 [info] <0.273.0> Running boot step rabbit_exchange_parameters defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.740 [info] <0.273.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.741 [info] <0.273.0> Running boot step rabbit_policies defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.742 [info] <0.273.0> Running boot step rabbit_policy defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.742 [info] <0.273.0> Running boot step rabbit_queue_location_validator defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.743 [info] <0.273.0> Running boot step rabbit_quorum_memory_manager defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.743 [info] <0.273.0> Running boot step rabbit_vhost_limit defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.743 [info] <0.273.0> Running boot step rabbit_mgmt_db_handler defined by app rabbitmq_management_agent
> rabbitmq_1  | 2021-05-12 16:43:00.743 [info] <0.273.0> Management plugin: using rates mode 'basic'
> rabbitmq_1  | 2021-05-12 16:43:00.743 [info] <0.273.0> Running boot step recovery defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.743 [error] <0.273.0> Discarding message {'$gen_cast',{force_event_refresh,#Ref<0.818128107.2789474308.172693>}} from <0.273.0> to <0.511.0> in an old incarnation (1620837234) of this node (1620837777)
> rabbitmq_1  | 
> rabbitmq_1  | 2021-05-12 16:43:00.743 [error] emulator Discarding message {'$gen_cast',{force_event_refresh,#Ref<0.818128107.2789474308.172693>}} from <0.273.0> to <0.511.0> in an old incarnation (1620837234) of this node (1620837777)
> rabbitmq_1  | 
> rabbitmq_1  | 2021-05-12 16:43:00.745 [info] <0.494.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@85f0e8659386/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
> rabbitmq_1  | 2021-05-12 16:43:00.747 [info] <0.494.0> Starting message stores for vhost '/'
> rabbitmq_1  | 2021-05-12 16:43:00.747 [info] <0.498.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
> rabbitmq_1  | 2021-05-12 16:43:00.749 [info] <0.494.0> Started message store of type transient for vhost '/'
> rabbitmq_1  | 2021-05-12 16:43:00.749 [info] <0.502.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
> rabbitmq_1  | 2021-05-12 16:43:00.751 [info] <0.494.0> Started message store of type persistent for vhost '/'
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step empty_db_check defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Will not seed default virtual host and user: have definitions to load...
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step rabbit_looking_glass defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step background_gc defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step routing_ready defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step pre_flight defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.756 [info] <0.273.0> Running boot step notify_cluster defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.757 [info] <0.273.0> Running boot step networking defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.757 [info] <0.273.0> Running boot step definition_import_worker_pool defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.757 [info] <0.374.0> Starting worker pool 'definition_import_pool' with 8 processes in it
> rabbitmq_1  | 2021-05-12 16:43:00.758 [info] <0.273.0> Running boot step cluster_name defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.758 [info] <0.273.0> Running boot step direct_client defined by app rabbit
> rabbitmq_1  | 2021-05-12 16:43:00.758 [info] <0.540.0> Resetting node maintenance status
> rabbitmq_1  | 2021-05-12 16:43:00.758 [info] <0.44.0> Application rabbit started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.758 [info] <0.44.0> Application cowlib started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.758 [info] <0.44.0> Application cowboy started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.760 [info] <0.44.0> Application rabbitmq_management_agent started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.781 [info] <0.44.0> Application prometheus started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.782 [info] <0.44.0> Application rabbitmq_web_dispatch started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.785 [info] <0.566.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
> rabbitmq_1  | 2021-05-12 16:43:00.785 [info] <0.540.0> Ready to start client connection listeners
> rabbitmq_1  | 2021-05-12 16:43:00.785 [info] <0.44.0> Application rabbitmq_prometheus started on node rabbit@85f0e8659386
> rabbitmq_1  | 2021-05-12 16:43:00.788 [info] <0.610.0> started TCP listener on [::]:5672
> rabbitmq_1  | 2021-05-12 16:43:01.036 [info] <0.540.0> Server startup complete; 3 plugins started.
> rabbitmq_1  |  * rabbitmq_prometheus
> rabbitmq_1  |  * rabbitmq_web_dispatch
> rabbitmq_1  |  * rabbitmq_management_agent
> rabbitmq_1  |  completed with 3 plugins.
> rabbitmq_1  | 2021-05-12 16:43:01.036 [info] <0.540.0> Resetting node maintenance status

My Environment:
Ubuntu 20.04

I apologize in advance if I did something wrong. My software engineering skills are quite little. Any help would be welcome.

**Comment by scheiblr** [comment]
We also had problems to run the `docker-compose.prod.yaml`. Any help would be appreciated.
The image `doccano/doccano` from the docker hub without any further services worked, though.

**Comment by Hironsan** [comment]
Related to https://github.com/doccano/doccano/issues/1199
