### ISSUE TITLE
Unable to import a dataset

### ISSUE THREAD

**Issue by Doodlera** [doccano/doccano#1371]
I install doccano 1.3.1 with pip install doccano in a conda env with Python 3.6.13. It's OK to login in http://0.0.0.0:8000/, but I can not import the dataset during or after create projects. Here are some screenshots.
![image](https://user-images.githubusercontent.com/32300708/118608606-72bbb080-b7ec-11eb-9afe-5da18e9cbeea.png)
![image](https://user-images.githubusercontent.com/32300708/118608750-9c74d780-b7ec-11eb-81ae-99c543b9f04d.png)

Operating System: CentOS Linux release 7.7.1908 (Core)
Web browser：Google Chrome 84.0.4147.105（64）,Microsoft Edge 44.18362.449.0.

**Comment by Doodlera** [comment]
> Would you write your environment? Thank you!
doccano 1.3.1
Python 3.7.6
Operating System: CentOS Linux release 7.7.1908 (Core)
Web browser：Google Chrome 84.0.4147.105（64）,Microsoft Edge 44.18362.449.0.

**Comment by Hironsan** [comment]
Did you run the task queue:

```bash
doccano task
```

**Comment by Doodlera** [comment]
> Did you run the task queue:
> 
> ```shell
> doccano task
> ```

Yes. The information is as follows.
![image](https://user-images.githubusercontent.com/32300708/118745986-f11a6000-b889-11eb-8023-a535b443c0de.png)

**Comment by Doodlera** [comment]
By the way, I test with Python 3.8.8, still the same problem.

**Comment by Hironsan** [comment]
I tested the following environments but I can't reproduce the problem:

Env1:
- Mac OS X 10.14.1
- Python 3.8.5
- doccano 1.4.0

Env2:
- Ubuntu 20.04
- Python 3.8.5
- doccano 1.4.0

Command:
```bash
doccano init
doccano createuser
doccano webserver
# In another terminal
doccano task
```

I found something strange: Some elements like encoding, example, and file drop area are not shown in your screenshot despite you select the file format.

![image](https://user-images.githubusercontent.com/6737785/118813658-54d47580-b8ea-11eb-83e6-25bf41e8fa6a.png)

**Comment by Doodlera** [comment]
> I tested the following environments but I can't reproduce the problem:
> 
> Env1:
> 
> * Mac OS X 10.14.1
> * Python 3.8.5
> * doccano 1.4.0
> 
> Env2:
> 
> * Ubuntu 20.04
> * Python 3.8.5
> * doccano 1.4.0
> 
> Command:
> 
> ```shell
> doccano init
> doccano createuser
> doccano webserver
> # In another terminal
> doccano task
> ```
> 
> I found something strange: Some elements like encoding, example, and file drop area are not shown in your screenshot despite you select the file format.
> 
> ![image](https://user-images.githubusercontent.com/6737785/118813658-54d47580-b8ea-11eb-83e6-25bf41e8fa6a.png)

Done. The reason for this problem is the browser. I update Google Chrome 84.0.4147.105 to 90.0.4430.212. This was annoying because the problem appeared on all my browsers. Sad ==. 
Thanks!
