### ISSUE TITLE
Unreachable EC2 after AWS one-click deployment

### ISSUE THREAD

**Issue by quentin-auge-tiime** [doccano/doccano#1372]
When deploying to AWS with one-click deployment to a `t2.micro` EC2, instance never seems to get available, at least within "reasonable" time (< 60 minutes).
Specifically, its public IP/DNS does not answer neither ping, SSH, or HTTP.

Is `t2.small` the minimal requirement?
The CloudFormation template rather seems to suggests that `t2.micro` is also valid.

Any thoughts on that?

Possibly related: https://github.com/doccano/doccano/issues/300 and https://github.com/doccano/doccano/issues/1061.

**Comment by quentin-auge-tiime** [comment]
Deploying on region `eu-west-1`.
Not sure it is relevant.

**Comment by datakop** [comment]
+1

**Comment by Hironsan** [comment]
I confirmed it is working on the `t2.medium` instance.
I will try the other instances.

In addition, I will consider changing from docker-compose to docker or pip version for reducing build time.
