### ISSUE TITLE
When annotating words, the line breaks in the textbox changing 

### ISSUE THREAD

**Issue by pa92trick** [doccano/doccano#1378]
Its maybe not really a technical bug but for us its makes working with Doccano less comfortable. Nearly every time, you annotate a word (for example at sequence labeling), the line breaks in the text changing. This is a bit confusing for the user so it would be better if the text, once displayed, stays the same.

Maybe related to #1378 and #1355

How to reproduce the behaviour
---------

1. Go to the main page of your Doccano installations, or use the official Heroku Demo: https://doccano.herokuapp.com/demo/named-entity-recognition 
2. Tag a word
3. The text will have new line breaks (annotated "extended" with PER in the text below)

![image](https://user-images.githubusercontent.com/39307599/119222525-21196b80-baf5-11eb-893f-fa6e45da2eb3.png)
![image](https://user-images.githubusercontent.com/39307599/119222532-2971a680-baf5-11eb-8521-c12ff42bd570.png)

Your Environment
---------

*   Operating System: MacOs / Firefox and Safari latest Verions
*   Python Version Used: From Dockerfile
*   When you install doccano: 2021-20-05
*   How did you install doccano (Heroku button etc): Docker/Ubuntu 20

**Comment by fernandodelacalle** [comment]
Also for the last label in a sentece the ui creates new lines with only the annotated word.

**Comment by Hironsan** [comment]
[The new UI](https://github.com/doccano/doccano/pull/1511) resolves this problem. Please try it.
