### ISSUE TITLE
Can not access http://0.0.0.0:8000

### ISSUE THREAD

**Issue by rotshine** [doccano/doccano#1380]
Description of the problem
---------
After installing the doccano using pip in a container, i initialize the webserver but it does not connect trhough the browser (http://0.0.0.0:8000).

How to reproduce the behaviour
---------
Install doccano on a container using Dockerfile and pip

Dockerfile
```
FROM fedora:latest

RUN dnf -y install pip
RUN pip install doccano
RUN doccano init
#Create a super user.
RUN doccano createuser --username admin --password pass

EXPOSE 8000/tcp
EXPOSE 8000/udp
```

My Environment
---------

*   Operating System: Hyper-V VM: Fedora 34
*   Python Version Used: python3
*   When you install doccano: after installing and initializing the webserver, it is not possible to access it.
*   How did you install doccano (Heroku button etc): using pip in a dockerfile

**Comment by Hironsan** [comment]
This is not related to doccano. Docker problem.

```FROM fedora:latest

RUN dnf -y install pip
RUN pip install doccano
RUN doccano init
RUN doccano createuser --username admin --password pass

EXPOSE 8000/tcp
EXPOSE 8000/udp
ENTRYPOINT ["doccano", "webserver", "--port", "8000"]
```

When you create a container after building the image, specify `-p` option.

**Comment by wuhq1** [comment]
have you address this question?
