### ISSUE TITLE
Export jsonl text labelling does not work

### ISSUE THREAD

**Issue by ChrisChross** [doccano/doccano#1383]
Do some entity annotation and try to download the data (jsonl format with text label)

---------

If i try to download the file, i always get the default file downloaded (without text labelling instead of the one i selected).
Can you fix that? 

As a workaround, how would i have to change the slug to make it work? 

---------

I am using heroku for it and the dataset contains ~9000 entries.

**Comment by LisaBanana** [comment]
I do have the same issue.
My environement : 
Os: Unix 5.4.0.1031
Python: 2.7.13
Installed on an Azuer Webapp
When you install doccano: janvier 2020

The issue : 
![image](https://user-images.githubusercontent.com/48214320/120009018-d8255380-bfdb-11eb-9090-f9ae7ce78cf4.png)

the dataset contains 5 lines (it's a test). I tried to import it on .txt format and had the same issue.

**Comment by ChrisChross** [comment]
Hi @LisaBanana ,

looks like your problem is with the upload, but yes I agree, its still buggy. 
For the upload I noticed that unicode matters. You could try to type one of the examples 
shown directly into a file and upload that one, if it works, your other file has some formatting issues. 
Yet, not sure if that helps.

Cheers 
Chris

**Comment by Hironsan** [comment]
The feature is updated in https://github.com/doccano/doccano/pull/1310.
