### ISSUE TITLE
Injest sequence data does not work, or yield errors

### ISSUE THREAD

**Issue by Michael-Bar** [doccano/doccano#1387]
How to reproduce the behaviour
---------
I deployed Doccano with AWS "one-click" onto ec2-medium instrance.

I had done this on May 7th and it worked fine.

However, when I deploy now and try to "injest" datasets in a sequence labelling project, I can choose either TextLine or TextFile, neither of which respond to the blue "injest" button. No error is given, simply nothing happens. 

Your Environment
---------
AWS one-click deploymenet
ec2-medium instance

**Comment by Hironsan** [comment]
I fixed in #1391. Please try it.
