### ISSUE TITLE
Injest error with docker-compose

### ISSUE THREAD

**Issue by bwulff** [doccano/doccano#1388]
How to reproduce the behaviour
---------
- Clone the doccano repo from GitHub
- change to the cloned repo directory
- bring up Doccano with `docker-compose -f docker-compose.prod.yml`(omitting -d so all the logs get printed)
- log in as 'admin'
- create a text annotation project 'Test'
- choose file type JSONL
- copy the example text from the dialog to into a file test.json
- upload test.json (green box appears indicating the upload was successful)
- click 'Injest'

Expected:
Dataset is injested.

Actually:
Nothing happens in the UI. But in the container logs there is an error message from the backend:
```
backend_1   | Error moving temporary file to permanent storage location
nginx_1     | 10.116.60.121 - - [01/Jun/2021:15:41:58 +0000] "POST /v1/projects/1/upload HTTP/1.1" 500 145 "http://XXX/projects/1/upload" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0" "-"
```

Your Environment
---------

*   Operating System: Ubuntu 20.04
*   Python Version Used: `Python 3.8.6 (default, Dec 11 2020, 14:38:29)`(in backend container)
*   When you install doccano: 01.06.2020
*   How did you install doccano (Heroku button etc): used the docker-compose.prod.yml file from the doccano repo
*   Docker Image versions:
*   *  rabbitmq:3.8
*   *  postgres:13.1-alpine
*   *  doccano images build from doccano git repo master commit cda25a68c3e7b6325c18f727f3b1b91703554faa

**Comment by bwulff** [comment]
Exec'd into the backend container. Is it a problem, that the directory /backend/media is owned by root?
```
doccano@c6973c83af5a:/backend$ ls -l
total 164
-rw-rw-r-- 1 doccano doccano   473 Jun  1 14:40 Dockerfile.dev
-rw-rw-r-- 1 doccano doccano  1095 Jun  1 14:40 Dockerfile.prod
-rw-rw-r-- 1 doccano doccano  1340 Jun  1 14:40 Pipfile
-rw-rw-r-- 1 doccano doccano 91697 Jun  1 14:40 Pipfile.lock
-rw-rw-r-- 1 doccano doccano     0 Jun  1 14:40 __init__.py
drwxrwxr-x 1 doccano doccano  4096 Jun  1 14:40 api
drwxrwxr-x 1 doccano doccano  4096 Jun  1 14:40 app
drwxrwxr-x 1 doccano doccano  4096 Jun  1 14:40 authentification
-rw-rw-r-- 1 doccano doccano  3993 Jun  1 14:40 cli.py
drwxr-xr-x 1 doccano doccano  4096 Jun  1 15:00 client
drwx------ 3 doccano doccano  4096 Jun  1 16:11 filepond-temp-uploads
-rwxrwxr-x 1 doccano doccano   535 Jun  1 14:40 manage.py
drwxr-xr-x 5 root    root     4096 Jun  1 15:11 media
drwxrwxr-x 1 doccano doccano  4096 Jun  1 14:40 server
drwxrwxr-x 6 doccano doccano  4096 Jun  1 15:11 staticfiles
```

**Comment by Michael-Bar** [comment]
Seeing the same issue with the One-Click AWS deployment.

**Comment by Hironsan** [comment]
Maybe permission problem.
I'll try to update Dockerfile.prod.

**Comment by bwulff** [comment]
@Hironsan Thanks for the quick fix, much appreciated!

**Comment by bwulff** [comment]
@sskorol When I applied the fix, I did the following
```
docker-compose -f docker-compose.prod.yml down
docker volume rm doccano_media doccano_postgres_data doccano_static_volume server_config
git pull
docker-compose -f docker-compose.prod.yml build
docker-compose -f docker-compose.prod.yml up -d
```
It is important that you delete the volumes from the faulty runs before, because the directories with the wrong permissions are already existing in those volumes. Don't know if `--force-recreate` is somehow connected to your problem, didn't test.

In essence: Try starting completely from scratch with the docker-compose setup.

**Comment by sskorol** [comment]
@bwulff volumes removal did the trick. However, it wipes out all the existing data. It's a much bigger problem than the inability to upload a file. I believe new releases must have backward compatibility. As far as I remember, this is the second time I had to wipe out my data due to some breaking changes.
