### ISSUE TITLE
Where is the code module for use machine learning model to help labeling ?

### ISSUE THREAD

**Issue by svjack** [doccano/doccano#1399]
Many non-open-sourced annotation toolkit support use machine learning model to help simplify the annotation process.
and i review the code, that auto-labeling-pipeline is the main part to handle request, so can i find the appropriate interface to add this support by myself, and can easy render the conclusion in the front end ?

**Comment by svjack** [comment]
> Would you write your environment? Thank you!

local (installed by pip, not docker)

**Comment by Hironsan** [comment]
Please see:
- https://github.com/doccano/auto-labeling-pipeline
