### ISSUE TITLE
After setting detail custom rest request template, FieldError at /v1/projects/1/docs/68/auto-labeling: Cannot resolve keyword 'document' into field when I used auto labeling in sequence labeling project. 

### ISSUE THREAD

**Issue by Mr-IT007** [doccano/doccano#1401]
Your Environment
---------

*   Operating System:  CentOS 7.6
*   Python Version Used: Python3.7.8
*   When you install doccano: about 2 weeks ago
*   How did you install doccano (Heroku button etc): Docker
---------
Is there a detail demo for auto labeling of custom rest request template? I have a local predict server for sequence labeling( BIO ) and provide restful api, so I want to know how to use auto labeling. 

here is my api demo
~~~javascript~~~
{
    "ret": "ok",
    "msg": "",
    "data": [
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "B-LOC",
        "I-LOC",
        "I-LOC",
        "B-LOC",
        "I-LOC",
        "O",
        "I-LOC",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "B-PER",
        "I-PER",
        "I-PER",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "B-LOC",
        "I-LOC",
        "I-LOC",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "O",
        "B-PER",
        "I-PER",
        "I-PER",
        "O",
        "O",
        "O",
        "O",
        "O"
    ]
}

**Comment by ksipma** [comment]
as far as I can see now it is broken, since the actual sentence/text is not being send in the API request to your local predicter

**Comment by ksipma** [comment]
I got it to work,

you need to add a custom parameter in your body. call it text. as value type: {{ text }}
because the brackets it will be translated to your actual sentence.

Next problem is the jinja template:

`[
  {% for entity in input.**entities**%}
    {
      "label": "{{ entity.label}}",
      "start_offset": {{ entity.start_offset}},
      "end_offset": {{ entity.end_offset}}
    }{% if not loop.last %},{% endif %}
  {% endfor %}
]`

I use the above example, my API has the following structure:

{
"**entities**":[{"label":"ORG","start_offset":10,"end_offset":20}, ....]
}

After that it is working

**Comment by Mr-IT007** [comment]
@ksipma thanks, I'm trying it. And setting custom parameter is ok, grateful for your answer!

**Comment by Mr-IT007** [comment]
Hi, @ksipma I got api structure the same as yours. Setting custom parameter and jinja template is ok. Everything is ok, you can look my screenshot. But doccano occured an error: Cannot resolve keyword 'document' into field when I use the auto labeling.


![1](https://user-images.githubusercontent.com/39551480/121146204-4a1a5a00-c872-11eb-8d46-9241e7bcd60c.png)
![2](https://user-images.githubusercontent.com/39551480/121146223-4dade100-c872-11eb-8442-d71db3f7ea8b.png)
![3](https://user-images.githubusercontent.com/39551480/121146245-51d9fe80-c872-11eb-8692-7dc4ac614bdf.png)
![4](https://user-images.githubusercontent.com/39551480/121146258-54d4ef00-c872-11eb-99c3-f2d60229f21e.png)
![5](https://user-images.githubusercontent.com/39551480/121146275-59010c80-c872-11eb-9fee-591038f20b17.png)
![6](https://user-images.githubusercontent.com/39551480/121146290-5d2d2a00-c872-11eb-8042-69644d5260f9.png)
![7](https://user-images.githubusercontent.com/39551480/121146305-60281a80-c872-11eb-9bf8-6ba3f7252d1f.png)

**Comment by ksipma** [comment]
is it a sequencelabeling project and did you create the labels first?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden

________________________________

**Comment by Mr-IT007** [comment]
@ksipma yes, it's a sequence labeling project and I had created the labels

**Comment by Mr-IT007** [comment]
@ksipma  Found the solution #1375
