### ISSUE TITLE
Dataset import not working with json

### ISSUE THREAD

**Issue by Telres** [doccano/doccano#1404]
How to reproduce the behaviour

try to import json file with text having line breaks:

import.json

`{"text":" saúde
gentho de emareg t
solicito avaliação da função muscular por dinamométria tuss
cintura escapular
dorsal
mao direita
mao esquerda
hd avaliação da força e função muscular
cid e .
medico
crmsp .-
clínica emagrecimento  saúde
rua ","url":"https://somewebsite.com/somephoto.jpeg?sv=2018-03-28"}
`

Error on console:
`{"ready":true,"result":null,"error":{"text":"<class 'json.decoder.JSONDecodeError'>(['Invalid control character at: line 1 column 48 (char 47)'])"}}`

Your Environment

Docker installed on GCP (Ubuntu VM)

**Comment by Telres** [comment]
Found the error. Doccano json parser can't deal with line breaks inside the text. for example:

`{"text" : "This
does
not
work"}`

`{"text" : "This \n work"}`

As an workaround please add popup message when there is an error parsing the files.

**Comment by jssson** [comment]
It would be really nice when there would be more error / log messages visible to the administrator
