### ISSUE TITLE
Does "Auto Labeling" work?

### ISSUE THREAD

**Issue by Ginnna** [doccano/doccano#1406]
When I annotate an article, I try to use this function to auto label.

But, nothing happen, after clicking the button to start this function

**Comment by Ginnna** [comment]
> Would you write your environment? Thank you!

CentOs 7.9.2009

docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano

**Comment by EnzoNclt** [comment]
Have you create / implement an auto-labelling model in the dedicated section in Settings > Auto-Labelling ?

**Comment by Ginnna** [comment]
> Have you create / implement an auto-labelling model in the dedicated section in Settings > Auto-Labelling ?

I forget it. But how to create the auto-labelling model.

I dont't understand what the page want to say.

**Comment by EnzoNclt** [comment]
You can start with [GCP](https://cloud.google.com/natural-language/docs/analyzing-entities) i guess, or try to create your own API over a NER algorithm, like SpaCy which is imo the easiest to implement. Though if you're not familiar / interested in natural language processing, it can be quite long.
