### ISSUE TITLE
What is the path for the result from labeling?

### ISSUE THREAD

**Issue by chawannut157** [doccano/doccano#1407]
I'm launching Doccano via Docker on my internal server without internet connection, then I do tunneling via ssh from my local to the server port to do labeling.

I wonder where can I find the result saved on the server? 
> docker exec -it doccano_test bash

I do see /data/doccano.db which is reading from /doccano/backend/media/file.csv, but it seems to be only the input file not the result from labeling.

Sure, I can export the result via the UI, but I want to make sure it's saved somewhere in case the docker is down.

**Comment by Michael-Bar** [comment]
I would also like to know where to find the results via command line (AWS deployment).

**Comment by Paooooo** [comment]
Hi, 
In my knowledge the results files from labelling are stored in the path @chawannut157 mentioned 
`/doccano/backend/media/` as .zip. So same path as input files.

**Comment by chawannut157** [comment]
I noticed that file too but it seems to save only the first time you click "export" on the UI. If you do additional export, it won't save the new zip file.
