### ISSUE TITLE
When I annotate an article, the right column "key  value" means what?

### ISSUE THREAD

**Issue by Ginnna** [doccano/doccano#1411]
It show "No data available"

**Comment by Paooooo** [comment]
Hi @Ginnna , 

In my knowledge, the right column in the annotation page is used to display meta data about the current document. 
When you import some data in doccano, if the data file contains meta data, they will  be displayed in the right column.
If your data file do not contain meta data, it will show "No data available" as you mentioned. 

Here is an example of  csv data with meta :
```
text,label,meta
AAA,,
BBB,Positive,The following is meta data
CCC,Negative
DDD,,This is meta data
```
