### ISSUE TITLE
Is there a proper way to get a Auth Token for external API call ?

### ISSUE THREAD

**Issue by EnzoNclt** [doccano/doccano#1415]
How to reproduce the behaviour
---------

Is there any documentation about Doccano API ? I'm trying to use it with my own machine learning API, and i need a proper way to connect it with doccano, so is there a simple way to get an auth token ? I tried /v1/auth-token but this route does not return anything close to an auth token.

I've also tried to pass by doccano-client, but the method get_me() who seems to use the route /v1/me doesn't sent back any auth token either

Your Environment
---------

*   Operating System: MacOS 10.15
*   Python Version Used: 3.9.5
*   When you install doccano: 1.4.1
*   How did you install doccano (Heroku button etc): installed through pip

**Comment by alexdashkov** [comment]
You could use this function as an example https://github.com/doccano/doccano-client/blob/master/doccano_api_client/__init__.py#L121

For me, the cookies auth works well, so I choose it instead of token auth. 

Another example : 

```python
class DoccanoClient:
    def __init__(self, host: str, login: str, password: str, project_id: int):
        self._url: str = f"{host}/v1"
        self._auth_data: dict = {"username": login, "password": password}
        self._session: requests.Session = requests.Session()
        self._project_id = project_id

    def authenticate(self):
        """
        Auth to the doccano service and keep csrf token in the headers
        """
        auth_response = self._request("POST", "auth/login/", data=self._auth_data)
        # keep csrf token to headers
        self._session.headers["X-CSRFToken"] = auth_response.cookies["csrftoken"]

    def _request(self, method: str, endpoint: str, *args, **kwargs) -> requests.Response:
        """
        Internal proxy method to convert calls to the requests format

        :param method: HTTP method POST, GET, etc..
        :param endpoint: HTTP endpoint
        """
        url = f"{self._url}/{endpoint}"
        response = self._session.request(method, url, *args, **kwargs)
        try:
            response.raise_for_status()
        except requests.exceptions.RequestException as re:
            logging.error(response)
            logging.error(response.text)
            raise re
        return response
```

**Comment by EnzoNclt** [comment]
Thanks @alexdashkov for the answer, worked for me !
