### ISSUE TITLE
Exporting only checked annotation always results in an empty zip file

### ISSUE THREAD

**Issue by armsp** [doccano/doccano#1416]
How to reproduce the behaviour
---------
I made a project for text annotation. I can annotate and export the *whole* dataset as well. But whenever I try to export only the checked data, I always get an empty zip file of 22 bytes. There is no code to reproduce this. I am not sure if others are facing this issue as well. But I guess if you have some documents that are checked and annotated and some that are not checked because you want to annotate them later, then when you want to export only the checked documents you get an empty zip file.

Any solution for this?

I am the Project Admin and I am only one working. Everything is running from inside a container.

Your Environment
---------
*   Operating System: Docker on Windows 10
*   Python Version Used: N/A
*   When you install doccano: Today
*   How did you install doccano (Heroku button etc): Docker

**Comment by D-Shah1427** [comment]
I am having same issue. I am also working alone. on top of that I am not able to download any of my work from doccano right now. I created large annotation project in last few hours but I can't extract it right now.
Environment
operating system anaconda prompt on windows 10 (pip install)
when did you install doccano: yesterday
python version: none specified

**Comment by gao9302027** [comment]
Same problem here, would like to know the solution...

**Comment by everfate** [comment]
I met the same problem.
I solved it by using ubuntu's firefox in virtual machine to export. It seems there are some bugs in codes that interact with window's chrome.
