### ISSUE TITLE
How to connect to a local REST API for auto annotation?

### ISSUE THREAD

**Issue by armsp** [doccano/doccano#1417]
How to reproduce the behaviour
---------
I want to use a local auto-annotator using spaCy. So I made a simple API using FastAPI as follows -
NOTE: Right now it does not annotate, but the idea is to be able to communicate first. Atleast for now I should get the input text back as it is.
Also, since the rest api is local, I exposed port 7000 of container to 7000 of my host
```py
from fastapi import FastAPI
import uvicorn
from pydantic import BaseModel


class TextToAnnotate(BaseModel):
    text: str

app = FastAPI()

@app.post("/auto_annotate")
async def auto_annotate(doc: TextToAnnotate):
    return {"message": doc.text}

if __name__=="__main__":
    uvicorn.run("auto_annotate:app", host='0.0.0.0', port=7000)
```
I checked this API from Postman by sending a simple text from body and was able to get the message back -
![image](https://user-images.githubusercontent.com/12681262/122534084-d0d3f180-d03f-11eb-8a7f-df5a62fc7ea2.png)

Then in doccano, I tried to setup the Auto Annotator as follows -
1. Config Template - Custom REST Request
![image](https://user-images.githubusercontent.com/12681262/122531370-0cb98780-d03d-11eb-88ad-8a9dcbae667a.png)
2. Parameters, headers, Body and Testing
url         -` 0.0.0.0:7000/auto_annotate`
method - `POST`
![image](https://user-images.githubusercontent.com/12681262/122533523-4b504180-d03f-11eb-92f0-30acfd4b24fa.png)

3. Params  - Nothing
4. Headers - `Content-Type` - `application/json`
5. Body      - Just provided the key as `text`
![image](https://user-images.githubusercontent.com/12681262/122533586-602cd500-d03f-11eb-968c-7d4478fb978a.png)

6. Test the parameters - Sample Text - "Does this work?"
![image](https://user-images.githubusercontent.com/12681262/122531656-573b0400-d03d-11eb-805d-4af67c4dec1e.png)
I don't get any output. it says that it **Failed to establish a connection**

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: Whatever ships with the Docker image
*   When you install doccano: 17th June 2021
*   How did you install doccano (Heroku button etc): Dockerfile

**Comment by EnzoNclt** [comment]
I have the same issue, through docker it's not working, however use pip package and everything should be fine

**Comment by armsp** [comment]
@EnzoNclt I got it working via pip. However I am not able to go very far. Right now atleast it communicates.

What I am having a hard time understanding is this, in postman I send the sentence to be annotated as json in "body". Here, I have added the "text" key to the Body but not provided any value because the value keeps on changing based on the input sentence. In the GUI there is a "Sample Text" in **Test the Parameters** section, however I just cannot understand what it does because the input text to it does not go to the API via body since I don't get any annotated output.
![image](https://user-images.githubusercontent.com/12681262/122806732-511c8000-d2e8-11eb-8500-e16aa82fc42a.png)
I expected that the Sample Text will be sent via Body. But apparently that is not the case. Also, when I give the value to the Body Key, then I do see the expected output.
![image](https://user-images.githubusercontent.com/12681262/122806925-9476ee80-d2e8-11eb-9e60-b1e44fc59e14.png)

But that is not that important. As you can see I have formatted the output in the way Doccano wants as it mentions in the next section. I am thinking that if the output is like what it expects then I don't have to provide any template, right? Moreover, I still don't understand the purpose of the template.....like how exactly am I supposed to use it? Just linking to the whole of Jinja's documentation does not help at all.
![image](https://user-images.githubusercontent.com/12681262/122807290-00f1ed80-d2e9-11eb-90dc-17fb67494ede.png)

Without any modifications if I run this, I get a massive error as follows -
![image](https://user-images.githubusercontent.com/12681262/122807405-2f6fc880-d2e9-11eb-8c28-31a8f5a211d9.png)

Any idea what to do in this section?

**Comment by uklft** [comment]
Assuming you are running doccano and your API in seperated containers with exposed ports you would need to specify your **docker hosts** public IP, eg. 192.168.0.10, as 0.0.0.0 refers to each __container's__ public address. Otherwise you could add them to a [docker network](https://stackoverflow.com/questions/31149501/how-to-reach-docker-containers-by-name-instead-of-ip-address) and refer to the container name.

If you didn't find out yet, you can specify the text to be sent to your api by setting it as jinja2 variable in your body:
key: text, value: {{ text }}. Your annotated Sample Text then should be returned by the API.

**Comment by armsp** [comment]
@uklft I have not been able to understand how to use the jinja template yet. I can however communicate with the REST API fine enough.
Based on what you said, I tried to do the following -
![image](https://user-images.githubusercontent.com/12681262/123041545-13684600-d413-11eb-8624-de07b9e741eb.png)
But I get some error. Is this the correct way to use the template? Is there an example in the documentation where I can see how exactly to use this? I have scoured the documentation but couldn't find anything. Any hint would be greatly appreciated.

**Comment by EnzoNclt** [comment]
I think you're pretty close, maybe try with the "if not loop.last" param like this it could work:
```
[
    {% for entity in input %}
        {
            "start_offset": {{ entity.start_offset }},
            "end_offset": {{ entity.end_offset}},
            "label": "{{ entity.label }}"
        }{% if not loop.last %},{% endif %}
    {% endfor %}
]
```

**Comment by uklft** [comment]
To POST the text you want to annotate the "key: text, value: {{ text }}" thing goes in the "Body" Section from the __Set Parameters__ card. I was referring to [this screenshot](https://user-images.githubusercontent.com/12681262/122806925-9476ee80-d2e8-11eb-9e60-b1e44fc59e14.png).

In my opinion just using `{{ input }}` should be fine but it doesn't work for me either. But @EnzoNclt's template works fine.

**Comment by Jian1273** [comment]
@armsp I used the same code as you, but there are still some problems in my first step here. Can you show me all your current code and related settings?
![image](https://user-images.githubusercontent.com/62092417/123069792-b934a880-d445-11eb-8c1d-ba6fac71e5a4.png)

**Comment by uklft** [comment]
You can use the parameters like this:
![doccano-post-params](https://user-images.githubusercontent.com/35134759/123072566-f3865180-d415-11eb-8041-44da79d81027.png)

Are you using the Spacy api from @armsp?

**Comment by Jian1273** [comment]
@uklft 
![image](https://user-images.githubusercontent.com/62092417/123073590-1ed66400-d449-11eb-8ba2-f2931c2244ef.png)
that's my code and use the Spacy api. Thanks!

**Comment by armsp** [comment]
I am so close @uklft and @EnzoNclt . I was able to set up auto annotation and all the tests passed. However, when I actually start annotating and click on **Auto Labeling** I don't see anything.
![image](https://user-images.githubusercontent.com/12681262/123076661-fc3b4f80-d436-11eb-8942-3df4b4de6534.png)
I clicked on the second icon from right and enabled Auto Labeling. 
In my custom API I can see it printing the text so basically it is able to pass all that text to the API. But why I am not seeing the labels?
NOTE: Since my labels are same as SapCy's labels in the last part of setting up the mapping, I didn't do anything.
I am one step away from my goal....any idea why I am not seeing the label's?

**Comment by EnzoNclt** [comment]
Do you have any logs ? Honestly for this one i have no idea, i still have issues on passing my data to the auto-labeling-pipiline, but if you have any logs maybe i could help

**Comment by armsp** [comment]
@EnzoNclt sorry to bother you once again...can you please tell me how do I get the logs and show it here?

**Comment by uklft** [comment]
With the SpaCy API i am also not getting any annotation if i activate __Auto Labeling__ for a Dataset.
Any help for debugging or logs would be highly appreciated!

**Comment by uklft** [comment]
> NOTE: Since my labels are same as SapCy's labels in the last part of setting up the mapping, I didn't do anything.

I would probably add a mapping although the labels are the same.

**Comment by armsp** [comment]
Yup even though the labels are same, mapping the label's made it work.

**Comment by EnzoNclt** [comment]
> @EnzoNclt sorry to bother you once again...can you please tell me how do I get the logs and show it here?
> 
> **EDIT**: Also are there any screenshots of how auto annotation looks like in the UI?

For the logs i was thinking about about smth like console log or any error that would raise from doccano task. For the screenshots, it look like exactly like someone who might have done it manually.

**Comment by Jian1273** [comment]
I successfully implemented the function of auto_labeling. Thanks for your help!

**Comment by FieteO** [comment]
I also had trouble with this and got it working based on your comments. Maybe [my repository](https://github.com/FieteO/doccano_spacy) could be useful for someone who wants to run it together with a spacy backend.

**Comment by wysohn** [comment]
Just as a side note, if you are running Doccano in a docker environment, use the address `host.docker.internal` instead of `127.0.0.1` to access the host computer from the container.

It works for windows, but it may need additional settings if not. (https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)

**Comment by DataXujing** [comment]
please, how to autolabel the annotation of relation?
