### ISSUE TITLE
How to export labeled relationship ?

### ISSUE THREAD

**Issue by Aureliano-Berlindia** [doccano/doccano#1418]
I have labeled the entities and relationships between these entities.(Using Sequence Labeling)

However, when exporting the result data, only entities were shown in the JSON, couldn't find any relationships in it.

So I wonder whether this version doesn't support relationship labeling completely or I am not using it correctly?

**Comment by Aureliano-Berlindia** [comment]
I pull from docker images following your readme tutorial

**Comment by zhouming-hfut** [comment]
the same problem!

**Comment by Ciaranshu** [comment]
The same question here

**Comment by cccccrj** [comment]
The same question here

**Comment by CrazyTianC** [comment]
The same！

**Comment by Aureliano-Berlindia** [comment]
After inspecting the SQLite database, I saw a table named "api_annotationrelations", and every marked relationship were shown here. Perhaps this version doesn't support exporting relationships.

For those who need relation data immediately, I suggest **read directly from SQLite and extract data from tables "api_annotationrelations" and "api_relationtypes"**

**Comment by CrazyTianC** [comment]
> After inspecting the SQLite database, I saw a table named "api_annotationrelations", and every marked relationship were shown here. Perhaps this version doesn't support exporting relationships.
> 
> For those who need relation data immediately, I suggest **read directly from SQLite and extract data from tables "api_annotationrelations" and "api_relationtypes"**

**Comment by CrazyTianC** [comment]
> After inspecting the SQLite database, I saw a table named "api_annotationrelations", and every marked relationship were shown here. Perhaps this version doesn't support exporting relationships.
> 
> For those who need relation data immediately, I suggest **read directly from SQLite and extract data from tables "api_annotationrelations" and "api_relationtypes"**

I found the database file 'db.sqlite3', and I inserted one annotation. But the file size is still 0.
I run it using docker. Do you have any idea about this issue?

**Comment by Aureliano-Berlindia** [comment]
> > After inspecting the SQLite database, I saw a table named "api_annotationrelations", and every marked relationship were shown here. Perhaps this version doesn't support exporting relationships.
> > For those who need relation data immediately, I suggest **read directly from SQLite and extract data from tables "api_annotationrelations" and "api_relationtypes"**
> 
> I found the database file 'db.sqlite3', and I inserted one annotation. But the file size is still 0.
> I run it using docker. Do you have any idea about this issue?

My SQLite database file name is 'doccano.db' , which located in /data
No idea what your 'db.sqlit3' is, maybe we are using different versions of docker images

**Comment by CrazyTianC** [comment]
> 
> 
> 
> 
> 
> 
> > > After inspecting the SQLite database, I saw a table named "api_annotationrelations", and every marked relationship were shown here. Perhaps this version doesn't support exporting relationships.
> 
> > > For those who need relation data immediately, I suggest **read directly from SQLite and extract data from tables "api_annotationrelations" and "api_relationtypes"**
> 
> > 
> 
> > I found the database file 'db.sqlite3', and I inserted one annotation. But the file size is still 0.
> 
> > I run it using docker. Do you have any idea about this issue?
> 
> 
> 
> My SQLite database file name is 'doccano.db' , which located in /data
> 
> No idea what your 'db.sqlit3' is, maybe we are using different versions of docker images

Got it. doccano.db is the right file. thx

**Comment by yuyunfeng666** [comment]
> > > > After inspecting the SQLite database, I saw a table named "api_annotationrelations", and every marked relationship were shown here. Perhaps this version doesn't support exporting relationships.
> > 
> > 
> > > > For those who need relation data immediately, I suggest **read directly from SQLite and extract data from tables "api_annotationrelations" and "api_relationtypes"**
> > 
> > 
> > > 
> > 
> > 
> > > I found the database file 'db.sqlite3', and I inserted one annotation. But the file size is still 0.
> > 
> > 
> > > I run it using docker. Do you have any idea about this issue?
> > 
> > 
> > My SQLite database file name is 'doccano.db' , which located in /data
> > No idea what your 'db.sqlit3' is, maybe we are using different versions of docker images
> 
> Got it. doccano.db is the right file. thx

But We cant get ann id. how to deal with it
