### ISSUE TITLE
Support for custom tokenization

### ISSUE THREAD

**Issue by lfoppiano** [doccano/doccano#142]
From a previous discussion (#113) I've been asked to open a new issue for this specific feature request. 

The use case is the following, as an independent annotation tool, Doccano is now be able to load pre-annotated data but we should add information about tokenisation. 

This because
 - different tasks might require different tokeniser 
 - different languages might be tokenised in several ways 

Therefore to avoid being lock-in with a particular tool and make doccano able to be plugged in any workflow. 
My training data is in sync with other part of my machinery it will be guarantee that such synchronization will be maintained. 

The tokenisation is also more robust and would allow to ship (without necessarly support) more information for each token (for example orthogonal features like formatting etc..)

My proposal is to follow the prodigy format (although I choose that just for simplicity - also the main elements can be called with any name):

```
{
"spans": [{"start": 58, "end": 72, "token_start": 16, "token_end": 25, "label": "label1"}], [...]
"tokens": [{"text": "We", "start": 0, "end": 2, "id": 0}, {"text": " ", "start": 2, "end": 3, "id": 1}] , [...]
"text": "We have measured the [...]"
}
```
- `spans` refer to the list of annotations, 
- `start/end` refer to the offset in the text, while 
- `token_start/token_end` to the index of the tokens.
- tokens `id`  can be any type, maybe string or long are better?

If a user upload plain text to be annotated, doccano can always output it's own tokenisation to export the data and maintain the consistency.
As mentioned before, attached to the `spans` there can be also `user` information but also formatting, and other information that doccano can happily ignore - they must kept and send out in the output)

**Comment by amanjain97** [comment]
I am not sure whether I understood your problem correctly or not but custom tokenizer means your own tokenizer or some pre-defined like Mecab, Kagome (for Japanese), SoMaJo (German).

I am interested in contributing. 
As a work around, you can pre-process the text and then import.

**Comment by lfoppiano** [comment]
@amanjain97 yes, if you want to integrate doccano in your system, you might use a different tokenzer, therefore you might want to load it as a token list and not as a text.

**Comment by atakanokan** [comment]
> @amanjain97 yes, if you want to integrate doccano in your system, you might use a different tokenzer, therefore you might want to load it as a token list and not as a text.

If the raw text is loaded as a list of token's will the annotators be able to see the context?

**Comment by Hironsan** [comment]
We released [doccano-transformer](https://github.com/doccano/doccano-transformer). It supports data transformation. Currently, supported tasks are named entity recognition and supported formats are CoNLL2003 and spaCy. 

We have a plan to extend tasks and formats.
Please look forward to it.
