### ISSUE TITLE
Unable to perform NER

### ISSUE THREAD

**Issue by pikapi-code** [doccano/doccano#1420]
I deployed doccano on docker and heroku, in both the cases, after adding the labels, when i try to annotate the text it does not suggests me the labels. Am i missing something?

![image](https://user-images.githubusercontent.com/18028128/122635414-700ced80-d101-11eb-9408-1a648f4b5f65.png)

**Comment by EnzoNclt** [comment]
Have you well configured your project as Sequence Labelling ? It might seems like a stupid question but i had the same issue at the very beginning

**Comment by pikapi-code** [comment]
No, i have created a text classification project. After importing the data and adding the labels, when i try to annotate the data, it does not suggest me any labels when i select the text i want to annotate.

**Comment by EnzoNclt** [comment]
That's why the labels aren't suggested on highlighting. For what i've understand text classification is only for labeling an entire example, and not a single entity. Try to reconfigure / recreate your project as Sequence Labeling

**Comment by pikapi-code** [comment]
OooOoooh, thanks a lot. These project types are really confusing. Its working now :)
