### ISSUE TITLE
Feature Request: Add AutoLabelingConfig to admin UI

### ISSUE THREAD

**Issue by uklft** [doccano/doccano#1423]
As far as i've seen there is no way to alter an existing Autolabeling Configuration except in the database, which makes it tedious to debug a pipeline.
It should be pretty easy to include editing these through the Admin UI:

```python
class AutoLabelingConfigAdmin(admin.ModelAdmin):                
    list_display = ('project', 'model_name', 'model_attrs',)    
    ordering = ('project',)                                     
                                                                
    def get_readonly_fields(self, request, obj=None):           
        if obj:                                                 
            return ["model_name"]                               
        else:                                                   
            return []                                           
                                                                
admin.site.register(AutoLabelingConfig, AutoLabelingConfigAdmin)
```

Which would give you:
![doccano-autolabel-admin](https://user-images.githubusercontent.com/35134759/122774733-c0bf4a80-d2a9-11eb-8bfb-249a2c330850.png)

If this is appreciated i would be happy to create a MR :)

**Comment by EnzoNclt** [comment]
Moreover if this feature could be integrated in the wrapper with doccano_api_client it would be really great imo

**Comment by uklft** [comment]
> Moreover if this feature could be integrated in the wrapper with doccano_api_client it would be really great imo

This is currently beyond my scope, but probably i will be using the doccano_api_client soon. Maybe i can add this to the client then.
