### ISSUE TITLE
Autolabeling not triggered automatically

### ISSUE THREAD

**Issue by uklft** [doccano/doccano#1426]
In the current master branch, the Autolabeling feature is not triggered when enabled on a document.
Only if i go to the next page and back to the original page the function is called and the annotations appear.

Probably was introduced [here](https://github.com/doccano/doccano/pull/1413), as it is working (for me) in 1.4.1.

How to reproduce the behaviour
---------

* Register an AutoLabelingConfig for a Sequence Labeling Project
* Open a document
* Hit `Auto Labeling` and flick the switch
* --> Nothing happens
* Go to next page and back to original page
* --> Labels are there

Also auto labeling is triggered by marking the Document as "Checked" though the UI.

Your Environment
---------
*   Operating System: Docker dev image on Manjaro Linux
*   Python Version Used: 3.8.6
*   When you install doccano: Few days ago
*   How did you install doccano (Heroku button etc): git clone

**Comment by Jian1273** [comment]
Because you use spacy api, the NER task has many labels, you should create all the labels。

**Comment by uklft** [comment]
I'm afraid this is not the issue, i verified this with a different API.

**Comment by daleevans** [comment]
I have noticed this as well, using a custom REST labeler which I personally operate.  When auto-labeling is turned on, doccano responds with an empty list of labels, and does not in fact hit my REST endpoint.  It only actually hits my REST endpoint when you navigate between examples.
