### ISSUE TITLE
Installation on Heroku - cannot add projects, cannot add new text or annotate

### ISSUE THREAD

**Issue by avtaylor** [doccano/doccano#1427]
How to reproduce the behaviour
---------
I have a Heroku Installation with a few projects I installed mainy Seq-to-Seq
Since yesterday I cannot add new projects - the buttons to create a project does nothing.
I also cannot import new text - I can select files but they do not get imported 
I also cannot annotate text that is already there.

What can be the problem? 
Many thanks
Amelia

**Comment by avtaylor** [comment]
I am not sure what you mean by this. 
I deployed this on heroku on feb 25th using the on-click button on doccano website.
I am using a free account on heroku

**Comment by Hironsan** [comment]
Confirmed to be able to add projects, new text and annotate it.
