### ISSUE TITLE
What is the problem that I cannot upload my data file on the browser?

### ISSUE THREAD

**Issue by mk0222-deep** [doccano/doccano#1434]
How to reproduce the behaviour
---------
It was succeeded to install and set up doccano, and then the web browser was started. I was able to log in to it with the set username and password, but once I tried to upload my data, the browser always showed a loading notice and it could not finish.
<img width="1084" alt="screen" src="https://user-images.githubusercontent.com/37922160/124371951-9f0a8e00-dcc1-11eb-9a8c-c7ca4b42271f.png">

What is the problem that I cannot upload my data file? 

```bash
$ doccano init
Role created successfully "project_admin"
Role created successfully "annotator"
Role created successfully "annotation_approver"

$ doccano createuser --username admin --password pass
Create admin user.
Superuser created successfully.
Setting password for User admin.

$ doccano webserver --port 8000
Starting server with port 8000.
[2867] [INFO] Starting gunicorn 20.1.0
[2867] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2867] [ERROR] Retrying in 1 second.
...
[2867] [ERROR] Can't connect to ('0.0.0.0', 8000)
```

Upload Data
TextLine
utf_8
sample.txt (65bytes)
```
Terrible customer service.
Really great transaction.
Great price.
```

Your Environment
---------

*   Operating System: Mac OS 11.4, terminal version 2.11
*   Python Version Used: Python 3.9.1 
*   Web Browser: Google Chrome 91.0.4472.114
*   When you install doccano: 3, July, doccano  1.4.1
*   How did you install doccano (Heroku button etc): pip3

**Comment by kim-seokyeung** [comment]
I had the same problem and solved it.

My problem was that the web server was starting, but the task queue was not running.
