### ISSUE TITLE
Text not passed to auto labeling REST endpoint

### ISSUE THREAD

**Issue by JFulweber** [doccano/doccano#1445]
How to reproduce the behaviour
---------

Make a Flask (or other service endpoint) and try to use the Custom REST endpoint.

When using the auto labeling custom REST endpoint, the text is not passed at all. Running a basic Flask service shows that the only things sent are those specified by me, but not the sample text that needs to be passed. 

![image](https://user-images.githubusercontent.com/1341193/125325751-ea96ea80-e306-11eb-8f3e-732826fc4fbb.png)
![image](https://user-images.githubusercontent.com/1341193/125325901-1a45f280-e307-11eb-8883-77c65c059279.png)
![image](https://user-images.githubusercontent.com/1341193/125325927-1fa33d00-e307-11eb-8038-c17dc02f29a7.png)

I would expect to see "wata" somewhere in there, without it the REST endpoint is entirely useless. I can see that there is a request to "auto-labeling-parameter-testing" that looks like this: 
![image](https://user-images.githubusercontent.com/1341193/125326066-43ff1980-e307-11eb-8f1c-e92038983acf.png)
and it has the text, but that is not passed when this is semi-redirected to the server.

Your Environment
---------

Latest docker version on Windows.

**Comment by jmn319** [comment]
Amazing tool so far - thanks for all the help. 

After the labels were stripped from jsonl import, I thought this was a reasonable alternative. I spun up a rest api connected to my model predictions and tried to implement it with the custom rest. I experience the same behavior as above for both get and post requests. Environment = raspbian.

**Comment by lxnch** [comment]
Same here, i was eager to start using some spacy for the auto labeling feature. I wonder if this is an easy fix though.

**Comment by lxnch** [comment]
I think the issue is this https://github.com/doccano/auto-labeling-pipeline/pull/16 !

**Comment by kekayan** [comment]
We have to specify value as `{{ text }}` in body or params for the key of our choice to pass the text to custom endpoint.
for example in body.
`content: {{ text}}` .
