### ISSUE TITLE
The button to deploy to Heroku doesn't work

### ISSUE THREAD

**Issue by mk0222-deep** [doccano/doccano#1456]
How to reproduce the behaviour
---------
I'm trying to install doccano using [the Heroku button ](https://doccano.github.io/doccano/)on the official website.

However, the loading screen doesn't change at all.
Why does it happen and how can I install doccano and deploy to Heroku?

<img width="1152" alt="screen" src="https://user-images.githubusercontent.com/37922160/126727513-f544dbb0-8ba9-4ad8-9be5-780a9d50de4b.png">

Your Environment
---------

*   Operating System: Mac OS
*   Python Version Used: None, Google Chrome version 92.0.4515.107
*   When you install doccano: 23, July
*   How did you install doccano (Heroku button etc): Heroku button

**Comment by DougTrajano** [comment]
Hey buddy! I'm not part of doccano contributors, but I did a Heroku's deployment right now using the same button and it works perfectly. Check your browser cache and if Heroku Cloud works as expected in other projects.
