### ISSUE TITLE
Image and Dependancy version updates

### ISSUE THREAD

**Issue by RSCArt** [doccano/doccano#1461]
Various images and node packages are out of date.
Looking at the docker hub repository for the various images it appears that many of the used images are not even listed in the tags anymore.

Examples:
Python 3.8.6 no longer is listed, newest 3.8.* is 3.8.11
( https://hub.docker.com/_/python )

Node 13.7 is no longer listed, closest is 14
( https://hub.docker.com/_/node )

pipenv 2020.11.15 --> newest is 2021.5.29
( https://pipenv.pypa.io/en/latest/changelog/ )

A large amount of the node packages are also out of date with some of them being deprecated, un-supported, or abandoned.
Example: @babel/eslint has been replaced by @babel/eslint-parser

## Your Environment
 
* Operating System: Ubuntu 20.04 Focal
* Python Version Used: Python 3.8.10
* When you install doccano: July 2021
* How did you install doccano (Heroku button etc): Docker Pull & Docker-Compose

**Comment by Hironsan** [comment]
Fixed by https://github.com/doccano/doccano/pull/1462.
