### ISSUE TITLE
Upload dataset not working when using docker-compose

### ISSUE THREAD

**Issue by CVxTz** [doccano/doccano#1463]
How to reproduce the behaviour
---------
I ran doccano using this command: 
docker-compose -f docker-compose.dev.yml up
And after setting up the project I could not load a dataset in jsonld format or in text format.
After the file upload is done the window keeps charging.

Your Environment
---------

*   Operating System: Docker + Ubuntu 20
*   Python Version Used: Docker-compose py3.8
*   When you install doccano: 31/07/2021
*   How did you install doccano (Heroku button etc): Docker-compose

(note that using docker instead of docker-compose allowed me to have doccano with a working dataset upload feature)

**Comment by Hironsan** [comment]
Solved by https://github.com/doccano/doccano/pull/1500

**Comment by CVxTz** [comment]
Thanks @Hironsan, @tmarice !
