### ISSUE TITLE
How to delete a project when the superuser was not listed under `Users`

### ISSUE THREAD

**Issue by ruian0** [doccano/doccano#1467]
To reproduce the behavior, 
Create a project with a superuser without including the superuser under the `Users`. Now the project won't show under `Projects` tab. It still can be seen using `xxxx/projects/10/` but there is no delete method on this page. 

How to delete the project created in this case?
---------

Your Environment
---------

*   Operating System: 18.04
*   Python Version Used: 3.6.7
*   When you install doccano: 2 years ago
*   How did you install doccano (Heroku button etc): forked from master

**Comment by youichiro** [comment]
In the PR #1453, the Create/Delete Project button is restricted to staff user or superuser.

To display the Delete Project button, please change the user to staff in admin page.

**Comment by Hironsan** [comment]
Please delete by using the admin page.

- https://doccano.github.io/doccano/faq/
