### ISSUE TITLE
Sudden login error on local machine (doccano installed using pip)

### ISSUE THREAD

**Issue by nikamurao** [doccano/doccano#1470]
Login details suddenly not working on local machine
---------

I installed doccano using pip instead of using the docker. It has been working fine since but suddenly I am now unable to login to http://127.0.0.1:8000/. It shows incorrect username and password. 

I tried to create another user using "doccano createuser --username admin --password pass" as suggested in the Github page and it is able to login this new user created but I need to retrieve the work I've already done through my old username and password...

Any idea what's gone wrong? Or how I can retrieve the work I've done? Is it version problems maybe? 
(I looked at other similar issues but most relate to doccano installed using docker or heroku etc.) 

Your Environment
---------

*   Operating System: Mac OS X (10.14.6) / ios
*   Python Version Used: Python 3.8.2
*   When you install doccano: 
*   How did you install doccano (Heroku button etc): pip install doccano

**Comment by brunsk** [comment]
What was the solution @nikamurao
