### ISSUE TITLE
Slow API call when use docker-compose on M1

### ISSUE THREAD

**Issue by huynguyengl99** [doccano/doccano#1482]
How to reproduce the behaviour:
Clone project and use `docker-compose -f docker-compose.dev.yml up` to start.
Go to browser, upload dataset, and start annotation, but the time for API call is very slow (5s).
![image](https://user-images.githubusercontent.com/49433085/131216803-b928ce4c-c24f-4783-8500-8c05d056cf8c.png)

I'm not sure this is caused by my local environment (M1 2020) or there are some issues related to that. If you know about the issue, please help me to fix that.
---------

Your Environment
---------

*   Operating System: Macbook M1 2020 BigSur 11.4
*   Python Version Used: 3.9.4
*   When you install doccano: 20.8.2021
*   How did you install doccano (Heroku button etc): install via git clone.

**Comment by quickstarts-owner** [comment]
It's hard to solve this problem now so I will close it, hope someone fix that in future.

**Comment by huynguyengl99** [comment]
It's hard to solve this problem now so I will close it, hope someone fix that in future.
