### ISSUE TITLE
docker-compose behind a corporate SSL termination proxy

### ISSUE THREAD

**Issue by ofervas** [doccano/doccano#1486]
Is there a way to configure the Doccano docker-compose process to trust our corporate CA when creating the images? alternatively, is there a way to make it ignore certificate verification errors?

I'm working from behind a corporate TLS/SSL termination proxy.
I was able to configure the compose process to use the proxy, but I keep running into errors like "SSL Certificate problem: unable to get local issuer" or CERTIFICATE_VERIFY_FAILED when it is trying to pull down packages from public repositories.
Configuring the proxy to temporarily disable SSL termination form some of the URL's helped, but I keep running into new URL's and the security administrator will not allow to any more changes to the security policy.

**Comment by ofervas** [comment]
I'm running Docker for windows v20.10.7 on Windows 10 21H1

**Comment by Hironsan** [comment]
Duplicate https://github.com/doccano/doccano/issues/983
