### ISSUE TITLE
can not delete the whole dataset in sequence labeling task, when we want to delete it, we can only delete it one by one, otherwise, we can delete whole dataset by deleting this project which cause all labels will need to add once more  

### ISSUE THREAD

**Issue by orangefly0214** [doccano/doccano#1489]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by Hironsan** [comment]
Please use "Clear labels" button.
