### ISSUE TITLE
Relations annotation is here, but is not included in export

### ISSUE THREAD

**Issue by sorenmc** [doccano/doccano#1491]
> The data are stored in the database but still not included in the export. I think the maintainers should study a clever format to add this data to the export.

_Originally posted by @DavideAllavena in https://github.com/doccano/doccano/issues/1384#issuecomment-911692033_

It would be valuable to have the relations tag outputted with the export, as this could be used to train models depending on the relations.

**Comment by Jacse** [comment]
At Firmnav we really needed this feature, so I created a [quick hack](https://github.com/Jacse/doccano/commit/2b366de68c0a0d5225e608347a3ca70321c156f8) which outputs annotation relations for sequence labeling. It only works for sequence labeling and hasn't been tested, so don't use in production!
