### ISSUE TITLE
Too many SQL variables

### ISSUE THREAD

**Issue by koren-v** [doccano/doccano#1507]
*   Operating System: macOS Big Sur v: 11.6
*   Python Version Used: 3.6
*   When you install doccano: Version: 1.4.1
*   How did you install doccano (Heroku button etc): via `pip install doccano`

Hi, I faced the problem described [here](https://github.com/doccano/doccano/issues/82), but for **downloading** the data. The `IMPORT_BATCH_SIZE` variable does not impact on downloading process.

To reproduce you need to try download `jsonl` dataset with more than 2k rows (in my case it was sequence labeling) via doccano. I've launch server via:
```
$ doccano init
$ doccano createuser --username admin --password pass
$ doccano webserver --port 8000
```
and then 
```
$ doccano task
```

**Comment by koren-v** [comment]
+

**Comment by MironKuznetsov** [comment]
Hello! 
I have the same problem. 
@koren-v How did u deal with it?

**Comment by koren-v** [comment]
@MironKuznetsov Hi, thanks for the question - completely forgot to share the solution :(

Basically, do not use Python one-time setup (a least for the old doccano version) if you are going to label a lot of data, this kind of usage was created just to quickly investigate the tool. Instead, consider the Docker Compose option.

If you have already done this mistake (as I did :)) - I found some way to save your labeled data:

(I lost that environment, but I approximately remember the solution)

I changed the source code [here](https://github.com/doccano/doccano/blob/de8d24f5f8b29399d29eda288880f78c6017f937/backend/data_export/pipeline/repositories.py#L119) (I had Sequence Labeling task) to something like:
```
def docs(self):
    results = []
    batch_size = 100
    for start_id in range(0, NUM_EXAMPLES_YOU_NEED_TO_DOWNLOAD, batch_size):
        results.append(
            Example.objects.filter(project=self.project)[start_id: start_id + batch_size].prefetch_related(
                "spans__user", "spans__label"
            )
        )
    return itertools.chain.from_iterable(results)
```

Hope, it will help you...
