### ISSUE TITLE
Can you use doccano for visualising text highlights when the spans are already given?

### ISSUE THREAD

**Issue by joseberlines** [doccano/doccano#1508]
I have a text string and a data structure that gives me already the NERs of the text as such:
```

[{name: 'organization', start:56, lenght: 45},
{name: 'person', start:156, lenght: 23},...]
```

Can I use doccano to visualize (not to annotate) that particuar document?
It would sufice an HTML output with the doccano alike highlighting.

Environement:
Working in jupyter lab Notebooks (part of a jupyter hub Server based enterprise solution)  Python 3.9.

**Comment by joseberlines** [comment]
Edited the question. Thanks.

**Comment by xsway** [comment]
Hi, sorry to barge in but I wanted to do the same thing but it doesn't work. My simple file is of right jsonl format:
```
{"text": "he ordered it on monday.", "label": [[3, 9, "high"], [17, 23, "low"]]}
```
but the labels are not imported, only text
