### ISSUE TITLE
Sentiment analysis demo broken?

### ISSUE THREAD

**Issue by webchick** [doccano/doccano#1526]
Let me preface this by saying this is the very first time I've tried doccano, so I could TOTALLY be missing something, but nevertheless...

How to reproduce the behaviour
---------
1. Go to http://doccano.herokuapp.com/demo/sentiment-analysis
2. Highlight a piece of text there

Expected behaviour: A contextual pop-up appears (this is what happens in the Named Entity Recognition demo)
Actual behaviour: Nothing happens. Nor does clicking in "positive" or "negative" labels seem to do anything.

(Side-note: https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions referenced in the issue template is not found.)

Your Environment
---------
I have tried this in both Chrome Version 94.0.4606.81 (Official Build) (x86_64) and Firefox 93.0 (64-bit) on MacOS Catalina 10.15.7 (19H1419) but the same issue occurs in both.

In case it is relevant to the problem, Web Developer Console in Firefox shows:

GET http://doccano.herokuapp.com/v1/me HTTP/1.1 403 Forbidden 79ms

**Comment by Hironsan** [comment]
The demo is a text classification demo. So you can't select a piece of text.
If you want to label a piece of text, please select the sequence labeling project.
