### ISSUE TITLE
Frontend in docker-compose dev installation does not work in v1.5.0

### ISSUE THREAD

**Issue by ghontolux** [doccano/doccano#1536]
How to reproduce the behaviour
---------

`doccano-frontend-1` container exits after installing the dev environment with `docker-compose -f docker-compose.dev.yml --env-file ./config/.env.example up` with the following error message:

```
env: can't execute 'bash': No such file or directory
```

That is probably caused by the node image `node:16.5-alpine3.14` in `docker-compose.dev.yml`, which does not include `bash`.

I got this problem only for doccano `v1.5.0`.

Your Environment
---------

*   Operating System: MacOS
*   Python Version Used: 3.8.11
*   How did you install doccano (Heroku button etc): `docker-compose -f docker-compose.dev.yml --env-file ./config/.env.example up`

**Comment by githubfzq** [comment]
> Thanks, that is one step ahead. Unfortunately the building was aborted during the frontend installation on my system:
> 
> ```
> Installing dependencies
> 
> yarn install v1.22.5
> 
> [1/4] Resolving packages...
> 
> [2/4] Fetching packages...
> 
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> error Couldn't find the binary git
> ```

I have the same problem.
