### ISSUE TITLE
Import multi-label JSON leads to single label of combined labels

### ISSUE THREAD

**Issue by shensmobile** [doccano/doccano#1537]
Currently trying to import a JSON for a text classification task.  An example entry in my JSON would be like this:
{"text": "This is some sort of text blah blah blah.", "labels": ["Type 1", "Type 2"]}

I would expect the imported text to have two labels applied, but instead it has a single label called "Type 1 Type 2"

Is there an easy fix for this?  Should I use a different import format?  I tried CSV at first but [this page](https://github.com/doccano/doccano/wiki/Import-and-Export-File-Formats) indicated that CSV was single-label only, so I switched to JSON but I'm getting the same result.  

Set up using Docker on Linux.

**Comment by Weber12321** [comment]
Hi, 
Did you fixed the problem about mixing labels? 
I got the same problem with you.

**Comment by shensmobile** [comment]
Hi,
My issue was actually in that I had ingested a previously bad data file with mixed up labels.  If you're using a JSON with the right label format, it should produce proper labels in Doccano.  I've since switched to a different labelling platform, but if you could post a sample of your JSON, that would help us review.

**Comment by Weber12321** [comment]
> Hi, My issue was actually in that I had ingested a previously bad data file with mixed up labels. If you're using a JSON with the right label format, it should produce proper labels in Doccano. I've since switched to a different labelling platform, but if you could post a sample of your JSON, that would help us review.   
  
Hi, I have solved the problem, just like you mentioned, the main reason of causing mixing labels is wrong label format uploading.    
[My problem](https://stackoverflow.com/q/72643207/13345077) and [solution], hope it may help others ppl.
