### ISSUE TITLE
Celery: Watchmedo command not found

### ISSUE THREAD

**Issue by TTitcombe** [doccano/doccano#1546]
How to reproduce the behaviour
---------

Running Doccano via docker-compose (`docker-compose -f docker-compose.dev.yml --env-file ./config/.env.example up`), I can connect to the frontend, login and begin to create a task. However when I click "ingest" when uploading a dataset, I get a permanent spinning icon as in #1353. Looking at the logs from docker-compose, Celery exited, which may have caused the silent failure on data ingestion

```bash
doccano-celery-1    | Starting celery
doccano-celery-1    | /src/tools/dev-celery.sh: line 11: watchmedo: command not found
doccano-celery-1 exited with code 127
```

Your Environment
---------

*   Operating System: Windows
*   Python Version Used: 3.9
*   When you install doccano:
*   How did you install doccano (Heroku button etc): Docker-compose

**Comment by Hironsan** [comment]
I found how to reproduce this problem:

```bash
# First, up the prod containers
docker-compose -f docker-compose.prod.yml --env-file ./config/.env.example up

# Second, down the containers
docker-compose -f docker-compose.prod.yml --env-file ./config/.env.example down

# Then, up the dev containers
docker-compose -f docker-compose.dev.yml --env-file ./config/.env.example up
...
celery_1    | Starting celery
celery_1    | /src/tools/dev-celery.sh: line 11: watchmedo: command not found
doccano_celery_1 exited with code 127
```

**Comment by Hironsan** [comment]
This can be solved by tagging image:

```yaml
build:
      context: .
      dockerfile: backend/Dockerfile.prod
image: doccano_backend:prod
```
