### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by johnbisc** [doccano/doccano#1547]
How to reproduce the behaviour
---------
after installing the first part 
this command "doccano task"  is bringing this issue:

```
  File ".....  \lib\site-packages\celery\app\trace.py", line 635, in fast_trace_task
    tasks, accept, hostname = _loc
ValueError: not enough values to unpack (expected 3, got 0)
```

Meaning after uploading an xls file (csv is not working),  we can ingest it but the values are not keeped  

I installed the docker via the pip command in a conda environment
os - windows 64 , python 3.10

**Comment by Hironsan** [comment]
This problem is related to the following issue:

- https://github.com/celery/celery/issues/4178

Solved in the following PR:

- https://github.com/doccano/doccano/pull/1552
