### ISSUE TITLE
Can you give a tutorial on running the code locally, because I want to develop it again.

### ISSUE THREAD

**Issue by anyi3c** [doccano/doccano#1553]
Can you give a tutorial on running the code locally, because I want to develop it again.

Your Environment
---------

*   Operating System:Ubuntu18
*   Python Version Used:python3.6
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by ghontolux** [comment]
I think that is still in the documentation. You have two possibilities:

# 1. Docker-Dev Evironment as described in the readme

### Development

Set the superuser account credentials in the docker-compose.dev.yml file:

```
ADMIN_USERNAME: "admin"
ADMIN_PASSWORD: "password"
```

Run Doccano:

```
$ docker-compose -f docker-compose.dev.yml --env-file ./config/.env.example up
```
Go to [http://127.0.0.1:3000/](http://127.0.0.1:3000/).

Run Backend API-Tests:

You can run the API-Tests for the backend with the following command:

```
docker exec doccano_backend_1 pipenv run app/manage.py test api
```

# 2. Setup a local environment as described in [docs/getting-started.md](https://github.com/doccano/doccano/blob/master/docs/getting-started.md)


Or, you can setup via Python and Node.js:
### Python

```
git clone https://github.com/doccano/doccano.git
cd doccano
pipenv sync --dev
pipenv shell
cd backend
python manage.py migrate
python manage.py create_roles
python manage.py create_admin --noinput --username "admin" --email "admin@example.com" --password "password"
python manage.py runserver
```

In another terminal, you need to run Celery to use import/export dataset feature:

```
cd doccano/backend
celery --app=app worker --loglevel=INFO --concurrency=1
```

### Node.js

```
cd frontend
yarn install
yarn dev
```

**Comment by TATOAO** [comment]
Hi, I'm having an issue running the backend environment: 
pipenv sync --dev
ERROR: Pipfile.lock not found!
