### ISSUE TITLE
Text Not Coming in a Single Line

### ISSUE THREAD

**Issue by Gul11** [doccano/doccano#1555]
Installed Doccano on docker using below commands -

```bash
docker pull doccano/doccano  
docker container create --name doccano   -e "ADMIN_USERNAME=admin"   -e "ADMIN_EMAIL=admin@example.com"   -e "ADMIN_PASSWORD=password"   -p 8000:8000 doccano/doccano
docker container start doccano
```

after importing data in dataset, when I go to 'annotate' I am getting text like this -

![image](https://user-images.githubusercontent.com/31441117/141134021-f9d40196-b676-4ec0-9422-8635d70d394a.png)

**Comment by Gul11** [comment]
environment is docker (hosted on ubuntu 18.04)

**Comment by Hironsan** [comment]
Hi, @Gul11 

I tried to reproduce the problem but I can't do that.
Can you give me the example data that can reproduce your problem? In addition, I want to know your browser and the version.

Thanks

![image](https://user-images.githubusercontent.com/6737785/141201143-6367cd8a-3908-4b17-bf3a-690fd1eb7a24.png)
