### ISSUE TITLE
Sequence Labeling with relationship linking

### ISSUE THREAD

**Issue by Upasna22** [doccano/doccano#1559]
How to reproduce the behaviour
---------
I wasnt able to achieve entity linking with the Sequence Labeling method, as shown in the demo.
How do we achieve this with Doccano ?

Example : 
{"text": "Before launching V-Bio Ventures, Christina was a partner at Forbion Capital Partners (previously ABN AMRO Capital) were she led and managed a series of successful investments in biopharmaceutical and pharmaceutical companies.", "label": [ [17, 31, "ORG"],[60,84,"ORG"],[97,113,"ORG"] ], "relation": [[ "V-Bio Ventures"," Christina was a partner at ", "Forbion Capital Partners"],["V-Bio Ventures"," Christina was a partner at Forbion Capital Partners (previously ","ABN AMRO Capital"],["Forbion Capital Partners", "(previously ", "ABN AMRO Capital"]]}

Using Docker to setup Doccano.

**Comment by Hironsan** [comment]
Currently under development. Please wait.

- https://github.com/doccano/doccano/pull/1511
