### ISSUE TITLE
After the deployment is successful, 0.0.0.0:port is inaccessible, but 127.0.0.1:port is accessible

### ISSUE THREAD

**Issue by GuocaiL** [doccano/doccano#1567]
How to reproduce the problem
---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by GuocaiL** [comment]
**How to reproduce the problem:**
doccano webserver --port 8000

**my Environment**
Operating System:wsl
Python Version Used:python:3.8
When you install doccano:doccano1.5.2
How did you install doccano (Heroku button etc):  pip install

**Comment by Hironsan** [comment]
`0.0.0.0` is not accessible in some operating systems. In that case, please use `127.0.0.1`.

- [how do I get 0.0.0.0 to resolve to localhost when browsing a url that contains 0.0.0.0?](https://superuser.com/questions/536156/how-do-i-get-0-0-0-0-to-resolve-to-localhost-when-browsing-a-url-that-contains-0)
