### ISSUE TITLE
Feature request: add a autocomplete in annotation menu

### ISSUE THREAD

**Issue by zxjlm** [doccano/doccano#1569]
---------
I have a project with many labels like this.

![Feature description](https://tva1.sinaimg.cn/large/008i3skNly1gwmy3x1wahj30cv0cq3z4.jpg)

Although we have short key, but when we have many labels startswith the same alpha, it is still not convenient.

so, may be this project need a autocomplete feature, labeling will be much easier with this.

I am a quite rookie of vue, but used to use react. if you need the feature but not have time to do it, i may take a try.

---------

**Comment by Hironsan** [comment]
May be helpful:
- https://vuetifyjs.com/en/components/autocompletes/

The another way is to introduce the prefix keys such as Carl, shift, alt, and so on. This will help to increase the number of shortcut keys.

**Comment by zxjlm** [comment]
> The another way is to introduce the prefix keys such as ctrl, shift, alt, and so on.

This is something i didn't notice. Thanks~
