### ISSUE TITLE
Cannot import data to postgres back DB

### ISSUE THREAD

**Issue by ygbingo** [doccano/doccano#1586]
# How I deploy doccano?

I deploy it on k8s and use image like this:
```Dockerfile
FROM python:3.8

RUN pip install doccano
RUN pip install psycopg2

ENV DATABASE_URL=postgres://***:***@***:***/***?sslmode=disable

RUN doccano init
RUN doccano createuser --username admin --password password
RUN doccano webserver --port 8000

```

And when I deploy my deployment It'll auto create some table in my database.

# What I got?
1. I create a project.
2. import data as txt file.
And then I got a waiting symbol and never complete. Can anyone give me some suggestion?

![image](https://user-images.githubusercontent.com/11473732/144579857-c9dbd3e3-2a6b-44d9-9f38-709ebf2b3ac0.png)

**Comment by ygbingo** [comment]
> 

yes, and I got these log at first.

![image](https://user-images.githubusercontent.com/11473732/144580170-ab841ff9-1c3b-4909-97c2-1e2acfb41d08.png)

**Comment by Hironsan** [comment]
Please run `doccano task`. Don't forget to set `DATABASE_URL`.
