### ISSUE TITLE
failed to add new relations by docker

### ISSUE THREAD

**Issue by floyddcn** [doccano/doccano#1593]
docker image:
doccano/doccano                              latest
docker version:
20.10.10

system:
Linux floyd-ubt 5.13.0-16-generic #16-Ubuntu SMP Fri Sep 3 14:53:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Just get nothing when i intend to add a new relation.Here is the screen snapshot
======
![image](https://user-images.githubusercontent.com/48442748/145565810-99095dfb-445b-4a90-abe0-056b97e7040c.png)
![image](https://user-images.githubusercontent.com/48442748/145565857-25a14adf-379c-4e9b-8b74-87ed9cedfc35.png)

**Comment by floyddcn** [comment]
i have post my system environment above,and i use the **doccano/doccano:latest** docker image. Besides,i also install the doccano==1.5.5 by pip ,but still got the errors above.Is the relation annotating function still under developing and not available yet?

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/pull/1511#issuecomment-957029516
