### ISSUE TITLE
Include extra columns when importing/exporting dataset

### ISSUE THREAD

**Issue by itaim** [doccano/doccano#1594]
Feature description
---------
I would like to map the data back to the original rows so I can add other columns in case of multimodal classification.
So would like to include `id` column in the import and export of the data.

**Comment by Hironsan** [comment]
I want to know the example.

**Comment by itaim** [comment]
We have an emails dataset where we want to combine the email subject and body text with tabular features like communication volume by department for a given month. We would like to use https://github.com/georgian-io/Multimodal-Toolkit or some similar model for classification.

**Comment by PauToroIsaza** [comment]
If I understand what you want correctly, the feature already exists. You can include meta data such as `id` when importing the dataset. It will show up on the table to the right. Here's an example.

<img width="1172" alt="Screen Shot 2022-03-03 at 9 34 52 AM" src="https://user-images.githubusercontent.com/54859106/156586267-677ef961-d498-4852-95d2-e0274101177f.png">

You can give the additional columns any name. Just make sure when importing that you select the right column for the annotation text.

Here's what the JSON looks like:
```
{
"text":"The text that you actually want to annotate.",
"number":"Some ID",
"annotator_1":"Paulina",
"annotator_2":"Selina",
"description":"You can also put text that might be helpful for the annotator, but that you don't want annotated."
}
```

**Comment by roonbug** [comment]
Hi, but this hard to do as a user. My annotation depends on multiple column values, for eg. comparing columns 1 and 2. I'd also like to ignore a set of columns from the CSV so they don't appear on the UI.
