### ISSUE TITLE
Cannot import exported JSONL

### ISSUE THREAD

**Issue by rjalexa** [doccano/doccano#1605]
How to reproduce the behaviour
---------
I am exporting an annotated dataset to JSONL. The resulting file (after unzipping) is all.jsonl. It is a valid UTF-8 encoded file. It has valid JSON Lines rows as validated by an online JSON linter

If I try re-importing without any edits this file into a new project I get:

Filename: /backend/media/Z2KHk8u6mekET3fWDYpxcV/b55k5z4bKd8rdmGKXerEAb/all.jsonl 
line:  -1 
message: ParseError: You cannot parse line 1 in /backend/media/Z2KHk8u6mekET3fWDYpxcV/b55k5z4bKd8rdmGKXerEAb/all.jsonl: text does not exist.

I also tried simplifying the offending file to the bare minimum and am attaching it as a sample file along with the original untouched export file.

Your Environment
---------

*   Operating System: macOS Monterey
*   Python Version Used: system has 3.8.5 but using container
*   When you install doccano: 21/Dec/2021
*   How did you install doccano (Heroku button etc): docker-compose

[Archive.zip](https://github.com/doccano/doccano/files/7768994/Archive.zip)

**Comment by rjalexa** [comment]
I have to update this since I have found the (human) error.
The default name of the expected data field was wrong. My JSONL had "data" as generated by DOCCANO while the import dialog expected a "text" field name. So once you understand this the fix is very easy and all is imported correctly. Maybe the "text does not exist" message was a bit misleading and a "text JSON label expected but not found" would have been easier to understand.
Please close as you wish.
Thank you.

**Comment by gilokip** [comment]
> I have to update this since I have found the (human) error. The default name of the expected data field was wrong. My JSONL had "data" as generated by DOCCANO while the import dialog expected a "text" field name. So once you understand this the fix is very easy and all is imported correctly. Maybe the "text does not exist" message was a bit misleading and a "text JSON label expected but not found" would have been easier to understand. Please close as you wish. Thank you.

Yes. I agree with you. For Jsonl exports you get 'data' as a key instead of 'text'. When transforming you get KeyError: 'text'. I would suggest manually changing the key from 'data' to 'text'. Doccano should update to export keys as 'text' instead of 'data'.
