### ISSUE TITLE
Unable to log in to admin account

### ISSUE THREAD

**Issue by Lucky-w0y** [doccano/doccano#1607]
After running doccano webserver, login to the admin site via http://localhost:{port}/admin/. When I input the username admin and the password password,It always notes that:
Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.
I don't understand.

Your Environment
---------
docker image:
doccano/doccano latest

**Comment by Juanvulcano** [comment]
Same! I get a 502 Bad Gateway when trying to go to the admin site.
