### ISSUE TITLE
Statistics (User stats) showing incorrect count

### ISSUE THREAD

**Issue by lucaseo** [doccano/doccano#1645]
How to reproduce the behaviour
---------

Hello,

I'm facing a but when the `User Stats` does not match with the actual user annotation statistics.

Please refer to the attached screenshot. (I have added the number since the number only shows in mouse point hover)

<img width="2233" alt="Screen Shot 2022-01-20 at 10 41 57 AM" src="https://user-images.githubusercontent.com/32409791/150249602-161f0a97-bd27-4326-b451-ecd384e1930e.png">

Currently there are 3 members participating in annotation project. 
- 2 Project Admin
- 1 Annotation Approver

According to Pie Chart, the Annotation Approver seems to have completed annotation for 497 samples, as Project Admins have completed 565 samples in total.

However, the `User Stats` show different numbers. (as below)
- Annotation Approver 497 != 490
- Project Admins 565 != (490 + 7)

I do not know where this problem is driven from.
Is there a limit to only show maximum 490 samples in `User Stats` ? (Viewing correct annotation status for each user is essential in our operation.)

Thanks

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: Python 3.8.2
*   When you install doccano: September 15th 2021.
*   How did you install doccano (Heroku button etc): By following the instructions in documentation Docker (`docker pull`, `docker container create`, `docker container start` ) on Azure VM

**Comment by Hironsan** [comment]
The latest metrics are changed as follows:

![image](https://user-images.githubusercontent.com/6737785/150464555-294e8a64-cebd-41d1-88c1-784a24de8e93.png)

**Comment by lucaseo** [comment]
@Hironsan 

I have 2 follow up quetions

1. Is this the latest release? I have pulled the lastest docker image, however

**Comment by lucaseo** [comment]
@Hironsan 

I have follow up questions, 

I don't understand what you meant by 'latest metrics'

Is your answer saying that the latest Statistics page layout has changed as you posted?  
Or, the method of metrics has changed? 

I have pulled the lastest docker image, however it shows the same layout.

**Comment by Hironsan** [comment]
Please try nightly:

```bash
docker pull doccano/doccano:nightly
```
