### ISSUE TITLE
A created label is not displayed in the label list page.

### ISSUE THREAD

**Issue by youichiro** [doccano/doccano#1648]
A created label is not displayed in the label list page.
It displays when I reload the page.

**Comment by Hironsan** [comment]
I want to know which version(v1.5.5?) and task to reproduce the problem.

**Comment by youichiro** [comment]
version is v1.5.5

steps
- open `/projects/1/labels`
  - <img width="1274" alt="スクリーンショット 2022-01-23 13 55 48" src="https://user-images.githubusercontent.com/20487308/150665484-60a66d13-947a-4c92-ba95-66063d07d32b.png">

- create a new label (input text and click a save button)
  - <img width="1276" alt="スクリーンショット 2022-01-23 13 56 40" src="https://user-images.githubusercontent.com/20487308/150665501-e5572e3f-a7d7-46ff-a950-63014cc634ae.png">
- The modal closes, but does not display in label list.
  - <img width="1275" alt="スクリーンショット 2022-01-23 13 57 37" src="https://user-images.githubusercontent.com/20487308/150665572-8f005e98-b469-493c-8085-b3191f91a43e.png">
- Reloaded 
  - <img width="1277" alt="スクリーンショット 2022-01-23 13 59 34" src="https://user-images.githubusercontent.com/20487308/150665676-4a725862-cf13-4fc4-b371-307ce98999bf.png">

**Comment by lucaseo** [comment]
I encountered the same bug in `doccano/doccano:lightly` version.

Also, 
I added the shortkey and clicked "Save", but it does not show nor applied when annotation.

1. add shortkey
<img width="1636" alt="Screen Shot 2022-01-24 at 1 44 37 PM" src="https://user-images.githubusercontent.com/32409791/150723419-680acb18-a0ab-4926-92d5-bf0a8f8a0e9f.png">

2. not reflected
<img width="1646" alt="Screen Shot 2022-01-24 at 1 44 51 PM" src="https://user-images.githubusercontent.com/32409791/150723429-dfaac411-8ec6-459b-a1bd-0d26a1b050c3.png">


My environment. 
======================================
Operating System: Ubuntu 18.04
Python Version Used: Python 3.8.2
When you install doccano: January 21st 2022.
How did you install doccano (Heroku button etc): By following the instructions in documentation Docker (docker pull, docker container create, docker container start ) on Azure VM

**Comment by Hironsan** [comment]
I could reproduce the problem and fixed in https://github.com/doccano/doccano/pull/1664.
