### ISSUE TITLE
I can't add members in the Django admin page.

### ISSUE THREAD

**Issue by youichiro** [doccano/doccano#1651]
I can't add members in the Django admin page.

steps
- Add a member in the admin page (click a SAVE button).
  - <img width="1273" alt="スクリーンショット 2022-01-27 9 52 17" src="https://user-images.githubusercontent.com/20487308/151271702-bf60ae7e-f131-45fe-8314-e7726e90f90c.png">
- However, I get a 500 error.
  - <img width="1085" alt="スクリーンショット 2022-01-27 9 53 08" src="https://user-images.githubusercontent.com/20487308/151271872-c3fa75e8-c491-4aff-b88e-c9d970406ede.png">
- The endpoints of the POST request are different between admin page and member page.
  - `POST /admin/members/member/add/`
  - `POST /v1/projects/1/members`

Environment
---------
doccano v1.5.5

**Comment by Hironsan** [comment]
Thanks! Fixed.

**Comment by jongyuni** [comment]
same problem...
