### ISSUE TITLE
Pagination of the project list

### ISSUE THREAD

**Issue by youichiro** [doccano/doccano#1666]
When fetching projects in the project list page, is it intentional that all projects are fetched at once even though there is pagination?

Endpoint of project list fetching: `/v1/projects`

When there are a lot of projects, it takes a long time to display them.

Your Environment
---------
doccano v1.5.5

**Comment by Hironsan** [comment]
Yes. It's intentional.
I thought we didn't join too many projects.

Do you think it should be paginated? It's relatively easy.

**Comment by youichiro** [comment]
I think it should be paginated on fetching.
Even if there are fewer projects, pagination does not let performance lower.

**Comment by Hironsan** [comment]
Enable to paginate projects by #1668. The response is changed.
