### ISSUE TITLE
Database table for SpanType has invalid name 

### ISSUE THREAD

**Issue by to-bee** [doccano/doccano#1669]
How to reproduce the behaviour
---------
- Pull latest changes from master
- ./manage.py migrate
- ./api/migrations/0033_auto_20220127_0654.py will migrate the database table for `SpanType` to `label_types_spanType`
- Delete a project `Project.objects.first().delete()``

Exception:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/6747788/152384221-a6a549b8-1cca-49c0-86e4-6a20f7d0a266.png">
 
The issue can be resolved by either renaming db table `label_types_spanType` to `label_types_spantype` or by explicitly setting `tb_table` for SpanType model like this: `db_table = "label_types_spanType"`

Your Environment
---------
*   Operating System: macOS Monterey, doccano is locally executed
*   Python Version Used: 3.9

**Comment by Hironsan** [comment]
Thanks! Fixed https://github.com/doccano/doccano/pull/1670
