### ISSUE TITLE
the type of IntentDetectionAndSlotFilling cannot export data

### ISSUE THREAD

**Issue by veenmakron** [doccano/doccano#1692]
How to reproduce the behaviour
---------
clone：
`git clone https://github.com/doccano/doccano.git`

update：
`vim docker/docker-compose.prod.yml`
replace nginx  ports 80 to 18000

then run：
`docker-compose -f docker/docker-compose.prod.yml --env-file ./docker/.env.example up`

export data：
`{"id": 1, "text": "But in a late-night tweet from Brussels, the US president reiterated his criticism.", "cats": [], "entities": []}`

![image](https://user-images.githubusercontent.com/99934890/154605178-1d86fc5c-b1ff-40ed-9a90-56c02e2b007f.png)
![image](https://user-images.githubusercontent.com/99934890/154605244-e21339f6-2a18-4594-aeef-c9a76ce7a31b.png)
![image](https://user-images.githubusercontent.com/99934890/154605267-c5507879-9ac5-4eb1-8c78-3146a2abecd0.png)

Your Environment
---------

*   Operating System: docker-compose

**Comment by Hironsan** [comment]
Fixed https://github.com/doccano/doccano/pull/1764
