### ISSUE TITLE
No Role Defined

### ISSUE THREAD

**Issue by guipaiva** [doccano/doccano#1701]
I'm experiencing a bug while managing the role mappings. I can't assign a member to a renamed role, as it shows "No Role Defined" even when in the Admin site it shows the correct role.

How to reproduce the behaviour
---------
- Edit role name in the admin site
- Try to assign the role to a member in doccano site

### Admin site:
![image](https://user-images.githubusercontent.com/48967900/155359293-e900be8e-dfed-4a73-96d7-3cd1c99c2e47.png)

### Docanno site: 
![image](https://user-images.githubusercontent.com/48967900/155352257-a071076e-daae-417a-96ce-84e9da805256.png)

### Trying to change roles:
![image](https://user-images.githubusercontent.com/48967900/155352369-23c05058-3580-4fca-89b6-596bd05d4bae.png)

Your Environment
---------
*   Operating System: 18.04
*   Python Version Used: 3.6
*   When you install doccano: Dec/2021
*   How did you install doccano (Heroku button etc): Docker

**Comment by Hironsan** [comment]
Cannot change the role name.
