### ISSUE TITLE
"delete all" improve

### ISSUE THREAD

**Issue by Tlntin** [doccano/doccano#1704]
When i click delete all, all data is erased.
But, one time i just want to erase one data when i click "delete all".

How about give secondary reminders, and take data to Recycle Bin when I want to use "delete all".
Also, I can just delete one sample by outside website but not lable website, when i found the sample data is bad.
Can you add a delete button to erase one sample data  in the lable website?

**Comment by Hironsan** [comment]
Isn't `Delete` button enough for you?

![](https://i.gyazo.com/850d15b874c26a7239740798b05c3d3d.gif)

**Comment by Tlntin** [comment]
i want't delete the data when i was in label mode.
but now, it's just has delete label button.

**Comment by Tlntin** [comment]
> Isn't `Delete` button enough for you?
> 
> ![](https://camo.githubusercontent.com/e239bba238917e5406c126c7566d1a7c6ba3858bb4eea9513315c80c532993ec/68747470733a2f2f692e6779617a6f2e636f6d2f38353064313562383734633236613732333937343037393862303563336433642e676966)

i want't delete the data when i was in label mode.
but now, it's just has delete label button in label mode.
I know this function delete one data, but today it was accidentally click "deleted all", and I didn't receive any second reminder.

**Comment by Hironsan** [comment]
Duplicate to https://github.com/doccano/doccano/issues/1912
