### ISSUE TITLE
Image annotation tool not working

### ISSUE THREAD

**Issue by das-mithun** [doccano/doccano#1705]
I deployed docanno on Heroku. For image annotation, while I am uploading the image for annotation it is not showing. The image is uploaded, but while labeling the image cannot be seen.
---------
I tried the default setting to deploy it in Heroku. Can anyone please help me how to resolve the issue?

**Comment by das-mithun** [comment]
It is not dependent on my environment.

**Comment by Hironsan** [comment]
Fixed https://github.com/doccano/doccano/pull/1667
