### ISSUE TITLE
can not add user

### ISSUE THREAD

**Issue by dancinghui** [doccano/doccano#1707]
when  i want to add a new user,the save button does not work
![image](https://user-images.githubusercontent.com/13185277/156114115-3ac94d60-84de-4300-99f6-b9d9f74af444.png)

THE Environment
---------
*   Operating System:win10
*   Python Version Used:3.8.12
*   When you install doccano:2022.3.1
*   How did you install doccano (Heroku button etc):pip

**Comment by kindziora** [comment]
you have to create your users here: http://127.0.0.1:8000/admin/
