### ISSUE TITLE
How to import the relations in sequence labelling project?

### ISSUE THREAD

**Issue by BladeSun** [doccano/doccano#1715]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/1561122/156551922-d101d826-5851-4fdb-9e2f-b2ce1ce01331.png">
When I try to import the annotated data in the sequence labelling project (with relations), i can only set the **column label** to one specific value.
In this way, only entities can be imported.

**Comment by Hironsan** [comment]
Currently, there is no way to import relations.
