### ISSUE TITLE
Doccano is not exporting data set after SequenceLabeling

### ISSUE THREAD

**Issue by Daremitsu1** [doccano/doccano#1724]
Hello,

I have annoted a dataset using Doccano Sequence Labelling. However it is not exporting the data set. It is exporting only in the case of approved documents and even then it is downloading a blank file. Tried using windows chrome/firefox and yet the same problem remained.

*   Operating System: Windows 10
*   Python Version Used: 3.8
*   When you install doccano: today
*   How did you install doccano (Heroku button etc): command line

**Comment by Eric8932** [comment]
I met the same problem using chrome/firefox, solved it  using edge.

**Comment by Tradunsky** [comment]
Cannot reproduce on the latest doccano docker version.
I created Sequence Labelling project and annotated one sample as admin role, then exported the dataset without clicking on `Exporting only annotated samples` checkmark, here is what I had in the file I downloaded:
![image](https://user-images.githubusercontent.com/4522842/158698796-6be54c2e-f3e0-4d38-bb28-a38e0529049b.png)

**Comment by Daremitsu1** [comment]
> Cannot reproduce on the latest doccano docker version. I created Sequence Labelling project and annotated one sample as admin role, then exported the dataset without clicking on `Exporting only annotated samples` checkmark, here is what I had in the file I downloaded: ![image](https://user-images.githubusercontent.com/4522842/158698796-6be54c2e-f3e0-4d38-bb28-a38e0529049b.png)

I am not using  any docker version. I have tried to export the dataset after annoting them but even in chrome/firefox/edge nothing is being exported.

**Comment by dhirajsuvarna** [comment]
Yes, this is an issue. 
After clicking the "Export" button, the file gets exported to `C:\Users\<username>\doccano\media` with the filename `all.jsonl`.

However, the data present in it is truncated to contain only 23 lines. doccano is not exporting more than 23 lines!!!

**Comment by Hironsan** [comment]
I can export the long file(more than 23 lines).

In any way, some reproducible procedure is required to fix the problem.

**Comment by dhirajsuvarna** [comment]
@Hironsan  
I got the issue in my case - 

It is exporting only 23 lines because on the 24th Line its getting an error - 
```
50e367] raised unexpected: UnicodeEncodeError('charmap', '{"id": 640, "data": "2000 2ml 22G x 1 1/4\\" (0.7 x 30mm) 1234567 YYYY-MM-DD YYYY-MM-DD 1000022514403 80% 5) 4) 3) 2) 1) Ctra. Mequinenza, s/n. -22520- Fraga, Spain +34 974 470900 Ctra. Mequinenza, s/n. -22520- Fraga, Spain Becton Dickinson, S.A. 碧迪公司 400-821-3091 348 458 307728 20163152896", "label": [[9, 34, "SIZE-DESCRIPTION"]], "FileName": "1000022514403 307728 CL.ai"}\r\n', 246, 250, 'character maps to <undefined>')
```
