### ISSUE TITLE
Annotation Label Cannot be cleared. 

### ISSUE THREAD

**Issue by SraavanChevireddy** [doccano/doccano#1736]
How to reproduce the behavior
---------

#### I created a Sequence Labelling Project from Doccano-latest which uses Labels and Relations. I accidentally made the wrong annotation for one label. When I try to clear the label, there is no way I can do it.

_Now I'm using Clear Labels in the annotation window. But, this is clearing all the labels which I don't want to delete. Each annotation and relation marking takes at least five minutes. Can someone help me get through this, please?_ 
 

Your Environment
---------

*   Operating System: macOS Monterery
*   Python Version Used: Python 3.8
*   When you install doccano: I got the latest. 
*   How did you install doccano (Heroku button etc): Docker

**Comment by guipaiva** [comment]
Have you tried to right-click on label's name?

**Comment by Hironsan** [comment]
Fixed in https://github.com/doccano/doccano/pull/1738

**Comment by SraavanChevireddy** [comment]
That's amazingly working. Thakyou! <3
