### ISSUE TITLE
What are the credentials to login into Doccano webpage?

### ISSUE THREAD

**Issue by teohsinyee** [doccano/doccano#1740]
I clicked the Login button located at the right top page [here](https://doccano.herokuapp.com/). 
I want to try the demo but can't find the credentials anywhere.

![image](https://user-images.githubusercontent.com/56106630/158566743-c0072a25-6e30-4c58-b928-ebe760192593.png)

**Comment by teohsinyee** [comment]
Okay, I tried it before and it didn't look like a demo for me. I thought the visitor can input our text and see the annotated result on the spot. Now we can only view the same text and result. 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/56106630/158717472-dcdd21c7-0292-46cd-94e9-4bd1818302ad.png">

**Comment by Hironsan** [comment]
OK. I understood it.
