### ISSUE TITLE
can not export data,there is nothing in the export compressed file

### ISSUE THREAD

**Issue by amzfc** [doccano/doccano#1749]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:  ubuntu16.4
*   Python Version Used: 
*   When you install doccano: 2022/3/23
*   How did you install doccano (Heroku button etc): docker

**Comment by amzfc** [comment]
After several attempts, a zip. XML file was exported Txt file, the content is {"status":"Not ready"}

**Comment by amzfc** [comment]
The project created is a sequence annotation

**Comment by liyp0095** [comment]
Same issue happens to me. I deploy the project on OpenShift Container Platform. The task is Text Classification. And I got the exported txt file with content {"status":"Not ready"} too.

**Comment by Hironsan** [comment]
Hmm, I can't reproduce the problem. 

What is output in the `docker logs`?

```bash
> docker logs YOUR_CONTAINER_ID
[2022-03-24 02:25:47 +0000] [18] [INFO] Starting gunicorn 20.1.0
[2022-03-24 02:25:47 +0000] [18] [INFO] Listening at: http://0.0.0.0:8000 (18)
[2022-03-24 02:25:47 +0000] [18] [INFO] Using worker: sync
[2022-03-24 02:25:47 +0000] [23] [INFO] Booting worker with pid: 23
[2022-03-24 02:25:47 +0000] [24] [INFO] Booting worker with pid: 24
 
 -------------- celery@8d85ef7a6f5f v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.47-linuxkit-x86_64-with-glibc2.2.5 2022-03-24 02:25:50
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         config:0x7f59c7580190
- ** ---------- .> transport:   sqla+sqlite:////data/doccano.db
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . data_export.celery_tasks.export_dataset
  . data_import.celery_tasks.import_dataset
  . health_check.contrib.celery.tasks.add

[2022-03-24 02:25:50,824: INFO/MainProcess] Connected to sqla+sqlite:////data/doccano.db
[2022-03-24 02:25:50,956: INFO/MainProcess] celery@8d85ef7a6f5f ready.
[2022-03-24 02:26:38,314: INFO/MainProcess] Task data_import.celery_tasks.import_dataset[3490eade-4d8f-42cd-a3a7-a312f79c361a] received
[2022-03-24 02:26:38,380: INFO/ForkPoolWorker-1] Task data_import.celery_tasks.import_dataset[3490eade-4d8f-42cd-a3a7-a312f79c361a] succeeded in 0.05503669998142868s: {'error': []}
[2022-03-24 02:26:49,363: INFO/MainProcess] Task data_export.celery_tasks.export_dataset[d1c9a5ff-781f-4cec-a8d7-acc44503cfb4] received
[2022-03-24 02:26:49,400: INFO/ForkPoolWorker-2] Task data_export.celery_tasks.export_dataset[d1c9a5ff-781f-4cec-a8d7-acc44503cfb4] succeeded in 0.03536610002629459s: '/doccano/backend/media/66c0c1a6-549b-4d7d-a434-a029ec4926a7.zip'
```

**Comment by Hironsan** [comment]
By the way, I show you how to copy the data from the container to the host as a quick fix:

1. check the database file in the container

```bash
> docker exec -it doccano bash
> doccano@8d85ef7a6f5f:/doccano/backend$ ls /data
doccano.db
> doccano@8d85ef7a6f5f:/doccano/backend$ exit
exit
```

2. copy the file to the host.

```bash
# Replace 8d85ef7a6f5f with your container id.
> docker cp 8d85ef7a6f5f:/data/doccano.db .
```

3. execute the SQL query.

```bash
> sqlite3 doccano.db
sqlite> select text from examples_example;
exampleA
exampleB
exampleA
exampleB
exampleC
```

**Comment by Hironsan** [comment]
I understand the problem.

The frontend tries to get the task status repeatedly. If the task is ready, it tries to download the file:

https://github.com/doccano/doccano/blob/27eff5caec1ec6ad31f1e74bd1b73b1dd43228dc/frontend/pages/projects/_id/dataset/export.vue#L114-L125

The download API is the following. This should be called after the task is ready. But it seems to me that the task is not ready for some reason and returns `{"status": "Not ready"}`. As a result, it is included in your content.

https://github.com/doccano/doccano/blob/27eff5caec1ec6ad31f1e74bd1b73b1dd43228dc/backend/data_export/views.py#L25-L35

**Comment by liyp0095** [comment]
Log streaming from OpenShift give me something like this. I do not know if it helps. 

```
10.128.5.154 - - [24/Mar/2022:02:58:45 +0000] "POST /v1/projects/11/download HTTP/1.0" 200 50 "https://qli-lab-doccano.apps.nimbus.las.iastate.edu/projects/11/dataset?limit=10&offset=0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
10.128.5.154 - - [24/Mar/2022:02:58:46 +0000] "GET /v1/tasks/status/a6d6238c-0138-486b-892d-c1db4142cdaf HTTP/1.0" 200 42 "https://qli-lab-doccano.apps.nimbus.las.iastate.edu/projects/11/dataset?limit=10&offset=0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
10.128.5.154 - - [24/Mar/2022:02:58:47 +0000] "GET /v1/tasks/status/a6d6238c-0138-486b-892d-c1db4142cdaf HTTP/1.0" 200 70 "https://qli-lab-doccano.apps.nimbus.las.iastate.edu/projects/11/dataset?limit=10&offset=0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
10.128.5.154 - - [24/Mar/2022:02:58:47 +0000] "GET /v1/projects/11/download?taskId=a6d6238c-0138-486b-892d-c1db4142cdaf HTTP/1.0" 500 145 "https://qli-lab-doccano.apps.nimbus.las.iastate.edu/projects/11/dataset?limit=10&offset=0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
Internal Server Error: /v1/projects/11/download
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/app-root/lib64/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/app-root/lib64/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/app-root/lib64/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/app-root/lib64/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/app-root/lib64/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/app-root/src/backend/api/views/export_dataset.py", line 34, in get
    return FileResponse(open(filename, mode='rb'), as_attachment=True)
TypeError: expected str, bytes or os.PathLike object, not OperationalError
```

**Comment by amzfc** [comment]
--- ***** -----
-- ******* ---- Linux-4.4.0-210-generic-x86_64-with-glibc2.2.5 2022-03-24 03:12:14
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         config:0x7f9fcffae190
- ** ---------- .> transport:   sqla+sqlite:////data/doccano.db
- ** ---------- .> results:
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . data_export.celery_tasks.export_dataset
  . data_import.celery_tasks.import_dataset
  . health_check.contrib.celery.tasks.add

[2022-03-24 03:12:14,358: INFO/MainProcess] Connected to sqla+sqlite:////data/doccano.db
[2022-03-24 03:12:14,402: INFO/MainProcess] celery@372447ef8f6f ready.
[2022-03-24 03:14:18,363: INFO/MainProcess] Task data_export.celery_tasks.export_dataset[5010e35b-7c98-45       26-9d4c-0d68a7427239] received
[2022-03-24 03:14:18,403: INFO/ForkPoolWorker-1] Task data_export.celery_tasks.export_dataset[5010e35b-7c       98-4526-9d4c-0d68a7427239] succeeded in 0.03686487604863942s: '/doccano/backend/media/bf8fd420-b4a2-43f2-       b208-917a82341006.zip'
----------------------------------------------------------------------------------------------------

**There is nothing in the exported compressed file, and it can't even be decompressed**

**Comment by amzfc** [comment]
> By the way, I show you how to copy the data from the container to the host as a quick fix:
> 
> 1. check the database file in the container
> 
> ```shell
> > docker exec -it doccano bash
> > doccano@8d85ef7a6f5f:/doccano/backend$ ls /data
> doccano.db
> > doccano@8d85ef7a6f5f:/doccano/backend$ exit
> exit
> ```
> 
> 2. copy the file to the host.
> 
> ```shell
> # Replace 8d85ef7a6f5f with your container id.
> > docker cp 8d85ef7a6f5f:/data/doccano.db .
> ```
> 
> 3. execute the SQL query.
> 
> ```shell
> > sqlite3 doccano.db
> sqlite> select text from examples_example;
> exampleA
> exampleB
> exampleA
> exampleB
> exampleC
> ```

the way is ok, but i want the annotationed data.

**Comment by amzfc** [comment]
![image](https://user-images.githubusercontent.com/48171458/159837666-7ae52f5b-7eb6-4ef5-a647-fbf20605f6a0.png)

**Comment by Hironsan** [comment]
> the way is ok, but i want the annotationed data.

For example, If you want to write the data id, start offset, end offset, and label name to some a csv file, the following queries are useful:

```bash
sqlite> .headers on
sqlite> .mode csv
sqlite> .output annotation.csv
sqlite> SELECT example_id, start_offset, end_offset, text FROM labels_span, label_types_spantype WHERE labels_span.label_id=label_types_spantype.id;
sqlite> .quit
```

Contents:

```bash
> head annotation.csv
example_id,start_offset,end_offset,text
20757,0,8,LOC
20758,4,23,ORG
20758,59,65,MISC
...
```

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/issues/1749#issuecomment-1077023647

Thanks.

The `task` is ready but the `result` is something wrong. I need some investigation.

**Comment by qiuminghai** [comment]
I solve this bug. in the D:\conda\envs\doccano\Lib\site-packages\backend\data_import\pipeline\writer.py file, 
Modify the code below：
line 9, add : encoding="utf-8"

class LineWriter(BaseWriter):
    extension = 'txt'

    def write(self, records: Iterator[Record]) -> str:
        files = {}
        for record in records:
            filename = os.path.join(self.tmpdir, f'{record.user}.{self.extension}')
            if filename not in files:
                _f = open(filename, mode='a',encoding="utf-8") #here_
                files[filename] = f
            f = files[filename]
            line = self.create_line(record)
            f.write(f'{line}\n')
        for f in files.values():
            f.close()
        save_file = self.write_zip(files)
        for file in files:
            os.remove(file)
        return save_file

**Comment by Hironsan** [comment]
Fixed https://github.com/doccano/doccano/pull/1754

**Comment by teohsinyee** [comment]
> 

I can't find `writer.py` file. But I have `writers.py`. 
When I open the file, I can't find the class that you mentioned: `class LineWriter(BaseWriter)` 

![image](https://user-images.githubusercontent.com/56106630/163970988-347de09c-48ec-4ac7-9ea5-45d7564fd237.png)

`import abc
import itertools
from collections import defaultdict
from typing import Any, Dict, List, Type

from django.conf import settings

from .exceptions import FileParseException
from .readers import BaseReader, Record
from examples.models import Example
from label_types.models import CategoryType, LabelType, SpanType
from projects.models import Project


class Writer(abc.ABC):
    @abc.abstractmethod
    def save(self, reader: BaseReader, project: Project, user, cleaner):
        """Save the read contents to DB."""
        raise NotImplementedError("Please implement this method in the subclass.")

    def errors(self) -> List[Dict[Any, Any]]:
        """Return errors."""
        raise NotImplementedError("Please implement this method in the subclass.")


def group_by_class(instances):
    groups = defaultdict(list)
    for instance in instances:
        groups[instance.__class__].append(instance)
    return groups


class Examples:
    def __init__(self, buffer_size: int = settings.IMPORT_BATCH_SIZE):
        self.buffer_size = buffer_size
        self.buffer: List[Record] = []

    def __len__(self):
        return len(self.buffer)

    @property
    def data(self):
        return self.buffer

    def add(self, data):
        self.buffer.append(data)

    def clear(self):
        self.buffer = []

    def is_full(self):
        return len(self) >= self.buffer_size

    def is_empty(self):
        return len(self) == 0

    def save_label(self, project: Project):
        labels = list(itertools.chain.from_iterable([example.create_label(project) for example in self.buffer]))
        labels = list(filter(None, labels))
        groups = group_by_class(labels)
        for klass, instances in groups.items():
            klass.objects.bulk_create(instances, ignore_conflicts=True)

    def save_data(self, project: Project) -> List[Example]:
        examples = [example.create_data(project) for example in self.buffer]
        return Example.objects.bulk_create(examples)

    def save_annotation(self, project: Project, user, examples):
        # Todo: move annotation class
        mapping = {}
        label_types: List[Type[LabelType]] = [CategoryType, SpanType]
        for model in label_types:
            for label in model.objects.filter(project=project):
                mapping[label.text] = label
        annotations = list(
            itertools.chain.from_iterable(
                [data.create_annotation(user, example, mapping) for data, example in zip(self.buffer, examples)]
            )
        )
        groups = group_by_class(annotations)
        for klass, instances in groups.items():
            klass.objects.bulk_create(instances)


class BulkWriter(Writer):
    def __init__(self, batch_size: int):
        self.examples = Examples(batch_size)
        self._errors: List[FileParseException] = []

    def save(self, reader: BaseReader, project: Project, user, cleaner):
        it = iter(reader)
        while True:
            try:
                example = next(it)
            except StopIteration:
                break
            try:
                example.clean(cleaner)
            except FileParseException as err:
                self._errors.append(err)

            self.examples.add(example)
            if self.examples.is_full():
                self.create(project, user)
                self.examples.clear()
        if not self.examples.is_empty():
            self.create(project, user)
            self.examples.clear()
        self._errors.extend(reader.errors)

    @property
    def errors(self) -> List[Dict[Any, Any]]:
        self._errors.sort(key=lambda e: e.line_num)
        return [error.dict() for error in self._errors]

    def create(self, project: Project, user):
        self.examples.save_label(project)
        ids = self.examples.save_data(project)
        self.examples.save_annotation(project, user, ids)`
