### ISSUE TITLE
relation

### ISSUE THREAD

**Issue by kingcwt** [doccano/doccano#1753]
docker pull doccano/doccano
Does not currently support relation?
There is no relation operation when the new version is pulled down

**Comment by Hironsan** [comment]
The latest image should support relation labeling.
You need to check the relation labeling option when you create a sequence labeling project:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/6737785/160536011-324e2c3d-1c3f-4061-b38c-02eb1dab389e.png">

**Comment by kingcwt** [comment]
Do you support connecting before labeling?

**Comment by kingcwt** [comment]
@Hironsan

**Comment by Hironsan** [comment]
Hello.

> Do you support connecting before labeling?

What do you mean? I have supported relation labeling:

![](https://user-images.githubusercontent.com/6737785/155683739-62848933-b065-477d-8d33-f39f9c7e06ad.png)

**Comment by kingcwt** [comment]
Is the branch master?

**Comment by kingcwt** [comment]
@Hironsan

**Comment by kingcwt** [comment]
The v-annotator component is available on NPM, but you don't seem to open source. Can you show me the source code of this component?
