### ISSUE TITLE
Can’t already export labeled data！

### ISSUE THREAD

**Issue by Edward-Joker** [doccano/doccano#1755]
When I export the data I've annotated, a zip file won't open and the content is empty and UTF-8 encoding is used.
![image](https://user-images.githubusercontent.com/40120224/160424333-3a82f67c-4478-4d8f-ae58-ceaa4eeeedcc.png)
![image](https://user-images.githubusercontent.com/40120224/160424367-c630ce9b-40d9-47fc-b4dc-3610c0794a2d.png)
![image](https://user-images.githubusercontent.com/40120224/160424407-993d887a-8913-493e-a42c-01946659636a.png)
![image](https://user-images.githubusercontent.com/40120224/160424469-32bfa1c5-754b-474e-91cc-7cd6a46a0346.png)
![image](https://user-images.githubusercontent.com/40120224/160424568-e67821bc-e651-40bb-bebf-626cba3df7af.png)

**Comment by Edward-Joker** [comment]
OS: Windows 10, Python==3.8.2

Ok, I checked the installed dependencies:
amqp                    5.1.0
asgiref                 3.5.0
auto-labeling-pipeline  0.1.21
backports.zoneinfo      0.2.1
billiard                3.6.4.0
boto3                   1.21.27
botocore                1.24.27
celery                  5.2.3
certifi                 2021.10.8
chardet                 4.0.0
charset-normalizer      2.0.12
click                   8.0.4
click-didyoumean        0.3.0
click-plugins           1.1.1
click-repl              0.2.0
colorama                0.4.4
coreapi                 2.3.3
coreschema              0.0.4
defusedxml              0.7.1
dj-database-url         0.5.0
dj-rest-auth            2.2.3
Django                  4.0.3
django-celery-results   2.2.0
django-cors-headers     3.11.0
django-drf-filepond     0.4.1
django-filter           21.1
django-health-check     3.16.5
django-polymorphic      3.1.0
django-rest-polymorphic 0.1.9
django-storages         1.12.3
djangorestframework     3.13.1
djangorestframework-xml 2.0.0
doccano                 1.6.2
drf-yasg                1.20.0
environs                9.5.0
et-xmlfile              1.1.0
furl                    2.1.3
greenlet                1.1.2
gunicorn                20.1.0
idna                    3.3
inflection              0.5.1
itypes                  1.2.0
Jinja2                  3.1.1
jmespath                1.0.0
joblib                  1.1.0
kombu                   5.2.4
lml                     0.1.0
MarkupSafe              2.1.1
marshmallow             3.15.0
numpy                   1.22.3
openpyxl                3.0.9
orderedmultidict        1.0.1
packaging               21.3
pip                     21.2.2
prompt-toolkit          3.0.28
pydantic                1.9.0
pyexcel                 0.7.0
pyexcel-io              0.6.6
pyexcel-xlsx            0.6.0
pyparsing               3.0.7
python-dateutil         2.8.2
python-dotenv           0.20.0
pytz                    2022.1
requests                2.27.1
ruamel.yaml             0.17.21
ruamel.yaml.clib        0.2.6
s3transfer              0.5.2
scikit-learn            1.0.2
scipy                   1.8.0
seqeval                 1.2.2
setuptools              59.6.0
shortuuid               1.0.8
six                     1.16.0
SQLAlchemy              1.4.32
sqlparse                0.4.2
texttable               1.6.4
threadpoolctl           3.1.0
typing_extensions       4.1.1
tzdata                  2022.1
uritemplate             4.1.1
urllib3                 1.26.9
vine                    5.0.0
waitress                2.1.1
wcwidth                 0.2.5
wheel                   0.37.1
whitenoise              6.0.0
wincertstore            0.2

**Comment by Edward-Joker** [comment]
Does doccnao have to do all the text annotations to be exported?

**Comment by LighthouseInTheSea** [comment]
This seems to be an existing bug #1422

**Comment by Edward-Joker** [comment]
> This seems to be an existing bug #1422

I've also seen this issue and it doesn't seem to be resolved.

**Comment by LighthouseInTheSea** [comment]
https://github.com/doccano/doccano/projects/13

**Comment by wpnbos** [comment]
This happens because "checking" the document after annotation does not actually "approve" it in the database. A workaround is to download all examples, deselecting the "only export approved documents" option in the interface, and manually filtering approved documents afterwards (I have provided some code for doing so in [this issue](https://github.com/doccano/doccano/issues/1422#issuecomment-1083068808).

**Comment by Edward-Joker** [comment]
**Thank you all for your help**
