### ISSUE TITLE
Not able to export annotated data

### ISSUE THREAD

**Issue by ukrcksaha** [doccano/doccano#1758]
How to reproduce the behaviour
---------
1) Login to docanno dashboard
2) Go to a specific project
3) Go to Data
4) Click on 'Action'
5) click "export data"
6) Select any file type to download
7)Click on 'Export'

After this the UI hangs without downloading the annotated data 

Your Environment
---------

*   Operating System: Based on latest image from docker hub (tried both master and latest)
*   Python Version Used: N/A
*   When you install doccano: today 29th March 2022
*   How did you install doccano (Heroku button etc): Running on k8 and pulling image from docanno docker hub

**Comment by Hironsan** [comment]
The following information is useful to resolve the problem:

- Project Type
- Project Options
- The number of data
- The selected format
- Do the text only contains ASCII characters or not?
