### ISSUE TITLE
My company restricted doccano Exe execution, how to start doccano task through Python

### ISSUE THREAD

**Issue by teloy99** [doccano/doccano#1761]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System: windows
*   Python Version Used: 3.8
*   When you install doccano: 20220401
*   How did you install doccano (Heroku button etc): python pip

**Comment by teloy99** [comment]
My company restricted doccano Exe execution, how to start doccano task through Python

**Comment by Hironsan** [comment]
`pip` or Docker is my recommendation. But you can use the other options. See:
- [Install doccano](https://doccano.github.io/doccano/install-and-upgrade-doccano/)
