### ISSUE TITLE
Doccano is not importing any text data

### ISSUE THREAD

**Issue by Daremitsu1** [doccano/doccano#1762]
Hello,

Doccano is not importing any text data. When importing the text data the following browser loading is going on:
![image](https://user-images.githubusercontent.com/54842807/161327838-33b120e9-428c-4ade-92c2-f5ac7c9fce5d.png)

The command line terminal is showing the following:-
```
<Starting server with port 8000.
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
Bad Request: /v1/auth/login/
WARNING:django.request:Bad Request: /v1/auth/login/
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1>
```

Your Environment
---------
*   Operating System: Windows 10
*   Python Version Used: 3.10
*   When you install doccano: Few days back
*   How did you install doccano (Heroku button etc): Command Line

**Comment by Hironsan** [comment]
Related to:

- [How to find the cause of "task queue depth" warnings from waitress?](https://stackoverflow.com/questions/55857058/how-to-find-the-cause-of-task-queue-depth-warnings-from-waitress)

Currently, we can't pass the number of workers to the server. We need to change the code to pass `threads=args.workers`.

- [Arguments to waitress.serve](https://docs.pylonsproject.org/projects/waitress/en/stable/arguments.html)
https://github.com/doccano/doccano/blob/350bc5e95fa459d1dc124a320cb8e34385b73021/backend/cli.py#L62-L67

**Comment by Hironsan** [comment]
The following may solve the problem:
https://github.com/doccano/doccano/issues/1762#issuecomment-1087141902

Unfortunately, I can't reproduce this problem.

**Comment by teohsinyee** [comment]
> The following may solve the problem: [#1762 (comment)](https://github.com/doccano/doccano/issues/1762#issuecomment-1087141902)
> 
> Unfortunately, I can't reproduce this problem.

Where should I paste the code? My Doccano folder don't have cli.py
![image](https://user-images.githubusercontent.com/56106630/163527888-82f47d93-1e73-47c5-9f1b-cbea9fec784b.png)

**Comment by Hironsan** [comment]
```bash
> which doccano
/venv/bin/doccano
> ls /venv/lib/python3.8/site-packages/backend/cli.py
```

**Comment by teohsinyee** [comment]
Oops, I'm using Windows 10. Do you mean we have to find out where Doccano is located, then paste the code above at `cli.py`? I've tried `gcm doccano`. 
It returned `C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\Scripts\doccano.exe`

So i change directory to `C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\Scripts\`
And listed down all the files there.

```
Folder PATH listing
Volume serial number is 005C0061 1818:A45E
C:.
│   asadmin
│   bundle_image
│   celery.exe
│   cfadmin
│   chardetect.exe
│   cq
│   csv2rdf.exe
│   cwutil
│   django-admin.exe
│   doccano.exe
│   dotenv.exe
│   dumppdf.py
│   dynamodb_dump
│   dynamodb_load
│   elbadmin
│   f2py.exe
│   fetch_file
│   glacier
│   gunicorn.exe
│   htmlmin-script.py
│   htmlmin.exe
│   instance_events
│   ipython.exe
│   ipython3.exe
│   jp.py
│   jsonschema.exe
│   jupyter-bundlerextension.exe
│   jupyter-console.exe
│   jupyter-dejavu.exe
│   jupyter-execute.exe
│   jupyter-kernel.exe
│   jupyter-kernelspec.exe
│   jupyter-migrate.exe
│   jupyter-nbconvert.exe
│   jupyter-nbextension.exe
│   jupyter-notebook.exe
│   jupyter-qtconsole.exe
│   jupyter-run.exe
│   jupyter-serverextension.exe
│   jupyter-troubleshoot.exe
│   jupyter-trust.exe
│   jupyter.exe
│   kill_instance
│   label-studio-converter.exe
│   label-studio.exe
│   launch_instance
│   list_instances
│   lss3
│   mturk
│   nltk.exe
│   normalizer.exe
│   pbr.exe
│   pdf2txt.py
│   pdfplumber.exe
│   pip.exe
│   pip3.10.exe
│   pip3.exe
│   pyami_sendmail
│   pygmentize.exe
│   pyrsa-decrypt.exe
│   pyrsa-encrypt.exe
│   pyrsa-keygen.exe
│   pyrsa-priv2pub.exe
│   pyrsa-sign.exe
│   pyrsa-verify.exe
│   pysemver.exe
│   pywin32_postinstall.py
│   pywin32_testall.py
│   rdf2dot.exe
│   rdfgraphisomorphism.exe
│   rdfpipe.exe
│   rdfs2dot.exe
│   route53
│   rq.exe
│   rqinfo.exe
│   rqw.exe
│   rqworker.exe
│   s3put
│   sdbadmin
│   send2trash.exe
│   shortuuid.exe
│   sqlformat.exe
│   taskadmin
│   tika-python.exe
│   tqdm.exe
│   virtualenv-clone.exe
│   virtualenv.exe
│   virtualenvwrapper.sh
│   virtualenvwrapper_lazy.sh
│   waitress-serve.exe
│   wheel.exe
│   xml2json.exe
│
└───__pycache__
        dumppdf.cpython-310.pyc
        jp.cpython-310.pyc
        pdf2txt.cpython-310.pyc
        pywin32_postinstall.cpython-310.pyc
        pywin32_testall.cpython-310.pyc
```
But still don't find `cli.py`

**Comment by Hironsan** [comment]
This line:

```python
serve(application, port=args.port, threads=args.workers)
```

**Comment by teohsinyee** [comment]
> This line:
> 
> ```python
> serve(application, port=args.port, threads=args.workers)
> ```

I've altered & saved the code. But did not solve the loading issue.
![image](https://user-images.githubusercontent.com/56106630/163739301-aeec61ea-0507-413b-86c4-dbc4d08d7e58.png)

**Comment by Hironsan** [comment]
Can you increase the number of workers?

```bash
doccano webserver --workers=8
```

**Comment by teohsinyee** [comment]
> Can you increase the number of workers?
> 
> ```shell
> doccano webserver --workers=8
> ```

Yup, have increased it. But issue still persisted

**Comment by Hironsan** [comment]
> BTW, is it normal there is no updates on the command prompt when running Doccano?
Yes, because the worker is not printed.

By the way, did you run the `doccano task` command?

**Comment by teohsinyee** [comment]
No, I didn't. I just run it after you told me. And now everything seems work perfectly! Thank youu!

**Comment by teohsinyee** [comment]
> > BTW, is it normal there is no updates on the command prompt when running Doccano?
> 
> Yes, because the worker is not printed.
> 
> By the way, did you run the `doccano task` command?
> 
> * [Install with pip](https://doccano.github.io/doccano/install-and-upgrade-doccano/#install-with-pip)

No, I didn't. I just run it after you told me. And now everything seems work perfectly! Thank youu!

**Comment by Hironsan** [comment]
Good! your welcome.

**Comment by RickQuest** [comment]
I encountered the same issue, and in my case, the problem was related to the file encoding. My text files were encoded in ANSI, but I was selecting UTF-8 during the import process. Converting my text files to UTF-8 resolved the problem.
