### ISSUE TITLE
Importing Entities and Relationships to Doccano

### ISSUE THREAD

**Issue by elexira** [doccano/doccano#1774]
Feature description
---------
Recently, Doccano allowed users to annotate tokens and also create relationships between them via Seq Labeling project type. The feature that is not supported is importing text that contains relationships to doccano. Only the export is possible. Use cases:

-  Assume i export the annotated tokens and relationships and text from one instance of doccano. Then, i want to import the exported data into another instance of doccano. That is not supported
- Assume i have a model that can partially perform annotation and relationship extraction. I would like humans to finalize this work (e.g., semi-supervised labeling). Currently, we cannot import text containing relationships to the tool. 
- Assume i have built some relationships using a model, and want to use doccano to show case the results in a visually digestible way to users. 

Proposed solution: Please add a feature that allows importing text that already contains annotations and relationships to Doccano using the same exact format/template that annotations/relationships are currently exported out the tool. 

Thank you very much !

**Comment by elexira** [comment]
We use dockerized Doccano in a Linux environment

**Comment by mkmark** [comment]
> We use dockerized Doccano in a Linux environment

you are replying to a bot... maybe edit your original post

**Comment by yin0713** [comment]
This should be an  important basic feature of the doccano! I hope this will be realized soon!
@[Hironsan](https://github.com/Hironsan)

**Comment by yin0713** [comment]
This should be an important basic feature of the doccano! I hope this will be realized soon!
@Hironsan

**Comment by Hironsan** [comment]
I'm working now.

**Comment by Hironsan** [comment]
Resolved in v1.7.0.
