### ISSUE TITLE
relationshape lalbel  can't create

### ISSUE THREAD

**Issue by dugudongfangshuo** [doccano/doccano#1776]
![image](https://user-images.githubusercontent.com/32250216/162405051-6409977e-6774-4d3c-b0ee-766ffac1f9c9.png)

What to do if the add relationship tag is invalid

**Comment by mollylanguange** [comment]
doccano==1.5.2 ,sequence labeling ,What to do if the add relationship ?

**Comment by cttcss** [comment]
请问这个问题解决了吗，我也遇到了这个问题

**Comment by Hironsan** [comment]
Please use v1.6.0+
- https://github.com/doccano/doccano/releases/tag/v1.6.0
