### ISSUE TITLE
Cannot access Django admin panel in a Heroku deployment

### ISSUE THREAD

**Issue by FieteO** [doccano/doccano#1778]
How to reproduce the behaviour
---------
The FAQ describes how to [create a user via the Django admin panel](https://github.com/doccano/doccano/blob/master/docs/faq.md#how-to-create-a-user) for a locally hosted Doccano. When run locally, I have no problem to reach the admin panel on `http://localhost:8000/admin/`, in Heroku however it is not working.

I have tried to reach it on
- `https://mydeployment.herokuapp.com/admin/`
- `https://mydeployment.herokuapp.com/admin/login`
- `https://mydeployment.herokuapp.com/admin/login/`
- `http://mydeployment.herokuapp.com/admin/`

Those urls all result in a `500 Internal Server Error`.
Am I missing something here, or is this perhaps a bug?

Your Environment
---------

*   Operating System: -
*   Python Version Used: -
*   When did you install doccano: A few days ago
*   How did you install doccano (Heroku button etc): Heroku button

**Comment by MatteusT** [comment]
Having the exact same problem, and cannot see anything in the logs as it is an internal error

**Comment by mosser** [comment]
Same problem here!

**Comment by Dimiftb** [comment]
I'm having the same issue. Has any1 here found a solution?

**Comment by leugh** [comment]
Same problem, does anybody have a solution?

**Comment by Dimiftb** [comment]
@leugh I found a very simple solution.

Devs for doccano are either extremely busy or don't really care, so [lighttag](https://www.lighttag.io) is a great alternative, think there's a limit of around 5000 annotations before you have to pay but it works great for smaller datasets.

**Comment by Hironsan** [comment]
Probably need to set [heroku.py](https://github.com/doccano/doccano/blob/master/backend/config/settings/heroku.py) instead of [production.py](https://github.com/doccano/doccano/blob/master/backend/config/settings/production.py) in [Dockerfile.heroku](https://github.com/doccano/doccano/blob/master/docker/Dockerfile.heroku) and fix some settings.

**Comment by Hironsan** [comment]
Resolved in https://github.com/doccano/doccano/pull/1907
