### ISSUE TITLE
relationshape lalbel can't create

### ISSUE THREAD

**Issue by mollylanguange** [doccano/doccano#1784]
How to reproduce the behaviour
---------

**doccano==1.5.2 ,sequence labeling ,relationshape label can't use to create relations label**

#1776 

Your Environment
---------

*   Operating System:ubuntu 18.04
*   Python Version Used:3.8
*   When you install doccano:2022/04/05
*   How did you install doccano (Heroku button etc):pip install doccano==1.5.2

**Comment by Hironsan** [comment]
Please use v1.6.0+

- https://github.com/doccano/doccano/releases/tag/v1.6.0
