### ISSUE TITLE
关系标签可以构建，但是使用时打不上标签

### ISSUE THREAD

**Issue by xxxsmilexxx** [doccano/doccano#1786]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:window10
*   Python Version Used:3.8
*   When you install doccano:2022.3
*   How did you install doccano (Heroku button etc):在anaconda的虚拟环境里pip安装

**Comment by sunyongdi** [comment]
您好，请问解决了吗，我的也无法标关系
