### ISSUE TITLE
Can't create sequence labeling project : WARNING:django.request:Forbidden: /v1/projects

### ISSUE THREAD

**Issue by teohsinyee** [doccano/doccano#1787]
When I create sequence labeling project > click Create. No response.

**Snap shot of command prompt console**
<img width="448" alt="image" src="https://user-images.githubusercontent.com/56106630/163906449-98a9ae48-6020-452c-857c-2375275256ff.png">

```
C:\Users\sin-yee.teoh>doccano webserver --port 8000
Starting server with port 8000.
Forbidden: /v1/projects
WARNING:django.request:Forbidden: /v1/projects
```
Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: 3.10
*   When you install doccano: Last week

**Comment by Hironsan** [comment]
Related to #1918
