### ISSUE TITLE
Exporting JSONL(relation) returns empty lists for spans

### ISSUE THREAD

**Issue by wpnbos** [doccano/doccano#1795]
How to reproduce the behaviour
---------
- Create a SequenceLabeling project with relation labeling, add some texts and label them with entities and relations;
- Export the dataset in the JSONL(relation) format;
- Result:
`{"id": 2547, "text": [ANONYMIZED], "relations": [], "entities": []}
{"id": 2548, "text": [ANONYMIZED], "relations": [], "entities": []}`

I labeled about a hundred documents, none of them show any entities. 
Exporting just a SequenceLabeling project without relation labeling works fine.

---------

Docker
Latest release
Installed about a month ago

edit: Solved by using the docker latest image

**Comment by saifrais** [comment]
I am using latest docker image. On export, I do not see any labels. Instead, I see the following entry in the labels:
{"id": 1, "data": "Sold! A beautiful blue dress priced at Rs. 1500/- only \n Size: S", "label": ["entities"]}

I have tried Pypi and docker. Both are giving the same result on export.

**Comment by wpnbos** [comment]
I solved my problem by using the nightly release of Doccano on the Docker repository

`docker pull doccano/doccano:nightly`

https://hub.docker.com/r/doccano/doccano/tags
