### ISSUE TITLE
Unable to deploy Doccano on Azure using template (login issue)

### ISSUE THREAD

**Issue by sebkeil** [doccano/doccano#1797]
I used a json deployment template for Azure Resource Manager, which is basically a modification of the template by [https://github.com/aribornstein/doccano4Azure]. This is the content of the json file:

`
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {   
    "appName": {
      "defaultValue": "doccanova22",
      "type": "string"
    },
    "admin_user": {
      "type": "string"
    },
    "admin_pass": {
      "type": "string"
    },
    "admin_email": {
      "type": "string"
    }

  },
  "variables": {
    "servicePlanName": "[concat('serviceplan',uniqueString(resourceGroup().id))]"
  },
  "resources": [
    {
      "type": "Microsoft.Web/serverfarms",
      "name": "[variables('servicePlanName')]",
      "apiVersion": "2016-03-01",
      "location": "[resourceGroup().location]",
      "sku": {
        "name": "B1",
        "capacity": 1
      },
      "kind": "linux",
      "properties": {
        "workerSizeId": 0,
        "reserved": true,
        "hostingEnvironment": ""
      }
    },
    {
      "type": "Microsoft.Web/sites",
      "name": "[parameters('appName')]",
      "apiVersion": "2016-03-01",
      "location": "[resourceGroup().location]",
      "properties": {
        "name": "[parameters('appName')]",
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('servicePlanName'))]"
      },
      "dependsOn": [
        "[resourceId('Microsoft.Web/serverfarms', variables('servicePlanName'))]"
      ],
      "resources": [
        {
          "name": "appsettings",
          "type": "config",
          "apiVersion": "2016-03-01",
          "dependsOn": [
            "[resourceId('Microsoft.Web/sites', parameters('appName'))]"
          ],
          "tags": {
            "displayName": "appSettings"
          },
          "properties": {
            "WEBSITES_PORT":8000 ,
            "DOCKER_CUSTOM_IMAGE_NAME": "doccano/doccano",
            "DOCKER_CUSTOM_IMAGE_RUN_COMMAND": "doccano/doccano -e ADMIN_USERNAME=parameters('admin_user') -e ADMIN_EMAIL=parameters('admin_email') -e ADMIN_PASSWORD=parameters('admin_pass')"
          }
        }
      ]
    }
  ]
}`

where I replace the image call to the image provided by doccano4Azure with the most recent version of doccano (doccano/doccano), and pass the enviroment variables as specified in the documentation. Then I run the following commands using the Azure command-line integration:

az login

az deployment group create --resource-group mygroupname --template-file azuredeploy2.json 

After passing my desired admin name and password, the app is successfully deployed (https://doccanova22.azurewebsites.net/), but I am not able to log in with the creditials I have passed. I keep receiving the error "Incorrect username or password, or something went wrong." I also receive the same error when passing the default values (admin, password). It seems to be that the docker application succesfully receives the credentials I am passing (otherwise it would not build), but they do not propagate to the Django application. Please let me know if you have any tipps, it would be much appreciated.

**Comment by Hironsan** [comment]
Azure has been no longer supported.

- https://github.com/doccano/doccano/pull/1332
