### ISSUE TITLE
No longer can remove sequence labels 

### ISSUE THREAD

**Issue by Tradunsky** [doccano/doccano#1811]
How to reproduce the behaviour
---------
1. Create a sequence labelling project with dataset and random set of a few labels;
2. Start annotation and put any label;
3. Click on the same label to remove it.
Expected behaviour: Previously selected label approach in the search list and has a cross icon to remove it;
Actual behaviour: No label is present and cannot remove it, only replace with another one.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/4522842/166398747-3e9ed720-5f57-40a2-9905-adc1856499d5.png">

Your Environment
---------
*   Operating System: Ubuntu/Linux
*   Python Version Used: doccano docker
*   When you install doccano: 2022-05-02
*   How did you install doccano (Heroku button etc): docker pull doccano/doccano

**Comment by Tradunsky** [comment]
I think it works in master branch now.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/4522842/166400346-b0e8606a-57a9-4f36-839d-fbb7df19bfe9.png">

Do you know when should we expect an official stable release? 🙏🏻

**Comment by Hironsan** [comment]
Resolved.
