### ISSUE TITLE
How to create a user after cloning the repo?

### ISSUE THREAD

**Issue by Sooraj577** [doccano/doccano#1813]
How to reproduce the behaviour
---------
I have cloned the repo from the github and used a virtual env in which i have installed all dependencies of the repo. Then I tried to run the project using "python manage.py runserver", I got the link (127.0.0.1:8000). When I clicked on the link, i have redirected to a page where it shows "You don't have permission to view or edit anything". Then I added "/admin/" to the link and got the login page. But, when I tried to login using default username (admin) and password (pass), the page shows that "Please enter the correct username and password for a staff account". So, I think in the installation process we create the username and password using the command line. But when user creation comes into this scenario how can i create a user.

Also what my intention is to check the mongodb and postgres Sql also azure blob storage support for the doccano. Also instead of uploading text files, I want to know whether I could select data from the table of the connected db if extracted text stored in a table.

I tried to connect db by editing the DATABASES section in the base.py file and give the connection string value to the ENV DATABASE_URL in Dockerfile.

While installing doccano using pip, how will we give the database url. You have given the format of the database url in the readme but how could we use that line to change the default sqlite.

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used:3.8
*   When you install doccano: 2 days back
*   How did you install doccano (Heroku button etc): tried pip install and also by cloning repo.

**Comment by Hironsan** [comment]
First, the following page will be useful for you:
- https://docs.djangoproject.com/en/4.0/intro/tutorial02/#creating-an-admin-user

> Also what my intention is to check the mongodb and postgres Sql also azure blob storage support for the doccano. Also instead of uploading text files, I want to know whether I could select data from the table of the connected db if extracted text stored in a table.

- SQLite3
- MySQL
- PostgreSQL
- SQL Server
