### ISSUE TITLE
Doccano is not importing files with complete numerics in the name

### ISSUE THREAD

**Issue by Daremitsu1** [doccano/doccano#1815]
Hello,

Doccano seems to be having a problem while importing text files with complete numerics in the filename.
I had named one text file 000445E4 which when trying to read Doccano was getting the following error:
![image](https://user-images.githubusercontent.com/54842807/167178963-91b357dd-e742-4526-aaf8-523ec5128117.png)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

However when I renamed that file to text.txt and imported it, the data was read and imported by Doccano.
![image](https://user-images.githubusercontent.com/54842807/167179412-ae558dc5-8e73-47a3-a810-f3cbea3aea9a.png)

My Environment
---------

*   Operating System: Windows 10
*   Python Version Used: Python 3.9
*   When you install doccano: Some time back
*   How did you install doccano (Heroku button etc): cmd

**Comment by Daremitsu1** [comment]
Any update on this issue?

**Comment by Hironsan** [comment]
I tried to import the exact same name and it works well in [v1.7.0](https://github.com/doccano/doccano/releases/tag/v1.7.0). Please try it.

If there still has a problem, please paste a part of your file here to reproduce the problem. It will be helpful to solve the problem.
