### ISSUE TITLE
auto-labeling - when open the auto-labeling, it erased the checked result

### ISSUE THREAD

**Issue by bifeng** [doccano/doccano#1816]
For some auto labeling result, after corrected and checked, the auto labeling still erase the checked result. 

Expected behavior:
After checked, then it will not post the auto labeing url.

My Environment
Operating System: linux
Python Version Used: Python 3.8.5
When you install doccano: Some time back
How did you install doccano : pip install
doccano version - 1.6.2
task - sequence labeling

**Comment by bifeng** [comment]
My Environment
Operating System: linux
Python Version Used: Python 3.8.5
When you install doccano: Some time back
How did you install doccano : pip install
doccano version - 1.6.2

**Comment by morioka** [comment]
c406942525cdbf0b9df97961cebf5753c2629020 may be a help (not tested yet).

**Comment by morioka** [comment]
My fix is done for sequence-labeling task only .  For other tasks, the same way will work.
