### ISSUE TITLE
Add ability to clone a project

### ISSUE THREAD

**Issue by LizMcQuillan** [doccano/doccano#1818]
Feature description
---------
Add a button on the Projects page that allows the user to clone an existing project and specify which sections to duplicate (Guidelines, Labels, Data, etc) into a new project.

Use Case
----------
Often, I want to do a test run of annotations to check the efficacy of my class labels and instructions before annotating a larger dataset. 
There are times when I need to perform multiple test runs after changing instructions, class labels, or both. This is a very manual workflow of creating multiple, near duplicate projects. Having the ability to duplicate or clone an existing project, and then make edits manually would be an improvement. Currently, the only option in Doccano is to create a new project from scratch and manually copy/paste the Guidelines and re-upload a labels file (or manually enter in the labels a second time).

Env: MacOS

**Comment by Hironsan** [comment]
Clone the following information at the same time:

- Project
- Label Types
- Guideline(Included in the project)

**Comment by ksprajwalgowda** [comment]
I am willing to work on this issue
