### ISSUE TITLE
CSRF verification failed. Request aborted. More information is available with DEBUG=True.

### ISSUE THREAD

**Issue by pujichun** [doccano/doccano#1820]
I deploy this system using docker-compose and I am able to login normally in the Web UI, but when I login through the http://127.0.0.1/admin get a Forbidden (403).

![](https://raw.githubusercontent.com/pujichun/image/main/img/20220516174705.png)

Sometimes I can directly enter the background management system, but as long as the form is submitted, the problem still occurs.

I have never used Django, so I'd like to ask why this is ?

**Comment by ismaelbonneau** [comment]
Hi, I have the same issue. I deployed doccano (through docker) on a distant machine, I can access it from one computer but not from from one other which gives me the CSRF verification failed error.

**Comment by spartazhangzhang** [comment]
I fix this error, just add the env to the docker-compose.backend.
![1659344056371](https://user-images.githubusercontent.com/31640191/182112081-aac491b0-7698-4995-bfd1-87fe24f7e27b.png)

![1659344076447](https://user-images.githubusercontent.com/31640191/182112094-f039a695-37c8-4cf7-8f43-9d5a44ef33a7.png)

**Comment by maks-mukhin** [comment]
> docker-compose.backend

Hello. Can you please tell me, what is the 'docker-compose.backend' file? Where is this file located?

**Comment by BisiOlaYemi** [comment]
I am encoutering the same issue on my django app in vps. Please how do I solve this, I noticed that all forms login throws the same error
