### ISSUE TITLE
How to recover deleted annotated dataset?

### ISSUE THREAD

**Issue by teohsinyee** [doccano/doccano#1822]
I have labeled 5000 lines of text (text classification) But accidentally deleted the dataset.
Is there any way to recover it?
![image](https://user-images.githubusercontent.com/56106630/168744519-a32a8194-6331-4ebd-9bf1-80a782a3218a.png)

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: 3.10
*   When you install doccano: April2022

**Comment by Hironsan** [comment]
Unfortunately, no way to recover it.
