### ISSUE TITLE
Doccano not able to annotate data

### ISSUE THREAD

**Issue by akshat-crypto** [doccano/doccano#1831]
How to reproduce the behavior
---------
I have tried to manually install doccano using the python package, also with docker hub image and the docker-compose file but in all these approaches I am not able to do the annotation part I have created different users too but still not able to work with it.

To reproduce the error spin up an ec2 instance -> install docker and docker-compose -> clone the repo https://github.com/doccano/doccano.git -> in the home dir run docker-compose -f docker/docker-compose.prod.yml   --env-file .env up. I have attached the screenshots for this application too

![image](https://user-images.githubusercontent.com/64367344/169639650-bcbbc656-f05c-4e36-9ca6-4c0ec335d186.png)

![image](https://user-images.githubusercontent.com/64367344/169639700-2f20f576-a4fb-4ba6-aeb6-24ee84c3abf7.png)

Environment
*   Operating System: Ubuntu:20.04
*   Python Version Used: 3.8.10
*   When you install doccano: 19th May 2022
*   How did you install doccano (Heroku button etc): Using Docker-compose file and also with the docker hub images

@kuraga !!!

**Comment by chenchen0508** [comment]
Dear friends, you can check whether your project type is set to "sequence labeling", and the default is set to "text classification". Under "text classification", doccano not able to annotate data.
