### ISSUE TITLE
how to annotate relation using the latest docker image

### ISSUE THREAD

**Issue by mayq97** [doccano/doccano#1838]
---------
How to annotate  entity-relationship,

Which position or key does the user need to click to mark the relationship between entities,

And in http://doccano.herokuapp.com/demo/named-entity-recognition, I don't see the instructions.

How to reproduce the behaviour

Your Environment
---------

*   Operating System: Ubuntu 20
*   Python Version Used:
*   When you install doccano: 2022-05-25
*   How did you install doccano (Heroku button etc): docker pull doccano/doccano:latest

**Comment by dogppatrick** [comment]
Want to know this too
already try few version (docker from docker hub / pip install / docker-compose after clone project)
It can create relation label but still don't know how to add relation.
