### ISSUE TITLE
v-annotator

### ISSUE THREAD

**Issue by JACK-YUNS** [doccano/doccano#1840]
我想要看看v-annotator的源码可以吗？这个插件是否可以开源呢

**Comment by Hironsan** [comment]
Sorry, I can't understand Chinese. Please in English.

**Comment by chioio** [comment]
@Hironsan He said, hope you can open source the `v-annotator` library.

**Comment by Hironsan** [comment]
Thanks. I have already published v-annotator. Please check the repository.
