### ISSUE TITLE
could not load data

### ISSUE THREAD

**Issue by phybrain** [doccano/doccano#1841]
![image](https://user-images.githubusercontent.com/29749341/170436716-2e987133-f9f0-4a8a-b40a-1eb9c9b1b578.png)

Your Environment
---------

*   Operating System: ubuntu18
*   Python Version Used: 3.7
*   When you install doccano: lastest
*   How did you install doccano (Heroku button etc): pip

**Comment by Hironsan** [comment]
Did you run `doccano task`? It is necessary to import dataset.

- https://github.com/doccano/doccano#pip

**Comment by syw2014** [comment]
The same issue

**Comment by Hironsan** [comment]
Please check whether running `doccano task` or not. If it does not solve the problem, please write your environment.
