### ISSUE TITLE
export data contains backslashes

### ISSUE THREAD

**Issue by yamidona** [doccano/doccano#1847]
OS:Windows10
Python:3.9.1
install date:2022/5/31,doccano(1.7.0)
how to:pip
Use function:SequenceLabling

When I export annotated data, the text in the exported data contains backslashes and is different from the original text. Please confirm.

**Comment by Hironsan** [comment]
Please paste the original text to be able to reproduce the issue.

**Comment by yamidona** [comment]
original text(jsonl):{"text":"2022/1/30","label":[]}
export_text:(jsonl):{"id":1,"text":"2022\/1\/30","entities":[],"relations":[]}
