### ISSUE TITLE
column_add

### ISSUE THREAD

**Issue by yamidona** [doccano/doccano#1848]
OS:Windows10
Python:3.9.1
install date:2022/5/31,doccano(1.7.0)
install date:2022/5/10,doccano(1.6.2)
how to:pip
Use function:SequenceLabling

I would like to add my own columns to the dataset display screen as shown in the figure, I thought I could do it using metadata tags. I tried various JSONL keys, but without success. Is it possible to add my own columns?
<img width="470" alt="column" src="https://user-images.githubusercontent.com/27544812/171368571-867d73d4-1b35-4fb7-be94-63a8a8cd835f.png">

**Comment by Hironsan** [comment]
No, impossible.

All the columns without id, text, and comments are stored in Metadata.
