### ISSUE TITLE
Sequence labelling: Annotate across line breaks

### ISSUE THREAD

**Issue by leonardlin** [doccano/doccano#1863]
How to reproduce the behaviour
---------
Based on latest doccano docker image and master-branch (reproducible in both cases)

* Create a project for sequence labelling (NER)
* configure a few SPAN-labels
* upload a textfile to annotate (should have long text that breaks into multiple lines or text with line-breaks
* start annotation
* Given line 1 and line 2,
** Annotate a few spans in the middle of line 1 and line 2
** try to mark with mouse for annotation the last word on line 1 - together with - first word of line 2
** The marker will highlight the last word of line 1 and first word of line 2 but also other existing labels

expected:
* the span label menu shows up for me to chose the label-type

actual:
* nothing happens

Screenshot:
I tried to label the two-word span "especially the"
* it highlights in purple the other text spans too
![image](https://user-images.githubusercontent.com/5815009/173187133-2afbfd01-a157-425d-93bc-8cfb8cc52c60.png)

Your Environment
---------

*   Operating System: Linux
*   Python Version Used: 3.8
*   When you install doccano: 10th of June 2022
*   How did you install doccano (Heroku button etc): via docker, pip install and plain master-branch (reproducible for all 3)

Special comment:
===============
I'm interested to contribute this improvement to the project myself, but I can't find the code to the v-annotator component.

I have noticed for larger labeling projects, the text becomes hard to read because all the markings.
I'm interested as well to help adjust the visual markings so that the text remains well readable.

Let me know how I can help.
Of course all contributes back to the open source community

**Comment by mc622426** [comment]
@leonardlin hello,I would like to know how 'DESCRIBES' is realized. Would you please tell me.

**Comment by leonardlin** [comment]
Hi @mc622426 "Describes" are relation-tags,
Steps:
* Go to settings of a project
* Where you can configure SPAN-labels, there is a tab for "relation"
* Add there 1 relation with text "Describes"
* go back to annotation mode
* On the left side, where the "labels" are displayed, there will be a toggle to switch to "relation"
* Toggle to relation mode
** select the relation-label "Describes"
* Click on two NER, the relation-link will be created

**Comment by roybka** [comment]
Problem occurs (doccano installed on 18/02/23 ) also when installing via pip install. 
I found the rest of the functionality very simple and functional, but this begs fixing.

**Comment by pankajthekush** [comment]
Is this fixed?

**Comment by FrozenYogurtPuff** [comment]
There's no such bug in my Chrome, but it can be replicated in Firefox (111.0.1).
It appears that in 
https://github.com/doccano/v-annotator/blob/07ffaf69fba488fa92d5289d980529d07e9b8136/src/domain/models/EventHandler/TextSelectionHandler.ts#L42-L43

Firefox may return ancestor elements (rather than `#text`) as `focusNode` or  `anchorNode`, which affects the value of `startElement` and `endElement`, leading to an exception in accessing offsets.

**Comment by cqray1990** [comment]
how to solver this problem?
@roybka @FrozenYogurtPuff @leonardlin

**Comment by roybka** [comment]
Yes using chromium solves it @FrozenYogurtPuff  thanks.

**Comment by cqray1990** [comment]
> My Chrome has no such bug, but it can be replicated in Firefox (111.0.1). It appears that in https://github.com/doccano/v-annotator/blob/07ffaf69fba488fa92d5289d980529d07e9b8136/src/domain/models/EventHandler/TextSelectionHandler.ts#L29-L30
> 
> Firefox may return ancestor elements (rather than `#text`) as `focusNode` or `anchorNode`, which affects the value of `startElement` and `endElement`, leading to an exception when accessing offsets.

which Chrome did you  use?
