### ISSUE TITLE
How to add one data from dict using RESTful API

### ISSUE THREAD

**Issue by lan2720** [doccano/doccano#1864]
Hi all, I just figure out how to use [RESTful API](https://github.com/doccano/doccano/blob/de8d24f5f8b29399d29eda288880f78c6017f937/backend/data_import/urls.py#L7) to operate doccano backend data. It is convenient for me.
I'm also wondering if it is possible to just add one document and its label from dict using API? Not from csv or json file.
Thanks a lot!

**Comment by lan2720** [comment]
docker deploy

**Comment by Hironsan** [comment]
If you want to add one document, the `projects/{id}/examples` endpoint will be useful. You can add a label and a label type by the API:

- https://github.com/doccano/doccano/blob/master/backend/label_types/urls.py
- https://github.com/doccano/doccano/blob/master/backend/labels/urls.py
