### ISSUE TITLE
Long Label causing the text width in annotation editor to shrink

### ISSUE THREAD

**Issue by abel98** [doccano/doccano#1873]
Add very long label in annotation task, and start annotating the screen will look like this

![image](https://user-images.githubusercontent.com/4136857/175435582-5c500d31-8719-48ef-b834-530262407570.png)

It is reproducible on both linux and Windows platforms and different screen widths.
---------

Your Environment
---------

*   Operating System:
Linux 5.17.9-100
*   Python Version Used:
Python 3.9.12
*   When you install doccano:
A week ago 6/14/2022
*   How did you install doccano (Heroku button etc):
Docker version and from sources

**Comment by Hironsan** [comment]
Memo: Need to fix `v-annotator`.
