### ISSUE TITLE
Exporting annotators' comments with the labeled dataset

### ISSUE THREAD

**Issue by CaseyZhang11** [doccano/doccano#1875]
Feature description
---------

Hi @Hironsan , I am Casey and from Expedia Group. We want to contribute the feature of **exporting annotators' comments with the labeled dataset**

In the export data file, there is a `comment` column which contains the comments left by annotators. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/71190898/175663663-058571c3-1206-4992-bda5-272df86d36df.png">

**Comment by Hironsan** [comment]
Hi @CaseyZhang11 

Thanks for the comment. I'm happy if you implement the feature.

You may need to change the `data_export` app:
- https://github.com/doccano/doccano/tree/master/backend/data_export

**Comment by gg22mm** [comment]
![图片](https://user-images.githubusercontent.com/6648329/226260477-ae5dae94-4fe5-4bcb-bec6-7b8072ba1b4a.png)
Problem exporting ！
