### ISSUE TITLE
Autolabeling not working in Intent Detection and Slot Filling Project

### ISSUE THREAD

**Issue by turulix** [doccano/doccano#1881]
How to reproduce the behaviour:

Step 1) Setup the project & Import a Dataset
Step 2) Setup Auto Labeling for both DocumentClassification & SequenceLabeling
Step 3) Enable Auto Labeling
Step 4) Nothing happens.

After some research I figured out the frontend isn't even sending the request for the data to be labeled.

---------

Your Environment: docker-compose

**Comment by Hironsan** [comment]
Need to fix auto labeling pipeline:

- https://github.com/doccano/doccano/tree/master/backend/auto_labeling/pipeline
