### ISSUE TITLE
windows下上传标注数据集一直转圈啊，这是什么情况，不兼容吗？？？？

### ISSUE THREAD

**Issue by weihua1379** [doccano/doccano#1884]
platform:windows
![image](https://user-images.githubusercontent.com/54572449/176817517-9d5e0d8b-fcac-4ce7-b1a7-ac2948c56831.png)

**Comment by weihua1379** [comment]
> Would you write your environment? Thank you!

the issue has been solved, thanks

**Comment by dad-world** [comment]
> > Would you write your environment? Thank you!
> 
> the issue has been solved, thanks

请问是怎么解决的吗，我在云服务器上部署，然后自己电脑本地上传文件，也遇到了同样的问题。

**Comment by travishsu** [comment]
I have a similar issue. I cannot upload a JSONL with multiple rows, each row has several other keys besides "text" & "label", in log of Doccano I got: `django.db.utils.IntegrityError: CHECK constraint failed: example_example`

But I found I can upload JSONL where each row has one another key (I concatenate the values of "meta" keys)

**Comment by Luke-lujunxian** [comment]
For anyone having a similar issue, this may be because Celery doesn't support Microsoft Windows. So anything could happen. The following works for me
https://stackoverflow.com/questions/45744992/celery-raises-valueerror-not-enough-values-to-unpack

**Comment by zhang-cuishan** [comment]
有几种情况

1. 你的celery没起来，后端一直等待数据上传。
2.  你的文件太大，超过5兆，也可能会报错。

**Comment by mz2sj** [comment]
> > > Would you write your environment? Thank you!
> > 
> > 
> > the issue has been solved, thanks
> 
> 请问是怎么解决的吗，我在云服务器上部署，然后自己电脑本地上传文件，也遇到了同样的问题。

请问你解决了吗

**Comment by sunbeibei-hub** [comment]
我在windows10上面也遇到了这个问题了。报错信息为：
django.db.utils.IntegrityError: NOT NULL constraint failed: examples_example.upload_name

**Comment by WTJ-github-ing** [comment]
> 我在云服务器上部附件，然后自己电脑本地上传文件，也遇到了同样的问题

me too

**Comment by yxlwfds** [comment]
me too
