### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by weihua1379** [doccano/doccano#1885]
![image](https://user-images.githubusercontent.com/54572449/176840244-17e189fc-d41b-4008-a8a0-55f280c1ac66.png)
When the mouse is over the label, there is no drop-down menu，why??

**Comment by weihua1379** [comment]
> Would you write your environment? Thank you!
platform：Linux version 5.15.3-1.el7.elrepo.x86_64
doccano: 1.7.0
python: 3.9

**Comment by karimmahalian** [comment]
The same issue, please. Even though I have checked single labeling, I can't see the drop-down menu

Could someone help, please?! 

Thank u

**Comment by Hironsan** [comment]
Need to select `Sequence Labeling` as a project type on project creation.
