### ISSUE TITLE
windows 执行doccano init报错

### ISSUE THREAD

**Issue by sxf20220704** [doccano/doccano#1887]
python3.8.0 版本，windows 系统执行doccano init报错 django.db.utils.OperationalError: no such function: JSON_VALID，请问这是什么原因？
![image](https://user-images.githubusercontent.com/108640316/177280376-93aea168-3644-4884-8e9c-beff4c0904ba.png)

**Comment by sxf20220704** [comment]
> 你会写你的环境吗？谢谢！

系统: Windows 10
python: 3.8.0
doccano: 1.7.0

**Comment by zhang-cuishan** [comment]
这有位中文老铁啊？

**Comment by Hironsan** [comment]
Maybe related to SQLite3 version. Please update it.
