### ISSUE TITLE
Can you plug Doccano to a managed database?

### ISSUE THREAD

**Issue by ahmedbesbes-servier** [doccano/doccano#1893]
Hello everyone,

First, thank you for developing such a useful and easy-to-use tool. 

I have two questions regarding databases: 

1. Is it possible to use a managed database (like Cloud SQL on GCP) instead of postgres database that lives inside the Docker container?

2. I notice that when I open the tool after annotation that the labels are persisted. Where are they stored? I think it's useful to be able to access the labels at any time without triggering the export.

Thank you!

Operating System: linux ?
Python Version Used: 3.7.12
When you install doccano: 1 month ago
How did you install doccano: pip / Docker

**Comment by Hironsan** [comment]
1. I have no idea about Cloud SQL, but if you set `DATABASE_URL`, you will be able to use a managed database. Depending on the managed database, it may be necessary to some extra steps(e.g. install some database adaptor like [psycopg2](https://pypi.org/project/psycopg2/))
- https://github.com/doccano/doccano#pip

2. This depends on the installation methods. In the case of pip, `db.sqlite3` is in the `~/doccano/` directory. In the case of docker, `db.sqlite3` is in `doccano-db` volume. In the case of docker-compose, postgres container.
