### ISSUE TITLE
can not delpy successfully use docker-compose

### ISSUE THREAD

**Issue by ZTurboX** [doccano/doccano#1902]
can not delpy successfully use docker-compose
![image](https://user-images.githubusercontent.com/5669444/178458189-50d972ea-fc16-4a83-8c67-885fcea0dd2c.png)

**Comment by Hironsan** [comment]
I can successfully build the `celery` image.
It seems to me that you changed something in `Dockerfile.prod` like adding `-i https://pypi.tuna.tsinghua.edu.cn/simple`. That or your environment causes the error.

**Comment by ZTurboX** [comment]
> 
i had add -i https://pypi.tuna.tsinghua.edu.cn/simple
but error caused by poetry, not pip

**Comment by Hironsan** [comment]
Anyway, I can't reproduce the problem and decide what is the root cause from the information.

**Comment by ZTurboX** [comment]
> Anyway, I can't reproduce the problem and decide what is the root cause from the information.

why use pip and poetry python environments, why not only use pip?

**Comment by Hironsan** [comment]
Because doccano uses Poetry as a dependency manager.
If you want to use pip to install the dependencies, please use `poetry export`. it creates `requirements.txt`:

- [poetry export](https://python-poetry.org/docs/cli/#export)

**Comment by ZTurboX** [comment]
> Because doccano uses Poetry as a dependency manager. If you want to use pip to install the dependencies, please use `poetry export`. it creates `requirements.txt`:
> 
> * [poetry export](https://python-poetry.org/docs/cli/#export)

how to modify in docker-compose deployment if  use pip to install?
