### ISSUE TITLE
Heroku deployment: Can't create new user

### ISSUE THREAD

**Issue by geheim01** [doccano/doccano#1905]
I can't create new user on a heroku deployment since I can't access the admin dashboard on _name_.herokuapp.com/admin.
Any ideas how to create new users? (Config vars to be set in heroku app settings?)

**Comment by Hironsan** [comment]
Resolved in https://github.com/doccano/doccano/pull/1907

**Comment by geheim01** [comment]
Deployed it again with 1 Click hosting
Receiving following error:

```
Whoops, 404
The page you were looking for does not exist
```

**Comment by Hironsan** [comment]
Please add a slash after admin
- name.herokuapp.com/admin/
