### ISSUE TITLE
Can't add Metadata to ImageClassification tasks

### ISSUE THREAD

**Issue by jcy204** [doccano/doccano#1911]
How do you add metadata to ImageClassification tasks as shown in the Demo ImageClassification task below? It seems you can only upload images.

![image](https://user-images.githubusercontent.com/56788220/179728040-e8353d16-f8c1-409b-918d-4c8d3bb0dde1.png)

### Your Environment

Operating System: windows 10
Python Version Used: 3.7
When you install doccano: lastest
How did you install doccano (Heroku button etc): Heroku Button

**Comment by Hironsan** [comment]
Unfortunately, we can now only upload images for image tasks.

**Comment by Hironsan** [comment]
Closed due to duplication: https://github.com/doccano/doccano/issues/1857
