### ISSUE TITLE
The site shows twice github instead of twitter

### ISSUE THREAD

**Issue by borgr** [doccano/doccano#1914]
How to reproduce the behaviour
---------
Enter the site
![image](https://user-images.githubusercontent.com/6416600/180170346-95cd3e5c-78a1-4753-a18d-9c0156550cf6.png)

e.g. https://doccano.github.io/doccano/#contact

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by Hironsan** [comment]
Oh, you have good eyes.
