### ISSUE TITLE
"Create Project" button doesn't work

### ISSUE THREAD

**Issue by jetsonai11** [doccano/doccano#1915]
Hi team - I have just ran Doccano using pip from my terminal, and I am trying to create a new project. However, when I hit "create project", it doesn't work - it doesn't take me to a new page to upload and annotate data and I am not sure why. I am just stuck on this page.

<img width="717" alt="Screen Shot 2022-07-21 at 9 35 13 PM" src="https://user-images.githubusercontent.com/64779050/180343028-8fa71af7-5637-4ed1-ac28-668482529efc.png">

And here is the terminal output I get when I hit "create project"...
<img width="527" alt="Screen Shot 2022-07-21 at 9 39 09 PM" src="https://user-images.githubusercontent.com/64779050/180343082-f06b7a40-d7b8-469b-a05b-d389ee3ddd6a.png">

Your Environment
---------
*   Operating System: Mac OS M1
*   Python Version Used: 3.8.11
*   When you install doccano: Today
*   How did you install doccano (Heroku button etc): pip

**Comment by slkh** [comment]
I have the exact same issue

    Operating System: Mac OS intel, BigSur 11.6
    Python Version Used: 3.8.0
    When you install doccano: Today
    How did you install doccano (Heroku button etc): pip within a venv

**Comment by kenho211** [comment]
Hi, installed doccano using docker and experience the same issue

OS: Ubuntu 18.04
![image](https://user-images.githubusercontent.com/32618031/219029348-73ae24b8-e9c1-4fc7-9597-54ff12a26797.png)
