### ISSUE TITLE
请问key、value指什么。

### ISSUE THREAD

**Issue by wn1652400018** [doccano/doccano#1922]
我在官方提供的try demo中，看到有些任务的标注页面的右侧会有，key和value，但是我自己上传数据时却不知道怎么设置这个key、value的值。
官方提供的text2sql：
![图片](https://user-images.githubusercontent.com/35511759/181477558-b3bf0d8f-a684-46fa-bd73-1999b40258bf.png)
我自己上传的：
![图片](https://user-images.githubusercontent.com/35511759/181477960-6faa5ab0-5ba0-4648-81e1-8e0ee1bbf5b8.png)

**Comment by FayolChang** [comment]
hi, @wn1652400018 
it seems that key is table_name.field_name and value is its field type.
key 是 表名.字段名 value 是字段类型

**Comment by wn1652400018** [comment]
最近使用时偶然发现，截图上的key和value是在上传jsonl格式数据时，额外上床的key-value对。
