### ISSUE TITLE
adding model for auto labeling

### ISSUE THREAD

**Issue by vitthalsing** [doccano/doccano#1923]
The model output is as below
```
{
  "res": [
    {
      "label": "PRICE",
      "start_offset": 0,
      "end_offset": 6
    },
    {
      "label": "QUANTITY",
      "start_offset": 7,
      "end_offset": 13
    },
    {
      "label": "PRODUCT",
      "start_offset": 23,
      "end_offset": 30
    },
    {
      "label": "PRODUCT",
      "start_offset": 34,
      "end_offset": 45
    },
    {
      "label": "QUANTITY",
      "start_offset": 46,
      "end_offset": 50
    },
    {
      "label": "QUANTITY",
      "start_offset": 53,
      "end_offset": 57
    },
    {
      "label": "BRAND",
      "start_offset": 61,
      "end_offset": 69
    },
    {
      "label": "PRODUCT",
      "start_offset": 70,
      "end_offset": 85
    },
    {
      "label": "QUANTITY",
      "start_offset": 86,
      "end_offset": 91
    }
  ]
}
```
I am using below jinja2 template, which works fine when checked  in online parser https://j2live.ttl255.com/

`[{% for item in res %}{ "label": "{{ item.label }}", "start_offset": {{ item.start_offset}}, "end_offset": {{ item.end_offset}}}, {% endfor %}]`

However it throws error on doccano step.
---------

Your Environment
---------

*   Operating System: Win 11
*   Python Version Used: 3.10
*   When you install doccano: 27th July 2022
*   How did you install doccano (Heroku button etc): pip env

**Comment by lan2720** [comment]
+1 我也是在这个网站可以render，但是doccano报错。请问你解决了吗

**Comment by lan2720** [comment]
+1
 I met the same problem. My template can be rendered online parser. But doccano cannot render it.
Do you solve it?

**Comment by vitthalsing** [comment]
#1937 for more screenshot on this issue

**Comment by Hironsan** [comment]
You need to add `input` before `res`:

```bash
[
    {% for entity in input.res %}
        {
            "start_offset": {{ entity.start_offset }},
            "end_offset": {{ entity.end_offset}},
            "label": "{{ entity.label }}"
        }{% if not loop.last %},{% endif %}
    {% endfor %}
]
```

Result:

![image](https://user-images.githubusercontent.com/6737785/190092878-41b39bc2-e016-4350-a28e-148bec579c67.png)


FYI
- [Use your own API](https://doccano.github.io/doccano/advanced/auto_labelling_config/#use-your-own-api)
