### ISSUE TITLE
Offset calculation

### ISSUE THREAD

**Issue by nk-alex** [doccano/doccano#1931]
Just wondering which is the strategy used to calculate start_offset and end_offset. 
Given a word start_offset has to be the first character index in the full text and end_offset the last character index.

Although, when I try to do it by myself, I get different values. That means doccano is ignoring/treating some characters in a different way.

Could you facilitate me the code to calculate this start_offset?

*   Operating System: Windows11
*   Python Version Used: 3.10.4
*   When you install doccano: last version
*   How did you install doccano (Heroku button etc): pip

**Comment by aroggel** [comment]
I have the same issue. When I try to extract the words labelled it gives me different words.
My environment is pretty much the same, a sightly older version of Python.
