### ISSUE TITLE
autolabeling mapping template error

### ISSUE THREAD

**Issue by lan2720** [doccano/doccano#1937]
How to reproduce the behaviour
---------

![image](https://user-images.githubusercontent.com/5330101/183066305-cae5bac3-e14b-4be8-92be-1c103a1dddf7.png)
![image](https://user-images.githubusercontent.com/5330101/183066437-c9b63e18-d9da-4299-a432-e13ac54c268d.png)
![image](https://user-images.githubusercontent.com/5330101/183066779-44c86af6-6680-4137-92ba-b2eb15509472.png)

```
[
    {% for entity in input %}
        {
            "start_offset": {{ entity.start_offset }},
            "end_offset": {{ entity.end_offset}},
            "label": "{{ entity.label }}"
        }{% if not loop.last %},{% endif %}
    {% endfor %}
]
```

Your Environment
---------

*   Operating System: centos 7
*   Python Version Used: None
*   When you install doccano: 2022.08.05
*   How did you install doccano (Heroku button etc): docker pull doccano 1.6.2

**Comment by Hironsan** [comment]
You need to add `input` before `res`:

```bash
[
    {% for entity in input.res %}
        {
            "start_offset": {{ entity.start_offset }},
            "end_offset": {{ entity.end_offset}},
            "label": "{{ entity.label }}"
        }{% if not loop.last %},{% endif %}
    {% endfor %}
]
```

FYI
- [Use your own API](https://doccano.github.io/doccano/advanced/auto_labelling_config/#use-your-own-api)
