### ISSUE TITLE
Add a function to filter labels

### ISSUE THREAD

**Issue by MartinRepo** [doccano/doccano#1941]
When I rechecked the labels of the annotated data, I had no way of filtering out the labels I wanted to see. For example, when I am doing a check of dichotomous annotations, I would like to filter the data set to find out which labels are positive and which are negative, so that I can save time on the check. However, due to the lack of this function, I have to filter one by one from dataset, which wastes a lot of time and manpower.

Thanks for every contributor!

**Comment by MrRace** [comment]
The same Wish
