### ISSUE TITLE
API giving CSRF verification failed

### ISSUE THREAD

**Issue by albin02t** [doccano/doccano#1948]
How to reproduce the behaviour
---------
On postman try the api /auth/login with body 
```
{
  "username": "admin",
  "email": "user@example.com",
  "password": "password"
}
```

Your Environment
---------

Installed docanno using docker
*   Operating System: Linux
*   Python Version Used: 3.7 
*   When you install doccano: 9th August 2022
*   How did you install doccano (Heroku button etc): docker
I want to try out the docanno apis using postman but it it requires a X-CSRF token. Where can i find the token or how can i fix the issue

**Comment by Hironsan** [comment]
Related to https://github.com/doccano/doccano/issues/1820
