### ISSUE TITLE
Can't change the port 8000

### ISSUE THREAD

**Issue by bifeng** [doccano/doccano#1962]
`docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -v doccano-db:/data \
  -p 8010:8010 doccano/doccano`

The port of `8010` is created, but the port of `8000` is still keeped, when i check the container, there are two port: 8010 and 8000.

**Comment by Hironsan** [comment]
If you want to change the host port, you only need to change the first one:

```bash
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -v doccano-db:/data \
  -p 8888:8000 doccano/doccano
```

- [Container networking](https://docs.docker.com/config/containers/container-networking/)

**Comment by bifeng** [comment]
thanks!

**Comment by lianmeng0** [comment]
> 如果要更改主机端口，只需更改第一个：
> 
> ```shell
> docker container create --name doccano \
>   -e "ADMIN_USERNAME=admin" \
>   -e "ADMIN_EMAIL=admin@example.com" \
>   -e "ADMIN_PASSWORD=password" \
>   -v doccano-db:/data \
>   -p 8888:8000 doccano/doccano
> ```
> 
> * [容器网络](https://docs.docker.com/config/containers/container-networking/)

如果使用docker-compose安装，修改端口时，会无法创建项目，[django.request::log_response::241] Forbidden: /v1/projects
