### ISSUE TITLE
How to deploy doccano in a VM using docker compose?

### ISSUE THREAD

**Issue by Sooraj577** [doccano/doccano#1967]
Suppose I am having a vm of ubuntu 18.04 and I want to configure doccano using docker compose for ip 1.2.3.4. How can i change the default localhost or 127.0.0.1 to 1.2.3.4 ? Where should i change the ip address?

Your Environment

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.8

**Comment by Hironsan** [comment]
I'm not sure, do you mean you want to use Docker Compose in a virtual machine?

**Comment by Sooraj577** [comment]
Yes, I want to use doccano in a virtual machine.To be precise what my need is I want to provide this doccano to some users in my gang and they could annotate data. So i want to host this doccano in our private network so that we can access the doccano by our own ip.
Suppose my server ip is 1.2.3.4 how should i configure doccano to use this ip so as to accessed by everyone. 

 I tried to setup gunicorn nginix for this and tried to deploy in a virtual machine but after uploading txt files when i click to the import the loading is shown but the documents are not uploading.

**Comment by Hironsan** [comment]
> I tried to setup gunicorn nginix for this and tried to deploy in a virtual machine but after uploading txt files when i click to the import the loading is shown but the documents are not uploading.

It seems me to that you fail to run or connect to the task queue.
