### ISSUE TITLE
doccano in docker has incomplete function

### ISSUE THREAD

**Issue by KlausLyon** [doccano/doccano#1979]
in sequence2sequence labeling task , i want to label the relation between of the entities， but i can't  do it in the doccano of docker.

**Comment by KlausLyon** [comment]
> Would you write your environment? Thank you!

the latest version, Apple Chip.

**Comment by Hironsan** [comment]
You need to create a "Sequence Labeling" project with `use relation labeling` option.

![](https://i.gyazo.com/46af9b623734b379407f078c412acd18.gif)

**Comment by KlausLyon** [comment]
<img width="1102" alt="截屏2022-09-02 14 12 17" src="https://user-images.githubusercontent.com/112490184/188070730-0fafce3f-3f8b-4b3f-b5ea-050b404df540.png">

but when I create a "Sequence Labeling" project,  there don't have relation labeling option. please tell me how to do.

**Comment by Hironsan** [comment]
The image version may be old. Please try:

```bash
docker pull doccano/doccano:master
```

**Comment by KlausLyon** [comment]
I have tried this way,  it has the same quesition.
there are two questions:
  1.when I create a "Sequence Labeling" project, there don't have relation labeling option.
  2.if i haved created this link ,but the link can't be seen in  the following table. 
  
![image](https://user-images.githubusercontent.com/112490184/188156049-b2b35ca5-8d70-4492-b282-2e50f24088c5.png)

 
the docker's log:
Making staticfiles
Initializing database
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, django_celery_results, django_drf_filepond, sessions, social_django
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api.0001_initial... OK
  Applying api.0002_speech2text... OK
  Applying api.0002_project_single_class_classification... OK
  Applying api.0003_merge_20200612_0205... OK
  Applying api.0002_comment... OK
  Applying api.0004_merge_20210114_1117... OK
  Applying api.0005_auto_20210201_0603... OK
  Applying api.0005_auto_20210120_1730... OK
  Applying api.0006_merge_20210221_1258... OK
  Applying api.0007_auto_20210301_0302... OK
  Applying api.0008_auto_20210302_1013... OK
  Applying api.0009_auto_20210411_2330... OK
  Applying api.0010_auto_20210413_0249... OK
  Applying api.0009_tag... OK
  Applying api.0011_merge_0009_tag_0010_auto_20210413_0249... OK
  Applying api.0012_auto_20210514_0654... OK
  Applying api.0009_annotations_relations_20210421_1445... OK
  Applying api.0013_merge_20210528_1016... OK
  Applying api.0014_auto_20210603_0438... OK
  Applying api.0015_examplestate... OK
  Applying api.0016_auto_20211018_0556... OK
  Applying api.0017_example_uuid... OK
  Applying api.0018_alter_label_background_color... OK
  Applying api.0019_auto_20211124_0506... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying django_celery_results.0001_initial... OK
  Applying django_celery_results.0002_add_task_name_args_kwargs... OK
  Applying django_celery_results.0003_auto_20181106_1101... OK
  Applying django_celery_results.0004_auto_20190516_0412... OK
  Applying django_celery_results.0005_taskresult_worker... OK
  Applying django_celery_results.0006_taskresult_date_created... OK
  Applying django_celery_results.0007_remove_taskresult_hidden... OK
  Applying django_celery_results.0008_chordcounter... OK
  Applying django_celery_results.0009_groupresult... OK
  Applying django_celery_results.0010_remove_duplicate_indices... OK
  Applying django_drf_filepond.0001_initial... OK
  Applying django_drf_filepond.0002_add_upload_dir... OK
  Applying django_drf_filepond.0003_add_storedupload... OK
  Applying django_drf_filepond.0004_tempupload_mods... OK
  Applying django_drf_filepond.0005_add_uploaded_by... OK
  Applying django_drf_filepond.0006_permupload_mods... OK
  Applying django_drf_filepond.0007_altered_stored_upload_file... OK
  Applying django_drf_filepond.0008_temporaryuploadchunked... OK
  Applying django_drf_filepond.0009_temporaryuploadchunked_offset_utime... OK
  Applying django_drf_filepond.0010_temp_chunked_biginteger... OK
  Applying sessions.0001_initial... OK
  Applying social_django.0001_initial... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
  Applying social_django.0009_auto_20191118_0520... OK
  Applying social_django.0010_uid_db_index... OK
Role created successfully "project_admin"
Role created successfully "annotator"
Role created successfully "annotation_approver"
Making staticfiles
Initializing database
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, django_celery_results, django_drf_filepond, sessions, social_django
Running migrations:
  No migrations to apply.
Creating admin
Superuser created successfully.
Starting django
 
 -------------- celery@bfdcec77b209 v5.1.2 (sun-harmonics)
--- ***** ----- 
-- ******* ---- Linux-5.10.104-linuxkit-x86_64-with-glibc2.2.5 2022-09-02 13:15:10
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         app:0x4004a29610
- ** ---------- .> transport:   sqla+sqlite:////data/doccano.db
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . api.tasks.export_dataset
  . api.tasks.ingest_data

Setting password for User admin.
[2022-09-02 13:15:06 +0000] [38] [INFO] Starting gunicorn 20.1.0
[2022-09-02 13:15:06 +0000] [38] [INFO] Listening at: http://0.0.0.0:8000 (38)
[2022-09-02 13:15:06 +0000] [38] [INFO] Using worker: sync
[2022-09-02 13:15:06 +0000] [53] [INFO] Booting worker with pid: 53
[2022-09-02 13:15:06 +0000] [55] [INFO] Booting worker with pid: 55
[2022-09-02 13:15:10,328: INFO/MainProcess] Connected to sqla+sqlite:////data/doccano.db
[2022-09-02 13:15:10,483: WARNING/MainProcess] /usr/local/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-09-02 13:15:10,483: INFO/MainProcess] celery@bfdcec77b209 ready.
Forbidden: /v1/me
Forbidden: /v1/me
Bad Request: /v1/projects/1/relation_types
Bad Request: /v1/projects/1/relation_types
