### ISSUE TITLE
iHow do I generate WHL files

### ISSUE THREAD

**Issue by 754563116** [doccano/doccano#1983]
How do I generate WHL files
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by Hironsan** [comment]
The following files will be useful:

- https://github.com/doccano/doccano/blob/master/.github/workflows/pypi-publish.yml
- https://github.com/doccano/doccano/blob/master/tools/create-package.sh
