### ISSUE TITLE
Automatic language interface changes label and project name

### ISSUE THREAD

**Issue by mariana-yn** [doccano/doccano#2002]
Hi,

I installed doccano from docker in Ubuntu 20.04 following the instructions and was using an English interface. I created some labels from my project, as illustrated in the figure below.

![image](https://user-images.githubusercontent.com/36300156/190497462-ba34db40-d93b-4719-9bb3-1dc1e3d9d909.png)

After that, I created a user for the person that was going to label my texts, but his interface was automatically set to Portuguese language and the labels and project name changed automatically. And when we try to change the interface to English it does not change anything.

![image](https://user-images.githubusercontent.com/36300156/190497532-8bcd2c74-1d74-422d-be3c-c8e9194137d3.png)

The project name changed from "Peticoes" to "Petiscos" and label "Valor" changed to "Valentia". In my interface I can't set to Portuguese, only Chinese, French and German.
Is this a bug or do I need to configure something?

**Comment by Hironsan** [comment]
doccano does not have a Portuguese interface(support English, Chinese, German, and French). Do you have some browser extension to translate language? I recommend you try to use secret mode which does not have any extension.

**Comment by mariana-yn** [comment]
Ok, it worked. I thought it was from the project because it was on the user interface.
Thank you for the help and the great project!
