### ISSUE TITLE
How can I directly edit the dataset?

### ISSUE THREAD

**Issue by CoachWong** [doccano/doccano#2007]
How can I directly edit the data text on the dataset webpage http://127.0.0.1:8000/projects/1/dataset?limit=10&offset=0？Sometimes the data text may be wrong and needs to be changed. It will be very troublesome if you can only import data files.

**Comment by CoachWong** [comment]
> Would you write your environment? Thank you!

I transplanted doccano to Windows and started it with pycharm

**Comment by Hironsan** [comment]
Please use admin page or doccano-client.
