### ISSUE TITLE
How to add metadata to image examples

### ISSUE THREAD

**Issue by mritonia** [doccano/doccano#2010]
How to reproduce the behaviour
---------
This is not a question about suspicious behavior. This is also not a general usage question. This is a specific **feature usage** question...

I am using the latest release of doccano, and I am trying to configure examples for a ImageClassification project. The import action for the examples will only allow me to upload `.png` file types, but I was wondering how I could upload metadata for individual examples. In the example in the deployed demo of doccano on Heroku, [this example has URL metadata](https://doccano.herokuapp.com/demo/image-classification), which I am interested in replicating in my project.

**Comment by mritonia** [comment]
This also shouldn't have anything to do with my environment, but I am seeing the same behavior between Ubuntu 20.04 deployment and local MacOS deployment (M1) Monterey 12.4

**Comment by Hironsan** [comment]
There is no way to add meta data to image examples now. If you want to do so, please use do [doccano-client](https://github.com/doccano/doccano-client/):
- https://doccano.github.io/doccano-client/usage/#doccano_client.client.DoccanoClient.update_example

**Comment by ymerouani** [comment]
Is there anyway at all to add metadata or any kind of text data to help the annotator. For instance under key/value. 
![image](https://github.com/doccano/doccano/assets/40887643/61ab2647-0d77-420f-8ec9-4233b0969bc5)
