### ISSUE TITLE
Document Classification with a subset of potential labels based on the document

### ISSUE THREAD

**Issue by david-engelmann** [doccano/doccano#2021]
Feature description
---------

The general idea of the request is to set up a document classification project where not every potential label is present on every single document. The best way to describe the project would be scoring the results of a multi-label classification project. After getting the results of the classification, I'd like to upload with each document a label that represents the returned results of the multi-label classification project and a label for incorrect. Currently, if you uploaded documents with different non-incorrect labels, both are added to the label section and both appear as options in the annotate section.

Example:
1. You upload a document with text and label as follows, and add to the label section a label for "incorrect".

| text   | label   |
|--------|--------|
| dog    | animal |
| apple  | fruit  |
| david  | person |
| google | animal |

2. When you enter the annotation section you see the label it was uploaded with as the selected label but all other labels as options (see screenshot below).

![image](https://user-images.githubusercontent.com/81196676/196264740-bb9ebf8a-2acb-4a9b-a0ca-eba6003abc9b.png)

Optimally, the uploaded label and the universal label we added ("incorrect") would be the only two label options that show up, such as the screenshot below.

![image](https://user-images.githubusercontent.com/81196676/196265078-3ffccc7d-9325-436d-a832-96e23f29cc76.png)

It may require a new project type, please let me know how I can help!

Environment:
OS: Docker
Doccano Version: v1.8.0

**Comment by david-engelmann** [comment]
> 

Added environment but it's not that relevant to a feature request

**Comment by Hironsan** [comment]
Do you want to switch the labels displayed for each document?

For example:

| text   | display label   |
|--------|--------|
| Text A    | fruit, person |
| Text B  | animal, person  |

**Comment by david-engelmann** [comment]
@Hironsan That's the idea
