### ISSUE TITLE
can't not see data in annotation after import dataset

### ISSUE THREAD

**Issue by DC-Lin** [doccano/doccano#2022]
![image](https://user-images.githubusercontent.com/38984443/196591780-72e31374-10df-49b0-b2c1-b0a6e94b8375.png)
I start annotation after import dataset ,but i can't see the text，that is black。

In Dataset page,there has data。
![image](https://user-images.githubusercontent.com/38984443/196592122-8b67eca1-889e-4fa2-aa15-84823700fba6.png)

**Comment by DC-Lin** [comment]
Environment:
ubuntu 18.04,
chrome 105.0.5195.127,
doccano 1.8.0

**Comment by DC-Lin** [comment]
dataset json(example):
{"text": "整体评价：给老妈买的，有补水功能就好啦，相宜本草老牌子了，还是很放心的 ;没有属性词;没有观点词", "entities": [{"start_offset": 20, "end_offset": 24, "label": "属性词", "text": "相宜本草", "id": 0}, {"start_offset": 24, "end_offset": 27, "label": "观点词", "text": "老牌子", "id": 1}], "relations": [{"from_id": 0, "to_id": 1, "type": "品牌"}, {"from_id": 0, "to_id": 1, "type": "正"}]}
{"text": "水有点刺眼睛  本人干皮  霜没什么效果  噱头太大;没有属性词;没有观点词", "entities": [{"start_offset": 22, "end_offset": 24, "label": "属性词", "text": "噱头", "id": 0}, {"start_offset": 24, "end_offset": 26, "label": "观点词", "text": "太大", "id": 1}], "relations": [{"from_id": 0, "to_id": 1, "type": "卖家服务"}, {"from_id": 0, "to_id": 1, "type": "负"}]}
{"text": "因为平时买的东西太多了 实在没精力一一评价 所以我觉得满意的东西就直接用这个模版了 凡是用到这个模版的东西 足以证明这个东西是物有所值的 也有的可能是物超所值的 东西好坏不在价格高低 自己满意就最好 平时也是习惯好评 同时祝店家生意兴隆 好东西都会继续关注的 ;没有属性词;没有观点词", "entities": [{"start_offset": 6, "end_offset": 8, "label": "属性词", "text": "东西", "id": 0}, {"start_offset": 63, "end_offset": 67, "label": "观点词", "text": "物有所值", "id": 1}, {"start_offset": 83, "end_offset": 84, "label": "观点词", "text": "好", "id": 2}], "relations": [{"from_id": 0, "to_id": 1, "type": "性价比"}, {"from_id": 0, "to_id": 1, "type": "正"}, {"from_id": 0, "to_id": 2, "type": "整体"}, {"from_id": 0, "to_id": 2, "type": "正"}]}
{"text": "护手霜质量不错，份量足，质地滑嫩，保湿很好。 ;没有属性词;没有观点词", "entities": [{"start_offset": 3, "end_offset": 5, "label": "属性词", "text": "质量", "id": 0}, {"start_offset": 5, "end_offset": 7, "label": "观点词", "text": "不错", "id": 1}, {"start_offset": 12, "end_offset": 14, "label": "属性词", "text": "质地", "id": 2}, {"start_offset": 14, "end_offset": 16, "label": "观点词", "text": "滑嫩", "id": 3}], "relations": [{"from_id": 0, "to_id": 1, "type": "质量"}, {"from_id": 0, "to_id": 1, "type": "正"}, {"from_id": 2, "to_id": 3, "type": "质量"}, {"from_id": 2, "to_id": 3, "type": "正"}]}
only 3 data,there was not work

**Comment by DC-Lin** [comment]
I found some errors from chrome
![image](https://user-images.githubusercontent.com/38984443/196605794-554e1cb2-61f1-47a6-bf79-70617019ff7e.png)

**Comment by Oubaaa** [comment]
Have you solved this problem? I had the same problem

**Comment by DC-Lin** [comment]
> Have you solved this problem? I had the same problem

Sorry,I can't fix it.

**Comment by Hironsan** [comment]
The problem seems to be in uploading the data. The `from_id` and `to_id` does not match any span id.

**Comment by Hironsan** [comment]
OK. Please use globally unique entity IDs:

```bash
{"text": "整体评价：给老妈买的，有补水功能就好啦，相宜本草老牌子了，还是很放心的 ;没有属性词;没有观点词", "entities": [{"start_offset": 20, "end_offset": 24, "label": "属性词", "text": "相宜本草", "id": 0}, {"start_offset": 24, "end_offset": 27, "label": "观点词", "text": "老牌子", "id": 1}], "relations": [{"from_id": 0, "to_id": 1, "type": "品牌"}, {"from_id": 0, "to_id": 1, "type": "正"}]}
{"text": "水有点刺眼睛 本人干皮 霜没什么效果 噱头太大;没有属性词;没有观点词", "entities": [{"start_offset": 22, "end_offset": 24, "label": "属性词", "text": "噱头", "id": 2}, {"start_offset": 24, "end_offset": 26, "label": "观点词", "text": "太大", "id": 3}], "relations": [{"from_id": 2, "to_id": 3, "type": "卖家服务"}, {"from_id": 2, "to_id": 3, "type": "负"}]}
{"text": "因为平时买的东西太多了 实在没精力一一评价 所以我觉得满意的东西就直接用这个模版了 凡是用到这个模版的东西 足以证明这个东西是物有所值的 也有的可能是物超所值的 东西好坏不在价格高低 自己满意就最好 平时也是习惯好评 同时祝店家生意兴隆 好东西都会继续关注的 ;没有属性词;没有观点词", "entities": [{"start_offset": 6, "end_offset": 8, "label": "属性词", "text": "东西", "id": 4}, {"start_offset": 63, "end_offset": 67, "label": "观点词", "text": "物有所值", "id": 5}, {"start_offset": 83, "end_offset": 84, "label": "观点词", "text": "好", "id": 6}], "relations": [{"from_id": 4, "to_id": 5, "type": "性价比"}, {"from_id": 4, "to_id": 5, "type": "正"}, {"from_id": 4, "to_id": 6, "type": "整体"}, {"from_id": 4, "to_id": 6, "type": "正"}]}
{"text": "护手霜质量不错，份量足，质地滑嫩，保湿很好。 ;没有属性词;没有观点词", "entities": [{"start_offset": 3, "end_offset": 5, "label": "属性词", "text": "质量", "id": 7}, {"start_offset": 5, "end_offset": 7, "label": "观点词", "text": "不错", "id": 8}, {"start_offset": 12, "end_offset": 14, "label": "属性词", "text": "质地", "id": 9}, {"start_offset": 14, "end_offset": 16, "label": "观点词", "text": "滑嫩", "id": 10}], "relations": [{"from_id": 7, "to_id": 8, "type": "质量"}, {"from_id": 7, "to_id": 8, "type": "正"}, {"from_id": 9, "to_id": 10, "type": "质量"}, {"from_id": 9, "to_id": 10, "type": "正"}]}
```

The result is:

![image](https://user-images.githubusercontent.com/6737785/201600203-75ca15fd-24ef-491f-bfad-a6fde53792f0.png)
