### ISSUE TITLE
How can I get the comment data under the samples？

### ISSUE THREAD

**Issue by janelu9** [doccano/doccano#2023]

**Comment by janelu9** [comment]
doccano-client is a way to get it

**Comment by david-engelmann** [comment]
The best way to do it will be the list_comments function

**Comment by david-engelmann** [comment]
I wrote a small script that demonstrates how you could get the sample and comments for samples with comments

```
doccano_client.login(username=doccano_username,
        password=doccano_password)

examples = list(doccano_client.list_examples(project_id=1))

results = []
for example in examples:
    if example.comment_count > 0:
        comments = doccano_client.list_comments(project_id=1,
                example_id=example.id)
        results.append((example,list(comments)))
```

Hope this helps!

**Comment by janelu9** [comment]
> I wrote a small script that demonstrates how you could get the sample and comments for samples with comments
> 
> ```
> doccano_client.login(username=doccano_username,
>         password=doccano_password)
> 
> examples = list(doccano_client.list_examples(project_id=1))
> 
> results = []
> for example in examples:
>     if example.comment_count > 0:
>         comments = doccano_client.list_comments(project_id=1,
>                 example_id=example.id)
>         results.append((example,list(comments)))
> ```
> 
> Hope this helps!

How about doccano 1.5
