### ISSUE TITLE
CSRF Failed: Origin checking failed - http://192.168.0.1:3000 does not match any trusted origins.

### ISSUE THREAD

**Issue by homealim2012** [doccano/doccano#2032]
How to reproduce the problem
---------
login and create a project
set environment variable:

```bash
DEBUG=false
CSRF_TRUSTED_ORIGINS=http://192.168.0.1:3000,http://localhost:3000,http://0.0.0.0:3000
```

Your Environment
---------

*   Operating System: Linux
*   Python Version Used: 3.8
*   When you install doccano: just now 
*   How did you install doccano (Heroku button etc):
* with frontend and backend

**Comment by homealim2012** [comment]
目前只能通过nginx中的set_proxy_header来解决跨域问题

**Comment by chenyongxiong** [comment]
请问下nginx中的set_proxy_header来解决跨域问题，这个nginx是怎设置，谢谢
