### ISSUE TITLE
More optimal to have many projects + few tasks per project or few projects + many tasks per project?

### ISSUE THREAD

**Issue by lance132** [doccano/doccano#2034]
Hi, looking for some guidance on the following issue. We're hoping to start up some continuous annotation projects in the near future (ones where new annotation tasks come in on a weekly or even daily cadence), and we have two options for managing new annotation tasks:
1. Create Doccano projects for the continuous annotation effort as a whole and keep adding new tasks to them as they come in.
2. Create separate projects for each new batch of annotations.

Are there any benefits/drawbacks to either approach from a Doccano perspective? (I.e. will things slow down if we're working in a project with many thousands of tasks? Will large numbers of projects somehow gum up the system? etc.)

**Comment by david-engelmann** [comment]
@lance132 My opinion is that it comes down to the end goal of the results and the annotator structure. From a technical perspective, I've found no slow downs to huge numbers of projects or projects with lots of documents. The project can be a super useful organizational structure. I tend to create lots of projects with a limited scope for one user. When that user logs on they only see their projects so it's not cluttered. Tools like the doccano-client make it extremely easy to ingest many projects with a similar naming structure to aggregate for analysis. That being said, if your end goal calls for three huge buckets then that's probably what the doccano project structure should look like.

**Comment by lance132** [comment]
@david-engelmann Thanks! That's very helpful 😃

**Comment by david-engelmann** [comment]
@lance132 No problem!
