### ISSUE TITLE
import data unsuccess

### ISSUE THREAD

**Issue by tszjqgs** [doccano/doccano#2035]
hi , I set up the doccano through Anaconda, and get the landing page , but when trying to test the annotation , the data import step never be success, and kept loading for a week without progress. It is a text file with couple of lines only

can some one share some advice 

![b661683d8b18e2009ee938538f5fcf0](https://user-images.githubusercontent.com/14088515/198107739-9906afbe-7445-4419-9c40-f86027a93c6d.jpg)

**Comment by tszjqgs** [comment]
> 

hi , My environment is windows 11 , Edge browser, Anaconda 3 , doccano 1.8.0

**Comment by david-engelmann** [comment]
@tszjqgs What does the upload doc look like and what line endings does it use?

**Comment by tszjqgs** [comment]
> @tszjqgs What does the upload doc look like and what line endings does it use?

Terrible customer service.
Really great transaction.
Great price.

**Comment by tszjqgs** [comment]
above is all contained in txt file

**Comment by david-engelmann** [comment]
@tszjqgs Do you know what line endings are used CRLF / LF

**Comment by tszjqgs** [comment]
not sure, does it matter

**Comment by Hironsan** [comment]
Run `doccano task` command.
