### ISSUE TITLE
Can the 1.0.0 system be upgraded to the latest version？

### ISSUE THREAD

**Issue by homealim2012** [doccano/doccano#2038]
Refer to https://doccano.github.io/doccano/install_and_upgrade_doccano/#before-v160，database and media folders need to be updated. But there is no media folder in 1.0.0 system and the filename is doccano.db instead of db.sqlite3. I tried to update the system with the command doccano migrate, but in the new system I only saw user data and label data, but the sample data and label data could not be found. So can the data of 1.0.0 or older platforms be synchronized to the new platform?

Your Environment
*   How did you install doccano (Heroku button etc): pip install doccano

**Comment by homealim2012** [comment]
目前的导入方法：

1、参考https://doccano.github.io/doccano/install_and_upgrade_doccano/#before-v160
   将doccano.db文件拷贝到~/doccano/上，并重命名为db.sqlite3
   运行 doccano migrate

2、将旧版本的api_sequenceannotation和api_document数据导出excel
   
    同时将api_sequenceannotation 的uuid填入数据
    excel中的 uuid计算方法：
    http://t.zoukankan.com/xueluozhangxin-p-7482840.html
   
    将api_document的uuid、filename、upload_name填入数据

3、将旧数据api_document、api_sequenceannotation追加到新数据库上
   api_document 在新数据库对应 example_example
   api_sequenceannotation 在新数据库对应 labels_span
   api_sequenceannotation中的字段document_id在新数据库对应example_id

**Comment by homealim2012** [comment]
---将sqlite3转化成postgres数据形式，不能直接转，因为存在数据格式丢失的问题
4、使用python postgres版本的migrate，将所有外键去掉

5、使用navicat的数据同步，将其他数据表从sqlite3同步到postgres上
6、将django_content_type表使用数据传输的形式覆盖到postgres上，将除主键外的所有属性的数据格式由text改为varchar(100)

7、将所有序列更新，参考 https://www.656463.com/wenda/Postgresgxsybdzjxl_402

**Comment by Hironsan** [comment]
No, there is no easy way.
