### ISSUE TITLE
Broken: Importing and Exporting SequenceLabeling projects with relations

### ISSUE THREAD

**Issue by david-engelmann** [doccano/doccano#2039]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System: Dockeer
*   Python Version Used: 3.8
*   When you install doccano: 11/1/22
*   How did you install doccano (Heroku button etc): docker-compose

I observed issues with the UI and interacting with relation labels. I am able create a relation label between two span labels in the UI, however the relation array get exported empty when going through the Export Dataset -> JSONL(relation) path. Furthermore, issues occur when trying to import relations as well. The import dataset flow only takes one "Column Label" field. When that is set to label, all of the span label and relation label info are uploaded as metadata. 

![image](https://user-images.githubusercontent.com/81196676/199328801-c98d3693-ff8f-45b3-80a3-7d916075ec56.png)

If the "Column Label" field is set to "entities" the span labels are imported and only the relation label data is uploaded as metadata. 

![image](https://user-images.githubusercontent.com/81196676/199329062-26b1ea53-8b03-464d-932e-15e0b0e83061.png)

The first goal would be that the export process, exports in the format displayed when you select the JSONL(relation) option from Export Dataset.

ie.

```
{
    "text": "Google was founded on September 4, 1998, by Larry Page and Sergey Brin.",
    "entities": [
        {
            "id": 0,
            "start_offset": 0,
            "end_offset": 6,
            "label": "ORG"
        },
        {
            "id": 1,
            "start_offset": 22,
            "end_offset": 39,
            "label": "DATE"
        },
        {
            "id": 2,
            "start_offset": 44,
            "end_offset": 54,
            "label": "PERSON"
        },
        {
            "id": 3,
            "start_offset": 59,
            "end_offset": 70,
            "label": "PERSON"
        }
    ],
    "relations": [
        {
            "id": 0,
            "from_id": 0,
            "to_id": 1,
            "type": "foundedAt"
        },
        {
            "id": 1,
            "from_id": 0,
            "to_id": 2,
            "type": "foundedBy"
        },
        {
            "id": 2,
            "from_id": 0,
            "to_id": 3,
            "type": "foundedBy"
        }
    ]
}
```

The second goal would be the ability to upload span labels and relation labels. Basically, Import Dataset should work with the Export Dataset -> JSONL(relation) results. I'll include a JSONL testing file for imports.

[relation_import_sample.zip](https://github.com/doccano/doccano/files/9913661/relation_import_sample.zip)

**Comment by Hironsan** [comment]
Related to #2022 2022
