### ISSUE TITLE
Excuse me, Does your project support relationship extraction for the part auto labeling?

### ISSUE THREAD

**Issue by xinlaid** [doccano/doccano#2042]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by david-engelmann** [comment]
[Most likely related to this issue](https://github.com/doccano/doccano/issues/2039)

**Comment by Hironsan** [comment]
The answer is No. If you want to use some trained model to annotate texts, please use [doccano-client](https://github.com/doccano/doccano-client/).
