### ISSUE TITLE
Is it possible when an input example annotated by multi person

### ISSUE THREAD

**Issue by 652994331** [doccano/doccano#2044]
Hi, Doccano is a good tool to use to annotate the data, good work, thank you! However, It seems we can't ask multi person annotate the same sample. Like when 3 people try to give a single article a score(3 different scores in total). Is it possible for Doccano to do such a thing? thank you

**Comment by david-engelmann** [comment]
It is definitely possible to have multiple labelers in one project. When you create your projects, make sure you set the setting to have share annotations across users to true. Check out the screenshot from the create project screen!

![image](https://user-images.githubusercontent.com/81196676/200031020-65b4ce89-4e6f-4ca6-9431-e05214c12bb0.png)

**Comment by 652994331** [comment]
@david-engelmann thank you David, but it seems that's not my question. I hope 3 different person can annotate one sentence(one data sample), like they are giving this sentence a score. A:0.3, B:0.5 C:0.4. so I can get an average score 0.4 for this sentence and then move on to the next sentence.

**Comment by david-engelmann** [comment]
@652994331 My suggestion would be to use the doccano-client, create a project for each annotator and upload the same inputs to the project. When everyone is done labeling, pull the results for all the projects and calculate the average for each sample!

**Comment by 652994331** [comment]
@david-engelmann  thank you, I will try it later
