### ISSUE TITLE
HTTPConnectionPool(host='d-gpu-003.elinkapp.com', port=5003): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c05825c0>, 'Connection to d-gpu-003.elinkapp.com timed out. (connect timeout=None)'))

### ISSUE THREAD

**Issue by zic13** [doccano/doccano#2045]
HTTPConnectionPool(host='d-gpu-003.elinkapp.com', port=5003): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc6c05825c0>, 'Connection to d-gpu-003.elinkapp.com timed out. (connect timeout=None)'))

connection error please help to resolve it

**Comment by david-engelmann** [comment]
Is d-gpu-003.elinkapp.com available?
