### ISSUE TITLE
Cannot create other user in 127.0.0.1/8000/admin, it'll show 404

### ISSUE THREAD

**Issue by jenfung** [doccano/doccano#2046]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

![image](https://user-images.githubusercontent.com/66559607/200226385-a646546c-d13f-4826-bb81-f3836f707550.png)
![image](https://user-images.githubusercontent.com/66559607/200226464-2b5c1af7-c1e4-4179-8324-6f9aa83adff7.png)

**Comment by biokraft** [comment]
You have to use /admin/ with a trailing /

**Comment by david-engelmann** [comment]
You will need to be logged into an admin account as well!

**Comment by SpringBree** [comment]
> ## How to reproduce the behaviour
> ## Your Environment
> * Operating System:
> * Python Version Used:
> * When you install doccano:
> * How did you install doccano (Heroku button etc):
> 
> ![image](https://user-images.githubusercontent.com/66559607/200226385-a646546c-d13f-4826-bb81-f3836f707550.png) ![image](https://user-images.githubusercontent.com/66559607/200226464-2b5c1af7-c1e4-4179-8324-6f9aa83adff7.png)

hi！  I want to know how did you fix it

**Comment by gal0is** [comment]
> You have to use /admin/ with a trailing /

Thanks.
