### ISSUE TITLE
CSRF Failed: login/project management issues and temporary workaround

### ISSUE THREAD

**Issue by FrancescoScandiffio** [doccano/doccano#2062]
### Short version
Installed from source, I had an authorization problem solved by adding the local client address to the list of `CORS_ORIGIN_WHITELIST` in the backend configuration file. I think a reference to this in the documentation might help until a solution is found to make the system work out of the box.
Related to #2032 but not many details were provided there so I preferred to open a new issue to also provide my workaround.

### Long version
I followed the tutorial [Install from source](https://doccano.github.io/doccano/install_and_upgrade_doccano/#install-from-source) with the only difference being I used pip with virtualenv instead of poetry. 
After starting both frontend and backend processes, I encountered the following problems:
1. sometimes I could not login because of "wrong credentials error" even if the credentials were in fact correct.
2. even when logged in as admin,  the button to create projects did not create anything. I was always redirected to a 404 page
3. projects manually added through the django console were still not displayed by the frontend

![image](https://user-images.githubusercontent.com/20610941/203400568-9dfe9c97-eb9b-4acc-ba74-3b15247a116a.png)

**Network log on client "bad credentials" error**
```
Request URL: http://192.168.1.242:3000/v1/auth/login/
Payload: {"username":"admin","password":"password"}
Response: Error occured while trying to proxy: 192.168.1.242:3000/v1/auth/login/
```

**Frontend service log on "bad credentials" error**
```
ERROR [HPM] Error occurred while proxying request 192.168.1.242:3000/v1/auth/login/ to http://127.0.0.1:8000/
[ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Backend log after "create project" button click**
```
Forbidden: /v1/projects
[22/Nov/2022 19:56:21] "POST /v1/projects HTTP/1.1" 403 112
```

**Chrome network log after "create project" button click**
```
Host: 192.168.1.242:3000
Origin: http://192.168.1.242:3000
Referer: http://192.168.1.242:3000/projects/create
Request URL: http://192.168.1.242:3000/v1/projects
Request Method: POST
Status Code: 403 Forbidden
Referrer Policy: strict-origin-when-cross-origin

Response: {"detail":"CSRF Failed: Origin checking failed - http://192.168.1.242:3000 does not match any trusted origins."}

```

------
### Workaround
I have added  the ip shown by the frontend service (here http://192.168.1.242:3000) to `CORS_ORIGIN_WHITELIST` list in  `doccano\backend\config\settings\development.py`.
Had to do the same for production.

This solved all the issues I encountered related to the login and project management.

Your Environment
---------

*   Operating System: Windows 10 Pro, build  19044
*   Python Version Used: 3.10.4
*   When you install doccano: 22 November 2022 (today)
*   How did you install doccano: from source (packages managed with pip)

**Comment by dimidd** [comment]
Thanks! I had to add the address that was used in `yarn dev`, which was different than the default, and add it to `CSRF_TRUSTED_ORIGINS` in `backend/config/settings/base.py`. Then I added `DEBUG = True` in `backend/config/settings/development.py`
