### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by Doubledongli** [doccano/doccano#2067]
![image](https://user-images.githubusercontent.com/20540661/204228990-94d738c9-8bf7-41a9-8b81-d88acaa55148.png)

**Comment by Doubledongli** [comment]
> Would you write your environment? Thank you!

environment:
centos
doccano:1.6.0

**Comment by Doubledongli** [comment]
solved：https://blog.csdn.net/qq_23953717/article/details/128084659?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22128084659%22%2C%22source%22%3A%22qq_23953717%22%7D

**Comment by FrancescoScandiffio** [comment]
I would flag this as a duplicate of #2062 both for bug report and solution
