### ISSUE TITLE
can't execute 'doccano task'

### ISSUE THREAD

**Issue by albeic** [doccano/doccano#2072]
![image](https://user-images.githubusercontent.com/51845996/204755833-19bc69ae-1158-4e64-80c8-6d61b2ca7e32.png)

**Comment by cuisws** [comment]
我今天也是这个错误，没整好

**Comment by PatrickStaehli** [comment]
As the error "_ValueError: path must be a filename, not a directory_" suggests, the doccano task cannot find the required .env file.

If there is no .env file created when executing doccano init (or at the wrong location), you can circumvent the issue by creating the .env file manually e.g., in your doccano folder with the following content:

```
# platform settings
ADMIN_USERNAME=admin
ADMIN_PASSWORD=password
ADMIN_EMAIL=admin@example.com

# rabbit mq settings
RABBITMQ_DEFAULT_USER=doccano
RABBITMQ_DEFAULT_PASS=doccano

# database settings
POSTGRES_USER=doccano
POSTGRES_PASSWORD=doccano
POSTGRES_DB=doccano

# Flower settings
FLOWER_BASIC_AUTH=""
```

Then, execute the doccano task by pointing to the .env file

```
doccano task env_file doccano/.env
```

**Comment by coolinstar** [comment]
@PatrickStaehli  
Thank you for your answer.
Just one more question ,  which directory should be doccano folder?

**Comment by cuisws** [comment]
doccano task env_file doccano/.env
usage: doccano.exe [-h] {init,migrate,createuser,webserver,task,flower,help} ...
doccano.exe: error: unrecognized arguments: env_file doccano/.env

**Comment by cuisws** [comment]
I have avoided this mistake now.
1. Download the sqlite3.def file from the SQlite official website and put it in the python DLLs folder.
2. Uninstall version 1.8.2 docanno
3. Delete django in the site packages folder_ celery_ Results and django_ celery_ results-2.2.0.dist-info
4. Delete the C:  Users  xxx  doccano folder
5. Install version 1.6.2 of docanno

**Comment by cuisws** [comment]
> ![image](https://user-images.githubusercontent.com/51845996/204755833-19bc69ae-1158-4e64-80c8-6d61b2ca7e32.png)

I have avoided this mistake now.
1. Download the sqlite3.def file from the SQlite official website and put it in the python DLLs folder.
2. Uninstall version 1.8.2 docanno
3. Delete django in the site packages folder_ celery_ Results and django_ celery_ results-2.2.0.dist-info
4. Delete the C:  Users  xxx  doccano folder
5. Install version 1.6.2 of docanno

**Comment by cuisws** [comment]
> As the error "_ValueError: path must be a filename, not a directory_" suggests, the doccano task cannot find the required .env file.
> 
> If there is no .env file created when executing doccano init (or at the wrong location), you can circumvent the issue by creating the .env file manually e.g., in your doccano folder with the following content:
> 
> ```
> # platform settings
> ADMIN_USERNAME=admin
> ADMIN_PASSWORD=password
> ADMIN_EMAIL=admin@example.com
> 
> # rabbit mq settings
> RABBITMQ_DEFAULT_USER=doccano
> RABBITMQ_DEFAULT_PASS=doccano
> 
> # database settings
> POSTGRES_USER=doccano
> POSTGRES_PASSWORD=doccano
> POSTGRES_DB=doccano
> 
> # Flower settings
> FLOWER_BASIC_AUTH=""
> ```
> 
> Then, execute the doccano task by pointing to the .env file
> 
> ```
> doccano task env_file doccano/.env
> ```

doccano task env_file doccano/.env
usage: doccano.exe [-h] {init,migrate,createuser,webserver,task,flower,help} ...
doccano.exe: error: unrecognized arguments: env_file doccano/.env

**Comment by hao-joey-zhang** [comment]
> As the error "_ValueError: path must be a filename, not a directory_" suggests, the doccano task cannot find the required .env file.
> 
> If there is no .env file created when executing doccano init (or at the wrong location), you can circumvent the issue by creating the .env file manually e.g., in your doccano folder with the following content:
> 
> ```
> # platform settings
> ADMIN_USERNAME=admin
> ADMIN_PASSWORD=password
> ADMIN_EMAIL=admin@example.com
> 
> # rabbit mq settings
> RABBITMQ_DEFAULT_USER=doccano
> RABBITMQ_DEFAULT_PASS=doccano
> 
> # database settings
> POSTGRES_USER=doccano
> POSTGRES_PASSWORD=doccano
> POSTGRES_DB=doccano
> 
> # Flower settings
> FLOWER_BASIC_AUTH=""
> ```
> 
> Then, execute the doccano task by pointing to the .env file
> 
> ```
> doccano task env_file doccano/.env
> ```



1. doccano folder should locate in your user directory and contains a sqlite file if you are using the default setting.
2. the command should be `doccano task --env_file doccano/.env`

**Comment by cuisws** [comment]
> 

Thanks

**Comment by cuisws** [comment]
> > As the error "_ValueError: path must be a filename, not a directory_" suggests, the doccano task cannot find the required .env file.
> > If there is no .env file created when executing doccano init (or at the wrong location), you can circumvent the issue by creating the .env file manually e.g., in your doccano folder with the following content:
> > ```
> > # platform settings
> > ADMIN_USERNAME=admin
> > ADMIN_PASSWORD=password
> > ADMIN_EMAIL=admin@example.com
> > 
> > # rabbit mq settings
> > RABBITMQ_DEFAULT_USER=doccano
> > RABBITMQ_DEFAULT_PASS=doccano
> > 
> > # database settings
> > POSTGRES_USER=doccano
> > POSTGRES_PASSWORD=doccano
> > POSTGRES_DB=doccano
> > 
> > # Flower settings
> > FLOWER_BASIC_AUTH=""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, execute the doccano task by pointing to the .env file
> > ```
> > doccano task env_file doccano/.env
> > ```
> 
> 1. doccano folder should locate in your user directory and contains a sqlite file if you are using the default setting.
> 2. the command should be `doccano task --env_file doccano/.env`

Thank you very much. The command 'doccano task --env_file doccano/.env'  was executed successfully！

**Comment by LittleZ2022** [comment]
> Hello guys, I had the same issue. I was trying to install doccano tool using pip and had the same issue with doccano task. So i have debug the code and found that there is a minor mistake in code. So please go to env/Lib/site-packages/environs/init.py and go to 398 number line and change if path is None: to if path is '': and try again with doccano task. it should work. Hope it helps. Happy labeling :-) ![image](https://user-images.githubusercontent.com/26756126/205100556-d056a6ca-304b-419d-bab9-72006c8edc70.png)

yeah,it works.but it mentions that 
`F:\Anaconda3\envs\doccano\lib\site-packages\environs\__init__.py:398: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if path is '':`

**Comment by kritikaksu** [comment]
> > Hello guys, I had the same issue. I was trying to install doccano tool using pip and had the same issue with doccano task. So i have debug the code and found that there is a minor mistake in code. So please go to env/Lib/site-packages/environs/init.py and go to 398 number line and change if path is None: to if path is '': and try again with doccano task. it should work. Hope it helps. Happy labeling :-) ![image](https://user-images.githubusercontent.com/26756126/205100556-d056a6ca-304b-419d-bab9-72006c8edc70.png)
> 
> yeah,it works.but it mentions that `F:\Anaconda3\envs\doccano\lib\site-packages\environs\__init__.py:398: SyntaxWarning: "is" with a literal. Did you mean "=="? if path is '':`

yes its same thing right? if path=='': or if path is '': 
basically path was empty string not None. thats why it was not working.
