### ISSUE TITLE
can't execute 'doccano task'

### ISSUE THREAD

**Issue by cuisws** [doccano/doccano#2073]
My Environment
---------
*   Operating System: Windows
*   Python Version Used: 3.8.10
*   When you install doccano: 2022/11/30
*   How did you install doccano (Heroku button etc): 

- doccano task
Traceback (most recent call last):
  File "D:\IT\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\IT\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\IT\python\python38\Scripts\doccano.exe\__main__.py", line 7, in <module>
  File "D:\IT\python\python38\lib\site-packages\backend\cli.py", line 174, in main
    env.read_env(args.env_file, recurse=False, override=True)
  File "D:\IT\python\python38\lib\site-packages\environs\__init__.py", line 409, in read_env
    raise ValueError("path must be a filename, not a directory.")
ValueError: path must be a filename, not a directory.

**Comment by PatrickStaehli** [comment]
see #2072

**Comment by coolinstar** [comment]
same issue here.
made a new venv
after pip installation, doccano task failed with this error.
It seems like this version is not go along with sqlllite

**Comment by cuisws** [comment]
> same issue here. made a new venv after pip installation, doccano task failed with this error. It seems like this version is not go along with sqlllite
I have avoided this mistake now.
1. Download the sqlite3.def file from the SQlite official website and put it in the python DLLs folder.
2. Uninstall version 1.8.2 docanno
3. Delete django in the site packages folder_ celery_ Results and django_ celery_ results-2.2.0.dist-info
4. Delete the C:  Users  xxx  doccano folder
5. Install version 1.6.2 of docanno

**Comment by kritikaksu** [comment]
Hello guys, I had the same issue. I was trying to install doccano tool using pip and had the same issue with doccano task. So i have debug the code and found that there is a minor mistake in code. 
So please go to env/Lib/site-packages/environs/__init__.py and go to 398 number line and change if path is None: to  if path is '':
and try again with doccano task. it should work.
Hope it helps. Happy labeling :-)
