### ISSUE TITLE
can't execute 'doccano task'

### ISSUE THREAD

**Issue by coolinstar** [doccano/doccano#2074]
**Environment Report :** 

- Operating System: Windows
- Python Version Used: 3.9
- When you install doccano: 2022/11/30
- How did you install doccano (Heroku button etc):  pip install doccano

Issue : 

>
![image](https://user-images.githubusercontent.com/9428499/204882922-600f47dc-b418-44c9-b840-910670f8b750.png)

**Comment by cuisws** [comment]
> 

I have avoided this mistake now.
1. Download the sqlite3.def file from the SQlite official website and put it in the python DLLs folder.
2. Uninstall version 1.8.2 docanno
3. Delete django in the site packages folder_ celery_ Results and django_ celery_ results-2.2.0.dist-info
4. Delete the C:  Users  xxx  doccano folder
5. Install version 1.6.2 of docanno

**Comment by coolinstar** [comment]
> > 
> 
> I have avoided this mistake now.
> 
> 1. Download the sqlite3.def file from the SQlite official website and put it in the python DLLs folder.
> 2. Uninstall version 1.8.2 docanno
> 3. Delete django in the site packages folder_ celery_ Results and django_ celery_ results-2.2.0.dist-info
> 4. Delete the C:  Users  xxx  doccano folder
> 5. Install version 1.6.2 of docanno

Thanks for your help,  temporarily solved.
