### ISSUE TITLE
data task error

### ISSUE THREAD

**Issue by GuocaiL** [doccano/doccano#2080]
*   Operating System:ubuntu22
*   Python Version Used:3.9
*   When you install doccano:2022-12-04
*   How did you install doccano (Heroku button etc):pip install doccano

<img width="732" alt="image" src="https://user-images.githubusercontent.com/43643599/205482588-64111fa6-23bc-4c19-ade7-a7fb4532b177.png">

**Comment by 1feres1** [comment]
same error with miniconda environment
