### ISSUE TITLE
ip:port/admin/   404

### ISSUE THREAD

**Issue by SpringBree** [doccano/doccano#2109]
*   Operating System: ubantu
*   Python Version Used: py 3.8
*   When you install doccano:   recently
*   How did you install doccano (Heroku button etc):  install from source 

I was install docanno from source and all  are ok 
but i cant get in ip:port/admin/ and it shows 404 and return 304 OK
<img width="954" alt="1" src="https://user-images.githubusercontent.com/44973927/211510191-c0b848a6-12e5-4bd3-b46d-286b7459db19.png">
how can i fix it

**Comment by SpringBree** [comment]
> 

yes

**Comment by SpringBree** [comment]
> Would you write your environment? Thank you!

yes

**Comment by Hironsan** [comment]
Use the background port number (8000 is default).
