### ISSUE TITLE
Heroku Dyno change

### ISSUE THREAD

**Issue by daotuanan** [doccano/doccano#2110]
After Heroku terminated their free tier, the Heroku Deploy Button doesn't work anymore.
Please change the dyno config to other options. 

How to reproduce the behaviour
---------

Click on Heroku Deploy Button at the template: [https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fdoccano%2Fdoccano](url)
<img width="750" alt="Screenshot 2023-01-10 at 21 06 25" src="https://user-images.githubusercontent.com/20960628/211547425-62b8d0a9-92b6-4cd9-940f-4bd44a0854a3.png">

Your Environment
---------

*   Operating System: MacOS
*   Python Version Used: Python 3.8
*   When you install doccano: Jan 10, 2023
*   How did you install doccano (Heroku button etc): Heroku button.

**Comment by rehmoh** [comment]
Facing the same issues, any work arounds to solve this?

**Comment by Hironsan** [comment]
The minimum plan is now `heroku-postgresql:mini`. So we may need to replace `heroku-postgresql:hobby-dev` to it in [app.json](https://github.com/doccano/doccano/blob/master/app.json).

- https://elements.heroku.com/addons/heroku-postgresql

**Comment by daotuanan** [comment]
Dear Hironsan,
Yes please add the `heroku-postgresql:mini` to the file. 
Thank you so much for your help.
