### ISSUE TITLE
How to update the code?

### ISSUE THREAD

**Issue by zhang-cuishan** [doccano/doccano#2161]
Hi, Dear. 
 Thank you for the open source code; We have customized some code in the use of engineering, how are these code updated and deployed? Especially how do we update our code according to the docker or docker-compose method you provide?

**Comment by dickymuhr** [comment]
> > Would you write your environment? Thank you!
> 
> What I want to know is how to deploy or update my own new code. And use the official docker image.

do you solve it? I am also customize the source code (frontend) then run using docker compose but facing some issue like 403 and 500 error
