### ISSUE TITLE
Something wrong with building frontend, could someone please help

### ISSUE THREAD

**Issue by Yuankus** [doccano/doccano#2184]
How to reproduce the behaviour
---------
Something wrong with the code: yarn dev. 

ERROR in pages/projects/_id/labels/import.vue:58:29
TS18046: 'e' is of type 'unknown'.
    56 |         this.$router.push(`/projects/${this.projectId}/labels`)
    57 |       } catch (e) {
  > 58 |         this.errorMessage = e.message
       |                             ^
    59 |       }
    60 |     },
    61 | 

TS2349: This expression is not callable.
  No constituent of type 'Function | PromiseConstructor' is callable.
    69 |     async tryLogin() {
    70 |       try {
  > 71 |         await this.login({
       |                    ^^^^^
    72 |           username: this.username,
    73 |           password: this.password
    74 |         })

My Environment
---------
npm version 9.5.1

*   Operating System: windows 10
*   Python Version Used: python 3.9
*   When you install doccano: 2023.5.11
*   How did you install doccano (Heroku button etc): pip install doccano

**Comment by Hironsan** [comment]
` (e: any)` solve the problem?
