### ISSUE TITLE
Error: eve@git://github.com/adobe-webplatform/eve.git#eef80ed: Couldn't resolve "eef80ed"

### ISSUE THREAD

**Issue by bill-mark** [doccano/doccano#2210]
yarn install
error is:
 Error: eve@git://github.com/adobe-webplatform/eve.git#eef80ed: Couldn't resolve "eef80ed" as either a commit, a tag, or a head

**Comment by Hironsan** [comment]
Did you install some packages?

https://github.com/doccano/doccano/blob/1c81e73bbe35f81c575d21d1b461c6656a75f371/frontend/yarn.lock#L6051

**Comment by bill-mark** [comment]
> 

windows 10
node v16.19.0
npm 8.19.3
yarn 3.6.0

**Comment by bill-mark** [comment]
> Did you install some packages? Please try to replace `git://` with `https://` in `yarn.lock`.
> 
> https://github.com/doccano/doccano/blob/1c81e73bbe35f81c575d21d1b461c6656a75f371/frontend/yarn.lock#L6051

thank you  it worked!
