### ISSUE TITLE
Admin & Labels page don't work

### ISSUE THREAD

**Issue by SP-CL** [doccano/doccano#2212]
*   Operating System: OSX Monterey
*   Python Version Used: 3.10.3

create labels page 404's 

<img width="1326" alt="image" src="https://github.com/doccano/doccano/assets/117802949/df6e3a17-2d14-4ca5-8e6f-8cd974ae811a">

<img width="1503" alt="image" src="https://github.com/doccano/doccano/assets/117802949/9a12f64d-33a8-4f7a-839e-669e8d4aa030">

Admin Page
<img width="1503" alt="Screenshot 2023-06-11 at 8 57 19 PM" src="https://github.com/doccano/doccano/assets/117802949/d1d6b075-7368-4bf2-8d11-95b89f7011fc">

EDIT: Interim fix, rollback to SHA: 0c6aecace682376a9552a3cd26fb1a4ef3857f08

**Comment by Hironsan** [comment]
Thanks. Fixed. Please try it.

**Comment by SP-CL** [comment]
Thanks for the quick update, unfortunately the admin page is still not displaying,

can confirm that labels work now

<img width="1503" alt="Screenshot 2023-06-11 at 10 36 14 PM" src="https://github.com/doccano/doccano/assets/117802949/c4b4c5bc-00f8-47e3-825b-db76437ec0d3">

**Comment by SP-CL** [comment]
Working well thank you
