### ISSUE TITLE
Edit doccano documentation to follow tech writing best practices

### ISSUE THREAD

**Issue by sblotner** [doccano/doccano#2215]
This is a request to edit and improve the doccano documentation to follow some tech writing best practices. I've installed and tried using doccano, and would like to contribute these documentation edits to help future users digest the doccano docs with ease. 

Here are the files I'd like to edit for grammar, clarity, and concision, ranked by priority:

-  [docs/index.md](https://github.com/doccano/doccano/blob/master/docs/index.md)
- [docs/faq.md](https://github.com/doccano/doccano/blob/master/docs/faq.md)
- [docs/tutorial.md](https://github.com/doccano/doccano/blob/master/docs/tutorial.md)
- [README.md](https://github.com/doccano/doccano/blob/master/README.md)
- [docs/developer_guide.md](https://github.com/doccano/doccano/blob/master/docs/developer_guide.md)

My environment is macOS Monterey, using the latest version of doccano installed with pip

**Comment by Hironsan** [comment]
It's very wonderful. Please make a pull request.

**Comment by sblotner** [comment]
Super! Related PR: https://github.com/doccano/doccano/pull/2216
