### ISSUE TITLE
doccano can't filter the specified label,if we want to modify the label which is annotated,and we need filter these label data,but the doccan seem to not include this

### ISSUE THREAD

**Issue by cqray1990** [doccano/doccano#2223]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):
doccano can't filter the specified label,if we want to modify the label which is annotated,and we need filter these label data,but the doccan seem to not include this func

**Comment by feng-1985** [comment]
https://github.com/doccano/doccano/pull/2228
