### ISSUE TITLE
Customize My Own Labeling Interface?

### ISSUE THREAD

**Issue by HRNPH** [doccano/doccano#2226]
Feature description
a good documentation on contributing to new Labeling Interfaces
or a label interfaces editor such as in Label Studio

![image](https://github.com/doccano/doccano/assets/51855316/7ebdf14a-51b3-4a6e-a8ca-dfa09d6f649a)

---------

**Comment by Hironsan** [comment]
There is no interface editor.
If you want to add a new interface, you need to create some pages like [text-classification](https://github.com/doccano/doccano/blob/master/frontend/pages/projects/_id/text-classification/index.vue). If you want to know the page, please see the Nuxt.js [documentation](https://nuxt.com/docs/guide/directory-structure/pages).
