### ISSUE TITLE
Download annotated dataset with request. 

### ISSUE THREAD

**Issue by bablf** [doccano/doccano#2231]
How to reproduce the behaviour
---------

I'm a beginnger when it comes to docker so please excuse if the question is stupid. 

I would like to download the annotated dataset with a GET/POST request from the specified endpoint (http://localhost/v1/projects/2/download). I know that I need to pass authentication/login information, but I do not know how and what parameters I have to set. 

Probably ADMIN_USERNAME and ADMIN_PASSWORD. But I tried specifying these in the request header but I still get the message: Authentication credentials were not provided. (I used Postman to create the request)

Would be great if someone could point me in the right direction. 

Your Environment
---------

*   Operating System: Ubuntu 20 
*   Python Version Used: python3.10
*   When you install doccano: 3.7. 
*   How did you install doccano (Heroku button etc): Docker compose

**Comment by Hironsan** [comment]
[doccano-client](https://github.com/doccano/doccano-client) would be helpful for you.

**Comment by bablf** [comment]
Thanks that's a lot easier ❤️
