### ISSUE TITLE
有遇到操作界面会自动变回英文的情况吗

### ISSUE THREAD

**Issue by zzwtop1** [doccano/doccano#2240]
我在语言选项中选择了中文，用了以后，忽然给切回了英文模式，我手动切回中文模式，用了一会又给切成了英文模型

**Comment by zzwtop1** [comment]
CentOS Linux release 7.5.1804的虚拟机
使用miniconda创建的虚拟环境
python版本：3.8.12
下载的最新doccano
在本地电脑windows10的edge浏览器登录的doccano网址

**Comment by zzwtop1** [comment]
还有一个问题，数据上传之后，在数据集的界面中文文本是正常的，进入标注界面中文文本是乱序的

**Comment by zzwtop1** [comment]
我知道了，因为我开启了LTR，关闭后就正常了

**Comment by JasonGuo1** [comment]
> 我知道了，因为我开启了LTR，关闭后就正常了

您好，我也会遇到这种情况。请问您提到的LTR是什么

**Comment by zzwtop1** [comment]
> > 我知道了，因为我开启了LTR，关闭后就正常了
> 
> 您好，我也会遇到这种情况。请问您提到的LTR是什么

标注的时候右上角有个按钮带有英文字母LTR
