### ISSUE TITLE
Issue being fixed, can not add custom auto labeling api at 1.8.4

### ISSUE THREAD

**Issue by kk412027247** [doccano/doccano#2285]
Login in then go to the link, 
[http://localhost:8000/v1/projects/1/auto-labeling/configs](http://localhost:8000/v1/projects/1/auto-labeling/configs)
And paste the json to content then press POST button.
```json
{
    "id": 99999,
    "model_name": "Custom REST Request",
    "model_attrs": {
        "url": "http://172.19.14.151:5000/",
        "method": "POST",
        "params": {},
        "headers": {
            "Content-Type": "application/json"
        },
        "body": {
            "text": "{{ text }}"
        }
    },
    "template": "[\n    {% for entity in input %}\n        {\n            \"start_offset\": {{ entity.start_offset }},\n            \"end_offset\": {{ entity.end_offset}},\n            \"label\": \"{{ entity.label }}\"\n        }{% if not loop.last %},{% endif %}\n    {% endfor %}\n]",
    "label_mapping": {},
    "task_type": "Span"
}
```

![image](https://github.com/doccano/doccano/assets/30715186/2a03ef8f-9371-457d-a4d6-79a8a5e86b4b)

template field it is 
```
[
    {% for entity in input.res %}
        {
            "start_offset": {{ entity.start_offset }},
            "end_offset": {{ entity.end_offset}},
            "label": "{{ entity.label }}"
        }{% if not loop.last %},{% endif %}
    {% endfor %}
]
```

then refresh the setting page, you could see the setting was added.

![image](https://github.com/doccano/doccano/assets/30715186/cdd61fc0-9de3-434b-84a3-85c63043bdbb)

**Comment by xiang-hui744** [comment]
请问application/json是什么意思

**Comment by HelpFireCode** [comment]
Thank you for your amazing solution! However, there is still some issues I have not resolved... Will you check this?
Following your operation, the `Rawdata` in this page can`t click just like picture 1. 
![image](https://github.com/user-attachments/assets/d59c4461-cf1f-4ee5-bec4-3526e61ef077)

Simutanesouly, bug information in the Terminal.

```[2024-11-27 09:27:00 +0800] [5888] [ERROR] [django.request::log_response::241] Internal Server Error: /v1/projects/2/auto-labeling
Traceback (most recent call last):
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\renderers.py", line 658, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\renderers.py", line 554, in get_raw_data_form
    serializer = view.get_serializer()
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\generics.py", line 112, in get_serializer
    serializer_class = self.get_serializer_class()
  File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\generics.py", line 126, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'AutomatedLabeling' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
```


I follow this [solution](https://github.com/axnsan12/drf-yasg/issues/754) to fix this bug, the page just like👇
![image](https://github.com/user-attachments/assets/44a8fbcb-3ae9-4805-a671-c3c8422b3f6d)

Unfortunately, the `Rawdata` still can\`t click and I can\`t paste your code to this page.

Do you have any other insights or solutions for this issue? Thank you very much!

**Comment by HelpFireCode** [comment]
> Thank you for your amazing solution! However, there is still some issues I have not resolved... Will you check this? Following your operation, the `Rawdata` in this page can`t click just like picture 1. ![image](https://private-user-images.githubusercontent.com/75774948/390221101-d59c4461-cf1f-4ee5-bec4-3526e61ef077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MjM3MzksIm5iZiI6MTczNjgyMzQzOSwicGF0aCI6Ii83NTc3NDk0OC8zOTAyMjExMDEtZDU5YzQ0NjEtY2YxZi00ZWU1LWJlYzQtMzUyNmU2MWVmMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDAyNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YjBjOThiZmQ4ZjVhYzk5ZDk2NDI2NWViMGY4MDNiNzFjNWVlNmZmYWNmZjY0NTg0YTQ5MjNjMmZiZTZhNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D0BD2ky-i4xjV78qXMKwbH6hGcWCHeiYye8PqwnCzNs)
> 
> Simutanesouly, bug information in the Terminal.
> 
> ```
> Traceback (most recent call last):
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
>     response = get_response(request)
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
>     response = response.render()
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\django\template\response.py", line 114, in render
>     self.content = self.rendered_content
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\response.py", line 74, in rendered_content
>     ret = renderer.render(self.data, accepted_media_type, context)
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\renderers.py", line 727, in render
>     context = self.get_context(data, accepted_media_type, renderer_context)
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\renderers.py", line 658, in get_context
>     raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\renderers.py", line 554, in get_raw_data_form
>     serializer = view.get_serializer()
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\generics.py", line 112, in get_serializer
>     serializer_class = self.get_serializer_class()
>   File "D:\SetUpSoftWare\Anaconda3\envs\yolo11\lib\site-packages\rest_framework\generics.py", line 126, in get_serializer_class
>     assert self.serializer_class is not None, (
> AssertionError: 'AutomatedLabeling' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
> ```
> 
> I follow this [solution](https://github.com/axnsan12/drf-yasg/issues/754) to fix this bug, the page just like👇 ![image](https://private-user-images.githubusercontent.com/75774948/390218690-44a8fbcb-3ae9-4805-a671-c3c8422b3f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4MjM3MzksIm5iZiI6MTczNjgyMzQzOSwicGF0aCI6Ii83NTc3NDk0OC8zOTAyMTg2OTAtNDRhOGZiY2ItM2FlOS00ODA1LWE2NzEtYzNjODQyMmIzZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDAyNTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMWIzNjg4ZjczZTQ5ZTg1ZTIwMTZhNTk3M2IyODE5Nzk2NmI3OTAzZTQwMzRlNjc1MGQ5Y2RhMTgzZWM2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XvhxFW9mGJWnXq5ZQIkWujiOzLiA6bqQuEmgJIlASxM)
> 
> Unfortunately, the `Rawdata` still can`t click and I can`t paste your code to this page.
> 
> Do you have any other insights or solutions for this issue? Thank you very much!

I followed this (link)[](http:/localhost:8000/admin/auto_labeling/autolabelingconfig/1/change/) that solved my problem.
