### ISSUE TITLE
Feature Request: Relation Annotation

### ISSUE THREAD

**Issue by eric-czech** [doccano/doccano#233]
I see it is on the [roadmap](https://github.com/chakki-works/doccano/blob/master/ROADMAP.md) already, but relation annotation would be a very useful feature for us.

**Comment by BrambleXu** [comment]
Could you give more detail about your needs for this feature?

**Comment by eric-czech** [comment]
Following the BRAT model, I think a great feature would allow:

1. Configuration of either directed or undirected relation annotations involving any number of entities (2 being most common) where each can be associated with any number of entity types (1 being most common)
2. The ability to draw these relations as arrows between spans in text 
3. Association of these relation annotations with attributes that are likely to be common to all of them (e.g. "Negated", "Confidence")

**Comment by illcat** [comment]
Overhead.

**Comment by AlJohri** [comment]
I would also like the ability to tag relation between entities particularly for tagging coreference resolution data.

**Comment by andrewkittredge** [comment]
This is what brat looks like, 

![image](https://user-images.githubusercontent.com/430274/72095960-50a44b00-32e7-11ea-8600-6e7e4c63fd81.png)

**Comment by snailkn** [comment]
The same request, is there any dev plan?

**Comment by tagizaade** [comment]
> The same request, is there any dev plan?

The same question

**Comment by Hironsan** [comment]
I have already added the feature to the ToDo list.
But for now, I don't have enough time to implement new features because I focus on fixing bugs now. The hard point is the implementation of the frontend.

**Comment by Oppengame** [comment]
Any timeline?
