### ISSUE TITLE
How to update frontend code and rebuild using docker compose?

### ISSUE THREAD

**Issue by dimidd** [doccano/doccano#2386]
How to reproduce the behaviour
---------
I'd like to update frontend code and rebuild using docker compose. The docker compose production file refers to  doccano/doccano:backend and  doccano/doccano:frontend, where can I find a Dockerfile for the latter?

Your Environment
---------
*   How did you install doccano (Heroku button etc): docker compose

**Comment by dimidd** [comment]
Ah, it's the nginx one
docker/Dockerfile.nginx

**Comment by Kyu-Hwan** [comment]
Please share the details of how you solved it. I also want to update the code and rebuild it using docker compose, but the code changes are not being applied when i rebuild and up container
