### ISSUE TITLE
Convert label to label-ID when exporting

### ISSUE THREAD

**Issue by tovare** [doccano/doccano#295]
# System information
- Mac / Docker / latest chakkiworks/doccano image

### Describe the problem

I´m not able to figure out which label-ID corresponds too which tag-name when exporting document classification in JSONP.

There have been related issues in the past and a patch, but I can´t seem to figure out how to get the labels in the json1 format.

Cheers

**Comment by c-w** [comment]
Tagging @erikamenezes (author of https://github.com/chakki-works/doccano/pull/217).

**Comment by icoxfog417** [comment]
#217 seems not to support document classification. We should consider supporting it.

**Comment by c-w** [comment]
@icoxfog417 I wonder if we should by default always dereference foreign-keys in the serializers, i.e. always replace the ID with something more human readable like a text field.

**Comment by icoxfog417** [comment]
@c-w It sounds good. So far as I know any dataset is labeled by its name, not by id except anonymized case (like Kaggle). @Hironsan is there any case that id is preferred than name?

**Comment by Hironsan** [comment]
Name is better than id.

**Comment by fierceX** [comment]
@c-w Label names are really more convenient, and the problem is that label downloads are not available in the document classification, and there is no label-corresponding ID

**Comment by eric-czech** [comment]
For anyone else that runs into this, at least one work around to get the name to id relationship (as a CSV) from a running container is:

```bash
docker exec -i doccano /bin/bash - << EOF
python -c '
import sqlite3
conn = sqlite3.connect("app/db.sqlite3")
rows = conn.execute("SELECT id, text FROM api_label WHERE project_id = 1;").fetchall()
print("\n".join([",".join(map(str, r)) for r in rows]))
'
EOF
> 1,my_label_1
> 2,my_label_2
> 3,my_label_3
> ... etc
```

**Comment by reinoldus** [comment]
@eric-czech thanks, here is the same as dict:

```
docker exec -i doccano /bin/bash - << EOF
python -c '
import sqlite3
conn = sqlite3.connect("app/db.sqlite3")
# Must replace your project_id here (e.g. from url in web app)
rows = conn.execute("SELECT id, text FROM api_label WHERE project_id = 5;").fetchall()
print({k: v for k,v in rows})
'
EOF
```

Do not forget to adjust the project id :)

**Comment by pogevip** [comment]
> 对于遇到此问题的其他任何人，至少有一个解决方法是从正在运行的容器中获取名称到ID关系（作为CSV）：
> 
> ```shell
> 搬运工EXEC -i doccano /斌/庆典 - <<  EOF
> 蟒蛇-c' 
> 进口sqlite3的
> 康恩= sqlite3.connect（“应用程序/ db.sqlite3”）
> ＃这里必须更换你的PROJECT_ID（例如，从网应用程序的URL）
> 行=康恩.execute（“SELECT id，text FROM api_label WHERE project_id = 1;”）。fetchall（）
> print（“\ n”.join（[“，”。join（map（str，str） r））对于行中的r]））
> ' 
> EOF
>  > 1，my_label_1
>   > 2，my_label_2
>   > 3，my_label_3
>   > ......等
> ```

What should I do if I'm not using docker

**Comment by h-2-0** [comment]
@pogevip,

Access your doccano's database and execute the SQL statement as mentioned above (eg. `SELECT id, text FROM api_label WHERE project_id = 5;`). Once you have the query return its results you could copy paste them into a text document.

**Comment by dcram** [comment]
> @eric-czech thanks, here is the same as dict:
> 
> ```
> docker exec -i doccano /bin/bash - << EOF
> python -c '
> import sqlite3
> conn = sqlite3.connect("app/db.sqlite3")
> # Must replace your project_id here (e.g. from url in web app)
> rows = conn.execute("SELECT id, text FROM api_label WHERE project_id = 5;").fetchall()
> print({k: v for k,v in rows})
> '
> EOF
> ```
> 
> Do not forget to adjust the project id :)

Very nice workaround. It works like a charm. Thanks !

**Comment by kuraga** [comment]
Implemented in #443?

**Comment by at-a-run** [comment]
> For anyone else that runs into this, at least one work around to get the name to id relationship (as a CSV) from a running container is:
> 
> ```shell
> docker exec -i doccano /bin/bash - << EOF
> python -c '
> import sqlite3
> conn = sqlite3.connect("app/db.sqlite3")
> # Must replace your project_id here (e.g. from url in web app)
> rows = conn.execute("SELECT id, text FROM api_label WHERE project_id = 1;").fetchall()
> print("\n".join([",".join(map(str, r)) for r in rows]))
> '
> EOF
> > 1,my_label_1
> > 2,my_label_2
> > 3,my_label_3
> > ... etc
> ```

The above didn't work for me due to #419. The following did:
```
http://hostname:port/v1/projects/{project-id}/labels?format=json
```
Ref:

#624
https://github.com/doccano/doccano/blob/master/app/api/urls.py

**Comment by at-a-run** [comment]
It would be nice if at export time there is an option to choose between label id or label text.

**Comment by lasp73** [comment]
I will submit a pull request to share a change I did to export label names and user names instead of their IDs.
My focus was text classification, but I have adjusted sequence classification also.
(I did not change the examples shown when you hit "Export Dataset"... sorry)

For text classification, json is like the following:

```
{"id": 1, "text": "Test 1 – Sentence 1", "annotations": [{"label": "Test1_Label1", "user": "admin"}, {"label": "Test1_Label4", "user": "guest"}, {"label": "Test1_Label0", "user": "guest"}], "meta": {}, "annotation_approver": null}
{"id": 2, "text": "Test 1 – Sentence 2", "annotations": [{"label": "Test1_Label2", "user": "admin"}, {"label": "Test1_Label5", "user": "guest"}], "meta": {}, "annotation_approver": null}
{"id": 3, "text": "Test 1 – Sentence 3", "annotations": [{"label": "Test1_Label3", "user": "admin"}], "meta": {}, "annotation_approver": null}
```

The CSV file is:

```
annotation_approver,id,label,text,user
,1,Test1_Label1,Test 1 – Sentence 1,admin
,1,Test1_Label4,Test 1 – Sentence 1,guest
,1,Test1_Label0,Test 1 – Sentence 1,guest
,2,Test1_Label2,Test 1 – Sentence 2,admin
,2,Test1_Label5,Test 1 – Sentence 2,guest
,3,Test1_Label3,Test 1 – Sentence 3,admin
```

For sequence classification, the json file is like this:

```
{"id": 301, "text": "Test 1 – Sentence 1", "annotations": [{"label": "Entity1", "start_offset": 0, "end_offset": 6, "user": "admin"}, {"label": "Entity2", "start_offset": 9, "end_offset": 19, "user": "admin"}], "meta": {}, "annotation_approver": null}
```

**Comment by nawshad** [comment]
I find that its easy to just write a query specially if you use heroku, you can take the help of data clip. I used the following query to fetch the labels, usernames, project-names and text for annotation for text annotation task, thought the following postgres query might be useful for some people.



SELECT  u.username as "Username",  
                l.text as "Label-Text",
                p.name as "Project-Name",
                d.text as "Tweet",
                (SELECT u.username WHERE u.id = d.annotations_approved_by_id) as "Approved-By"

FROM  api_documentannotation as da, 
            api_label as l, 
            api_project_users as pu,
            auth_user as u,
            api_project as p,
            api_document as d

WHERE da.label_id = l.id AND 
              pu.user_id = da.user_id AND
              pu.user_id = u.id AND
              p.id = pu.project_id AND
              d.project_id = p.id AND
              da.document_id = d.id

**Comment by ChiLynn123** [comment]
> @eric-czech thanks, here is the same as dict:
> 
> ```
> docker exec -i doccano /bin/bash - << EOF
> python -c '
> import sqlite3
> conn = sqlite3.connect("app/db.sqlite3")
> # Must replace your project_id here (e.g. from url in web app)
> rows = conn.execute("SELECT id, text FROM api_label WHERE project_id = 5;").fetchall()
> print({k: v for k,v in rows})
> '
> EOF
> ```
> 
> Do not forget to adjust the project id :)

Hello, may I ask why I execute this code but output an empty dictionary? @
