### ISSUE TITLE
Feature Request: Export as fasttext format

### ISSUE THREAD

**Issue by alext234** [doccano/doccano#362]
Hi is there any plan to support the export option on fasttext format? 

Here is an example
```
__label__greet Good luck
__label__greet Happy Birthday
__label__greet Happy Journey
__label__wish __label__question Good Morning.  Did you have break - fast ?
```

Reference 

https://fasttext.cc/docs/en/supervised-tutorial.html

**Comment by Hironsan** [comment]
We released [doccano-transformer](https://github.com/doccano/doccano-transformer). It supports data transformation. Currently, supported tasks are named entity recognition and supported formats are CoNLL2003 and spaCy. 

We have a plan to extend tasks and formats.
Please look forward to it.

**Comment by cgill95** [comment]
@Hironsan if I were to code this feature, would there be a chance of it getting implemented? or would it make more sense to code it for the [doccano-transformer](https://github.com/doccano/doccano-transformer)?
I am interested in this feature as well which is why I am asking.
