### ISSUE TITLE
Huge memory usage and not freed when exporting the annotation

### ISSUE THREAD

**Issue by prokotg** [doccano/doccano#383]
**Environment**:

Docker image running on Ubuntu 18.04, Installed on 9/26/2019

Hello!
------------------------------------------------------------
First of all, thank you for developing such brilliant tool :) I'm using it again for yet another project. This time I have a machine that has only 2GB of RAM and I have a dataset that in json has ca. 200 MB. I managed to import it without problems. When I want to export it, however, Memory usage jumps to nearly 1.6 GB and I can download the exported file but **it still occupies the RAM after I download it.** _well, something does_

Having 2GB of RAM in total and 1.6GB taken after this operation, the next time I want to export my annotations I have to click on the Download button twice. The first time, my machine is totally blocked being out of resources and at some point ( I guess) because process run out of memory and is killed _(?)_, RAM usage drops to initial 300mb and then I click on the Download button again and I can export my file. RAM is clocked with 1.6 GB again and here come the vicious circle...

**Question1**: Could you please explain (out of curiosity) why exporting 200MB file requires 5x more RAM?

**Question2**: Why memory is not freed after the export is finished? 

Cheers :)

**Comment by c-w** [comment]
Are you seeing this behavior when exporting the annotations to JSONL or CSV or both?

**Comment by icoxfog417** [comment]
We released doccano 1.0. Please try the new version and if it is not solved, please raise an issue.
