### ISSUE TITLE
Feature Request: Support JSON format (not JSONL)

### ISSUE THREAD

**Issue by liumingwei94** [doccano/doccano#454]
Feature description
---------

Currently, the doccano support import and export as JSONL form. Why not supoort JSON format?
Something like this:
```
[
{"text": "EU rejects German call to boycott British lamb.", "labels": [ [0, 2, "ORG"], [11, 17, "MISC"], ... ]},
{"text": "Peter Blackburn", "labels": [ [0, 15, "PERSON"] ]},
{"text": "President Obama", "labels": [ [10, 15, "PERSON"] ]}
]
```
Because we need to parse the data every time.
Thanks!

**Comment by cgill95** [comment]
I started working on this and finished the import so far. Not sure if I should create a pull request already for it or implement the export first as well.
https://github.com/cgill95/doccano/tree/feature/json_import
