### ISSUE TITLE
Display error?

### ISSUE THREAD

**Issue by attenton** [doccano/doccano#463]
when the annotation text meet '\n', the annotated text will float up which is out of flow.
just as shown below:
before:
![before](https://i.loli.net/2019/11/26/gYMUPOaAz5GiFur.png)

after:
![after](https://i.loli.net/2019/11/26/4CwpDvk2MV7fe93.png)

**Comment by Hironsan** [comment]
Hmm, OK. I will check the problem.
Thanks!

**Comment by owlas** [comment]
I've experienced the same problem. Is there any fix at the moment?

I'm going to try stripping new line chars

**Comment by aakanksha19** [comment]
Are there any updates on this issue? I am facing the same problem with my data, and I would prefer to avoid stripping newlines since I am annotating conversations.
