### ISSUE TITLE
No project listed in the projects page | 404 Error

### ISSUE THREAD

**Issue by vcjob** [doccano/doccano#472]
Hello everyone.
First I've tried to use the newest version of doccano using the docker. It appeared to be fine, none of the users, even Admin could reach the projects page, though. There was always 404 error. Well, when the admin creates the project on the web interface, it appears until the next log in. Then the page again could not be found (404 error) 
![image](https://user-images.githubusercontent.com/51916323/69699433-f1a0c300-10f8-11ea-83b4-50f9ac4f5489.png)
So, due to that, the decision to use an older version of doccano was made. 
It was compiled from the binaries. Everything seemed to be fine, except for no role were available. So I created two roles (the spelling really matters, otherwise nothing will work). But as soon as I did it, admin no longer can see any of the projects on the web interface (I even tried to create the other user with admin privileges, the same thing). So I have to put the url myself, which is not comfortable.. At least, I cannot see the name of the project, so have to memorize the project id..
One more thing to mention, now admin is never greeted by the web interface with it's name. on the name spot just space. I guess it actually the main problem here since the user with such a name naturally is not allowed to view projects.
![Сни22мок](https://user-images.githubusercontent.com/51916323/69700139-c919c880-10fa-11ea-8476-59b14045ece7.JPG)

Any ideas on how to solve it?
Thank you a lot.
---------

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.7
*   When you install doccano: Yesterday
*   How did you install doccano (Heroku button etc): 1st - Docker. 2nd - build binaries

**Comment by Mundayne** [comment]
I'm having a similar error: logged in as the default admin account, set up a project with data and labels ready to go, went and made some other user accounts in Django and turned on collaborative annotation, and then the project disappeared off my projects list. I can still access it via the URL on the admin account, but not on any of the other accounts (despite having given the other accounts superuser permissions) - I get a 404 error when I attempt to navigate to `localhost/projects/1`, which is the correct URL.

**Comment by Hironsan** [comment]
Please try to sign out from admin page.

**Comment by vcjob** [comment]
> Please try to sign out from admin page.

No, id doesn't help at all.

**Comment by vcjob** [comment]
> Please try to sign out from admin page.

Thank you, but though the user can see now the project and no error appears, I can not make him see the data needs to be annotated. Only admin can see it. What should  I do?

**Comment by vcjob** [comment]
> > Please try to sign out from admin page.
> 
> Thank you, but though the user can see now the project and no error appears, I can not make him see the data needs to be annotated. Only admin can see it. What should I do?

UPD. Actually if I go directly to the http://host/projects/1/sequence-labeling page, admin can not also see anything (see the picture)
![image](https://user-images.githubusercontent.com/51916323/69855589-dcfd3000-129c-11ea-966c-457fc9826954.png)
Though the data is available here:
![image](https://user-images.githubusercontent.com/51916323/69855614-ea1a1f00-129c-11ea-829c-c85070e8f92e.png)
But only after I select all data and click "Annotate" I can finally annotate it. But it is possible to select all data when you are an admin. What to do for the user?
![image](https://user-images.githubusercontent.com/51916323/69855631-f43c1d80-129c-11ea-994d-0c8418b82269.png)
And there are no labels available, I created them throw /admin panel though.

**Comment by vcjob** [comment]
> I'm having a similar error: logged in as the default admin account, set up a project with data and labels ready to go, went and made some other user accounts in Django and turned on collaborative annotation, and then the project disappeared off my projects list. I can still access it via the URL on the admin account, but not on any of the other accounts (despite having given the other accounts superuser permissions) - I get a 404 error when I attempt to navigate to `localhost/projects/1`, which is the correct URL.

Did you manage to fix the issue?

**Comment by krn0x2** [comment]
@vcjob I'm having the same issue. Tried reverting my build to v1.0.0 and it still has the same bug. Could you please share the commit hash which seems to work for you?

Also, requesting a fix for the issue

**Comment by icoxfog417** [comment]
Merge to #521
