### ISSUE TITLE
How to get the id of all labels?

### ISSUE THREAD

**Issue by attenton** [doccano/doccano#483]
In the past version, we can get the version by the method mentioned in #295 . However, in the latest version, there are three docker containers, how can i get the id of all labels? Thanks a lot.

**Comment by Hironsan** [comment]
In the latest version, you can export labels as a file and it includes ids:
![image](https://user-images.githubusercontent.com/6737785/69046991-87738880-0a3d-11ea-8e6d-d6bc39000139.png)
