### ISSUE TITLE
cookie error？

### ISSUE THREAD

**Issue by attenton** [doccano/doccano#484]
thanks a lot for your works.
Here are some post errors.
sometimes I cannot login correctly though I input the correct username and password.
![login_error.png](https://i.loli.net/2019/12/03/yWcEzZd4YGQJkwM.png)
and sometimes I cannot delete labels successfully
![delete_label_error.png](https://i.loli.net/2019/12/03/OLskhx6VbgJt4nY.png)

My solution is to restart the browser, reopen the page, then it works.
Does the tools' cookie management cause these problem？
Thank a lot!!!

**Comment by Hironsan** [comment]
Did you login to the admin page?

**Comment by attenton** [comment]
yeah, I loged in to admin page. Thanks.

**Comment by Hironsan** [comment]
Once you logged out from the admin page, you can probably log in to the doccano from the login page.

**Comment by attenton** [comment]
ok, thank you for your patience
