### ISSUE TITLE
import/export removes leading and trailing spaces

### ISSUE THREAD

**Issue by cohen-ori** [doccano/doccano#485]
import a json file with text that include leading or trailing spaces
annotate them
export the json file and those with extra spaces will stripped.

**Comment by orico** [comment]
this is not a question, its a bug IMO

**Comment by icoxfog417** [comment]
@cohen-ori Thank you for reporting the issue. When you annotate, spaces is not stripped?
The head/tail spaces will be removed when importing, and of course exporting.

**Comment by orico** [comment]
did not check that, it will be hard to see trailing spaces. I did not check leading ones.

**Comment by icoxfog417** [comment]
Merge to #521
