### ISSUE TITLE
Annotation statistics counts number of annotated labels (not number of samples)

### ISSUE THREAD

**Issue by cohen-ori** [doccano/doccano#486]
for any multi-label annotation project, let's say you annotate 10 samples with 30 labels, the graph will show 30 annotations and not 10. 
this doesn't sound like a reasonable behavior.

**Comment by afparsons** [comment]
@icoxfog417: Our team has also been confused as to why we observe different completion values for the same project across several accounts (example: 4/847 vs 263/847). We had thought that the progress bar and pie chart was representative of how many samples ("documents") had been marked as "approved". 

Thanks @cohen-ori for explaining this behavior.
Interestingly, this observed behavior does not appear to be present in [this screenshot](https://camo.githubusercontent.com/fb1384fdacf5ec153d05bd34846aa485764dbbf8/68747470733a2f2f7773312e73696e61696d672e636e2f6c617267652f303036744e62527767793166796a773676363834726a3331723330753074626a2e6a7067) from [the tutorial](https://github.com/doccano/doccano/wiki/A-Tutorial-For-Sequence-Labeling-Project). 

As an end user, this is unexpected. If the counter is intentionally designed and implemented this way, then we find it to violate the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Without looking at the source code, I would assume that this is an artifact from the way progress tracking works in classification projects; a classified sample ("document") has just one label, so tracking the number of labels over the number of samples functions as a completion counter.

**Comment by icoxfog417** [comment]
Thank you for your valuable opinions. We deal with this as an enhancement not question and consider improvement.

**Comment by tusharmakkar08** [comment]
Hey @icoxfog417 @Hironsan @cohen-ori 

I am picking up this issue for development. 

Thanks.

**Comment by tusharmakkar08** [comment]
Added the PR for this issue's fix: https://github.com/doccano/doccano/pull/678
