### ISSUE TITLE
pressing left key or right key causes wrong effect

### ISSUE THREAD

**Issue by attenton** [doccano/doccano#488]
An inconvenient effect on pressing right key or left key when I focused on the input box at the annotation of seq2seq type. 
No matter what the status of the input box is, the annotation text will go to previous one or next one when you press left key or right key. So if I want to change the cursor's location, I just can use the mouse not the keyboard. Maybe it's a little bit inconvenient. Can you fix it? Thanks a lot.

**Comment by haryoa** [comment]
Can anyone handle this problem? It annoys us a lot when annotating seq2seq tasks. I think the right and left key can be disabled and let up and down key to change the page.
