### ISSUE TITLE
Invalid "Annotate" button redirection

### ISSUE THREAD

**Issue by jdixosnd** [doccano/doccano#490]
The "Annotate" button on an individual list item is supposed to open that particular record to annotate but it is opening any random record.

Observation: If the displaying list is of size 10, then it opens the 10th index and if the size is 100, then it opens the 100th index irrespective of your selected("clicked") sample.

How to reproduce the behaviour
---------
1. load more than 100 records 
2. goto dataset and change the list size from 10 to 100 
3. click on > to load different records on the list
4. click on "Annotate" 
5. it will open 100th record irrespective of chosen one.

**Comment by icoxfog417** [comment]
Merge to  #522
