### ISSUE TITLE
Cannot login after using manage.py createsuperuser

### ISSUE THREAD

**Issue by squeeko** [doccano/doccano#491]
How to reproduce the problem
---------
I even ran the npm migrate and then ran the manage.py createsuperuser and that ran successfully but when I deploy into AWS Elastic BeanbStalk and get the login page, I cannot login using the account created.

```bash
# cannot login 
```

Your Environment
---------

*   Operating System: Docker running on 64bit Amazon Linux/2.14.0
*   Python Version Used: 3.6
*   When you install doccano: Today
*   How did you install doccano (Heroku button etc): git clone, docker -t build <<appname>> ., manage.py createsuperuser.

**Comment by icoxfog417** [comment]
Did you run ` createsuperuser` on the AWS Elastic BeanbStalk? You have to run the command on your deployed environment.
