### ISSUE TITLE
Unable to login after one click deployment on AWS

### ISSUE THREAD

**Issue by akhilnegi** [doccano/doccano#492]
Unable to login(Your username and password didn't match. Please try again.) after one-click deployment on AWS. 

I was not able to login with the AdminUserName and AdminPassword set during the CloudFormation stack setup.

When I ssh into the EC2 instance, the values were not set for $ADMIN $PASSWORD $EMAIL. I had to run `source /env.list` to set the values and then run `sudo docker exec doccano tools/create-admin.sh ${ADMIN} ${EMAIL}  ${PASSWORD}` in order to set the desired login ID/PASSWORD.

Regards
Akhil Negi

**Comment by akhilnegi** [comment]
Any update on the issue?

**Comment by lohant** [comment]
I have the exact same issue. Would really appreciate a fix to this as the program overall is great.

Best Regards,
lohant

**Comment by ramok** [comment]
There are fix in pull request https://github.com/doccano/doccano/pull/841

https://github.com/doccano/doccano/pull/841/commits/92016a956bd8a35a0b0a88c3edad835cc471bdfa

**Comment by akhilnegi** [comment]
Hi @ramok 

It's still not working with the user and password used while setting up the cloud formation stack.

Thanks!
Akhil Negi
