### ISSUE TITLE
function enhance 

### ISSUE THREAD

**Issue by lanxingdouble** [doccano/doccano#498]
When I use doccano, I find some fucnction can be enhanced. Therefore I make the following suggestions : 
1、My text is long  and contains special character such as "\n". This character is a symbol which can make text easy to read. When I add my data to seq2seq project, there is  is no newline effect. I hope seq2seq can maintain the original format.
![image](https://user-images.githubusercontent.com/18391135/70900518-f12e8480-2033-11ea-966e-d45374918b67.png)
2、Based on above suggest, if the format of data is html, hope the data can be show as html format. Because some of data are obtain from some website, if the project can show as the html. it will be easy to read.
3、The new version can contain left panel and right panel.  Size of two panels are fixed. Hope they  can be adjustive. Because some time, the addtional information is more than the left text.
![image](https://user-images.githubusercontent.com/18391135/70900627-318e0280-2034-11ea-838d-c1b0f76e2a8e.png)

**Comment by icoxfog417** [comment]
Thank you for feature proposal. We discussed this feature at #35.
