### ISSUE TITLE
doccano ran successfully on win10!

### ISSUE THREAD

**Issue by troublemaker-r** [doccano/doccano#499]
How to reproduce the problem
---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System: win 10 64bit
*   Python Version Used:python 3.6
*   When you install doccano: 2019.12.10
*   How did you install doccano (Heroku button etc):
refer to csdn: https://blog.csdn.net/weixin_44912159/article/details/103473275

**Comment by icoxfog417** [comment]
Thank you for reporting!
