### ISSUE TITLE
Enable resize of information pane

### ISSUE THREAD

**Issue by lanxingdouble** [doccano/doccano#501]
The new version can contain left panel and right panel. We can add additional infomation in the right side. However, size of two panels are fixed. Hope they can be adjustive. Because some time, the addtional information is more than the left text.
![image](https://user-images.githubusercontent.com/18391135/70961686-76aa4700-20bd-11ea-9667-07f1b95bb91b.png)

**Comment by icoxfog417** [comment]
We reopen this issue if someone needs this enhancement.
