### ISSUE TITLE
using the arrows & label short-cuts has a weird behavior of skipping a document and not allowing you to correct the label if you go back

### ISSUE THREAD

**Issue by orico** [doccano/doccano#502]
How to reproduce the behavior:
label a document and quickly push one of the keyboard arrows, you have to click it without a delay.
what will happen is that the document will advance, the previous document will not be labeled, the current document, which was advanced to will be labeled, if you go back it the visual will not allow you to label. i think this is a visual bug more than a labeling bug, i.e., the label exists in the first document but the ui wont show it.
unless you reload the page, which will force you to advance from 1 to your current sample.

**Comment by icoxfog417** [comment]
Thank you for the reporting the issue. Could you provide your environment information following to the ISSUE_TEMPLATE?

https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/02-bug.md

**Comment by orico** [comment]
Operating System: ubuntu 16 or 18
Python Version Used: 3.6.5
When you install doccano: a month ago
How did you install doccano (Heroku button etc): docker installation

**Comment by icoxfog417** [comment]
Merge to #555
