### ISSUE TITLE
Documentation: wrong port

### ISSUE THREAD

**Issue by DSLituiev** [doccano/doccano#503]
in [FAQ](https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions#i-want-to-add-annotators):

```
2. Use docker
...
Create & Run doccano container: docker run -d --name doccano -p 8000:80 chakkiworks/doccano
```

which fails, because the port within the container is 8000. It must read:

`docker run -d --name doccano -p 8000:8000 chakkiworks/doccano`

**Comment by icoxfog417** [comment]
Thank you for pointing out the miss. Thank you for pointing out the miss. We fixed it.

**Comment by kuraga** [comment]
Hm...
In [README.md](https://github.com/doccano/doccano/blob/72cafaf881aa239393566278613a725c35b60ee8/README.md): `-p 8000:8000`.
In [FAQ](https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions): `-p 80:8000`.
