### ISSUE TITLE
Deleting undone documents that are pre-annotated

### ISSUE THREAD

**Issue by lukaskovarik** [doccano/doccano#507]
Hi community,

I'm using Doccano for sequence labelling and ran into the following problem in my workflow:

**Background**

1. I imported about 500 _automatically pre-labelled_ documents and started annotating.
2. After annotating quite a few, I realized I was stupid and there's a lot of near-duplicates and gibberish.
3. I decided to delete the remaining (not yet annotated) documents and replace them with new ones. That's where I got stuck.

**The Problem**

I'm unable to delete a specific subset of the documents when using pre-labelling.

**What I tried**

- Filters - _Undone_ filter shows only docs without any annotation, so not useful for my case.
- _Dataset_ listing - select all and uncheck the first _N_ documents. Unfortunately, it seems that they don't reliably keep their order in the listing and therefore I might accidentally delete the done docs. 
- Django Admin - didn't find anything helpful concerning document order
- _Checked / Not checked_ button - unfortunately, the status doesn't show anywhere, neither in the UI nor in Django admin.

Actually what would easily solve my problem would be a simple "delete this document" button from document detail view - it wouldn't disturb the workflow and it would make sure that I'm actually deleting the document I want to delete.

Or am I missing something?

Many thanks in advance for looking at this! 

Lukas

**System Info**

Basic Ubuntu 18 image on AWS, freshly installed through docker-compose a few days ago.

**Comment by icoxfog417** [comment]
Merge to #523
