### ISSUE TITLE
Provide prebuilt Docker image that enables using doccano just only docker run

### ISSUE THREAD

**Issue by mhf-ir** [doccano/doccano#508]
I use docker-compose for build image it's ok but it's really painfull.

Docker images must container all prebuild and must ready application but seems be after install using docker-compose build, API not have static contents.

![Screenshot from 2019-12-21 21-59-18](https://user-images.githubusercontent.com/1172526/71312207-6d163b80-243d-11ea-91cc-d4bc1d984ddf.png)

End user(of software) must just run docker container build must be part of creating docker image not deploy part.

**Comment by icoxfog417** [comment]
docker-compose is now updated. Please try the new one! (#558)
