### ISSUE TITLE
Different UIs?

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#509]
Good day!

After starting doccano (via Docker-compose) I have interface such as 
![1](https://user-images.githubusercontent.com/1063219/71345567-c766e780-2576-11ea-8f79-b117a1b496fa.png)

But we have another [in demo](https://doccano.herokuapp.com/demo/text-classification/): 
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/1063219/71345673-190f7200-2577-11ea-9b49-f93d48b49a44.png">

Why? Thanks.

**Comment by icoxfog417** [comment]
We do not update the demo site to v1.0,0 (your installed version is v1.0.0). Please wait for a little it'll be coming soon!

**Comment by kuraga** [comment]
@icoxfog417 well, 1.0.2.

But... We have more features in demo: key labeles (hints), progress bar... Were they removed?

**Comment by kuraga** [comment]
@icoxfog417 sorry about ping but what about key progress bar and labels?

**Comment by kuraga** [comment]
@c-w @icoxfog417 sorry about ping but what about key progress bar and labels?
