### ISSUE TITLE
Small enhancement requests

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#515]
Good day!

Thank you for your GREAT work!

I have some enhancement requests... Just for a note, maybe. I will update them permanently.

1. URLs should become to a corresponding state. On Dataset page, URL is `/projects/4/dataset`. But refreshing the page redirects to `/projects/4`.
2. IMHO menu should be opened on Project page and subpages by default.
3. Let key shortcut hints and progress bar back to Annotation page (#509).
4. Show number of imported rows.
5. Show number of deleting rows only in confirm dialog. It's difficult to delete many rows.
6. Add First/Last pagination links.
7. Pagination should change URL.
8. "Rows per page" should change URL or/and this field should be free editing.
9. Removing rows freezes page. Could it be improved?
10. Add importing of Excel and CoNLL files to UI?
11. More concrete importing file's validating errors.
12. Use Alpine versions of Nginx, Node and Python (Docker)?
13. On Annotation page: implement Label client side validation.
14. [needs investigating] Seems like I can't sign in into Django Admin and Daoccano in parallel (error: incorrect password)
15. Show current user name.
16. Implement project edit page.
17. Show Filter button even if there are no filtered documents (yes, it disappears).
18. Don't show Not checked button unless user has permission to click it (now: error 403 on click).

Doccano 1.0.2.

Thanks!

**Comment by icoxfog417** [comment]
Thank you for your proposal. Please raise the issue after your enhancement request is fixed.

**Comment by kuraga** [comment]
@icoxfog417 , could you clarify, please, which points would you accept a PR for (p.1, p.2, ..., p.19)?

**Comment by kuraga** [comment]
@c-w , @icoxfog417 , @Hironsan could you clarify, please, which points would you accept a PR for (p.1, p.2, ..., p.19)? I could implement some of them...

**Comment by icoxfog417** [comment]
We are welcome to any improvement PR! If you make the PR, please read the [contribution guideline](https://github.com/doccano/doccano/wiki/How-to-Contribute-to-Doccano-Project) before your working.

**Comment by kuraga** [comment]
Another list: #882.

**Comment by br-dr3** [comment]
#869 is under review after @Hironsan said in #928

**Comment by kuraga** [comment]
Stop updating now.

**Comment by kuraga** [comment]
Thanks for 1.1.0! Stop updating now.
