### ISSUE TITLE
[Bug report] Access denied state doesn't redirect to root page

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#518]
Go to `http://192.168.105.160/projects` before you signed in.

Actual:
- 403 error `window.alert()`.
- (an empty) Projects page.
- there is no Sign in link.

Expected:
- root page?
- Sign in link

Doccano 1.0.2

**Comment by icoxfog417** [comment]
Merge this issue to #522

**Comment by Hironsan** [comment]
I couldn't reproduce the situation.

**Comment by kuraga** [comment]
Yes, seems like redirection to `/auth` works on `master` now.
