### ISSUE TITLE
[Bug report] "Share annotations across all users" is discarded

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#519]
![image](https://user-images.githubusercontent.com/1063219/71471653-48291c00-27e1-11ea-93cc-7122dcc97501.png)

but in Django Admin...

![image](https://user-images.githubusercontent.com/1063219/71471687-655dea80-27e1-11ea-8c92-77a4916b1fd9.png)

**Comment by c-w** [comment]
Confirmed the issue and working on a fix.
