### ISSUE TITLE
Known issue about Page Access

### ISSUE THREAD

**Issue by icoxfog417** [doccano/doccano#522]
**Please read this issue when you can't reach the page or faced strange navigation**  
**If you faced the following issue, please upvote 👍 related issue that let us judge priority .**

- [ ] Can' access the page
  - [ ] [Bug report] Annotator doesn't see the project #822
  - [ ]  Deployment to cloud platform (Azure WebApp / Google Cloud Run/ Heroku) causes Request failed with status code 403 #1098

### Our correspondence

1. Make clear access control by role.
2. Make a clear concept of 404/403 navigation.
3. Make a clear recovery path from 404/403 page.

**Comment by icoxfog417** [comment]
Access Control should be ...

|             | no-role | with-role | with-admin |
|-------------|---------|-----------|------------|
| /projects/  | o       | o (#574)        | o          |
| /project/x/ | x       | o         | o          |

The projects list shown on the `/projects/` should be restricted by role.

**Comment by sharmila-polamuri** [comment]
> Access Control should be ...
> 
> -auth/-role	+auth/-role	+auth/+role	admin
> /projects/	x	o	o	o
> /project/x/	x	x	o	o
> But now... (maybe)
> 
> -auth/-role	+auth/-role	+auth/+role	admin
> /projects/	x (403 but no login (#518))	x?	**x** (#574 )	o
> /project/x/	x	x	o	o
> * auth: login authentication (-: can't login, +: can login)
> * role: has role to the specific project (-: doesn't have role, +: has role)

How to change x,o of +auth/+role to o,o ?

**Comment by argideritzalpea** [comment]
Perhaps my issue is related to this: https://github.com/doccano/doccano/issues/1269

Are there any specific steps known to recovering access after `403` when loading projects?
