### ISSUE TITLE
Feature Request: Bulk Delete

### ISSUE THREAD

**Issue by lanxingdouble** [doccano/doccano#523]
I want to clear all data but don't want delet the project. So i use the function in Dataset, i find something wrong.
1、Sometimes it doesn't show the remaining data unless i refresh the project. I want to delete 100 pieces of data at a time, so I have to choose 100 again.  It is inconvenient.
![image](https://user-images.githubusercontent.com/18391135/71570737-bb989980-2b11-11ea-8fd4-52548cb85e01.png)

2、So I hope there is a button to clear all the data.

**Comment by nbroad1881** [comment]
It also would be nice to separate the imported datasets with labels. Then just one dataset could be deleted

**Comment by shijieyao** [comment]
+1 defo want this feat! thanks! 🤩
