### ISSUE TITLE
Uploading plain text file errors

### ISSUE THREAD

**Issue by KIC** [doccano/doccano#529]
`docker compose up`

Your Environment
---------
Ubuntu 19.04
Docker version 18.09.7
Chrome: 79.0

Upload new plain text document:
This field may not be blank.

**Comment by kuraga** [comment]
See also #521, https://github.com/doccano/doccano/issues/521#issuecomment-569203192. Merge there?

**Comment by icoxfog417** [comment]
Thank you for reporting the issue! It may be same as #516.
