### ISSUE TITLE
Allow user to change another users' annotation

### ISSUE THREAD

**Issue by Slyne** [doccano/doccano#531]
How to reproduce the behaviour
---------

I have added the permission to allow users change the annotations.
But I cannot find where to allow users to change other people's annotations.
This is especially important because I've already had some annotations. I need multiple people to correct these annotations.

Your Environment
---------

*   Operating System: linux
*   Python Version Used: python 3.6
*   When you install doccano: Oct 2019
*   How did you install doccano (Heroku button etc):

**Comment by icoxfog417** [comment]
Did you try Share annotations across all users"?

![image](https://user-images.githubusercontent.com/544269/72195532-1c02d180-3456-11ea-8b2f-763b810f1406.png)

**Comment by Slyne** [comment]
@icoxfog417 yes, i've set this option when creating the project.

**Comment by kuraga** [comment]
#519 ?

**Comment by icoxfog417** [comment]
@Slyne Thank you for reporting, please help me to clarify your problem.

* You checked "Share annotations across all users" then ...
  * You can't "watch" any annotations by other users?
  * You can't "edit" any annotations by other users?
  * You can't "control" the role of other annotators for editing/watching?

**Comment by Slyne** [comment]
Yes, I checked "share annotations across all users" and also set collaborative annotation in admin page.
I can watch annotations by other users.
I can't edit any annotations by other users.
I'm not sure where to control the role.  I give all the permissions to all users on the admin page but it still doesn't work.

**Comment by icoxfog417** [comment]
@Slyne Thank you for the clarification. We arrange the relation between the feature to share the annotation and the feature to control the authority to it (read/write).

**Comment by cgill95** [comment]
I think this should be fixed with my implementation of #703 if it gets approved. After that annotation approvers can edit/remove other annotations that were made by annotators.

**Comment by br-dr3** [comment]
I guess annotator should be able to edit other annotators tags only if document was not approved.

**Comment by Hironsan** [comment]
To make my mind clear:

- If `share annotation` is not checked:
  - all the roles can't view other's annotations.
- If `share annotation` is checked:
  - all the roles can view other's annotations.
  - `project_admin` and `annotation_approver` can edit/delete other's annotations.
  - `annotator` cannot edit/delete other's annotations.

Ideal situation:
- If `share annotation` is checked, all the roles can view/edit/delete other's annotations.

**Comment by br-dr3** [comment]
I think approver annotator should be capable to annotate too. Sometimes there are just a few errors, that do not need to "retag" all the document. 

In future, maybe should be necessary to keep annotation history / who annotated, what each one had annotated, what specific annotation haven't been approved and so on.

**Comment by Hironsan** [comment]
Thanks for your opinion. I agree with you that retagging the entire document is not necessary.

I will organize what each role can and cannot do. After that, I'm looking forward to your opinion.
