### ISSUE TITLE
Error reading webpack-stats.json

### ISSUE THREAD

**Issue by Rioghasarig** [doccano/doccano#533]
I followed the instructions to build Doccano from source on my Windows laptop. Everything ran with no errors. But when I tried to visit the server on my browser I was met with the error.

`Error reading C:\Users\oekenta\doccano\app\server\static\webpack-stats.json`

When I go to that file location it is indeed the case that this file does not exist. Is this file necessary? 

So when / where was this file supposed to have been created? 

Can I stop the program from trying to use it? Or is there a way I can create the file myself?

**Comment by icoxfog417** [comment]
Please follow the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/01-question.md), we can't help you without your environment information.

**Comment by Rioghasarig** [comment]
Thanks for the quick response. Here's a bit more information.

Operating System: Windows 10
Python: Python 3.6 from Anaconda

As for reproducing the issue, I just followed the instructions for installing from source found on the FAQ. 

Thanks for your help.

**Comment by Rioghasarig** [comment]
I tried the same thing using Ubuntu linux with the same result.  I don't think the instructions provided properly creates the required webpack-stats.json file.  

I managed to get it running by doing the following
1. Navigate to app\server\static in the doccano directory. 
2. Run npm install webkit-cli 
3. Run npx webkit --config webpack.config.js 

I don't know anything about node.js so I'm not sure if this is a good solution.

**Comment by prakhar9998** [comment]
Did you run the webpack server? https://github.com/doccano/doccano/issues/439#issuecomment-552515746

I tried this and it worked:
`cd app/server/static`
`npm install`
`npm start`

This will start the webpack server on port 8080. Then run the django server.

**Comment by Rioghasarig** [comment]
Yep this works for me. Thanks so much for your help.

**Comment by icoxfog417** [comment]
Thank you @prakhar9998 for your nice support!
