### ISSUE TITLE
The trick to show line break on doccano

### ISSUE THREAD

**Issue by darkzenon** [doccano/doccano#534]
if you have \n in JSONL and you want see new lines in fataset you can add css white-space:"pre" to class text-sequence.

in JS it will be 
`$(document).ready(function () {
$('.text-sequence').css("white-space","pre");
});`
for chrome you can use browser extension.

**Comment by icoxfog417** [comment]
Thank you for suggesting nice hack!

**Comment by elric-dev** [comment]
Can you explain in a bit more detail on how to accomplish this?
thanks!
