### ISSUE TITLE
Switching the theme. No option on header as shown in Readme.

### ISSUE THREAD

**Issue by Deepthi-Chand** [doccano/doccano#536]
How to reproduce the behaviour
---------
Proceed with normal installation steps.
Bring up docker instance and go to home page/login.

Do not see the option to switch theme between light and Dark.
Demo environment seems to be in same state.

Your Environment
---------

*   Arch Linux
*   Python Version Used: 3.8
*   When you install doccano: 13th january 2020
*   How did you install doccano (Heroku button etc): Docker

**Comment by Hironsan** [comment]
Switching theme is now available only in docker-compose version.
If you want to use the feature, please use docker-compose.
