### ISSUE TITLE
Redirect to the specific page by id, not by offset.

### ISSUE THREAD

**Issue by GitOffice** [doccano/doccano#540]
Feature description
Currently, I can locate the annotated documents with offset variable in the formatted url, http://demo.herokuapp.com/projects/1/#offset=.  It works in the same session but it fails if I log out because the documents are in randomized order .

Could you please tell me how to locate document by id  from the url like  demo.herokuapp.com/projects/1/#**docid**=?

**Comment by icoxfog417** [comment]
We now support only offset link #261. But id based link is required.

**Comment by kuraga** [comment]
Superset: #595.
