### ISSUE TITLE
Is there a way to export the annotated data to a JSONL via the API?

### ISSUE THREAD

**Issue by julianeagu** [doccano/doccano#543]
I am trying to (1) upload data to Doccano -> annotate data in Doccano -> export annotated data -> annotate more data via external script -> upload annotated data to Doccano

Is there way to export data from Doccano in a format that is also accepted as an input? It looks like the JSONL should work, but I can only figure out how to export it via the UI. Is there a way to export the data in a JSONL format via the API?

**Comment by rnikiforova** [comment]
You can use the API but it's not documented. See #299 . There's a separate project [doccano_api_client](https://github.com/afparsons/doccano_api_client) (mentioned in #299) which has `get_doc_download` but it downloads csv, not json (I think that the issue is probably in doccano).

**Comment by icoxfog417** [comment]
@rnikiforova Thank you for your contribution to solve the question!
