### ISSUE TITLE
Feature Request: Support Nested Named Entity Recognition

### ISSUE THREAD

**Issue by alokpadhi** [doccano/doccano#544]
Feature description
---------

Currently NER tagging only provides to label single entity at a time. Is it possible to do entity inside entity (nested entity).
For example inside an entity personal info, an entity name can be placed.
My name is xxx and I live in yyy. Here the whole sentence is personal info but the xxx is a name entity.

**Comment by icoxfog417** [comment]
There are some variations of entity overwrapping. We have to deal with these cases carefully to implement the annotation feature.

Reference: [Recognizing Complex Entity Mentions: A Review and Future Directions](https://www.aclweb.org/anthology/P18-3006/)

**Comment by Hironsan** [comment]
Hello @alokpadhi ,

Do you know any annotation tool which can annotate nested NER?
If you know it, please tell me for my reference.

**Comment by alokpadhi** [comment]
> Hello @alokpadhi ,
> 
> Do you know any annotation tool which can annotate nested NER?
> If you know it, please tell me for my reference.

For that matter you can use [Inception](https://inception-project.github.io/), [Dataturks](https://dataturks.com/), [brat](http://brat.nlplab.org/)

I found inception and dataturks user friendly. But I will be very happy if Doccano comes with this feature asap.

**Comment by scheiblr** [comment]
> Hello @alokpadhi ,
> 
> Do you know any annotation tool which can annotate nested NER?
> If you know it, please tell me for my reference.

[Anafora](https://github.com/weitechen/anafora) could be interesting, too.

**Comment by alokpadhi** [comment]
> > Hello @alokpadhi ,
> > Do you know any annotation tool which can annotate nested NER?
> > If you know it, please tell me for my reference.
> 
> [Anafora](https://github.com/weitechen/anafora) could be interesting, too.

I see, it's quite an interesting tool. and It looks more advance tool for labeling schema than the ones I have mentioned earlier.

**Comment by MikeVlad6** [comment]
I needed this feature for myself so i made an implementation which is fine for my use. Unfortunately i had to remove the update functionality because the outer NER would always juxtapose the inner NER in terms of v-menu. 
I've also added the functionality to "round" selection to whole words.

**Comment by Hironsan** [comment]
Rough design idea:

![image](https://user-images.githubusercontent.com/6737785/88457207-885b9480-cebf-11ea-92fe-d9608e6f1610.png)

**Comment by Hironsan** [comment]
Coming soon...
![](https://i.gyazo.com/8126c2d28675007fd05c916e7cadee71.gif)

**Comment by akinolawilson** [comment]
Is there currently an alternative path anyone suggests?

I am working on a named entity recognition and linking pipeline. I would like to be able to specify the unique identifier inside of the labels provided by Doccano.

**Comment by PeterPanUnderhill** [comment]
> Coming soon...
> ![](https://camo.githubusercontent.com/51e916d8bda88e3167fe52e150eb6565a8ffe4df19ebce4e9e0abc2eeb147bdb/68747470733a2f2f692e6779617a6f2e636f6d2f38313236633264323836373530303766643035633931366537636164656537312e676966)

Is there an estimated time?
