### ISSUE TITLE
Won't Allow New Users Sign-up in Azure

### ISSUE THREAD

**Issue by xuanlv2** [doccano/doccano#546]
Hi, 

I managed to deploy doccano in Azure (https://text-annotator-doccano.azurewebsites.net/).
Everything works well except that it won't allow new users to sign up. If I try to sign up a new account, it will show Server Error (500).

*   Operating System: Windows 10
*   Python Version Used: Python 3.7.3
*   When you install doccano: 1/21/2019
*   How did you install doccano: Azure button

**Comment by isaackod** [comment]
I have the same issue. Interestingly, the users that failed to register show up under 'add existing user' in the project tab if you log in as admin.

**Comment by isaackod** [comment]
So I haven't found the actual bug, but you can get user accounts to work by going to the Django admin page http://{APP_NAME}.azurewebsites.net/admin/auth/user/. All of the signups that led to the 500 error seem to exist here, you can click the user and check the 'active' checkbox. After that, users seem to be able to log in normally... You can also create users there. 

This is 
![Capture](https://user-images.githubusercontent.com/13242382/72922639-61a78000-3d1b-11ea-8259-e83cc90bc343.PNG)

**Comment by c-w** [comment]
When a new user registers on Doccano, a confirmation email is sent to the email address provided during sign-up and the user account is only activated when the user clicks the link in that email.

Sending these emails was implemented fairly recently for the Azure deployment so perhaps your instance doesn't have this feature yet (see https://github.com/doccano/doccano/pull/504)? Could you confirm that your version of Doccano deployed with a Sendgrid resource?

Alternatively, given that you're already in Azure, I would also suggest to consider using the Azure Active Directory integration (see https://github.com/doccano/doccano/pull/75) to manage user access to Doccano. It's even possible to manage admin access to the application via Azure Active Directory (see https://github.com/doccano/doccano/pull/210).

**Comment by icoxfog417** [comment]
@c-w Thank you for your detail answer!
