### ISSUE TITLE
Welcome nginx page after installation

### ISSUE THREAD

**Issue by swicaksono** [doccano/doccano#548]
I follow the installation instruction using docker-compose, but after the installation finished and there's info that the application listening at http://0.0.0.0:8180 (I changed the port runserver), I open the IP address but it returns the welcome nginx page. It seems I did wrong steps or other misconfiguration, but I don't know what it is.
Any helps or how should I trace this? 

Your Environment
---------

*   Operating System: Ubuntu
*   Python Version Used: 3.6
*   When you install doccano: 27/1/2020
*   How did you install doccano (Heroku button etc):
Using docker-compose

**Comment by Hironsan** [comment]
Hello @swicaksono,

Please tell me what file did you change?

**Comment by swicaksono** [comment]
hi @Hironsan it is already solved. I change the nginx port at the docker-compose yaml, but I forgot to change the server listen at nginx/nginx.conf. Thanks !

**Comment by Hironsan** [comment]
Your welcome!
