### ISSUE TITLE
Deploy on Azure fails

### ISSUE THREAD

**Issue by edarzi** [doccano/doccano#550]
trying to deploy on Azure by "Azure button" but deployment failed due to **INVALID_HOST_CHARS**

```
File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1337, in load
    self.netloc = tokens.netloc  # Raises ValueError in Python 2.7+.
  File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1801, in __setattr__
    object.__setattr__(self, attr, value)
  File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1464, in netloc
    self.host = host
  File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1801, in __setattr__
    object.__setattr__(self, attr, value)
  File "/usr/local/lib/python3.6/site-packages/furl/furl.py", line 1379, in host
    raise ValueError(errmsg % (host, INVALID_HOST_CHARS))
ValueError: Invalid host 'doccanocompliance-state:y_7Org1m10HncGBk@doccanocompliance-state.postgres.database.azure.com'. Host strings must have at least one non-period character, can't contain any of '!@#$%^&'"*()+=:;/', and can't have adjacent periods.
```
provided the following params:
app name: doccanocompliance
admin user: dsuser
secret key:y_7Org1m10HncGBk
admin password: y_7Org1m10HncGBk

all other remain with default values

we tried with different values but all failed on same error.

please advise

**Comment by icoxfog417** [comment]
Your secret key/password is exposed as the hostname. Would you please confirm your setting for Azure deploy? If this is a certain behavior, it is critical security issue.

**Comment by edarzi** [comment]
Nothing is exposed, Of course it was removed in advanced. i just gave the details for the BUG.
i tried it several times with different values, the result was the same for all attempts. INVALID_HOST_CHARS

**Comment by icoxfog417** [comment]
The hostname is exactly invalid because it includes non-period character, and it seems to be your secret key (admin password) ( `doccanocompliance-state:`**y_7Org1m10HncGBk**).
So I confirmed the above question.

`ValueError: Invalid host 'doccanocompliance-state:y_7Org1m10HncGBk@doccanocompliance-state.postgres.database.azure.com'. Host strings must have at least one non-period character, can't contain any of '!@#$%^&'"*()+=:;/', and can't have adjacent periods.`

**Comment by dudubis** [comment]
@icoxfog417 The above error stack is from the azure container that runs the webapp. They are not exposed in any way externally hence no security issues here. The issue at hand is the connection string to the postgres db thats invalid given the following parameters (you can reproduce yourself during the deployment):

app name: doccanocompliance
admin user: dsuser
secret key:y_7Org1m10HncGBk
admin password: y_7Org1m10HncGBk

As you can see above we don't have the "-state" in our hostname (value is: doccanocompliance) and it was added automatically during the deployment.

**Comment by c-w** [comment]
I looked into this and was unable to reproduce the startup failure. The error message to me looks like an exception in parsing the database connection string where some part (username, password, etc.) broke [furl](https://pypi.org/project/furl/).

Could you confirm that the `DATABASE_URL` setting in the WebApps for Containers resource looks something like this:

![Screenshot showing value of DATABASE_URL](https://user-images.githubusercontent.com/1086421/73797830-0e9fe500-477f-11ea-8b5c-2857092551ee.png)

The desired pattern for the database connection string is `pgsql://{your_admin_name}%40{your_app_name}-state:{your_admin_password}@{your_app_name}-state.postgres.database.azure.com:5432/doccano`. Neither the app name or the admin name should contain URL unsafe characters.

**Comment by dudubis** [comment]
@c-w, I have used different credentials for secretkey and passwd (only upper/lower/digits no special characters) and it works fine now. I guess we can reopen it if someone runs into it the 
 same issue in the future 
`(raise ValueError(errmsg % (host, INVALID_HOST_CHARS)) ValueError: Invalid host ).`

Thanks for your help and time.
