### ISSUE TITLE
Mouse selection of first words in row fail to tag until after another selection is made

### ISSUE THREAD

**Issue by jolittma** [doccano/doccano#551]
How to reproduce the behavior
---------
- When on a new sentence or example, if the first thing you tag is the first word of a row, it will fail to annotate the label if you select to the left of the first letter with your mouse and drag the highlight to the right. Once the word is highlighted in the way, if you click on any label it will not assign the label and it will deselect you selection. 

- This can be seen in the DEMO on your website: https://doccano.herokuapp.com/demo/named-entity-recognition/#
- happens in both Chrome and Edge

- You can select a single word or multiple, in either case this will fail occasionally (probably 5 in 10 times). 
- moving your selector from right to left also fails to tag occasionally. 
1. Go into the live demo on the site, select the "The Democratic Party is one of the two major contemporary po..." example
2. Select the 3rd row "Republican" text by starting the click before the "R" and ending at the completion of the word
3. Select the "Person" tag
4. If this did actually annotate the word Republican as person, do not refresh the page but try again with the word "Republican" in the 2nd row, this should word but then when you select the word "the" in the second row and try to assign it to the tag "Person", this should fail

- double clicking seems to mostly work but does also fail 
1. Go into the live demo on the site, select the "The Democratic Party is one of the two major contemporary po..." example
2. Select the 3rd row "Republican" text by double clicking the word
3. Select the "Event" tag, this should work
4. select 2nd row "Republican" by double clicking
5. Select the "Event" tag, this should work
6. now select the word "the" in the 2nd row by double clicking
7. try to assign it the tag of "Event" and this should fail

Your Environment
---------
- LIVE DEMO page on Doccano website
- also saw failures with personal data, Docker load, V1.0.2

**Comment by V15HAL** [comment]
I'm facing a similar issue. Sometimes when I select a text and try to tag it, it doesn't tag it until I try multiple times. Including a gif describing the issue.
![doccano](https://user-images.githubusercontent.com/8018870/73377786-3bd32b80-4285-11ea-8f2d-eb173ab7ea98.gif)

**Comment by lebionick** [comment]
Same story as V15HAL has. 

![vid](https://user-images.githubusercontent.com/8808008/77301671-26b4cf00-6d01-11ea-9b85-19b4a6489193.gif)

**Comment by icoxfog417** [comment]
Please use the latest doccano!

**Comment by scottholiday** [comment]
Hi, the issue is still there even I installed the latest Doccano. Do you know why?

**Comment by xhw205** [comment]
Same story as you has，how did you solve it ?

**Comment by lebionick** [comment]
I changed my place of work and there is no NLP :)
