### ISSUE TITLE
I cannot access http://127.0.0.1:8000/login/ after installing it using docker

### ISSUE THREAD

**Issue by Srijha09** [doccano/doccano#552]
---------
I chose the 2nd option to install doccano using docker in cmd prompt after downloading docker for windows 10 pro.
I am able to start doccano from docker. But when I try to access: http://127.0.0.1:8000/login/ it does not go to the login page.

After installing doccano I cannot access the server. Please let me know what can be done as soon as possible
<img width="733" alt="Capture1" src="https://user-images.githubusercontent.com/50697493/73535016-9c5e9600-4448-11ea-80d6-397740014d32.PNG">

```

Your Environment
---------

*   Operating System: Windows 10 Pro
*   Python Version Used: Python 3.7
*   When you install doccano: I could'nt install it
*   How did you install doccano (Heroku button etc):  I used the docker method to install it

**Comment by icoxfog417** [comment]
Would you please provide the commands that you executed on cmd prompt?
At the same time, please confirm your network setting especially the proxy setting.

**Comment by PastranaG** [comment]
I had a similar error when I used  docker-compose, try this way:

```
docker pull chakkiworks/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 chakkiworks/doccano
docker container start doccano
```

**Comment by icoxfog417** [comment]
related PR #558

**Comment by Hironsan** [comment]
I can access http://127.0.0.1:8000.
Try to add it as a proxy exception.
* https://www.stlouis-mo.gov/government/departments/information-technology/web-development/web-tutorials/browsers/add-exception-proxy-settings.cfm
