### ISSUE TITLE
Scroll multiple times on button press

### ISSUE THREAD

**Issue by nbroad1881** [doccano/doccano#555]
When using the arrow keys to go to the next sample, occasionally it flips through multiple samples very quickly.

See attached gif

How to reproduce the behaviour
---------
I was annotating using keyboard shortcuts and changing samples with left/right arrow keys.

Your Environment
---------
Mac OS Catalina 10.15.2 (19C57)
Docker version 19.03.5, build 633a0ea
Python 2.7.16
Installed with docker compose
![doccano_gif](https://user-images.githubusercontent.com/24982805/73976634-b68bee80-48f6-11ea-9ae7-2c8ab756ffdc.gif)

**Comment by icoxfog417** [comment]
Let me confirm the behavior you faced. If you press the left/right key, doccano occasionally skips some samples, ok?

The #488 maybe related issue.  Would you please update the doccano and confirm the phenomenon?

**Comment by icoxfog417** [comment]
related: #502

**Comment by nbroad1881** [comment]
> Let me confirm the behavior you faced. If you press the left/right key, doccano occasionally skips some samples, ok?
Correct
 
> The #488 maybe related issue. Would you please update the doccano and confirm the phenomenon?
What do you mean by update?

**Comment by icoxfog417** [comment]
Thank you for the response. The "update" means to use the latest doccano / docker-compose if you use the older one.

**Comment by Hironsan** [comment]
In fact, doccano fetches 10 documents at one time and stores them in local memory. If we press the left/right key, doccano changes the current document index(0-9). If we press the right key when the current document index is 9, doccano changes it to 0 and fetches new 10 documents. Due to the network delay, there is some time to show old documents.

**Comment by kuraga** [comment]
> Due to the network delay, there is some time to show old documents.

So you confirm it is a bug?

**Comment by aam1r** [comment]
This is a bad bug. I have people on my team who are skipping over dozens of documents because of this.

They have to consistently go back and find "Undone" tasks and re-do them and it's slowing us down.

Can we get a fix for this please?
