### ISSUE TITLE
Strange redirect

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#556]
I noticed some strange behavior debugging #554 issue. So:

1. Reproduce conditions of #554 issue.
2. Go to `http://<ip address>:<port>/projects`.
3. Yo get `window.alert()` with 500 error message.
4. Press <F5>.
5. You are redirected to `http://<ip address>/projects` (without `<port>`!). Why?

P.S. I don't get this redirection without #554 conditions (i.e. without 500 error).

**Comment by icoxfog417** [comment]
duplicate to #458
