### ISSUE TITLE
Installation on windows. how to solve this error

### ISSUE THREAD

**Issue by prakashwarbler** [doccano/doccano#557]
(base) C:\Users\prakash\doccano>docker-compose -f docker-compose.prod.yml up
Creating network "doccano_default" with the default driver
Creating network "doccano_network-frontend" with the default driver
Creating network "doccano_network-backend" with the default driver
Creating volume "doccano_static_volume" with default driver
Creating volume "doccano_postgres_data" with default driver
Creating volume "doccano_www" with default driver
Building frontend
Step 1/6 : FROM node:13.2.0
13.2.0: Pulling from library/node
844c33c7e6ea: Pull complete                                                                                                                                                                                        ada5d61ae65d: Pull complete                                                                                                                                                                                        f8427fdf4292: Pull complete                                                                                                                                                                                        f025bafc4ab8: Pull complete                                                                                                                                                                                        7a9577c07934: Pull complete                                                                                                                                                                                        9b4289f800f5: Pull complete                                                                                                                                                                                        e5b5cb6034b3: Pull complete                                                                                                                                                                                        77980c72a787: Pull complete                                                                                                                                                                                        7c5d27382edd: Pull complete                                                                                                                                                                                        Digest: sha256:ead25ba89fdbace5701281b1f8c35c317ed09d10ba30fcd01ded881406b84e7f
Status: Downloaded newer image for node:13.2.0
 ---> 760e12e87878
Step 2/6 : WORKDIR /app
 ---> Running in a25bbbc6a331
Removing intermediate container a25bbbc6a331
 ---> 8474828efb92
Step 3/6 : COPY . /app/
 ---> 930e042eaf6d
Step 4/6 : RUN npm install -g npm@latest
 ---> Running in 901d04bc650d
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.13.7
added 8 packages from 4 contributors, removed 4 packages and updated 16 packages in 19.145s
Removing intermediate container 901d04bc650d
 ---> 313d303032a7
Step 5/6 : RUN npm install
 ---> Running in a2dc2ce280b8
n**pm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()**

> fibers@4.0.2 install /app/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/app/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/app/node_modules/fibers/build'
Installed in `/app/node_modules/fibers/bin/linux-x64-79-glibc/fibers.node`

> core-js@2.6.11 postinstall /app/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> ejs@2.7.4 postinstall /app/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

> nodemon@1.19.4 postinstall /app/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

> nuxt@2.11.0 postinstall /app/node_modules/nuxt
> opencollective || exit 0

                                     :-:
                                   .==-+:
                                  .==. :+- .-=-
                                 .==.   :==++-+=.
                                :==.     -**: :+=.
                               :+-      :*+++. .++.
                              :+-      -*= .++: .=+.
                             -+:      =*-   .+*: .=+:
                            -+:     .=*-     .=*-  =+:
                          .==:     .+*:        -*-  -+-
                         .=+:.....:+*-.........:=*=..=*-
                         .-=------=++============++====:

                          Thanks for installing nuxtjs
                 Please consider donating to our open collective
                        to help us maintain this package.

                           Number of contributors: 224
                              Number of backers: 288
                              Annual budget: $80,233
                             Current balance: $20,564

                 Donate: https://opencollective.com/nuxtjs/donate

**npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN eslint-config-standard@14.1.0 requires a peer of eslint@>=6.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/nodemon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})**

added 1663 packages from 1975 contributors and audited 903547 packages in 77.32s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Removing intermediate container a2dc2ce280b8
 ---> 809657ee7993
Step 6/6 : RUN npm run build
 ---> Running in 8750e283cf8b

> doccano@1.0.0 build /app
> nuxt build

Ôä╣ Production build
Ô£ö Builder initialized
Ô£ö Nuxt files generated
Ôä╣ Compiling Client
Ô£ö Client: Compiled successfully in 1.24m

**Hash: a5e4ef82de2a49921ca4**
Version: webpack 4.41.5
Time: 74129ms
Built at: 02/06/2020 2:14:52 PM
                         Asset      Size  Chunks                                Chunk Names
../server/client.manifest.json  45.5 KiB          [emitted]
       14167c67316199762674.js  2.21 KiB       9  [emitted] [immutable]         pages/projects/_id/guideline/index
       20f1ab51704bc6023712.js  2.13 MiB      19  [emitted] [immutable]  [big]  vendors.app
       47a3c9c396941d81ebbf.js  14.3 KiB       2  [emitted] [immutable]         pages/auth
       4c9a2c29a1cb565c0e5e.js  36.1 KiB      20  [emitted] [immutable]         vendors.pages/projects/_id/dataset/index
       4e16aa58a904daa5eb62.js  12.1 KiB      14  [emitted] [immutable]         pages/projects/_id/sequence-to-sequence/index
       4fada684823777d497d3.js  91.3 KiB       0  [emitted] [immutable]         app
       5e261fdaebca5178602f.js  11.9 KiB       6  [emitted] [immutable]         pages/demo/translation/index
       60ba7c5168b51d683821.js  10.9 KiB       3  [emitted] [immutable]         pages/demo/named-entity-recognition/index
       6edd26d7f3dff2931a20.js  29.4 KiB      21  [emitted] [immutable]         vendors.pages/projects/_id/guideline/index
       710f0329c12876bc6697.js  6.24 KiB      15  [emitted] [immutable]         pages/projects/_id/statistics/index
       79cc9db5e2f4d2546851.js  15.9 KiB       8  [emitted] [immutable]         pages/projects/_id/dataset/index
       7f46daffd39d55d01c5e.js  14.7 KiB      11  [emitted] [immutable]         pages/projects/_id/labels/index
       81c325e1442025ca0f58.js  12.1 KiB       5  [emitted] [immutable]         pages/demo/text-to-sql/index
       8b96bd6205d90e7db7d6.js  22.2 KiB      17  [emitted] [immutable]         pages/projects/index
                      LICENSES  1.66 KiB          [emitted]
       a6fc60b88a5e0ea696c3.js  2.78 KiB      18  [emitted] [immutable]         runtime
       a8efe91afd5abbb433bb.js  14.1 KiB      10  [emitted] [immutable]         pages/projects/_id/index
       b7569d9429cb9060e90e.js  16.8 KiB      16  [emitted] [immutable]         pages/projects/_id/text-classification/index
       b91531bf4162d40356cf.js   187 KiB       1  [emitted] [immutable]         commons.app
       bc8447cdc1b5220e5515.js  57.3 KiB      22  [emitted] [immutable]         vendors.pages/projects/_id/labels/index
       be36ffd9b56dba00ea2f.js  21.9 KiB      12  [emitted] [immutable]         pages/projects/_id/members/index
       d12c28f48757f0f5b55a.js  7.72 KiB       7  [emitted] [immutable]         pages/index
       dcb7e53774eeba577874.js  16.3 KiB       4  [emitted] [immutable]         pages/demo/sentiment-analysis/index
       de61f7281abc0575ff4c.js   435 KiB      23  [emitted] [immutable]  [big]  vendors.pages/projects/_id/statistics/index
       fe40503f1903591a7880.js  10.5 KiB      13  [emitted] [immutable]         pages/projects/_id/sequence-labeling/index
               img/30dd0f5.png  10.6 KiB          [emitted]
               img/8612b9c.png  62.4 KiB          [emitted]
               img/b436124.png  23.9 KiB          [emitted]
 + 1 hidden asset
Entrypoint app [big] = a6fc60b88a5e0ea696c3.js b91531bf4162d40356cf.js 20f1ab51704bc6023712.js 4fada684823777d497d3.js

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  20f1ab51704bc6023712.js (2.13 MiB)
  de61f7281abc0575ff4c.js (435 KiB)

**WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (1000 KiB). This can impact web performance.
Entrypoints:
  app (2.4 MiB)
      a6fc60b88a5e0ea696c3.js
      b91531bf4162d40356cf.js
      20f1ab51704bc6023712.js
      4fada684823777d497d3.js**

Ôä╣ Generating pages
Ô£ö Generated /auth
Ô£ö Generated /projects
Ô£ö Generated /
Ô£ö Generated /demo/named-entity-recognition
Ô£ö Generated /demo/text-to-sql
Ô£ö Generated /demo/translation
Ô£ö Generated /demo/sentiment-analysis
Removing intermediate container 8750e283cf8b
 ---> 1097e60b8456

Successfully built 1097e60b8456
Successfully tagged doccano_frontend:latest
WARNING: Image for service frontend was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling postgres (postgres:12.0-alpine)...
12.0-alpine: Pulling from library/postgres
89d9c30c1d48: Pull complete                                                                                                                                                                                        66ddea140797: Pull complete                                                                                                                                                                                        977cf4e465c1: Pull complete                                                                                                                                                                                        ba931f945c10: Pull complete                                                                                                                                                                                        7b61205fe7a7: Pull complete                                                                                                                                                                                        2beee0482414: Pull complete                                                                                                                                                                                        c2d37df49a3b: Pull complete                                                                                                                                                                                        8c44ef2c13b8: Pull complete                                                                                                                                                                                        Digest: sha256:5115ec0afd378e91b5eed848a7e0ae0a9c7995fe05ad14f1eb3038bcf53acbf7
Status: Downloaded newer image for postgres:12.0-alpine
Building backend
Step 1/9 : FROM python:3.6
3.6: Pulling from library/python
dc65f448a2e2: Pull complete                                                                                                                                                                                        346ffb2b67d7: Pull complete                                                                                                                                                                                        dea4ecac934f: Pull complete                                                                                                                                                                                        8ac92ddf84b3: Pull complete                                                                                                                                                                                        a3ca60abc08a: Pull complete                                                                                                                                                                                        c3b874b43f86: Pull complete                                                                                                                                                                                        465553161802: Pull complete                                                                                                                                                                                        48a6aaac4f1e: Pull complete                                                                                                                                                                                        24817f242d67: Pull complete                                                                                                                                                                                        Digest: sha256:8adf67de8bc2254c5d7ce0a9584cd5f600b074d79e9692eb5b51300bf7c351ae
Status: Downloaded newer image for python:3.6
 ---> 971c66f6a27f
Step 2/9 : WORKDIR /app
 ---> Running in 2aece0827121
Removing intermediate container 2aece0827121
 ---> 1c353dba75ab
Step 3/9 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Running in 0f53c2979f92
Removing intermediate container 0f53c2979f92
 ---> 8391295081be
Step 4/9 : ENV PYTHONUNBUFFERED 1
 ---> Running in dc0bef6de839
Removing intermediate container dc0bef6de839
 ---> 97356e222aac
Step 5/9 : RUN apt-get update     && apt-get install --no-install-recommends -y python3-dev libpq-dev unixodbc-dev
 ---> Running in 034a7a525788
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7908 kB]
**Reading package lists...
E: Release file for http://security.debian.org/debian-security/dists/buster/updates/InRelease is not valid yet (invalid for another 7h 13min 59s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/buster-updates/InRelease is not valid yet (invalid for another 12h 14min 22s). Updates for this repository will not be applied.
ERROR: Service 'backend' failed to build: The command '/bin/sh -c apt-get update     && apt-get install --no-install-recommends -y python3-dev libpq-dev unixodbc-dev' returned a non-zero code: 100**

(base) C:\Users\prakash\doccano>

**Comment by icoxfog417** [comment]
We are tackling the docker-compose file problem (#558). Please wait a little and try it after the release!

**Comment by prakashwarbler** [comment]
may i know when the next release is? is there any alternatives i can try in windows 10 os
