### ISSUE TITLE
No admin account in GCP

### ISSUE THREAD

**Issue by BenoitLebreton** [doccano/doccano#559]
Hello  @callingmybluff,

I am refering to the commit #125e081fd876187683821873b869b1e722bdc2d9 to deploy on GCP.

Contrary to Azure or AWS deployment files, cloudbuild.yaml does not include the creation of the admin account script : 

(in aws or azure) docker exec doccano/tools/create-admin.sh ${ADMIN} ${ADMIN_MAIL} ${ADMIN_PWD}

Is it normal ? I also tried to log in to the admin UI with the default "admin" and "password" credentials and it didn't work.

To reproduce the problem : 
The deployment button did'nt worked for me and I wanted to deploy in europe-west1 zone so 
1. I forked the project (and added no modification in it)
2. I created an image using : gcloud builds submit 
(no problem until now, the image is well created)
3. On Google Cloud Run I deployed the image and all worked well so I can go to the url of the deployed doccano. But I don't have admin account. I checked the logs and I noticed no mention of credentials for the admin.

Should the doccano/tools/create-admin.sh be executed in the cloudbuild.yaml ? Or did I miss something ?

Have a nice day,
Benoit

**Comment by BenoitLebreton** [comment]
Hello again, 

I founded a quick solution to my problem.
The creation may be done in the doccano/tools/run.sh if the environnement variables 
- ADMIN_USERNAME
- ADMIN_EMAIL
- ADMIN_PASSWORD

are set in the running.

**Comment by icoxfog417** [comment]
@BenoitLebreton Thank you for sharing your solution!
