### ISSUE TITLE
How to upload pdf and docx files?

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#563]
Feature description
---------

Actually  what i have to do is  upload .pdf and .docx files in section of dataset import option , and then convert that files into .txt files ,i will do annotations on this conversion .txt file . 
for this purpose i add file formats to getImportFormats in projects.js file , and then i apply  sudo docker system prune -a --volumes command outside of doccano folder and then coming in to doccano folder by using cd doccano command and then apply sudo docker-compose -f docker-compose.prod.yml up command , but this didn't give any effects in doccano tool , what am i expect here is PDF name with radio button at the Upload data window. If i get this i will look for where uploaded files are stored and work on conversion . Please help me anyone.

**Comment by icoxfog417** [comment]
Thank you for using the doccano. We do not support PDF/DOCX format yet. I could not advise you without any specific code. So if you are trying to implement it, please raise the Pull Request. Then we are welcome to review your code.
