### ISSUE TITLE
auto-advance to next text

### ISSUE THREAD

**Issue by alohia** [doccano/doccano#564]
Is it possible to have auto-advance to the next text when one has been tagged?

Primarily asking for document classification project.

**Comment by Hironsan** [comment]
For now, it is not possible.
To implement the feature, we have to add `movePage` method of pagination store before/after `addLabel` method of `TextClassification` component.

https://github.com/doccano/doccano/blob/8166677c5823c0dc6514584a1c564e7196e6658a/frontend/components/containers/annotation/TextClassification.vue#L80-L82
