### ISSUE TITLE
How to get the real label name instead of the label id after export the dataset?

### ISSUE THREAD

**Issue by lazysjb** [doccano/doccano#565]
This is the exact same question as posed in #240 except that the solutions proposed in that thread didn't work for me.

The initial question as copied from #240 (from @littleji) is:
```
after export the labeled dataset, like this
{"id": 12881, "text": "some text ", "annotations": [{"label": 3225, "user": 1}], "meta": {}}
how can I get the label-id:label-name map to identify the label name?
```

I deployed using the commands
```
docker pull chakkiworks/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 chakkiworks/doccano
``` 
since the `docker-compose` method was giving me errors on the server side.

As suggested by @rbagd in #240 I would like to copy the DB file from the docker container to local, but it seems that my label / results are not saved in `$CONTAINER_ID:/doccano/app/db.sqlite3` (also the table names are slightly different from the thread, so I'm guessing the docker container was updated since then).
So I'm wondering if there is any other db (such as postgres) that I could use to get the label information? Any other solutions would work perfectly also.

**Comment by c-w** [comment]
You may be interested in https://github.com/doccano/doccano/pull/217 which added support for exporting the label names from Doccano.

**Comment by icoxfog417** [comment]
#217 enables to export the annotated file with text labels. Thank you @c-w !
