### ISSUE TITLE
Project Structure Documentation

### ISSUE THREAD

**Issue by callmeashish** [doccano/doccano#569]
I am trying to learn the structure of the code, I'm trying to fix issue #455.

I looked through rules.js and other Vue files but none of them is returning the error that's logging the said error.

I replicated it and it does show in the network tab but couldn't find the rule that's return that error.

It would be great if we have a document describing the structure and their functionality so it makes it easier for new comers to debug and fix issues quicker.

Thanks and the tool is great I'm enjoying using it.

Your Environment
---------
*   Operating System: Windows
*   Python Version Used: 3.6
*   When you install doccano: 16th February
*   How did you install doccano (Heroku button etc): docker-compose -f docker-compose.dev.yml up

**Comment by Hironsan** [comment]
Hello, @callmeashish 

I wrote project structure documentation:

- [docs/project_structure.md](https://github.com/doccano/doccano/blob/master/docs/project_structure.md)

If you want to know something, please let me know. I will update the documentation.

**Comment by callmeashish** [comment]
Thanks @Hironsan,
Appreciate the help.

I'll go through the documentation and let you know if I any concerns.

Thanks again.

**Comment by kuraga** [comment]
@Hironsan ,
For what we have `/Dockerfile`, `requirements.txt` (in the root)?

I just see: [`/requirements.txt`'s Django version](https://github.com/doccano/doccano/blob/bdba2961bf7942eb529a1591a7499b5d15af73bf/requirements.txt#L7) differs from [`/app/requirements.txt`'s Django version](https://github.com/doccano/doccano/blob/bdba2961bf7942eb529a1591a7499b5d15af73bf/app/requirements.txt#L7). Why?

Thanks!
