### ISSUE TITLE
Website not reachable 

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#570]
When I tried to start the server in gcp instance with the command 
`docker-compose -f docker-compose.prod.yml up`

in the terimal it is showing (attaching only last few lines of log)
```
backend_1   | DETAIL:  Key (name)=(annotation_approver) already exists.
backend_1   | "
backend_1   | User admin already exists.
backend_1   | Starting django
backend_1   | [2020-02-19 06:09:35 +0000] [30] [INFO] Starting gunicorn 19.9.0
backend_1   | [2020-02-19 06:09:35 +0000] [30] [INFO] Listening at: http://0.0.0.0:8000 (30)
backend_1   | [2020-02-19 06:09:35 +0000] [30] [INFO] Using worker: sync
backend_1   | [2020-02-19 06:09:35 +0000] [33] [INFO] Booting worker with pid: 33

```
But when I am trying to open the website with my ip address it is showing 
```
This site can’t be reached xx.xxx.xx.xxx (IP address of instance)
refused to connect.

```
Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.6
*   When you install doccano: 18th February 2020
*   How did you install doccano (Heroku button etc): git clone and docker-compose

**Comment by Hironsan** [comment]
Is the following document useful for you?
https://cloud.google.com/compute/docs/tutorials/basic-webserver-apache?hl=en#test_your_server

**Comment by sharmila-polamuri** [comment]
> Is the following document useful for you?
> https://cloud.google.com/compute/docs/tutorials/basic-webserver-apache?hl=en#test_your_server

I tried the same thing, but it's still the same. Do you know any way I can host it on other port?

**Comment by Hironsan** [comment]
If you want to change the port, the following issue is useful:
https://github.com/doccano/doccano/issues/548

**Comment by sharmila-polamuri** [comment]
> If you want to change the port, the following issue is useful:
> #548

Do I need to change the port in docker-compose.yml as well as in the nginx/nginx.conf. And can you tell me in docker-compose.yml where I can change my IP and Port so that it will work?

**Comment by Hironsan** [comment]
Change this line in docker-compose.prod.yml:

https://github.com/doccano/doccano/blob/7833c1ef12ed7a777d392a3f657269889fe15ef4/docker-compose.prod.yml#L33

If you want to change the port from 80 to 8080, change the line `8080:80`.
I could access the application in GCP.

![image](https://user-images.githubusercontent.com/6737785/74816886-5dcd4480-533f-11ea-8a7e-51af8b13d758.png)

**Comment by sharmila-polamuri** [comment]
> Change this line in docker-compose.prod.yml:
> 
> https://github.com/doccano/doccano/blob/7833c1ef12ed7a777d392a3f657269889fe15ef4/docker-compose.prod.yml#L33
> 
> If you want to change the port from 80 to 8080, change the line `8080:80`.
> I could access the application in GCP.
> 
> ![image](https://user-images.githubusercontent.com/6737785/74816886-5dcd4480-533f-11ea-8a7e-51af8b13d758.png)

Yeah It's working by changing the port there. Thanks.
