### ISSUE TITLE
Delete the last data in the last page will lead to 404 page.

### ISSUE THREAD

**Issue by loner233** [doccano/doccano#573]
How to reproduce the behaviour
---------

This is not a big defect, but it should be easily fixed.
I uploaded a lot of data in dataset page, started to delete all data from back. When I deleted the only last data in the last page, it lead me to the 404 page. It can be more friendly if return the page before the last page when I delete the last data in the last page.

Your Environment
---------

*   Operating System: Archlinux
*   Python Version Used: not sure which version the python is in the docker container.
*   When you install doccano: Now
*   How did you install doccano (Heroku button etc): docker

**Comment by tusharmakkar08-eightfold** [comment]
@Hironsan @Loner233 : I am unable to replicate this bug. Can you check if this still exists?

**Comment by tusharmakkar08** [comment]
@Hironsan @icoxfog417 @Loner233 : I am unable to replicate this bug. Can you please verify if this still exists?

**Comment by Loner233** [comment]
@tusharmakkar08 Yes, It still exists.

Like this, I have the only one data in the last page.
![2020-04-08 17-00-20屏幕截图](https://user-images.githubusercontent.com/16119486/78765378-7f9b8d00-79ba-11ea-8628-5bba16627a17.png)

When I delete the data, It leads me to the 404 page if the debug == True.
![2020-04-08 17-00-35屏幕截图](https://user-images.githubusercontent.com/16119486/78765500-ac4fa480-79ba-11ea-911a-5c05805f97d6.png)

**Comment by tusharmakkar08** [comment]
Hey @Loner233 

Are you on the latest version of doccano? For me the link which is in your screenshot doesn't exist and interface also looks a lot different.

<img width="1438" alt="Screenshot 2020-04-08 at 2 38 55 PM" src="https://user-images.githubusercontent.com/2357025/78766358-caaba500-79a6-11ea-9533-f3d624e98b4e.png">
<img width="1435" alt="Screenshot 2020-04-08 at 2 39 06 PM" src="https://user-images.githubusercontent.com/2357025/78766369-ced7c280-79a6-11ea-91d0-7e62009dd5e9.png">

**Comment by Loner233** [comment]
@tusharmakkar08 I pull from docker repository directly by `docker pull doccano/doccano`, not sure whether it is the latest verison doccano, but it should be the latest one in docker repository.

**Comment by tusharmakkar08** [comment]
@icoxfog417 @Hironsan Is the version present in dockerhub the latest one? I doubt so because the issue isn't coming in the latest master build.

**Comment by Hironsan** [comment]
Please use the `docker-compose.prod.yml`.
