### ISSUE TITLE
How to upload json files bigger than 1MB

### ISSUE THREAD

**Issue by igormis** [doccano/doccano#575]
Is there possibility to change the limit of file upload?

**Comment by rbagd** [comment]
You might try modifying line `43` in the frontent Javascript.

https://github.com/doccano/doccano/blob/7833c1ef12ed7a777d392a3f657269889fe15ef4/frontend/rules/index.js#L41-L44

**Comment by icoxfog417** [comment]
Dear @rbagd , thank you for your answer!

**Comment by igormis** [comment]
@rbagd I tried to comment that line or put larger file size (100MB) but still on front-end I receive the same message (`File size should be less than 1 MB! `). When I changed the `index.js` file in `doccano/frontend/rules `I executed the command `docker-compose -f docker-compose.prod.yml up`. Maybe I am missing something

**Comment by ValentinaKV** [comment]
You can split your doc into smaller ones less than 1M and import them one by one.  Probably, the simplest way for today

**Comment by jimmec** [comment]
@igormis you need to rebuild the containers with `docker-compose -f docker-compose.prod.yml build` and also delete the existing doccano_www volume that held the original compiled javascript artifacts `docker volume rm doccano_www`.

**Comment by ASC689561** [comment]
you have to add line 
```
server {
    listen 80;
    charset utf-8;
    client_max_body_size 1000M;   <-- this line
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
```
in nginx config. rebuild nginx image and docker-compose up again

**Comment by P-mir** [comment]
A lot of us encountered this problem, it may be worth it to change the default size?

**Comment by monk1337** [comment]
Can someone please fix the issue?

**Comment by ricjhill** [comment]
Why is there a restriction?

**Comment by drmayu7** [comment]
i'm still having this issue in v1.8.4

The frontend stated error > size of 100mb however my file is only around 5mb
