### ISSUE TITLE
Annotation labels of multi-line document do not respect new lines

### ISSUE THREAD

**Issue by lapolonio** [doccano/doccano#577]
How to reproduce the behaviour
---------

- Create sequence-labeling project.
- Add labels
- Add records with multiple line 
```
EU rejects German call to boycott British lamb.
This is cool
```
- Annotate different records of line
![Issue](https://media.giphy.com/media/VbttcmPzTsxdAyAH9P/giphy.gif)

Your Environment
---------

*   Operating System: Mac
*   Python Version Used: 3
*   When you install doccano: Feb 27 2020
*   How did you install doccano (Heroku button etc): From source

**Comment by icoxfog417** [comment]
related: #463

**Comment by sezaru** [comment]
I also have this problem, it is present in older versions too

**Comment by lapolonio** [comment]
I looked into the problem some. I think if each line was wrapped in a div container that would addres the problem. Right now each group of word is wrapped in a span and that does not play nice with new lines.
