### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by kakatofoli** [doccano/doccano#578]
Hey peoples,

I'm trying to create custom routes in doccano but it doesn't respect the routes, could you help me?

For example, we have the default route "/ projects / project.id"

furthermore i would like to pass filter attributes, like for example the page number that contains the sentences and the labels "project / project.id / PageNumber"

To display the exact page where the sentences and labels are found to change them.

How to do this ?

**Comment by icoxfog417** [comment]
The doccano is built by [Django](https://docs.djangoproject.com/) and your question is related to Django feature itself.

**Comment by kuraga** [comment]
@icoxfog417, sorry? Routes are made by Doccano itself. It would be excellent to have an URL on each view's state!

**Comment by kakatofoli** [comment]
Exactly !!

**Comment by icoxfog417** [comment]
It means to "create custom route" is out of our (doccano's issue) scope. If you think the url for page numbers is useful for doccano, please raise it as a feature request.

**Comment by kuraga** [comment]
Superset: #595.
