### ISSUE TITLE
Wiki documentation has broken images

### ISSUE THREAD

**Issue by mprinc** [doccano/doccano#579]
How to reproduce the behaviour
---------

At the link [A Tutorial For Sequence Labeling Project](https://github.com/doccano/doccano/wiki/A-Tutorial-For-Sequence-Labeling-Project) all images are broken.

Your Environment
---------

I don't think it matters here, but anyway :) : 
+ OSX Catalina, 
+ Browser: Google Chrome, Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by Hironsan** [comment]
Hi, @mprinc 

I moved the tutorial to [docs/tutorial.md](https://github.com/doccano/doccano/blob/master/docs/tutorial.md) and fixed broken images.
Please see it!
