### ISSUE TITLE
Documents jump out of order in sequence annotation project

### ISSUE THREAD

**Issue by mmisiewicz-yext** [doccano/doccano#584]
How to reproduce the behaviour
---------
When clicking through documents to label, or using the arrow keys, sometimes documents jump out of order. The page indicator on the upper right corner only increments by one item at a time. 

[Here is a video that might make this more clear](https://michaelmisiewicz.com/stuff/doccano_pagination_bug_demo.mov). The bug first occurs at 0:08 and I am able to cause it again a few times. 

There are no obvious errors in the browser console or logs from Nginx or Django that appear to explain it.

Behavior appears to occur both in Safari and Chrome on Mac. I have observed it occurring around the transition from 10-11 which makes it seem like a pagination bug, but possibly it occurs elsewhere in sequence of documents (e.g. 145 to 146) as well. 

Your Environment
---------
*   Operating System:
CentOS 7.5 on AWS, running Docker 18.06.1-ce, build e68fc7a
*   Python Version Used:
According to `Dockerfile`, 3.6.
*   When you install doccano:
Today, from HEAD
*   How did you install doccano (Heroku button etc):
Docker compose. i.e.: `docker-compose -f docker-compose.prod.yml up -d`.

**Comment by icoxfog417** [comment]
related #555.

**Comment by can-keklik** [comment]
There can be another clue. In list view (rows per page=10) last element in each page is replaced with a certain document. That document can be seen at the end of each page. This also occurs in annotation view. 

When you increase rows per page to 50, you can see that 10th, 20th, 30th and 40th elements are shown correctly, yet it is not possible to annotate them. Clicking on annotate for them takes you to repeating document. And repeating document still stays at the end of the list page. So when you are at 31th document, it means you have skipped 3 of them like:

1, 2, 3, ... 9, Repeating doc, 11, 12 ,13, ..., 19, Repeating doc, 21, 22, 23, ..., 29, Repeating doc, 31

BTW, I use shuffling for this project.
