### ISSUE TITLE
How to access Postgres in doccano?

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#585]
How to reproduce the behaviour
---------

Hi sir , 
     I wish to store and retrieve data from postgres database in doccano tool and also wish to know about how uploaded files are stored into postgres docker container . Please help me or suggest me how to do this task .

One more thing I want to know, Can i run the django server with the defined frontend without the docker, if yes then can you tell what steps should I need to do?

Your Environment

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.7
*   When you install doccano: one month back
*   How did you install doccano (Heroku button etc): git clone + docker-compose

**Comment by sharmila-polamuri** [comment]
Any update to access and retrieve data from postgres docker  image in doccano? 
And one more thing i wish to know from you , where uploaded files are stored before storing into  database ? Please give any idea about this issue .

**Comment by louisguitton** [comment]
Hi @sharmila-polamuri , I'm not part of the team but saw your question.
You need to export the port of the PostgreSQL DB.

Add this at the end of these lines https://github.com/doccano/doccano/blob/master/docker-compose.prod.yml#L39-L48
```yml
    ports:
        - "5432:5432"
```

And then 
```sh
pgcli postgresql://doccano:doccano@localhost:5432/doccano
```

**Comment by evanmiller29** [comment]
Hey @louisguitton @icoxfog417 is the ability for me to contribute documentation?
I use this same trick to push data to the postgres database and this lets us easily set up sessions on Doccano quickly by using a yml config file.

**Comment by icoxfog417** [comment]
@evanmiller29 Thank you for your proposal of contribution! Would you please send the PR to F&Q documentation if you could?

https://github.com/doccano/doccano/blob/master/docs/faq.md

**Comment by evanmiller29** [comment]
Cool, PR coming your way

**Comment by sam-qordoba** [comment]
@evanmiller29 when you push data to progress, is that instead of using the doccano GUI to import? did you ever write this up?
