### ISSUE TITLE
[Bug report] Filters toolbar disappears

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#587]
How to reproduce the behaviour
---------

1. Create a project
2. Import a dataset
3. Start annotation
4. Select `Done` filter's state

OR

1. Create an empty project
2. Start annotation

What's happened? Filters toolbar disappears.
I don't know a way to restore it.

Your Environment
---------
* Operating System: Ubuntu 18.04.2 LTS
* Python Version Used: system-wide Python is 3.6.8 but how is it used?
* When you install doccano: 5c1a5e0a84126f3ec5f89b563b78125a02205f74
* How did you install doccano (Heroku button etc): `$ /opt/docker-compose -f docker-compose.prod.yml up --build`

**Comment by icoxfog417** [comment]
Thank you for the but report. Please provide your environment information following the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/02-bug.md).

*   Operating System:
*   Python Version Used:
*   When you install doccano: => https://github.com/doccano/doccano/commit/5c1a5e0a84126f3ec5f89b563b78125a02205f74
*   How did you install doccano (Heroku button etc):

**Comment by kuraga** [comment]
@icoxfog417 , updated.

**Comment by Hironsan** [comment]
I couldn't reproduce the behavior.

**Comment by kuraga** [comment]
@Hironsan ,

blank container on bdba2961bf7942eb529a1591a7499b5d15af73bf, new project, "Start annotation":

![image](https://user-images.githubusercontent.com/1063219/76503970-d6638480-6457-11ea-8022-d70bbefcd17a.png)

blank container on bdba2961bf7942eb529a1591a7499b5d15af73bf, new project, import labeled dataset, "Start annotation", check "Undone": the same.
