### ISSUE TITLE
[Bug report] Errors on Nuxt stage with new NodeJS

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#588]
How to reproduce the behaviour
---------
Since commit 0cabdcee1ee1ab96c3ed3654b5efeed9a5f25bca up to current `master` I have tones of similar errors on building Doccano (via production docker-compose) on Nuxt stage:

```
$ git checkout 0cabdcee1ee1ab96c3ed3654b5efeed9a5f25bca
$ /opt/docker-compose -f docker-compose.prod.yml up --build
<...>
ERROR in ./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--17-0!./node_modules/vue-loader/lib??vue-loader-option
s!./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve 'core-js/modules/es6.array.find' in '/app/components/containers/annotation'
 @ ./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--17-0!./node_modules/vue-loader/lib??vue-loader-options!./co
mponents/containers/annotation/TextClassification.vue?vue&type=script&lang=js&) 4:0-40
 @ ./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js&
 @ ./components/containers/annotation/TextClassification.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--17-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/projects/_id/text-classification/index.vue?vue&type=script&lang=js&
 @ ./pages/projects/_id/text-classification/index.vue?vue&type=script&lang=js&
 @ ./pages/projects/_id/text-classification/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
```

Your Environment
---------
* Operating System: Ubuntu 18.04.2 LTS
* Python Version Used: system-wide Python is 3.6.8 but how is it used?
* When you install doccano: 0cabdcee1ee1ab96c3ed3654b5efeed9a5f25bca
* How did you install doccano (Heroku button etc): `$ /opt/docker-compose -f docker-compose.prod.yml up --build`

**Comment by icoxfog417** [comment]
Thank you for the but report. Please provide your environment information following the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/02-bug.md).

*   Operating System:
*   Python Version Used:
*   When you install doccano: =>https://github.com/doccano/doccano/commit/0cabdcee1ee1ab96c3ed3654b5efeed9a5f25bca
*   How did you install doccano (Heroku button etc):

**Comment by kuraga** [comment]
@icoxfog417 , sorry, updated.

**Comment by agoalofalife** [comment]
I have same error😐

**Comment by Hironsan** [comment]
Maybe solved by https://github.com/doccano/doccano/issues/600. Please try again.

**Comment by kuraga** [comment]
Yes, fixed
