### ISSUE TITLE
How to start django server without docker ?

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#592]
How to reproduce the behaviour
---------

How Can i run the django server with the defined frontend without the docker ?  If is it possible please tell me the steps what i have to do ?

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used:3.6
*   When you install doccano: One month back
*   How did you install doccano (Heroku button etc): git clone + docker-compose

**Comment by icoxfog417** [comment]
Please check [Frequently Asked Questions](https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions#i-cant-install-doccano) > I can't install doccano. > Install from source. But we don't recommend it if you are not familiar with Python and Node.js.

**Comment by sharmila-polamuri** [comment]
Yeah tried steps in [https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions#i-cant-install-doccano](url) .  I got an error when i run below command 
`
npm run build
`
I got this error 
```
 FATAL  Nuxt build error                                                                                                                             09:03:10

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5326:21)
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5275:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5598:5)
  at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:70:7)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:40:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:96:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-command.js:2575:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doccano@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doccano@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sharmila/.npm/_logs/2020-03-11T09_03_10_523Z-debug.log
```
What i have to do now to fix it. Please suggest
