### ISSUE TITLE
[Tiny enhancement request] Clarify dataset export format

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#593]
Feature description
---------
We have `JSON` option as format for dataset export. But seems like real format on this iption is JSONL: whole file is not correct JSON but each line of it is JSON instead.

Let's change the option's title?

BTW, we have `JSON` option  for import. Seems like it's also incorrect.

Update: not only option name should be corrected but file extension, also.

Thanks.

**Comment by tusharmakkar08** [comment]
Hey @Hironsan @kuraga 

Next I would be picking this issue (Mentioning this so that anyone else who wants to contribute knows).

**Comment by tusharmakkar08** [comment]
Created a PR: https://github.com/doccano/doccano/pull/671
