### ISSUE TITLE
'front' service build failed after docker-compose + impossible to pull doccano >= 1.0.0

### ISSUE THREAD

**Issue by raymar13** [doccano/doccano#596]
Hello,

I have been using Doccano consistently but I wanted to try the new interface that appeared with v1.0.0. I tried to pull v1.0.2, v1.0.1, v1.0.0 but I always get the "old" user interface and none of the features announced (Dark Mode, new beautiful interface).

I also tried to pull git repo and run the docker-compose but the "front" service build failed. 
Here is the output

Can you guide me please ? Thank you in advance.
[failed_build.log](https://github.com/doccano/doccano/files/4295550/failed_build.log)

Config
- MacOS Catalina
- Docker Desktop v2.2
- Compose v1.25.2

**Comment by icoxfog417** [comment]
@raymar13 Thank you for using the doccano. We are tackling the this problem at #588.
