### ISSUE TITLE
[Enhancement request] Show menu by default

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#598]
Feature description
---------
On project's page, there is menu which hidden by default. It's also hidden by default on subpage.

Proposition: make it visible by default on this page. And maybe, on subpages.

**Comment by kuraga** [comment]
Seems like not fixed: https://github.com/doccano/doccano/pull/606#issuecomment-597828736

**Comment by Hironsan** [comment]
Please rebuild the images.

**Comment by kuraga** [comment]
@Hironsan , I really sorry much: I didn't know `docker-compose`'s `--build` doesn't do all need. :-( Confirm it works.

P.S. What I need to do for complete rebuild?
