### ISSUE TITLE
[Enhancement request] Allow digit keys as shortkeys

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#599]
Feature description
---------
English letters are allowed as shortkeys for annotation now, only.

Proposition: allow English letters and digits as shortkeys.

**Comment by Hironsan** [comment]
OK.

**Comment by kuraga** [comment]
Thanks very much!!!

**Comment by kuraga** [comment]
@Hironsan , thanks but seems like doesn't work: https://github.com/doccano/doccano/pull/603#issuecomment-597833566

**Comment by Hironsan** [comment]
Please rebuild the images.

**Comment by kuraga** [comment]
@Hironsan , I really sorry much: I didn't know `docker-compose`'s `--build` doesn't do all need. :-( Confirm it works.

P.S. What I need to do for complete rebuild?
