### ISSUE TITLE
Frontend failed to build

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#600]
How to reproduce the behaviour
---------

I run 
`
sudo docker-compose -f docker-copose.prod.yml up 
`
i got this error 
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
so after i was change node version in frontend/Dockerfile file from 13.2 to 13.6 and then go out of doccano folder and then run prune volumes with this command 

`
sudo docker system prune -a --volumes
`

and again run 
`
sudo docker-compose -f docker-compose.prod.yml up
` 

command but i got still same error . Please tell me what i have to do now to fix this error.

Your Environment
---------

*   Operating System:18.04
*   Python Version Used:3.6
*   When you install doccano: one  month back
*   How did you install doccano (Heroku button etc): git clone + docker-compose

**Comment by Hironsan** [comment]
OK. I confirmed the problem.

**Comment by Hironsan** [comment]
Hi @sharmila-polamuri 

Could you please run the following command:

```bash
$ git clone -b fix-#600 https://github.com/doccano/doccano.git
$ cd doccano
$ docker-compose -f docker-compose.prod.yml up
```

**Comment by kuraga** [comment]
@Hironsan , could it fix #588?

**Comment by Hironsan** [comment]
@kuraga Yes.

**Comment by sharmila-polamuri** [comment]
I run this  command
`
git clone -b fix-#600 https://github.com/doccano/doccano.git
`

gave error like below 
`
Cloning into 'doccano'...
`
`
fatal: Remote branch fix-#600 not found in upstream origin
`
how to fix this error ?

**Comment by Hironsan** [comment]
Oh sorry.
The branch is merged and deleted. So please run the following command.

```bash
$ git clone https://github.com/doccano/doccano.git
$ cd doccano
$ docker-compose -f docker-compose.prod.yml up
```

**Comment by sharmila-polamuri** [comment]
Thank you , it is working now .
