### ISSUE TITLE
[Tiny enhancement request] Show current user name

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#604]
Feature description
---------
Let's show current user name above "Sign out" link.

**Comment by tusharmakkar08** [comment]
Hey @icoxfog417 @kuraga 

I am willing to contribute in this project. Let me know if I can pick this up as a starter task.

Thanks.

**Comment by Hironsan** [comment]
@tusharmakkar08 

Pull request is always welcome.

**Comment by tusharmakkar08** [comment]
@Hironsan 

Can you give some pointers on how to go ahead working on it since I am new to vue.js? I figured out i have to change`TheHeader.vue`. I am playing around with it, just wondering what's the best place to fetch username. Is it `Me()` class? 

Thanks

**Comment by tusharmakkar08** [comment]
Hey @Hironsan 

Added PR for this fix: https://github.com/doccano/doccano/pull/664

Thanks.
