### ISSUE TITLE
[Tiny enhancement request] Localize roles in UI

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#605]
Feature description
---------
We have these role namings in UI: "project_admin", "annotator", "annotation_approver". I think it comes from here: 
https://github.com/doccano/doccano/blob/b526c7cd4389a769dee3dded1a3f48cfa9676a49/app/app/settings.py#L180-L182
But it would be good to localize them in UI: "Project Admin", "Annotator", "Annotation Approver", respectively.

**Comment by kuraga** [comment]
@tusharmakkar08 , could you, please, help with PR here? :)

**Comment by icoxfog417** [comment]
We reopen this issue if someone needs this enhancement.
