### ISSUE TITLE
Installing doccano from source 

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#608]
How to reproduce the problem
---------
Hi i got same error as #138 . I run the following commands inside `frontend/`  folder but when I tried to run those commands inside `app/server/static/` it's not working. 
`
npm run build 
`
or 
`
npm start
`

And in the django server it's showing the error

```bash
OSError at /
Error reading /home/sharmila/new_doccano/doccano/app/server/static/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
```

Your Environment
---------

*   Operating System:18.04
*   Python Version Used:3.7
*   When you install doccano: one mouth before
*   How did you install doccano (Heroku button etc): git clone + docker-compose

**Comment by sivaprakash123** [comment]
The webpack-stats.json is supposed to be in the repository. But it is not there. 
I fixed by running it in docker and copied it to my location.
Follow these steps and check if its working for you
# docker run -d --name doccano -p 80:8000 chakkiworks/doccano
# docker exec doccano tools/create-admin.sh "admin" "email" "password" [This is not required, you can use if you want to continue using docker]
### Copy the file from docker container to your local
# docker cp  doccano:/doccano/app/server/static/webpack-stats.json .

Now copy the webpack-stats.json to your server location <ROOT_PATH>/doccano/app/server/static

**Comment by icoxfog417** [comment]
> When you install doccano: one mouth before

Would you please update to the latest doccano. If you still face this problem, please raise the new issue.

**Comment by sharmila-polamuri** [comment]
I run those commands 
```
docker run -d --name doccano -p 80:8000 chakkiworks/doccano
docker exec doccano tools/create-admin.sh "admin" "email" "password"
docker cp doccano:/doccano/app/server/static/webpack-stats.json .

```
and then copy webpack-stats.json file to my own directory and then open app folder and run below
`
python manage.py runserver 
`
that gave frontend page but when i open any thing like trydemo and after logging projects that gives empty like below image

i found one thing in webpack-stats.json file , in webpack-stats.json file path mentioned as 
`"path":"/doccano/app/server/static/bundle/projects.js"`  
i searched for bundle folder in side static folder but there is no bundle folder . But what files are mentioned in side webpack-stats.json file like /bundle/projects.js  or /bundle/user.js all those files are available in /static/pages/ folder . I changed path variable value like 
`"path":"/doccano/app/server/static/pages/projects.js"` 

but frontend didn't changed.
`<script type="text/javascript" src="/static/bundle/projects.js"></script>`

Please suggest me , how to fix this problem ?


![Screenshot (1)](https://user-images.githubusercontent.com/28034607/76491257-4c192180-6453-11ea-939e-4e940baaa1de.png)

**Comment by sivaprakash123** [comment]
Hey,

I missed that part. You need to copy the bundle folder as well. Not sure why the bundle is not generated as well.

docker cp  0877bd5ff882:/doccano/app/server/static/bundle bundle

Now copy the bundle folder under doccano/app/server/static/

Thanks,
Sivaprakash R

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sharmila-polamuri** [comment]
Thank you its working now .
