### ISSUE TITLE
How to add user annotator after deploying project on heroku?

### ISSUE THREAD

**Issue by yonatanbitton** [doccano/doccano#609]
I've seen posts that says to add from the django admin page, but how do I enter this admin page? 

Can you please support instructions? 

I have deployed a project on heroku. 

I see this instructions:
I want to add annotators.
You can create other annotators by Django Admin site.
your/doccano/site/admin

I'm inserting this URL: https://myweb.herokuapp.com/doccano/site/admin

But it doesn't reach anything.
Where should I connect? 

Thanks!

**Comment by ryubidragonfire** [comment]
same question here

**Comment by Borg93** [comment]
Any answer yet?

**Comment by HananeNourMoussa** [comment]
Hey people, here is a quick fix I found on https://bytemeta.vip/repo/doccano/doccano/issues/1814 :
On Heroku, go to settings
Add the Config Var "DEBUG" with the value set to "True"
I was then able to access the admin pane, add users etc.
Set the value to "False"

**Comment by AbeHandler** [comment]
For me it worked if you add set the DEBUG var to true as in previous post and then do 

https://myapp.herokuapp.com/admin/**login**
