### ISSUE TITLE
Login/logout problem

### ISSUE THREAD

**Issue by MikeVlad6** [doccano/doccano#613]
When trying to login after you logout there's a leftover `Authorization` in the ApiService header which will make ` path('auth-token', obtain_auth_token),` from the backend to return `Forbidden` . The workaround is to change the `postCredential` method from `auth.service.js` from

  postCredential(data) {
    return this.request.post('/auth-token', data)
  }
}

to 

  postCredential(data) {
    this.request.removeHeader() // clear the header before posting.
    return this.request.post('/auth-token', data)
  }
}

or even better just clear that particular header before posting the login credentials.

 removeAuth() {
    delete this.instance.defaults.headers.common["Authorization"]
  }

**Comment by icoxfog417** [comment]
Thank you for the but report. Please provide your environment information following the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/02-bug.md).

*   Operating System:
*   Python Version Used:
*   When you install doccano
*   How did you install doccano (Heroku button etc):

**Comment by kuraga** [comment]
Related to #545?
