### ISSUE TITLE
Why changes in frontend didn't build frontend ?

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#614]
How to reproduce the behaviour
---------

Hi,
  I tried to add some code to **nuxt.config.js**  inside **frontend** folder after changes i came out of doccano folder and run 
`sudo docker system prune -a --volumes` 
to prune volumes and then `cd doccano` and run below command
`sudo docker-compose -f docker-compose.prod.yml up`

again i got frontend so i removed my changes and then again run 
```
sudo docker system prune -a --volumes
cd doccano
sudo docker-compose -f docker-compose.prod.yml up
```
But i got same error . Why  this error occur frequently ?

Your Environment
---------

*   Operating System: ubuntu 18.04
*   Python Version Used: 3.6 
*   When you install doccano: 2 months back
*   How did you install doccano (Heroku button etc): git clone + docker-compose

**Comment by icoxfog417** [comment]
Could you please show us your error?
And please confirm if it is caused by your edited `nuxt.config.js`.

**Comment by sharmila-polamuri** [comment]
few lines of error :- 
```
npm ERR! errno 1
npm ERR! doccano@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doccano@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-13T05_04_36_003Z-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by icoxfog417** [comment]
@sharmila-polamuri doccano seems not to be the latest version, please update.

**Comment by kuraga** [comment]
@sharmila-polamuri , are you looking for [`docker-compose build --no-cache`](https://docs.docker.com/compose/reference/build/)?

**Comment by sharmila-polamuri** [comment]
> @sharmila-polamuri Please show the error log itself (`2020-03-13T05_04_36_003Z-debug.log`). And the doccano seems not to be the latest version, please update.

Ok ,  how to update doccano ? do i clone doccano code again ?

**Comment by icoxfog417** [comment]
The procedure of update is not unique for doccano. Please refer the [git document](https://www.atlassian.com/git/tutorials/syncing/git-pull). We want to use the GitHub issue to handle doccano dependent problems. So If you face this problem after the update, please raise a new issue with a concrete error log.
