### ISSUE TITLE
Project to do document classification and sequence labelling at the same time

### ISSUE THREAD

**Issue by nemccarthy** [doccano/doccano#617]
Feature description
---------
It would be very useful to classify an entire document at the same time as doing sequence labelling. 
Is this possible?

**Comment by icoxfog417** [comment]
Thank you for your proposal. Currently, we don't have any plans to support it.

**Comment by Jacse** [comment]
I just want to raise my support for this. One example we have is annotation of news, social media posts etc. We want to simultaneously NER-tag documents and categorise them into a few different categories.
