### ISSUE TITLE
Enabling auto labeling for data annotation

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#619]
Auto labeling for uploaded data
-----------------------------------

I have an external django api which auto label the uploaded data, and can able to return the labeled data with the required format by doccano. What I want is how can I catch the labeled data file for further annotation/verification inside doccano? What I am thinking is, I have to replace the new labeled data file with the old unlabeled data file. Because after the new data file replaced it will appear in doccano properly. Want some help regarding this.

Your Environment
--------------

*   Operating System: Ubuntu 18.04
*   Python Version Used: python 3.6
*   When you install doccano: February 2020
*   How did you install doccano (Heroku button etc): Installed from source

**Comment by icoxfog417** [comment]
Could you please clarify your situation?

* If you annotate by your Django API, please upload after annotation complete (by your API).
  * After upload, you can do additional annotation on the doccano.
* If you annotate the data directly, you can use doccano REST API.

**Comment by icoxfog417** [comment]
related: #299

**Comment by sharmila-polamuri** [comment]
> Could you please clarify your situation?
> 
> * If you annotate by your Django API, please upload after annotation complete (by your API).
>   
>   * After upload, you can do additional annotation on the doccano.
> * If you annotate the data directly, you can use doccano REST API.

Ok let me explain what I am currently doing and what I am expecting.

* First I create a project inside doccano with my unlabeled data.
* Then I put a button inside doccano which calls my API for auto labeling, and the API returns the required file format of doccano with the labels
* So here what I want now is, when the API call finishes how can I replace my old uploaded data with the new returned data without re-uploading the data itself. Which means I need to store the labeled file under the same project replacing the old one(unlabeled one).

**Comment by icoxfog417** [comment]
You can annotate the data directly by API. Please refer following issue.

#624

And afparsons's work.

https://github.com/afparsons/doccano_api_client
