### ISSUE TITLE
Unable to import large CoNLL document

### ISSUE THREAD

**Issue by devanshbatra04** [doccano/doccano#623]
I am trying to import a very large NER CoNLL dataset for my research work around 1.5 million lines. I am using the heroku deployment. The file gets uploaded but the docs don't show up. When I upload a file with around 5000 lines, it gets loaded without any problem

Using one-click deploy heroku version

**Comment by icoxfog417** [comment]
Thank you for using the doccano. We need to confirm it is caused by doccano or Heroku (limited resource). Could you please provide the log?

**Comment by devanshbatra04** [comment]
Hi thanks for the response. It was indeed due to heroku. I have shifted to my own hosting. Closing the issue. Thanks!
