### ISSUE TITLE
Regression - data import from cloud

### ISSUE THREAD

**Issue by kut** [doccano/doccano#625]
How to reproduce the behaviour
---------
Go to the data import page. There isn't a way to import via the cloud, as there was in #213 

Your Environment
---------
Latest docker build of Doccano (prod and dev)

Am I overlooking something, or has the button for cloud uploading (introduced in #213, requested in #141) gone missing since the move to vuetify?

**Comment by Hironsan** [comment]
> gone missing since the move to vuetify?
Yes. All features in the previous version have not been migrated yet.
If you want to use data import from cloud storage, please use the previous doccano.

**Comment by ltoniazzi** [comment]
@Hironsan Is data upload from (download to) cloud storage currently not available?

**Comment by Ruben0550** [comment]
> @Hironsan Is data upload from (download to) cloud storage currently not available?
have you found a way to import dataset from s3 / cloud storage? . i'm still stuck to import dataset from s3

**Comment by simonwoodhead** [comment]
Is there any update on this? I have been trying to follow [the instructions to enable S3 support](https://doccano.github.io/doccano/setup_cloud_storage/) (at least for providing persistent storage). I created the .enb file but I had used the nifty one-click deployment to AWS which uses [template.aws.yaml](https://github.com/doccano/doccano/blob/master/cloud/aws/template.aws.yaml). I tried to get my deployment to recognise the new env file by ssh-ing into the EC2 instance and running:

    sudo docker-compose -f docker/docker-compose.prod.yml down
    sudo docker-compose -f docker/docker-compose.prod.yml up -d

That successfully stopped and restarted but there did not seem to be any connection to S3. Fundamentally I'm afraid I do not understand how it is connecting to S3 (is this relying on a Django property). I could not see anything relevant in the `template.aws.yml` file or my searching the codebase. 

Is it the case that I cannot use the one-click method if I want to use S3? 

Thank you!

**Comment by simonwoodhead** [comment]
I managed to get the docker (not docker compose) deployment method to work using this code:

```
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -v doccano-db:/data \
  --env-file .env \
  -p 8000:8000 doccano/doccano
```

I think I made two errors before: 
1. I had a typo in my S3 bucket name
2. The down/up cycle does not reapply the environment variables

I got it working on docker desktop but unfortunately all it does is store the uploaded files. It does not save copies of the anotated files. For that you still need to export the data or download the database.

Please correct me if I am wrong!
