### ISSUE TITLE
Display available labels in Document Classification Tasks

### ISSUE THREAD

**Issue by elric-dev** [doccano/doccano#627]
Feature description
---------

When annotating document classification tasks, Doccano doesnt display the list of available labels. It will be beneficial to display them as in the previous version.

**Comment by kuraga** [comment]
...and key shortcut hints (https://github.com/doccano/doccano/issues/509#issuecomment-568403172)!

**Comment by elric-dev** [comment]
@kuraga really like your list of enhancements. 
Especially:
- Show current user name
- Show menu by default 

Also an option to choose  to display metadata.

**Comment by Hironsan** [comment]
@elric-dev When we focus on the `select` element, we can see all the labels. So I don't think we need to display them as in the previous version.

**Comment by elric-dev** [comment]
Thanks @Hironsan!
