### ISSUE TITLE
Documents with no labels are not marked as completed

### ISSUE THREAD

**Issue by buriy** [doccano/doccano#630]
For sequence labeling projects, sometimes you have no matches in the document and that's absolutely correct.
You should be able to mark them as complete and see that they are completed.

Instead of displaying the number of marked occurrences (zero or non-zero), one should mark them as complete when they are marked by annotator as complete.

Also see #280

**Comment by icoxfog417** [comment]
We merged the discussions about the annotation status and its display at #280.
