### ISSUE TITLE
A button to clear the markup.

### ISSUE THREAD

**Issue by buriy** [doccano/doccano#631]
Sometimes, after an automatic markup (for active learning), it's easier to start from scratch rather than removing wrong annotations.
So we need a button to do the reset.

---------

**Comment by Hironsan** [comment]
OK. I will consider how to do that.

**Comment by CBvanYperen** [comment]
How is the progress on this issue? I would like to contribute.

Just to make sure I understand the feature correctly, the request is about a button (like drawn in the screenshot) that would clear all annotations and result in the situation as displayed in the second screenshot?

![Screenshot 2020-12-10 105557](https://user-images.githubusercontent.com/55229791/101756453-50539780-3ad6-11eb-8de5-a14cdcbdec48.png)
![Screenshot 2020-12-10 105624](https://user-images.githubusercontent.com/55229791/101756472-56497880-3ad6-11eb-924c-21ac3a5847f8.png)
