### ISSUE TITLE
[Feature request] Put label hints and key shortcut hints back to Annotation page

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#635]
Feature description
---------
As mentioned in #509, #627, we have removed:
1. label buttons,
2. key shortcut hints,
3. annotation progress bar
in v1 UI.

This proceed some disadvantages:
1. Annotators don't see key shortcuts.
2. Annotators have to do **two** additional mouse movements:
  a. open labels list,
  b. close labels list: because they don't see next document's text until.

So I propose to put label buttons and key shortcut hints back to Annotation page.

**Comment by kuraga** [comment]
@tusharmakkar08 , could you, please, help with PR here? :)

**Comment by icoxfog417** [comment]
duplicate to #834

**Comment by kuraga** [comment]
@icoxfog417 , no, #834 is only a **subset** of this.

**Comment by kuraga** [comment]
Fixed.
