### ISSUE TITLE
[Bug] Release v1.0.2 fails on doccano@1.0.0 build /app nuxt build

### ISSUE THREAD

**Issue by Raimmaster** [doccano/doccano#636]
How to reproduce the behaviour
---------
When running `docker-compose -f docker-compose.prod.yml up` it fails when it reachs the `npm run build`.

It starts:
```Step 6/6 : RUN npm run build
---> Running in 9bd02da208cc

> doccano@1.0.0 build /app
> nuxt build
```
However, it fails with:
```ERROR in ./node_modules/vuetify/lib/components/VColorPicker/VColorPickerEdit.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.to-string' in '/app/node_modules/vuetify/lib/components/VColorPicker'
 @ ./node_modules/vuetify/lib/components/VColorPicker/VColorPickerEdit.js 5:0-46
 @ ./node_modules/vuetify/lib/components/VColorPicker/VColorPicker.js
 @ ./node_modules/vuetify/lib/components/VColorPicker/index.js
 @ ./components/containers/labels/LabelList.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--17-0!./node_modules/vue-loader/lib??vue-loader-options!./pagenpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doccano@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doccano@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-20T17_26_56_109Z-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

I have also looked into [the following issue](https://github.com/doccano/doccano/pull/539) and updated the frontend node version to 13.2.0 in the frontend Dockerfile; however, the output above is after doing that change.

Here is the complete error log output:
https://hastebin.com/urimuketup.sql

## Your Environment
---------

*   Operating System: Ubuntu 18.04.3 LTS
*  Docker version 19.03.5, build 633a0ea838
* docker-compose version 1.25.0, build 0a186604
*   When you install doccano: https://github.com/doccano/doccano/releases/tag/v1.0.2
*   How did you install doccano (Heroku button etc): downloaded the release, unzipped, run the docker-compose.prod.yml file.

**Comment by Hironsan** [comment]
Use [v1.0.3](https://github.com/doccano/doccano/releases/tag/v1.0.3) instead.
