### ISSUE TITLE
[Bug] Frontend container exits immediately with docker-compose

### ISSUE THREAD

**Issue by Raimmaster** [doccano/doccano#637]
How to reproduce the behaviour
---------
While running `docker-compose -f docker-compose.prod.yml up`, all services start except the frontend container. Whenever I run it, there's not a single line of output or logs of any kind that indicates what happened.

[Containers terminal output.](https://i.imgur.com/juonfLc.png)

`docker ps -a` shows the following:
```CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                      PORTS                NAMES
1c744c8b3930        doccano_nginx          "nginx -g 'daemon of…"   34 minutes ago      Up 34 minutes               0.0.0.0:80->80/tcp   doccano_nginx_1
da2f20e2d337        doccano_backend        "/app/tools/run.sh"      34 minutes ago      Up 34 minutes                                    doccano_backend_1
a20044108403        postgres:12.0-alpine   "docker-entrypoint.s…"   34 minutes ago      Up 34 minutes               5432/tcp             doccano_postgres_1
44a28ce58904        doccano_frontend       "docker-entrypoint.s…"   34 minutes ago      Exited (0) 33 minutes ago                        doccano_frontend_1
```

Any reasons as to why this is happening?

Your Environment
---------

*   Operating System: Linux Mint 19.3 Tricia
*   Docker version 19.03.8, build afacb8b7f0
*   docker-compose version 1.25.0, build 0a186604
*   When you install doccano: today from commit: https://github.com/doccano/doccano/commit/fa39e8908c7258798f4bc3f11e318bf59efacdc5
*   How did you install doccano (Heroku button etc): installing from source, running docker-compose.prod.yml

**Comment by resonancellc** [comment]
Raimmaster, this appears to be an issue with Dockerfile settings in the /frontend folder.
After seeing your post I tested the following:

git clone https://github.com/doccano/doccano.git
cd doccano/frontend/
npm install
npm run build
cp dist/ /var/www/html/ -r
service apache2 status
sudo ls /var/log/apache2/
sudo cat /var/log/apache2/access.log
sudo cat /var/log/apache2/error.log
ls /var/www/html/dist/_nuxt/ -al
sudo chown -R www-data:www-data /var/www/html/dist/
cd /var/www/html/dist/
ls
nano index.html
npm run
cd doccano/frontend/
cat package.json
npm start


The instructions in the Dockerfile build the project in a way that the setup cannot find the javascript files.  Running the local project from npm start produced a working unit.

**Comment by Hironsan** [comment]
The `frontend` container is used to build javascript files. So once it has finished building, it is unnecessary. That's why it exits immediately.
