### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by aabid0193** [doccano/doccano#642]
When was the UI for annotating documents changed to the current version, form the version in the heroku app demo? https://doccano.herokuapp.com/demo/named-entity-recognition/.

**Comment by icoxfog417** [comment]
The demo on the Heroku is not the latest version. Please wait a moment!

**Comment by aabid0193** [comment]
Yes! I'm aware, just wanted to know when it was changed. i liked the asthetics of the demo a little more though hah.
