### ISSUE TITLE
Django Rest Framework api

### ISSUE THREAD

**Issue by zhentaoCoding** [doccano/doccano#646]
I know the backend is based on Django Rest Framework. 

how can I auto document for the django framework api of the doccano .

Your Environment
---------

*   Operating System:mac os
*   Python Version Used:3.6
*   When you install doccano:2020.3.24
*   How did you install doccano (Heroku button etc):docker-compose.dev.yml

**Comment by Hironsan** [comment]
Hi, @zhentaoCoding 

The following page will be helpful for you:

* [Documenting your API](https://www.django-rest-framework.org/topics/documenting-your-api/)

If you make a pull request, I'm very happy.

**Comment by zhentaoCoding** [comment]
I followed this document,but something error

![](https://user-images.githubusercontent.com/5669444/77533906-b8c00180-6ed2-11ea-9df7-46a35b1af88b.png)
