### ISSUE TITLE
Issues while installing using docker-compose

### ISSUE THREAD

**Issue by tusharmakkar08** [doccano/doccano#652]
How to reproduce the problem
---------
When I am trying to install via `docker_compose.prod.yml`, I see this error:

```bash
~/doccano$ docker-compose -f docker-compose.prod.yml up

ERROR: Version in "./docker-compose.prod.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

So for fixing this I converted the `version` parameter to `3` and it started running fine

Your Environment
---------

*   Operating System:  Ubuntu 18.04.4 LTS
*   Python Version Used: Python 2.7.17
*   Docker version: Docker version 19.03.6, build 369ce74a3c
*   How did you install doccano (Heroku button etc): docker-compose command mentioned in Readme

**Comment by Hironsan** [comment]
Looks like you have an older docker-compose version that doesn't support yet the docker-compose file version 3.7. The following issue is helpful:

* https://github.com/docker/compose/issues/6994
