### ISSUE TITLE
Tools connect in web pages whether network is required

### ISSUE THREAD

**Issue by zlwzlwzlw** [doccano/doccano#655]
How to reproduce the behaviour
---------
i use docker deploy my server in centos and connect server web user other windows which can't connect the internet, i can't open web. Whether is not connect the net and to be used? 

Your Environment
---------

*   Operating System:The deployment system is centos and used in windows web
*   Python Version Used:docker install
*   When you install doccano:Recently
*   How did you install doccano (Heroku button etc):docker install

**Comment by Hironsan** [comment]
Need network.
