### ISSUE TITLE
Unify Docker bases?

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#659]
Good day!

Current (v1.0.3) situation:
* Nginx's Docker base [is Alpine](https://github.com/doccano/doccano/blob/v1.0.3/nginx/Dockerfile#L1),
* Node's Docker base [is Ubuntu](https://github.com/doccano/doccano/blob/v1.0.3/frontend/Dockerfile#L1),
* Python's Docker base [is Ubuntu](https://github.com/doccano/doccano/blob/v1.0.3/app/Dockerfile#L1).

Would you accept a patch to unify bases to Alpine (or Ubuntu)?

**Comment by icoxfog417** [comment]
I think that it is needless to unify the base image because each component works distinctly. To use an appropriate base image is meaningful.

**Comment by kuraga** [comment]
Ahaha, it was a bad idea, at all: docker-library/docs#904, pypa/manylinux#37.
