### ISSUE TITLE
[Question] Some files are not documented

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#660]
For what we have `/Dockerfile`, `requirements.txt` (in the root)? These files [are not documented](https://github.com/doccano/doccano/blob/554d0cd9c362c70f660ab94a260cf02aa5bb304f/docs/project_structure.md).

Also I see: [`/requirements.txt`'s Django version](https://github.com/doccano/doccano/blob/554d0cd9c362c70f660ab94a260cf02aa5bb304f/requirements.txt#L7) differs from [`/app/requirements.txt`'s Django version](https://github.com/doccano/doccano/blob/554d0cd9c362c70f660ab94a260cf02aa5bb304f/app/requirements.txt#L7). Why?

Thanks!

**Comment by Hironsan** [comment]
Docker compose version uses `app/requirements.txt`, while Docker version uses `requirements.txt`. `requirements.txt` remains for backward compatibility.

**Comment by kuraga** [comment]
Should they be synced?
