### ISSUE TITLE
In git bash superuser is created succesfully. but i have a doubt like where should i login with this superuser account details?

### ISSUE THREAD

**Issue by vishnukelam03** [doccano/doccano#662]
when i tried logging in https://doccano.herokuapp.com/login/ i am getting error saying that username and password didn't match.
![1](https://user-images.githubusercontent.com/47236920/78157614-c985ef80-745d-11ea-9b22-64a92e5b1ec4.JPG)

How to reproduce the problem
---------

```bash
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions, social_django
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
**Superuser created successfully**.
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by icoxfog417** [comment]
You can't log in https://doccano.herokuapp.com/login/ because it is our demo site. Please create your own environment to login.
