### ISSUE TITLE
Signup verification email not received

### ISSUE THREAD

**Issue by bheuju** [doccano/doccano#663]
How to reproduce the behaviour
---------
I setup the project using AWS one-click deployment button. Everything works fine, but when a new user sign ups, email verification is not received. I believe I have to set up a email host configurations in `settings.py`. How do I set it up as the project has already been deployed? Is it in the `/env.list` file, or the AWS one-click automatically does this?

```
# necessary for email verification of new accounts
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', False)
EMAIL_HOST = env('EMAIL_HOST', None)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', None)
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', None)
EMAIL_PORT = env.int('EMAIL_PORT', 587)
```
Your Environment
---------

*   Operating System: AWS ubuntu
*   Python Version Used: 3.6
*   When you install doccano: Mar 30, 2020
*   How did you install doccano (Heroku button etc): AWS one-click deployment

---------
Also, when I deployed the project using docker-compose by pulling the github project, the project looks older and not as in demo http://doccano.herokuapp.com/. Why is that? Am I missing something here?

**Comment by srbek-cmd** [comment]
I am having the same issue when deploying doccano using the one-click button for Heroku. 

Any advice would be greatly helpful.

**Comment by bheuju** [comment]
@srbek-cmd I have figured out how to make email verification work. You have to add the Email host configurations in the `/env.list` file and rerun the doccano.

> Note: It will erase all the previous doccano containers and create a new one, so all your old data from doccano will be erased.

Eg:

/env.list
```
ADMIN=admin
EMAIL=admin@email.com
PASSWORD=password
DEBUG=False
SECRET_KEY=your_secret_key

EMAIL_USE_TLS=True
EMAIL_HOST=smtp.gmail.com
EMAIL_HOST_USER=email_host@gmail.com
EMAIL_HOST_PASSWORD=email_host_password
EMAIL_PORT=587
```

Then remove the docker containers and rebuild them using the new /env.list file.
```
sudo docker stop doccano
sudo docker rm doccano
sudo docker run -d --name doccano --env-file /env.list -p 80:8000 chakkiworks/doccano:latest
sudo docker exec doccano tools/create-admin.sh ${ADMIN} ${EMAIL} ${PASSWORD}
```

**Comment by pranavrajt** [comment]
@bheuju I am facing the same issue as you are. Did you make the changes locally and then re-deploy using one click AWS deployment? 
Or did you launch your own project using docker-compose? The latter doesnt make sense, because as you rightly mentioned, the UI does seem to be outdated.

**Comment by bheuju** [comment]
@pranavrajt No not in the local. The file exists in the server at /env.list . I did not use docker-compose, but the docker image that the AWS one-click deployment uses by default. And yes, the docker-compose version of the UI does seem outdated but it is said to be the recent one.
