### ISSUE TITLE
unable to add same label more than once in a given annotator

### ISSUE THREAD

**Issue by vishnukelam03** [doccano/doccano#665]
Below is the screenshot of the data.
![annotator error](https://user-images.githubusercontent.com/47236920/78272539-44690c00-752b-11ea-9017-77a4f43851f3.JPG)

In this data i am unable to label united states and washingtonDC as loc label.
It is allowing me to label only one. I don't know what is the error in this. 
This is **DocumentClassification.**
And one more question is why my label is not reflecting in the data?

How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System: win 10
*   Python Version Used: 3.6
*   When you install doccano: 01-apr-2020
*   How did you install doccano (Heroku button etc): docker

**Comment by icoxfog417** [comment]
If you want to add the label by each word, please use Sequence Labeling. And the duplicate label is not allowed in the general sequence labeling task.
