### ISSUE TITLE
Can't upload data in any format

### ISSUE THREAD

**Issue by rproskuryakov** [doccano/doccano#681]
How to reproduce the behaviour
---------
Create a new project for text classification. 
Try to upload a dataset test.jsonl with the next lines:
```
{"text": "Terrible customer service.", "labels": ["negative"], "meta": {"wikiPageID": 1}}
{"text": "Really great transaction.", "labels": ["positive"], "meta": {"wikiPageID": 2}}
{"text": "Great price.", "labels": ["positive"], "meta": {"wikiPageID": 3}}
```
File is in UTF-8.
Get error "The file could not be uploaded. Maybe invalid format. Please check available formats carefully. "

My Environment
---------

*   Operating System: CentOS 7 
*   Python Version Used: 2.7.5 (Host)
*   When you install doccano: 9.04.2020
*   How did you install doccano: docker-compose

**Comment by Hironsan** [comment]
For now, I could upload your data in the latest doccano:
![image](https://user-images.githubusercontent.com/6737785/78948222-93eaa180-7b02-11ea-80b0-16d5f6a55174.png)

We need further information to resolve the situation such as server log, client network log, and so on.

**Comment by paulakeen** [comment]
Well, I'm having exactly the same problem when trying to import very basic pieces of text encoded as UTF-8...getting desperate.

**Comment by paulakeen** [comment]
OK, I just discovered that if I cut the text to small paragraphs it is imported. But the message I'm getting is misleading because it tells that something wrong is happening with the format of the content. And I was able to load the same text without changes if a cut it into small pieces.

**Comment by anuragkumar95** [comment]
> For now, I could upload your data in the latest doccano:
> ![image](https://user-images.githubusercontent.com/6737785/78948222-93eaa180-7b02-11ea-80b0-16d5f6a55174.png)
> 
> We need further information to resolve the situation such as server log, client network log, and so on.

Can you tell us the version of doccano you are using. I am facing a similar problem.

**Comment by jganseman** [comment]
I had this problem uploading a plain text file with only 10 lines of text in a freshly installed pip version of Doccano (1.2.2, running Django 3.1.7). The problem disappeared when I removed the empty newlines from the end of the file!

**Comment by D0C2005** [comment]
Indeed, removing the empty newlines (regardless of their position) did the trick. Thanks for the suggestion!

> I had this problem uploading a plain text file with only 10 lines of text in a freshly installed pip version of Doccano (1.2.2, running Django 3.1.7). The problem disappeared when I removed the empty newlines from the end of the file!
