### ISSUE TITLE
For Docker, what's the difference between "chakkiworks/doccano" vs "doccano/doccano"?

### ISSUE THREAD

**Issue by aam1r** [doccano/doccano#682]
In the FAQ, [it says](https://github.com/doccano/doccano/wiki/Frequently-Asked-Questions#i-cant-install-doccano) to do:

```
docker pull chakkiworks/doccano
```

But in the main README, [it says](https://github.com/doccano/doccano#docker) to do:

```
docker pull doccano/doccano
```

What's the difference?

Which one should I be pulling?

**Comment by Hironsan** [comment]
You should use `doccano/doccano`. `chakkiworks/doccano` is older version.

**Comment by aam1r** [comment]
Thanks. Please update FAQs.
