### ISSUE TITLE
Vue project

### ISSUE THREAD

**Issue by ycchen1989** [doccano/doccano#683]
Hi all,

I just deployed this project to Heroku and it works well. Now I need to customize the user interface. What I did is simply editing the files in the folder `frontend/pages/index.vue`.
I removed the following three lines (in comments):
`<template>
  <v-content>
    
    
    
  </v-content>
</template>` 
When I push to the github and the Heroku built it again, the landing page doesn't change. I wonder if I need to do other things to make these modifications effective.

Thanks,

**Comment by Hironsan** [comment]
You should edit `app/server/templates/` files. Heroku version is not using `frontend/pages/` files.
