### ISSUE TITLE
How do I disable the landing page on the Docker image?

### ISSUE THREAD

**Issue by aam1r** [doccano/doccano#685]
I have deployed a `doccano/doccano` Docker container to give to my team of annotators.

It's a bit confusing though because as soon as they land on my internally hosted application, they see the landing page along with the nav bar that says "Live Demo" and "GitHub".

How do I disable this page and take them straight to Login?

![image](https://user-images.githubusercontent.com/566418/78960264-85c56280-7abb-11ea-9728-3d62d577cb87.png)

Only thing I can think of is using Docker Compose to put an Nginx proxy and doing a redirect in there. But that seems overkill. In fact there's no point in having this landing page. Perhaps it should be removed entirely from the distributed Docker image.

**Comment by Hironsan** [comment]
I'm not going to remove the landing page.

But if you want to do so, rewrite `urls.py`:
https://github.com/doccano/doccano/blob/ec889bf43a4c83be455876d57b5ddeedd0bd6a07/app/server/urls.py#L10
