### ISSUE TITLE
why after adding user , admin lost all projects ? 

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#686]
How to reproduce the behaviour
---------
Hi Sir ,
I tried to add user , create user and then mapping role to user for a specific project in admin page . And then i logout from admin page and login to projects page using admin credentials . But all projects are removed and also at the top text changed from **Hello,Admin.** to **Hello,.** . 
Please suggest any one , how to fix this one ?

Your Environment
---------

*   Operating System: ubuntu 18.04
*   Python Version Used: python 3.6
*   When you install doccano: 2 months ago
*   How did you install doccano (Heroku button etc):  git clone + From source

**Comment by Hironsan** [comment]
You need to create a user to the application in the admin page, but you should not add the user to the project and map role to the user in the admin page. They should be done in the project member page.

**Comment by sharmila-polamuri** [comment]
@Hironsan  I tried your solution but same result.

**Comment by sharmila-polamuri** [comment]
I added  new user in admin page using Users option under Authentication and authorization section .And add annotator role using roles under API section . And then i map role to user using role mappings under API section. And logout from admin page . Login to doccano to with admin credentials . But same result . 

Please help me anyone to fix this problem.

**Comment by amjltc295** [comment]
I got the problem as well. There are some bugs if you give multiple roles to a user (which I did) and encountered this problem. Removing additional roles helps solve some problems, but I'm not sure if this one could be fixed.
