### ISSUE TITLE
How do I locally modify a .vue file and then use it with Docker Compose?

### ISSUE THREAD

**Issue by aam1r** [doccano/doccano#689]
**What I am trying to do**

I am trying to tweak some CSS for my specific use-case.

**What I have done**

I modified CSS in `frontend/components/molecules/EntityItem.vue` and `frontend/components/organisms/annotation/EntityItemBox.vue`.

**What doesn't work**

When I run with `docker-compose.dev.yml` locally, I can see the CSS changes.

However when I do `docker-compose -f docker-compose.prod.yml up`, it doesn't pick up my new changes. It continues to show the old CSS.

**What I have tried**

I have tried clearing my Docker caches, deleting my Docker images, and rebuilding images. No luck.

I have tried clearing out the `frontend/_dist`, doing a `yarn build && yarn generate` and then re-running the docker-compose command.

How do I get the Docker Compose up and running locally with my CSS changes?

**Comment by Hironsan** [comment]
Remove `doccano_www` volume and build with `--no-cache` option:

```bash
$ docker volume rm doccano_www
$ docker-compose -f docker-compose.prod.yml build --no-cache
$ docker-compose -f docker-compose.prod.yml up
```

**Comment by kuraga** [comment]
@Hironsan 
```
Error response from daemon: remove doccano_www: volume is in use
```
even all containers are stopped. Is there a workaround?

And is it correct - **all** projects data is inside `doccano_postgres_data`? Is it safe to remove `doccano_www`?
