### ISSUE TITLE
annotations are misplaced / text wrapping in sequence annotation interface

### ISSUE THREAD

**Issue by DSLituiev** [doccano/doccano#690]
### Unexpected behaviour

The lines and labelled entities are flying around out of their order, and the text appears messed up 

### with annotations
![Screen Shot 2020-04-10 at 15 54 51](https://user-images.githubusercontent.com/8426290/79028143-d08abd00-7b43-11ea-819a-292297e968e8.png)

### without annotations
![Screen Shot 2020-04-10 at 15 55 18](https://user-images.githubusercontent.com/8426290/79028118-bf41b080-7b43-11ea-9df8-ef62e007c5db.png)

Notice: words "Complaint" and "Illness" are in completely wrong line (several lines before they are supposed to be).  

### How to reproduce the behaviour
---------
1. Run doccano docker image per instruction 
```
docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano
docker container start doccano
```

2. Upload jsonl content (see below)

### JSONL annotation
<details>

`
{"title": "abdominal-pain-unc-part1.txt", "text": "Margareth Pierre-Louis\nInternal Medicine Rotation August 20-October 19, 2000\n\nChief Complaint:  abdominal pain\n\nHistory of Present Illness:\n\nMs. ___ is a 47 year old African American female with Crohn's Disease, DM, and HTN who  presented to the ED after two days of severe abdominal pain, nausea, vomiting, and diarrhea. She  stated that on Wednesday evening after being in her usual state of health she began to experience  sharp lower abdominal pain that radiated throughout all four quadrants. The pain waxed and  waned and was about a 4/10 and more intense than the chronic abdominal pain episodes she  experiences periodically from her Crohn's disease. The pain was sudden and she did not take any  medications to alleviate the discomfort. The abdominal pain was quickly followed by two  episodes of partial diarrhea and soft stool that was tan in color with no signs of blood. Her  abdominal pain continued and she developed nausea and then vomited six times that evening  before going to sleep.  Overnight her abdominal pain worsened and she stayed in bed for most of  the day on Thursday. She had nausea again all day but had no other episodes of diarrhea or  vomiting that day and did not eat anything for fear of vomiting. She was able to drink water and  keep it down. By late Thursday night, her pain had intensified to a 10/10 and she called 911 and  was brought to the ER by ambulance from her home in Burlington.\n\nMs. ___ also stated that she had just ended a three week course of prednisone four days ago,  which she had started about a month ago at 60 mg and tapered herself down over a few days by  10 mg. She began the course of prednisone last month because she felt as if she was about to  have a Crohn's flare at the time. Ms. ___ was last hospitalized at UNC for Crohn's disease  exacerbation in March 2007. She denies any recent hemoptysis, constipation, hematochezia,  melena, and changes in her bowel habits since Wednesday. She has been compliant with taking  her medications for Crohn's and has been stable on her mesalamine, mercaptopurine, and omega-3-acid supplement.\n\nUpon arrival to the ED, Ms. ___ was put on IV fluids, given fentanyl 50 mcg IVP, phenegran  12.5 mg diluted with 10 mL NS IVP, and Mg sulfate IVP. Radiological images were obtained  through an abdominal CT scan, ultrasound, and 2V XR. Ms. ___ was not given any other  narcotics for her pain because of a past violation of a pain contract after a positive toxicology  screen for cocaine resulted in her discharge from her family medicine provider and due to  suspicions that she was narcotic-seeking.\n\nPast Medical History\n\nCrohn's disease, diagnosed 1998\nAdenocarcinoma of terminal ileum 1998 - s/p resection of terminal ileum, rad and chemo, no  mets.\nhx of small bowel obstruction secondary to Crohn\u2019s Disease\nDM\nHTN\nDVT and PE 2001\nPUD\nGERD\nCOPD\nPosttraumatic stress disorder\nBipolar disorder\nhx of multiple suicide attempts\nosteoarthritis of knee joints\nleft knee arthroscopy, 1995\npartial hysterectomy, 1990\nnicotine dependence, 30 years\n\nMedications\n\nCymbalta 60 mg po qday\nFluticasone furoate nasal spray 27.5 mcg prn   \nalbuterol inhalation aerosol 17 g prn  \nomacor 900 mg QID\nmesalamine(pentasa) 500 mg QID\nAmbien CR 12.5 mg qhs prn\nfluticasone/salmeterol (Advair diskus) 250/50 prn\nProtononix 40 mg qday\npalidperidone (invega) 3 mg qday\nsitalgliptin/metformin (Junamet) 50/500 mg qday   \ngabapentin 400 mg TID\nconjugated g-estrogens (premarin) .625 mg qday\nlisinopril 5 mg qday\nmecaptopurine 50 mg BID\nnexium 40 mg qday\nclonazepam 1.5 mg BID\n\nAllergies\n\nPenicillin, causes rash and anaphylaxis\nmorphine, causes itching  \nIV Contrast, causes tachycardia\n\nSocial History\n\nMs. ___ lives in _________ with her husband. She has 6 children who are in good health but do  not live with her. Ms. ___ is on disability for her bipolar diagnosis and usually spends her days at  home and caring for a sick older relative. She smokes half a ppd and has done so for the past 30  years. She states that she does not use any other drugs and that she does not consume alcohol.  She has been involved in the distribution of crack cocaine for years in the past but stopped two  years ago. While her husband is a crack user, she states that she has never been a user of any  illicit drugs or narcotics. She is not physically active and her diet consists of small food portions  but is generally unhealthy. She suffers from chronic abdominal pain secondary to her Crohn\u2019s,  and also chronic right knee and lower back pain from a fall injury and osteoarthritis.  She uses a  cane when her knee and back pain become debilitating. She has a history of narcotic-seeking  behavior and has left during past hospital visits when narcotic medications would not be  prescribed for her pain. She no longer receives narcotics from UNC after breaking her pain  contract with her family medicine provider but it is unclear if she receives pain medications from  an outside hospital. She has been incarcerated in the past for arson and attempted murder.\n\nFamily History\n\nMother - bipolar and Schizophrenia, \"drank herself to death\"\nFather - living with diabetes, s/p CABG.\n2 sisters with HTN  Maternal grandfather, leukemia\n\nReview of Systems\n\nConstitutional: denies anorexia and weight loss\nHEENT: denies decreased hearing blurring, diplopia, irritation, discharge, vision loss, eye pain,  photophobia, ear pain or discharge, tinnitus, nasal obstruction or discharge, nosebleeds, sore  throat, hoarseness, dysphagia\nCardiovascular: dyspnea on exertion; denies chest pains, palpitations, syncope, orthopnea, PND,  edema\nRespiratory: denies cough and wheezing\nGastrointestinal: denies jaundice\nGenitourinary: denies incontinence, dysuria, hematuria, urinary frequency\nMusculoskeletal: arthritis in left knee and pain in lower back pain from past injury; denies other  3\njoint pain, joint swelling, muscle cramps, muscle weakness, stiffness,\nSkin: denies rash, dryness, suspicious lesions\nNeurologic: chronic weakness in her left knee; denies transient paralysis, paresthesias, seizures,  syncope, tremors, vertigo\nPsychiatric: denies depression, anxiety, memory loss, mental disturbance, suicidal ideation,  hallucinations, paranoia\nEndocrine: denies cold intolerance, heat intolerance, polydipsia, polyphagia, polyuria\nHeme/lymphatic: denies bruising, bleeding, enlarged lymph nodes\nAllergic/Immunologic: denies urticaria, hay fever, persistent infections, HIV exposure\n\nPhysical Examination\nVitals from ED admission\nTemperature : 36.3\nPulse : 79\nRespiratory Rate : 16\nBlood Pressure : 116/82\nOxygen Saturation%: 97% on RA\nPain Score : 10/10\n\nGeneral\nObese, sleepy but oriented woman lying in bed\n\nEyes\nConjunctivae and lids normal, pupils equal, round, reactive to light and, accommodation, discs  sharp and flat, no a/v nicking, hemorrhages, or exudates, normal visual acuity, EOM intact.\n\nENNT\nExternal ears normal, no lesions or deformities; external nose normal, no lesions or deformities;  canals clear bilaterally, tympanic membranes intact with good movement, no fluid; hearing  grossly intact bilaterally; nasal mucosa, septum, and turbinates normal; poor dentition and  missing a few teeth on both sides of top and bottom but does not wear dentures, tongue normal,  posterior pharynx without erythema or exudates. Neck is supple, no masses, trachea midline; no  thyroid nodules, masses, tenderness, or enlargement\n\nRespiratory\nClear to auscultation bilaterally, normal tactile fremitus, no egophony, normal respiratory effort  with no use of accessory muscles.\n\nCardiovascular\nS1, S2, normal rhythm, no murmur, rub, or gallop; no thrill or palpable murmurs on palpation, no  JVD, no displacement of PMI; no carotid or abdominal bruits; no enlargement of abdominal  aorta. Carotid, radial, posterior tibialis, and pedal pulses 2+ symmetric, no edema\n\nGastrointestinal\nsuprapubic surgical scar, obese, soft, non-tender, and non-distended abdomen with no masses;  bowel sounds hyperactive, liver size appears within normal limits but not measured in  midclavicular and midsternal line because of RUQ pain and tenderness to palpation; no liver  nodularity or masses, no splenomegaly\n\nRectal Exam\nNo rashes, lesions or sores, guaiac positive stool\n\nLymph Nodes\nNo cervical, clavicular, or posterior auricular lymphadenopathy\n\nSkin\nno rash, lesions, ulcerations, subcutaneous nodules or induration\n\nMusculoskeletal\nnormal alignment, mobility and no deformity of head and neck, spine, ribs, pelvis; normal ROM  and 5/5 strength in all extremities except compared to 4/5 strength in LLE, no joint enlargement  or tenderness; no clubbing, cyanosis, petechiae, or nodes of digits and nails; gait and station  deferred because patient supine\n\nNeurologic\nCranial nerves: II - XII grossly intact; 2+, symmetric, reflexes; intact to touch, pin, vibration, and  position in lower extremities; normal finger-to-nose, Rhomberg and Pronator drift deferred  because patient was supine and would not stand\n\nMental Status Exam\nJudgment and insight intact; oriented to time, place, and person; intact memory for recent and  remote events; no depression, anxiety, or agitation\n\nPertinent Diagnostic Tests\nNotes:\nLABS\nChem 10: Na 137, K 3, Cl 104, C02 27, BUN 9, Cr 0.7, gluc 91, Ca 9.8, Mg 1.4, PO4 2.3\nCBC: WBC 4.3, Hb 10.7, Hct 32.9, plts 312\nTotal Bili 0.2, AST 14, ALT 23, Alk Phos 88, GGT 53, Lipase 12\nU/A - not completed\n\nAbdominal Acute 2V XR\n1. No focal airspace consolidation or effusion.\n2. Multiple dilated small bowel loops with scattered air-fluid levels and posse of distal gas,  concerning for small bowel obstruction. There is also suggestion of colonic wall thickening  likely representing active colitis in a patient with Crohn's disease.\n\nAbdominal CT\n1. Findings consistent with active Crohn's disease in the terminal ileum with mucosal thickening.  No bowel obstruction, abscess or fistula identified.\n\nAbdominal U/S\n1. Limited abdominal ultrasound showing mild sludge in the gallbladder, without evidence for  cholelithiasis or acute cholecystitis.\n2. Mild prominence of the common bile duct. Stable since 7/27/07.\n\nProblem List\nCrohn's disease flare (abdominal pain, nausea, vomiting, diarrhea)\nAdenocarcinoma of terminal ileum, s/p resection 1998\nhx of small bowel obstruction secondary to Crohn\u2019s Disease  \nDM  \nHTN\nhx of DVT and PE, 2001\nPUD\nGERD\nCOPD\nPosttraumatic stress disorder\nBipolar disorder\nhx of multiple suicide attempts\ninsomnia\nchronic abdominal, back, and left knee pain\nosteoarthritis of knee joints\nuse of cane for walking\nnicotine dependence and abuse\nhx of narcotic seeking behavior\npoor dentition without denture\nuse  exposure to crack cocaine and possible abuse or hx of abuse\nresponsibility for care of dying relative\nobesity\n\nAssessment and Recommendation\n\nMs. ___ is a 47 year old African American woman with Crohn\u2019s disease, HTN, and DM who  presented to the ER after two days of acute abdominal pain, nausea, vomiting, and diarrhea most  likely due to Crohn\u2019s disease exacerbation.\n\n#1 Crohn\u2019s exacerbation (abdominal pain with nausea, vomiting, and diarrhea)\nMs.  ___  presented  with  acute  diffuse  abdominal  pain  that  was  followed  by  nausea,  vomiting, and diarrhea.  The pain  was much more intense than the chronic pain she usually  experiences with her Crohn\u2019s disease. The differential diagnosis for her cluster of symptoms  includes  inflammatory  bowel  disease,  specifically  a  Crohn\u2019s  disease  exacerbation,  intestinal  obstruction, and mesenteric insufficiency or infarction. Ms. ___\u2019s abdominal pain is most likely  from a Crohn\u2019s disease flare because of her presenting symptoms, radiological imaging findings,  and history of these exacerbations that have resolved with the use of prednisone. Crohn\u2019s disease  is an inflammatory bowel disease condition of unknown etiology that can affect any part of the  GI tract. Its primary characteristic is transmural inflammation that can affect the GI tract from  mouth to anus and can result in severe abdominal pain, bleeding, ileitis, colitis, bowel perforation  and fistula formation, and perianal abscesses. 80% of patients have small bowel involvement,  including the distal ileum with possible sparing of the rectum. Patients with Crohn\u2019s disease can  be asymptomatic at times but when the disease is exacerbated, patients can present with weight  loss, fever, nausea, abdominal pain, diarrhea, and anal bleeding. Crohn\u2019s disease is diagnosed by  colonoscopy and intestinal biopsy. Pathologically, Crohn\u2019s disease is noted for its cobblestone  appearance  from  polypoidy  mucosal  changes  and  focal  areas  of  ulceration  next  to  normal  mucosa.  Crohn\u2019s differs from another inflammatory bowel disease ulcerative colitis (UC) in that  UC has a continuous area of inflammation to the level of the submucosa that begins at the rectum  and works up backwards up the GI tract, rarely forms fistulas or perforations, and has a higher  association with colon cancer. There are also extraintestinal manifestations of Crohn\u2019s disease,  including eye involvement (uveitis, iritis, and episcleritis), skin disorders (erythema nodosum  and  pyoderma  gangrenosum),  arthritis  of  large  joints  or  sacroilitis,  primary  sclerosing  cholangitis, secondary amyloidosis, and venous or arterial thromboembolism. Ms. ___\u2019s medical  history indicates that she has debilitating knee arthritis and back pain and developed a DVT in  2001 that resulted in a PE. These other disease manifestations may be associated to her Crohn\u2019s  disease.  As in Ms. ___\u2019s case, abdominal imaging can detect active Crohn\u2019s disease and its  inflammatory  process.  Crohn\u2019s  disease  can  be  treated  with  numerous  medications  that  play  primarily a role in immunosuppression. These medications in order of importance include 5- ASA  drugs  (sulfasalazine  and  mesalamine),  steroids  (prednisone  or  budesonide),  immunosuppressive agents (azathioprine, 6-mercaptopurine, methotrexate), immune modulators  (infliximab,    adalimumab)  omega  3-  acid  supplements,  and  antibiotics  when  warranted.  A  combination  of  these  medications  can  be  used  to  control  the  disease  and  prevent  Crohn\u2019s  exacerbation  but  corticosteroids  have  been  found  to  give  the  most  immediate  relief  from  inflammation.\n\nFor her Crohn's flare, Ms. ___ will start prednisone 60 mg and take the medication for two weeks and then slowly taper herself every two weeks decreasing the dosage by 10 mg.  The  vomiting and diarrhea had resolved by admission and her nausea will be treated with phenegran  if it persists. An erythrocyte sedimentation rate will also be obtained to see if there is an increase  in inflammation and possible infection process.  Ms. ___ will also continue taking her other  medications for Crohn\u2019s:  mercaptopurine, mesalamine, and omega 3-acid supplement.\n\nA  small  bowel  obstruction  is  also  on  the  differential  and  occurs  when  the  passage  of  normal GI contents is blocked. This usually occurs as a result of post-operative complications or  hernias but can be due to masses, strictures, gastroparesis, or simply constipation. This ileus  would present with abdominal pain and bloating, nausea, vomiting, and constipation, a reduced  appetite due to a feeling of fullness, and abdominal distention. However, Ms. ___ was able to  pass stool with the onset of her symptoms and was not constipated or abnormally distended,  which would be expected in an intestinal obstruction.  It is also unlikely that a  small bowel  obstruction would present with guaiac positive stool. Furthermore, while the abdominal XR did  show dilated small bowel loops that are seen in a small bowel obstruction, the CT image better  identified this as thickening of the terminal mucosal ileum, which is more suggestive of Crohn\u2019s  disease  than  a  small  bowel  obstruction.  Also,  the  acute  nausea  and  vomiting  resolved  spontaneously by the time of admission. A small bowel obstruction can be a medical emergency  and should be diagnosed quickly to prevent complications, such as ischemia and strangulation of  intestines. Medical management for small bowel includes mobilizing the patient, discontinuing  medications that may have reduced gut motility, enemas, decompression with NGT, rectal tubes,  or colonoscopy, or operative procedure if the condition merits it.\n\nAcute  mesenteric  ischemia  of  the  small  intestine  is  on  the  differential  for  Ms.  ___\u2019s  abdominal pain. Mesenteric ischemia occurs when there is a reduction in arterial or venous  intestinal blood flow due to an occlusion, vasospasm, and/or hypoperfusion of the mesenteric  vasculature.  Mesenteric  ischemia  can  result  in  bowel  infarction,  sepsis,  and  is  a  medical  emergency.  The four major causes of acute mesenteric ischemia are superior mesenteric artery  embolism  or  thrombosis,  mesenteric  venous  thrombosis,  and  nonocclusive  ischemia.  Most  mesenteric ischemia is of arterial origin. The patient usually presents with rapid onset of severe  periumbilical abdominal pain that is out of proportion to physical exam findings in addition to  nausea and vomiting. Sudden pain associated with minimal abdominal signs and forceful bowel  evacuation increase the likelihood of mesenteric ischemia. Also, a state of metabolic acidosis and  acute abdominal pain also suggest mesenteric ischemia. Ms. ___\u2019s risk factors for mesenteric  ischemia include hypercoagulability, specifically her DVT resulting in PE in 2001. Also, Ms.  ___  has  a  history  of  small  bowel  obstruction,  which  can  predispose  an  individual  to  hypoperfusion  leading  to  ischemia.    Mesenteric  angiography  is  used  to  detect  mesenteric  ischemia and Doppler ultrasound can help visualize occlusions and stenoses of vessels.  A CT  scan can be helpful in detecting a mesenteric thrombosis. Labs to consider are lactic acid levels  and CBC for leukocytosis and elevated hematocrit, even though these studies are nonspecific.  While she experienced nausea and vomiting with her abdominal pain, Ms. ___\u2019s abdominal pain  is unlikely to be from acute mesenteric ischemia because of the duration of her abdominal pain,  normal vital signs and physical exam that was not out of proportion in regards to her appearance. \n\n#2 DM\n\nMs. ___ is a diabetic and her glucose on admission was 91. Her glucose will be strictly  monitored during her stay and her AIC will be checked. She has been on a combination of  Sitalgliptin  and  metformin  to  treat  her  insulin  resistance  diabetes.  Sitalgliptin  is  a  DPP-4  inhibitor that improves glycemic control by increasing the amount of glucagon-like peptide -1  and  gastric  inhibitory  polypeptide  secretion,  leading  to  increased  secretion  of  insulin  and  inhibition  of  glucagon  secretion.    Metformin  is  a  biguanide  that  reduces  hepatic  glucose  production, therefore also lowering glucotoxicity. We do not have this combination medication  and will start Ms. ___ on sliding scale insulin to control her glucose levels.\n\n#3 HTN\n\nMs.  ___  has  hypertension  that  appears  to  be  well  controlled  on  lisinopril.  Her  hypertension,  DM,  and  physical  inactivity  are  major  cardiovascular  risk  factors  and  it  is  important to keep her blood pressure well-controlled under 130/80 to prevent end-organ damage  and  future  cardiovascular  and  cerebrovascular  events.  We  will  continue  her  lisinopril  as  prescribed.\n\n#4 Nicotine dependence\n\nMs. ___ has smoked at least half a pack of cigarettes for the past 30 years. Smoking toxins  can exacerbate Crohn\u2019s and cause more active episodes of inflammation. She will be counseled  on  the  importance  of  smoking  cessation  and  the  effects  it  has  on  her  cardiovascular  and  pulmonary health, risk of cancer development, and current Crohn\u2019s disease condition.\n\n", "labels": [[84, 93, "symptoms"], [96, 110, "symptoms"], [131, 138, "hx_symptoms"], [267, 288, "symptoms"], [290, 320, "symptoms"], [426, 452, "symptoms"], [502, 506, "symptoms"], [571, 593, "symptoms"], [663, 667, "symptoms"], [734, 744, "symptoms"], [750, 764, "symptoms"], [814, 822, "symptoms"], [827, 837, "symptoms"], [889, 903, "symptoms"], [932, 938, "symptoms"], [996, 1001, "symptoms"], [1018, 1032, "symptoms"], [1106, 1112, "symptoms"], [1156, 1177, "symptoms"], [1216, 1220, "symptoms"], [1224, 1232, "symptoms"], [1242, 1246, "symptoms"], [1298, 1313, "symptoms"], [1854, 1864, "neg_symptoms"], [1866, 1878, "neg_symptoms"], [1880, 1892, "symptoms"], [1895, 1901, "neg_symptoms"], [1922, 1934, "symptoms"], [2387, 2391, "symptoms"], [2425, 2429, "symptoms"], [2772, 2783, "symptoms"], [2864, 2870, "symptoms"], [2912, 2928, "hx_symptoms"], [3139, 3149, "symptoms"], [3555, 3564, "symptoms"], [3585, 3589, "symptoms"], [3594, 3605, "symptoms"], [3623, 3630, "symptoms"], [3653, 3664, "symptoms"], [3666, 3680, "symptoms"], [3810, 3820, "symptoms"], [3901, 3905, "symptoms"], [4306, 4323, "neg_symptoms"], [4415, 4437, "symptoms"], [4497, 4512, "symptoms"], [4520, 4524, "symptoms"], [4579, 4597, "symptoms"], [4767, 4771, "symptoms"], [4815, 4838, "symptoms"], [4917, 4921, "symptoms"], [5102, 5107, "symptoms"], [5257, 5268, "symptoms"], [5283, 5300, "symptoms"], [5301, 5309, "neg_symptoms"], [5311, 5319, "neg_symptoms"], [5344, 5355, "symptoms"], [5361, 5384, "symptoms"], [5385, 5389, "symptoms"], [5404, 5412, "symptoms"], [5414, 5444, "symptoms"], [5458, 5470, "symptoms"], [5472, 5482, "symptoms"], [5510, 5529, "symptoms"], [5538, 5549, "neg_symptoms"], [5551, 5563, "symptoms"], [5565, 5572, "symptoms"], [5574, 5583, "symptoms"], [5591, 5596, "symptoms"], [5617, 5622, "symptoms"], [5627, 5635, "neg_symptoms"], [5661, 5669, "symptoms"], [5706, 5713, "neg_symptoms"], [5715, 5724, "neg_symptoms"], [5726, 5743, "symptoms"], [5788, 5806, "symptoms"], [5807, 5811, "symptoms"], [5858, 5872, "symptoms"], [5881, 5887, "symptoms"], [5889, 5915, "symptoms"], [5930, 5934, "symptoms"], [5956, 5963, "symptoms"], [5984, 5992, "symptoms"], [6028, 6037, "neg_symptoms"], [6053, 6061, "symptoms"], [6064, 6071, "symptoms"], [6073, 6080, "neg_symptoms"], [6082, 6089, "symptoms"], [6131, 6137, "symptoms"], [6164, 6181, "symptoms"], [6227, 6261, "neg_symptoms"], [6263, 6273, "symptoms"], [6275, 6285, "symptoms"], [6287, 6295, "symptoms"], [6329, 6337, "symptoms"], [6339, 6359, "symptoms"], [6404, 6409, "neg_symptoms"], [6546, 6560, "symptoms"], [6600, 6610, "symptoms"], [6635, 6641, "symptoms"], [6646, 6654, "symptoms"], [6710, 6722, "symptoms"], [6776, 6781, "symptoms"], [6808, 6819, "symptoms"], [6834, 6854, "symptoms"], [6899, 6906, "neg_symptoms"], [6932, 6943, "symptoms"], [6948, 6955, "neg_symptoms"], [7035, 7043, "symptoms"], [7055, 7062, "symptoms"], [7237, 7250, "symptoms"], [7374, 7384, "neg_symptoms"], [7456, 7472, "symptoms"], [7477, 7485, "neg_symptoms"], [7494, 7512, "neg_symptoms"], [7590, 7596, "neg_symptoms"], [7617, 7623, "neg_symptoms"], [7636, 7643, "neg_symptoms"], [7662, 7665, "neg_symptoms"], [7670, 7682, "neg_symptoms"], [7694, 7721, "neg_symptoms"], [7800, 7812, "symptoms"], [7816, 7825, "symptoms"], [7830, 7835, "neg_symptoms"], [7874, 7878, "symptoms"], [7923, 7945, "symptoms"], [7948, 7972, "symptoms"], [7993, 8013, "neg_symptoms"], [8084, 8103, "symptoms"], [8153, 8165, "neg_symptoms"], [8182, 8188, "neg_symptoms"], [8190, 8197, "neg_symptoms"], [8208, 8229, "symptoms"], [8271, 8306, "neg_symptoms"], [8316, 8320, "neg_symptoms"], [8322, 8329, "symptoms"], [8344, 8364, "neg_symptoms"], [8368, 8378, "neg_symptoms"], [8414, 8422, "symptoms"], [8430, 8456, "neg_symptoms"], [8567, 8602, "neg_symptoms"], [8607, 8615, "neg_symptoms"], [8617, 8625, "neg_symptoms"], [8668, 8672, "symptoms"], [8775, 8784, "symptoms"], [8786, 8794, "symptoms"], [8806, 8811, "symptoms"], [8901, 8915, "symptoms"], [8974, 8987, "symptoms"], [8993, 9001, "symptoms"], [9006, 9013, "symptoms"], [9066, 9072, "symptoms"], [9131, 9140, "neg_symptoms"], [9176, 9180, "symptoms"], [9453, 9461, "neg_symptoms"], [9586, 9597, "symptoms"], [9640, 9650, "symptoms"], [9822, 9832, "symptoms"], [9844, 9855, "neg_symptoms"], [10103, 10110, "symptoms"], [10139, 10153, "symptoms"], [10155, 10161, "symptoms"], [10163, 10181, "symptoms"], [10254, 10265, "symptoms"], [10357, 10363, "symptoms"], [10405, 10421, "hx_symptoms"], [10422, 10430, "symptoms"], [10465, 10474, "symptoms"], [10521, 10528, "symptoms"], [10553, 10558, "symptoms"], [10666, 10671, "symptoms"], [10681, 10686, "symptoms"], [10894, 10914, "symptoms"], [10916, 10946, "symptoms"], [11023, 11037, "symptoms"], [11043, 11073, "symptoms"], [11102, 11133, "symptoms"], [11160, 11191, "symptoms"], [11198, 11202, "symptoms"], [11235, 11247, "symptoms"], [11458, 11469, "symptoms"], [11503, 11513, "symptoms"], [11525, 11539, "symptoms"], [11899, 11911, "symptoms"], [11979, 12000, "symptoms"], [12002, 12010, "symptoms"], [12036, 12047, "symptoms"], [12245, 12257, "symptoms"], [12330, 12342, "symptoms"], [12344, 12349, "symptoms"], [12351, 12357, "symptoms"], [12369, 12393, "symptoms"], [12394, 12402, "symptoms"], [12604, 12614, "symptoms"], [12760, 12772, "symptoms"], [12895, 12907, "symptoms"], [12927, 12938, "symptoms"], [13280, 13295, "symptoms"], [13379, 13388, "symptoms"], [14263, 14269, "symptoms"], [14277, 14289, "symptoms"], [14473, 14494, "symptoms"], [14529, 14535, "symptoms"], [14587, 14617, "symptoms"], [14675, 14687, "symptoms"], [14867, 14878, "symptoms"], [14972, 14979, "symptoms"], [15031, 15044, "symptoms"], [15083, 15093, "symptoms"], [15120, 15132, "symptoms"], [15165, 15192, "symptoms"], [15194, 15200, "symptoms"], [15202, 15210, "symptoms"], [15216, 15228, "symptoms"], [15232, 15249, "symptoms"], [15259, 15266, "symptoms"], [15284, 15304, "symptoms"], [15327, 15331, "symptoms"], [15386, 15401, "symptoms"], [15416, 15425, "symptoms"], [15469, 15480, "symptoms"], [15524, 15535, "symptoms"], [15555, 15576, "symptoms"], [15681, 15692, "symptoms"], [15734, 15744, "symptoms"], [15845, 15856, "symptoms"], [15871, 15899, "symptoms"], [15965, 15976, "symptoms"], [16048, 16061, "neg_symptoms"], [16071, 16079, "symptoms"], [16122, 16132, "symptoms"], [16235, 16243, "symptoms"], [16379, 16387, "symptoms"], [16460, 16474, "symptoms"], [16487, 16495, "symptoms"], [16544, 16573, "symptoms"], [16584, 16593, "symptoms"], [16595, 16604, "symptoms"], [16613, 16626, "symptoms"], [16672, 16680, "symptoms"], [16706, 16716, "symptoms"], [16803, 16811, "symptoms"], [16844, 16852, "symptoms"], [16858, 16889, "symptoms"], [16891, 16901, "symptoms"], [16923, 16931, "symptoms"], [16951, 16959, "symptoms"], [17032, 17068, "symptoms"], [17137, 17156, "symptoms"], [17165, 17169, "symptoms"], [17279, 17287, "symptoms"], [17316, 17324, "symptoms"], [17330, 17350, "symptoms"], [17375, 17383, "symptoms"], [17424, 17432, "symptoms"], [17531, 17569, "symptoms"], [17616, 17629, "symptoms"], [17644, 17652, "symptoms"], [17716, 17724, "symptoms"], [17767, 17777, "symptoms"], [17782, 17790, "symptoms"], [17845, 17866, "symptoms"], [17868, 17872, "symptoms"], [17921, 17933, "symptoms"], [18025, 18044, "symptoms"], [18054, 18068, "symptoms"], [18080, 18094, "symptoms"], [18136, 18144, "symptoms"], [18176, 18190, "symptoms"], [18193, 18211, "symptoms"], [18524, 18543, "symptoms"], [18684, 18727, "symptoms"], [18783, 18793, "symptoms"], [19043, 19057, "symptoms"], [19285, 19299, "symptoms"], [19371, 19415, "symptoms"], [19627, 19658, "symptoms"], [19704, 19726, "symptoms"]]}
`
</details>

### Environment
---------
doccano docker image

**Comment by aam1r** [comment]
Does the following git patch help?

```
diff --git a/frontend/components/molecules/EntityItem.vue b/frontend/components/molecules/EntityItem.vue
index cf7e805..4179ae1 100644
--- a/frontend/components/molecules/EntityItem.vue
+++ b/frontend/components/molecules/EntityItem.vue
@@ -119,6 +119,7 @@ export default {
   flex-wrap: wrap;
   align-items: center;
   padding: 2px 2px 0px 6px;
+  white-space: pre;
 }
 .highlight.bottom .highlight__content:after {
   content: " ";
diff --git a/frontend/components/organisms/annotation/EntityItemBox.vue b/frontend/components/organisms/annotation/EntityItemBox.vue
index c6460eb..5d6d7f7 100644
--- a/frontend/components/organisms/annotation/EntityItemBox.vue
+++ b/frontend/components/organisms/annotation/EntityItemBox.vue
@@ -224,11 +224,18 @@ export default {
   align-items: flex-start;
 }
 .highlight-container {
-  line-height: 42px!important;
+  font-family: monospace !important;
+  font-size: 15px !important;
+  font-smoothing: auto;
+  -webkit-font-smoothing: auto !important;
+  line-height: 22px!important;
   display: flex;
   flex-wrap: wrap;
   white-space: pre-wrap;
-  cursor: default;
+  cursor: text;
+}
+.theme--light .highlight-container {
+  color: black;
 }
 .highlight-container.highlight-container--bottom-labels .highlight.bottom {
   margin-top: 6px;
```

You can save that file as `patch.diff` then run `git apply patch.diff`.

**Comment by DSLituiev** [comment]
@aam1r  that destroyed newlines ;(

**Comment by DSLituiev** [comment]
actually after that patch, I am getting old interface (w/o underline label)

**Comment by Hironsan** [comment]
The latest version looks fine. Please update.

![image](https://user-images.githubusercontent.com/6737785/79038051-4d379d00-7c11-11ea-93ee-4fddfb5537b7.png)
