### ISSUE TITLE
Google authentication on frontend

### ISSUE THREAD

**Issue by forsoff** [doccano/doccano#694]
Hello, I'm completely new to Django, Docker and Nuxt.js
Firstly, many thanks to the creators of this project!

As I understood, you have 2 versions of website - the first is initial on django with html pages and the second is on nuxt.js. I wanted to add Google OAuth to social-auth, but then realized that it can't be represented on nuxt.js frontend. Am I right and should use django web version for that?
If so, how can I avoid building and launching of frontend service?

**Comment by aam1r** [comment]
Please see https://github.com/doccano/doccano/issues/620

**Comment by forsoff** [comment]
Yes, I've seen it but the question is whether it would be available on frontend. For now I don't see any login options (Azure, GitHub) in LoginForm

**Comment by setu4993** [comment]
@forsoff : My understanding is that they'd be enabled on the login form IF the env variables have been set for those cases. My attempt at adding Google as an OAuth provider is #676.

**Comment by forsoff** [comment]
@setu4993 Yes, I've added env vars. My concern is that it's not visible on frontend. As I understood they have two login forms: old one (django), new one (nuxt.js). So, there's no option of custom log in in a new one. I've added Google Auth similar to yours, but now I'm experiencing issues of deploying it. So, I want to drop frontend at all, but don't know how to do that.

**Comment by setu4993** [comment]
@forsoff : Based on my understanding, there are 2 versions. The older version that can be served through a [single Docker container](https://github.com/doccano/doccano/blob/master/Dockerfile), and another that separates the frontend and backend Docker containers.

If you use the single container setup, you could either fork the repo and modify the container to include env vars or SSH into the container and have the env vars to be sourced on container boot, and restart. Also, do remember you will need to make changes to the `login.html` and `views.py`.

**Comment by forsoff** [comment]
@setu4993 Thank you very much. Setting up via Dockerfile gave me exactly what I needed.

**Comment by setu4993** [comment]
@forsoff : Awesome, glad it helped :).
