### ISSUE TITLE
Doccano bug? Also missing webpack-stats.json

### ISSUE THREAD

**Issue by oscare2** [doccano/doccano#695]
Hi! First off, I'm new to this program and have never installed anything like it before. I successfully managed to set up a server by running npm start through the frontend folder. Two things are strange when I try to use doccano: 
1. I can log in with any credentials
2. I cannot seem to create new projects (see the picture in the link https://prnt.sc/rzctna).  My client does not look the same as the one they are displaying on the video.
(Worth noticing too is that if I press the button "Start Annotation", I always end up at the same page which leads me to an unusable page)
Screenshot 1: https://prnt.sc/rzctna

ALSO: When I try to run the server through "python manage.py runserver", this happens when I open the server: https://prnt.sc/rzczqn

Screenshot 2: https://prnt.sc/rzczqn
```



Your Environment: virtualenv env (doccano-fresh?)
---------
<!-- Include details of your environment.-->
*   Operating System: Windows 10
*   Python Version Used: 3.8.2
*   When you install doccano: 4/13/2020
*   How did you install doccano (Heroku button etc): npm start through frontend folder

**Comment by icoxfog417** [comment]
Thank you for your using doccano. Did you try Docker version? If you are new to Python, I recommend this type of install.

https://github.com/doccano/doccano#docker-compose

**Comment by oscare2** [comment]
> Thank you for your using doccano. Did you try Docker version? If you are new to Python, I recommend this type of install.
> 
> https://github.com/doccano/doccano#docker-compose

I've tried installing with the Docker version, when I inserted the following command: docker run -d --name doccano -p 8000:80 chakkiworks/doccano I got this error: docker: Error response from daemon: failed to start service utility VM (createreadwrite): hcsshim::CreateComputeSystem. I have looked for solutions on this error but none seem to work, my Hyper-V is running as it should according to Services.

**Comment by icoxfog417** [comment]
It seems to be your environment problem that fails to use Docker. Please confirm the working Docker correctly after that, re-try running the doccano.
