### ISSUE TITLE
Admin lost all projects after role mapping.

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#696]
How to reproduce the behaviour
---------
Hi sir,

I am trying to add annotators to project but after this step admin lost everything.

I follow below mentioned steps.

1. I  created  a project in doccano project page using **create project** .
2. Then created  new user or annotator in admin page using **add user** and gave only active and staff status permissions to that user.
3. I also created role in admin page with **annotator** name.
4. And then create  role map  using **add role mapping** for user with role name for a specific project and then logout from admin page.
5. After i login to doccano page using admin credentials. There is no projects  in **http://xx.xxx.xx.xxx:xxxx/projects/**   and also no **create project** button at the top of the project list.
6. I also observed one this , before role mapping  **http://xx.xxx.xx.xxx:xxxx/projects/**  contain some welcome message like **HELLO,Admin.** but after role mapping that becomes like **HELLO, .** , Admin replaced with empty string.
7. And one more thing i can able to access and annotate project from **http://xx.xxx.xx.xxx:xxxx/projects/4/** here 4 is the project_id but  in this link **http://xx.xxx.xx.xxx:xxxx/projects/** number of projects are zero.

Before adding annotators , i have 4 projects in **http://xx.xxx.xx.xxx:xxxx/projects/** 

Please anyone suggest me whatever steps i have to follow or how  to fix this problem.

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: python 3.6
*   When you install doccano: February  2020
*   How did you install doccano (Heroku button etc): git clone + install from source

**Comment by sharmila-polamuri** [comment]
Please help me anyone , how to fix this problem ?

**Comment by icoxfog417** [comment]
maybe related to #723
