### ISSUE TITLE
How do I view someone's annotation and approve/reject them?

### ISSUE THREAD

**Issue by aam1r** [doccano/doccano#697]
I am using the latest version of doccano (the Vue JS frontend).

A few of my colleagues did some annotations. I am the `admin`, they have the `annotation` permission.

As an `admin`, how do I visually see someone else's annotations and approve/deny them?

**Comment by aam1r** [comment]
Related: https://github.com/doccano/doccano/issues/703

**Comment by icoxfog417** [comment]
merge to #703
