### ISSUE TITLE
Compose fails in Fedora 31

### ISSUE THREAD

**Issue by petasis** [doccano/doccano#700]
Hi all,

I am following the instructions on Fedora 31:
```bash
$ git clone https://github.com/doccano/doccano.git
$ cd doccano
$ podman-compose -f docker-compose.prod.yml up
```

The containers seem to build and run, however the nginx container returns only status 500 (internal server error). And I have the feeling that its /var/www folder is empty (I cannot start a bash in the container).

How to reproduce the problem
---------

```bash
$ git clone https://github.com/doccano/doccano.git
$ cd doccano
$ podman-compose -f docker-compose.prod.yml up

...

Starting django
[2020-04-16 14:44:16 +0000] [66] [INFO] Starting gunicorn 19.9.0
[2020-04-16 14:44:16 +0000] [66] [INFO] Listening at: http://0.0.0.0:8000 (66)
[2020-04-16 14:44:16 +0000] [66] [INFO] Using worker: sync
[2020-04-16 14:44:16 +0000] [69] [INFO] Booting worker with pid: 69
2020/04/16 15:51:52 [error] 2#2: *1 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 10.88.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:36002"
10.88.0.1 - - [16/Apr/2020:15:51:52 +0000] "GET / HTTP/1.1" 500 170 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0" "-"
```

Your Environment
---------

*   Operating System: Fedora 31
*   Python Version Used: What docker file chose (python3.7-dev (3.7.3-2+deb10u1))
*   When you install doccano: 15/16-04-2020
*   How did you install doccano (Heroku button etc): docker-compose (podman-compse)

**Comment by petasis** [comment]
[compose.log](https://github.com/doccano/doccano/files/4488372/compose.log)

This is the log of podman-compose.

**Comment by Hironsan** [comment]
I set up a Fedora 31 instance and ran the containers using `docker-compose`. There is no error. While when I ran the containers using `podman-compose`, I got the error. Therefore, I think the problem is caused by `podman-compose`.

If you don't mind, please use `docker-compose` instead of `podman-compose`.

**Comment by petasis** [comment]
Thank you very much for your quick response. In the man time, I am using the single container version, seems to work with podman. Although it took me a while to make it work with a proxy_pass in nginx, using a url prefix.

**Comment by petasis** [comment]
Also, I opened an issue in podman-compose: https://github.com/containers/podman-compose/issues/150
