### ISSUE TITLE
Long annotations brakes the container

### ISSUE THREAD

**Issue by edgarascom** [doccano/doccano#702]
If you select long chunk of text and tag it, the tag block will break out through content container, instead of breaking to another line.

**Comment by icoxfog417** [comment]
Could you tell us the procedure to reproduce and your environment information?

**Comment by edgarascom** [comment]
Mac, safari.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/725324/79515264-778dbe00-8048-11ea-8df6-d64f23efee09.png">

**Comment by aam1r** [comment]
@edgarascom 

There's actually a new version of doccano that hasn't been published to Docker yet (I think). Try doing `git clone` of master and running that. It's an entirely new UI.

**Comment by Hironsan** [comment]
Please use `docker-compose` version. It supports long annotations:

![image](https://user-images.githubusercontent.com/6737785/80430335-4c00b280-8929-11ea-9c10-0a57dca88624.png)
