### ISSUE TITLE
Allow the annotation approver to edit/remove existing annotations

### ISSUE THREAD

**Issue by deathg0d** [doccano/doccano#703]
How to reproduce the behavior
---------
I have set couple of users as `annotation_approver` for sequence labeling. However, when an approver starts reviewing annotations, they cannot see what tags other users have created (even the admin cannot see) by default. They have to press the ✖️ button first and only then annotations from other users are visible. But now even though they can see the annotations after pressing ✖️, they cannot delete them, shows 403 error (only admins can delete annotations).

Edit: I have tried to add individual labeling permissions from the `admin page > users > user page`, still no change

Your Environment
---------
*   Operating System: MacOS Mojave
*   Python Version Used: 3
*   When you install doccano: April 8 (a guess)
*   How did you install doccano (Heroku button etc): docker

**Comment by deathg0d** [comment]
Okay so the first issue was due to collaboration being turned off. However, if I turn it on everyone can see each other's tags. Wouldn't it make sense to show all tags by default to approvers and admins because they are the ones cleaning other peoples' inputs?

My second issue - approver not being able to remove tags is still unsolved. Any help is appreciated. Thank you.

**Comment by icoxfog417** [comment]
related: #531
