### ISSUE TITLE
Text classification: make labels exclusive and allow annotation by several users?

### ISSUE THREAD

**Issue by johann-petrak** [doccano/doccano#705]
I have set up a text classification project but I do not understand how to configure to rather basic things:

* how to not allow an annotator to pick more than one label. I have defined two labels which show up above the text in the annotation interface and a user can select either or both. However since this is not multilabel classification, I would like that only one can be selected.
* how does annotating the same document by different users work? I tested this using different users and I only get one of the annotations by one user in the exported data, even though two different users have annotated the same document in two different ways. Should this work?

**Comment by Hironsan** [comment]
> how to not allow an annotator to pick more than one label. I have defined two labels which show up above the text in the annotation interface and a user can select either or both. However since this is not multilabel classification, I would like that only one can be selected.

As of now, doccano hasn't supported the single label. But it's easy to support the single label. From the point view of the frontend, just remove the following line(`multiple` attribute in [MultiClassClassification.vue](https://github.com/doccano/doccano/blob/master/frontend/components/organisms/annotation/MultiClassClassification.vue#L10)):

https://github.com/doccano/doccano/blob/c31dd82c31f38f0398b2699d3303b4d676201106/frontend/components/organisms/annotation/MultiClassClassification.vue#L10

**Comment by johann-petrak** [comment]
Thanks that works! 
Would be great to be able to configure this in the GUI or have it mention in some documentation somewhere.

**Comment by meetnileshhere** [comment]
Sorry but when I removed the Multiple attribute from the mentioned file, I get 404 error. Do we need to anything else to stop multi-label classification? Thanks in advance

**Comment by cgill95** [comment]
> * how does annotating the same document by different users work? I tested this using different users and I only get one of the annotations by one user in the exported data, even though two different users have annotated the same document in two different ways. Should this work?

this does work for me. the exported file contains multiple lines with different labels by the users (this is for CSV format) or if you choose JSON export you'll get an array of multiple labels for one text. I tested this in a document classification task with both sharing and not sharing of annotations.

**Comment by johann-petrak** [comment]
Why has this been closed, as far as I can see it is still not possible to configure a text classification project from within the tool so that only one label is allowed, i.e. prevent picking multiple labels?
