### ISSUE TITLE
Why is there a file size restriction to just 1 MB?

### ISSUE THREAD

**Issue by johann-petrak** [doccano/doccano#706]
When I use docker-compose from the latest master version of doccano and when I try to import a JSONL file, I get the error message "File size should be less than 1 MB" and I cannot upload my file.
Why does this restriction exist?

I previously ran the docker version of doccano and there it was possible to import my file without problems. 

Is there a configuration option somewhere to disable this limitation?

**Comment by kuraga** [comment]
Duplicate of #575, #514.

**Comment by johann-petrak** [comment]
Thank you for those pointers to other issues!

#575 mentions a work-around by modifying some constant deep in the code which I think is not a solution and does not answer the question why such a small limit is the default. Also there is a report that the workaround did not fix the problem for the reporter.

#514 has been merged into #521 which seems to be about documenting the limitation but not telling why the upload size is so tiny. 

Ideally this should be configurable in a config file (as opposed to changing code) and the config option should be documented (unless there is an important reason why the upload has to be so small in which case I think it would not really be usable for some users).

**Comment by kuraga** [comment]
> Ideally this should be configurable
Yes, I also think so.

I ask you to fill an issue via [Feature Request template](https://github.com/doccano/doccano/issues/new?template=04-request.md) and close this question. It will be more effectively.

**Comment by johann-petrak** [comment]
OK, created #708
