### ISSUE TITLE
Deploy with Docker Compose can't import file properly

### ISSUE THREAD

**Issue by tamio96** [doccano/doccano#707]
There are 2 issues:
1) When deploying the app with `docker-compose -f docker-compose.prod.yml up`, I realized that the UI is different from demo and I could only import file less than 1mb. I think there must be a bug or the docker is not updated.

2) When deploying the app with 
`docker pull doccano/doccano
docker container create --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 doccano/doccano
`
I couldn't import large file (250mb, has 3m samples) even though there is no error in file. Import with API also very slow, 100k samples takes 40m.

**Comment by icoxfog417** [comment]
* Demo version is the old one, `docker-compose` version is the latest.
* 1mb limit is the default behavior ( #708  )
* Upload speed also depends on your environment. Please let us know your machine spec to classify an application (doccano) issue and a hardware issue.

**Comment by tamio96** [comment]
I use Ubuntu 18.04, deploy with docker container (old version)
I assume that Doccano uploads quite slow because It uploads sample by sample, instead of by batches.

**Comment by icoxfog417** [comment]
Please use the latest version. [Bulk insert is already supported](https://github.com/doccano/doccano/commit/95f5c79a1d97630f9afbcbe2d3906ed4e0f24777).
