### ISSUE TITLE
Make maximum file upload (import) size configurable

### ISSUE THREAD

**Issue by johann-petrak** [doccano/doccano#708]
Currently there is a hard coded upload size limit of 1MB.

This should be easily configurable and the config option should be documented somewhere.

NOTE: see #575 for a possible work-around.

**Comment by aam1r** [comment]
Just a heads up: if you're going to make the file size substantially large, you will also need to update `client_max_body_size` to avoid getting an Nginx upload error

https://www.daveperrett.com/articles/2009/11/18/nginx-error-413-request-entity-too-large/

**Comment by tamio96** [comment]
#575 don't works, even though I updated nginx.conf like @aam1r says

**Comment by icoxfog417** [comment]
related : #521

**Comment by br-dr3** [comment]
Any update on that?

**Comment by ricjhill** [comment]
Why was the 1MB limit introduced?

**Comment by Hironsan** [comment]
Now we can upload file up to 100MB:

- https://github.com/doccano/doccano/pull/1175
