### ISSUE TITLE
doccano_frontend_1 exited with code 0

### ISSUE THREAD

**Issue by swicaksono** [doccano/doccano#710]
How to reproduce the behaviour
---------
I tried to run the doccano using docker-compose, and I made a modification on the nginx listen port to 8181, and change the docker-compose.prod.yaml on nginx ports service to 
```nginx:
    build: ./nginx
    volumes:
      - www:/var/www/html:ro
      - static_volume:/static
    ports:
      - 8181:8181
```

After I run the docker compose, it returns nginx 500 Internal Server Error when I access the web. I check the logs, I think there are some issues on the front-end and or the nginx image.
This is the error logs,
```
doccano_frontend_1 exited with code 0
```
and
```
nginx_1     | 2020/04/21 09:38:16 [crit] 8#8: *2 stat() "/var/www/html/index.html" failed (13: Permission denied), client: X.X.X.X, server: , request: "GET /favicon.ico HTTP/1.1", host: "X.X.X.X:8181", referrer: "http://X.X.X.X:8181/"
nginx_1     | 2020/04/21 09:38:16 [error] 8#8: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 192.168.20.116, server: , request: "GET /favicon.ico HTTP/1.1", host: "X.X.X.X:8181", referrer: "http://X.X.X.X:8181/"
```

Any solution to solved this?
Many thanks!

My Environment
---------
*   Operating System: Ubuntu 16.04
*   Python Version Used: 3.7
*   When you install doccano: April 9, 2020
*   How did you install doccano (Heroku button etc): docker-compose

**Comment by VitaliyPetroff** [comment]
It's normal, just skip it.

**Comment by swicaksono** [comment]
@VitaliyPetroff any ideas how to solved on the 2nd issues? Why nginx return that way? Because everytime I acces the web it returns nginx 500 Internal Server Error.

**Comment by VitaliyPetroff** [comment]
Sorry man, I'm newbie as you.
But what type of running app do you use - Docker image or Docker Compose?

**Comment by swicaksono** [comment]
Actually I have asked on this #679 but I still couldn't figure it out. Before this I successfully installed and everything works fine. But then after all of the images and volumes is erased, I tried to install by run using docker-compose again but I got that error.

**Comment by tamio96** [comment]
`    ports:
      - 8181:80`
Only change the first number.

Port 8181 in your localhost will be forwarded to port 80 of nginx images

**Comment by swicaksono** [comment]
@tamio96 I did that. I set nginx listening on port 80, and I using port 8181 to be forwarded to port 80 of nginx images. But still got the following error:

```
nginx_1     | 2020/04/21 09:38:16 [crit] 8#8: *2 stat() "/var/www/html/index.html" failed (13: Permission denied), client: X.X.X.X, server: , request: "GET /favicon.ico HTTP/1.1", host: "X.X.X.X:8181", referrer: "http://X.X.X.X:8181/"
nginx_1     | 2020/04/21 09:38:16 [error] 8#8: *2 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 192.168.20.116, server: , request: "GET /favicon.ico HTTP/1.1", host: "X.X.X.X:8181", referrer: "http://X.X.X.X:8181/"
```

**Comment by swicaksono** [comment]
I inspect the IPv4Address on doccano_network-frontend, the nginx container been allotted to 172.20.0.3.  I checked by curl from inside doccano_backend container, I still get the same error. Is this the problem on the nginx config? I'm missing something here.
```
# curl 172.20.0.3:80
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
# 
```

**Comment by icoxfog417** [comment]
#704 will be helpful to change the port number.

**Comment by swicaksono** [comment]
@icoxfog417 which port number??

**Comment by swicaksono** [comment]
or should I change the label [www volumes](docker-compose.prod.yml) in the nginx service to :z instead :ro based on the discussion [here](https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker)?

**Comment by tamio96** [comment]
Try to build and then up it again to update docker
`docker-compose -f docker-compose.prod.yml up`

**Comment by swicaksono** [comment]
@tamio96 I did that, even I prune all of images and volumes, but still I got the error. :joy:

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/issues/471 is the answer.
