### ISSUE TITLE
How to use User SIGNUP in Compose Production version?

### ISSUE THREAD

**Issue by VitaliyPetroff** [doccano/doccano#711]
How to reproduce the behaviour
---------
I use Docker Compose version with Prod environment (It's important! Cause in old Docker Image version it's working).
I know about ALLOW_SIGNUP: "True" options.

But I have now any ability to signup on frontend. Only sign in.

Is it enable to use SIGNUP and how to switch it on?

**Comment by icoxfog417** [comment]
Thank you for reporting the issue. Do you mean "ALLOW_SIGNUP" option does not work correctly?

**Comment by VitaliyPetroff** [comment]
For me it does not work in any case.

**Comment by VitaliyPetroff** [comment]
Any Ideas how to get signup in frontend (vue), also with OAuth?

**Comment by Hironsan** [comment]
Docker Compose version hasn't supported signup yet. If you want to add some users, please use admin site:
- [FAQ](https://github.com/doccano/doccano/blob/master/docs/faq.md)

**Comment by midnightradio** [comment]
> Docker Compose version hasn't supported signup yet. If you want to add some users, please use admin site:
> 
> * [FAQ](https://github.com/doccano/doccano/blob/master/docs/faq.md)

SIGNUP is for a user for registering himself, while adding a user with django admin page is only for admins. Admin page cannot be a workaround for this issue and I think this issue should be remain open until frontend works well with signup option.
