### ISSUE TITLE
Login found——Error: Request failed with status code 500

### ISSUE THREAD

**Issue by zhanwen** [doccano/doccano#713]
step1:
run: `docker-compose -f docker-compose.prod.yml up`
![image](https://user-images.githubusercontent.com/11382789/80170730-3c2c5a00-861b-11ea-882a-995a8dccef4f.png)

step2: login
username:admin
password:password
![image](https://user-images.githubusercontent.com/11382789/80170770-57976500-861b-11ea-8871-7285777b943b.png)

then remind me status code 500.
![image](https://user-images.githubusercontent.com/11382789/80170803-6847db00-861b-11ea-9301-9e714fee2202.png)

terminate response.
![image](https://user-images.githubusercontent.com/11382789/80170843-7b5aab00-861b-11ea-91aa-4ae47d1cbdb5.png)

Then can create dataset and operate other. but can't annotation, i see Home->step5. annotate the dataset, but now i try annotate found not operate.
![image](https://user-images.githubusercontent.com/11382789/80171189-46028d00-861c-11ea-8fc9-050ac675907b.png)

**Comment by icoxfog417** [comment]
Please provide your environment information following to the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/01-question.md).

**Comment by greenspray9** [comment]
I also have the same issue

**Comment by greenspray9** [comment]
Steps to reproduce :

Login as admin -> Create project -> Logout -> Try to login as admin -> Pop up with status 500

I am running this code in Ubuntu via ` docker-compose -f docker-compose.dev.yml up`

**Comment by Hironsan** [comment]
It's a lack of information. Please show me network request/response by using chrome/safari developer tools.

**Comment by zephyrous** [comment]
I face similar issues. I was logged in as admin, created a project, and logged out. 
Then I logged in as a superuser, but I got the status 500 popup:

```
Request Method: GET
Status Code: 500 Internal Server Error
```

Then I try to create a project and I receive a 403 error:

```
HTTP 403 Forbidden
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Authentication credentials were not provided."
}
```

**Comment by zhanwen** [comment]
@zephyrous @greenspray9 hello, I have solved it. shows step.
# need docker-compose command
`sudo apt install docker-compose`
# doccano images download：
`sudo docker pull chakkiworks/doccano`

# then exec,：
`sudo docker run -d --rm --name doccano \
  -e "ADMIN_USERNAME=admin" \
  -e "ADMIN_EMAIL=admin@example.com" \
  -e "ADMIN_PASSWORD=password" \
  -p 8000:8000 chakkiworks/doccano`
#### --rm exit delete images, note: data save

# chrome or safari input：
`http://127.0.0.1:8000/login/`
username：admin , password：password`

**Comment by zephyrous** [comment]
@zhanwen I was probably missing the --rm step. Will check, thanks!

**Comment by cmehak** [comment]
I am also facing same error, how to solve this issue as i am unable to annotate.I have windows OS and have docker running but error is coming : request failed with status code 500??? 
Please help

**Comment by zhanwen** [comment]
@cmehak please see: my above comment. windows 10 can use windowspower shell execute command.

**Comment by look4regev** [comment]
We are also facing the same issue, ran `docker-compose -f docker-compose.prod.yml up -d` on a Centos 7. No logs from the backend indicating on any issue. Perhaps it can be run with a debug mode to be able to trace the exception?

**Comment by pyxis777** [comment]
I am having the same problem as zhanwen and zephyrous  Using Ubuntu 18.04
Python Version 3.7.8
When you install doccano: September 22, 2020
How did you install doccano (Heroku button etc): docker-compose -f docker-compose.prod.yml up

I get 500 error when I use Firefox, Chrome

**Comment by MKatereggaExigent** [comment]
Was this issue fully resolved. I am running Debian 10 server and I installed doccano using: `docker-compose -f docker-compose.prod.yml up` . The login page loads fine and I can successfully login with `admin` and `password`. However, the 500 error still pops up. I am tried everything suggested above.

**Comment by mlussati** [comment]
I'm having the same problem can someone help me solve please? I receive status error 500 with the administrator user

**Comment by icoxfog417** [comment]
Please try to logout from the admin site after you change the password.

https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-change-users-or-admins-password

**Comment by martinezhermes** [comment]
Are there any users of this web app that have made it possible to run docker-compose as of 2021 without this error? I am talking latest commit, no fork, do different version, docker-compose as of 2021. How do you make this work?

clean computer, clean everything, IT DOES NOT WORK, error 500.

**Comment by Hironsan** [comment]
I have experienced it sometimes. But I can't reproduce it 100%.

I found the difference between 500 errors and no errors. When we meet the 500 error, The `Allow` header in the response is empty. If we replace `DEBUG: False` with `DEBUG: True` in `docker-compose.prod.yml`, the header won't be empty. But it's not a good solution for a production environment.

**Comment by Hironsan** [comment]
I found the cause. We need to remove `image` property from Project models and serializers.
