### ISSUE TITLE
Couldn't download whole dataset with API

### ISSUE THREAD

**Issue by tamio96** [doccano/doccano#715]
Currently restful API only allows to download 50 first samples of dataset instead of whole dataset. 
I tested with the UI of swagger and also with my code. It don't point to next batch of files so I could only get first batch (50 samples)

My env:
*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.7
*   When you install doccano: 21.04.2020
*   How did you install doccano (Heroku button etc): Docker compose

**Comment by kuraga** [comment]
What API HTTP request are you talking about?

**Comment by louisguitton** [comment]
Hi @tamio96 , 
the current restful API does allow for downloading the full dataset (I do that with my own python client).

```python
    def download_docs(self, project_id: int, download_format: str = "json") -> requests.Response:
        """
        download_format is either csv or json
        """
        data = {"q": download_format, "format": download_format}
        url = f"{self.entrypoint}/v1/projects/{project_id}/docs/download"
        response = self.client.get(url, params=data)
        return response
```

In this case, the entrypoint is the URL to your doccano server. You need to authenticate but it sounds you're already doing this since you're downloading 50 docs.

**Comment by tamio96** [comment]
Hi, thanks for your answer. It worked :)

**Comment by ChiLynn123** [comment]
> Hi @tamio96 ,
> the current restful API does allow for downloading the full dataset (I do that with my own python client).
> 
> ```python
>     def download_docs(self, project_id: int, download_format: str = "json") -> requests.Response:
>         """
>         download_format is either csv or json
>         """
>         data = {"q": download_format}
>         url = f"{self.entrypoint}/v1/projects/{project_id}/docs/download"
>         response = self.client.get(url, params=data)
>         return response
> ```
> 
> In this case, the entrypoint is the URL to your doccano server. You need to authenticate but it sounds you're already doing this since you're downloading 50 docs.

How to set the path of the download document? Thank you very much!
