### ISSUE TITLE
feature request: keyboard shortcut for approval button

### ISSUE THREAD

**Issue by mmisiewicz-yext** [doccano/doccano#718]
Feature description
---------
Hello! I'd like to request a keyboard shortcut for the approval button. Ideally pressing this key would also advance to the next item in the queue. 

I could implement this myself if there's a place to do it!

**Comment by Hironsan** [comment]
Solved in #980.

**Comment by maxtrem** [comment]
@Hironsan 
This does not work anymore since the last update (at least for me). I found the "enter" solution to work great. 
Assuming this was removed by accident,  would it be possible to add this functionality again?

Thanks!

**Comment by dpusat** [comment]
@Hironsan 
Hi - keyboard shortcut for approval isn't working for me as well. Has it been removed?

Thanks!

**Comment by Hironsan** [comment]
Oops!

**Comment by davidpomerenke** [comment]
I think it would be nice to have one key (perhaps enter) that marks the item as checked and at the same time moves to the next item.

(My use case is binary classification, which could be done with a single key press; but as I see it, I currently need 3 key presses in doccano: For selecting the label, for approving, and for moving to the next item. – Would be nice to cut that down to 2 key presses, or even one.)

Thansk for consideration!

**Comment by hermlon** [comment]
I implemented (a probably pretty quick and dirty) solution for ImageClassification which automatically marks the image as accepted and opens the next page after assigning a label. Having to press 3 buttons (hotkey for label, enter to accept, right arrow for next) when only one is required is ridiculous when labeling about 1000 pictures. 

https://github.com/hermlon/doccano/commit/6d11d3cd3b9d70733c59eac9b2416448949fc049
