### ISSUE TITLE
How to implement forgot password in the signin page

### ISSUE THREAD

**Issue by alokpredictly** [doccano/doccano#719]
In the sign-in page, there is no option for resetting the password. How can I implement resetting password for a user in the doccano tool.

Your Environment
---------

*   Operating System: Ubuntu 160.04
*   Python Version Used: Python 3.7
*   When you install doccano: 23rd April
*   How did you install doccano (Heroku button etc): from source

**Comment by icoxfog417** [comment]
Please reset the password from [Django admin site](https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-add-annotators).
