### ISSUE TITLE
Error uploading when text is whitespace

### ISSUE THREAD

**Issue by radkoff** [doccano/doccano#720]
Using JSON, if a dataset has a document with only whitespace text, it fails with "The file could not be uploaded. Maybe invalid format. Please check available formats carefully. "

Reproduce with any of these:
```
{"meta": {"foo": "bar"}, "text": "\n"}
{"meta": {"foo": "bar"}, "text": " "}
{"meta": {"foo": "bar"}, "text": ""}
```
They can be filtered out pre upload, but it was hard to figure this out since nothing more specific was in logs

*   Operating System: mac os
*   Python Version Used: 3.7
*   When you install doccano: Feb 6 '20
*   How did you install doccano (Heroku button etc): docker-compose

**Comment by radkoff** [comment]
I found another way to trigger this (I won't bother opening another issue unless you want me to)
A null-terminated string as text, eg `foo\u0000`

**Comment by icoxfog417** [comment]
doccano does not allow uploading the missing text data because can not annotate to these.
