### ISSUE TITLE
ERROR: Version in "./docker-compose.prod.yml" is unsupported

### ISSUE THREAD

**Issue by liuyixin-louis** [doccano/doccano#721]
How to reproduce the behaviour
---------

I install docker and docker-compose, and try to run this project:
`docker-compose -f docker-compose.prod.yml up`
However, I get this result:

> ERROR: Version in "./docker-compose.prod.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

Any help will be appreciated!!

Your Environment
---------

*   Operating System:Deepin
*   Python Version Used:3.7
*   When you install doccano:04/30
*   How did you install doccano (Heroku button etc):gitclone

**Comment by icoxfog417** [comment]
Please update your docker-compose as the error message suggests.

https://docs.docker.com/compose/install/

**Comment by mikkokotila** [comment]
> Please update your docker-compose as the error message suggests.

Updating does not resolve the issue.

**Comment by anurag-cser** [comment]
Same issue here.

System:
Centos 7

tried to update/remove versions. Didn't work. Did anyone try to run this locally?

**Comment by anurag-cser** [comment]
Solved the issue by changing the version to "3" instead of "3.x"
or "2" instead of "3.x" which ever works!
