### ISSUE TITLE
More comprehensive error message when login fails due to active django admin session

### ISSUE THREAD

**Issue by TobiasRoeddiger** [doccano/doccano#723]
Thank you very much for the great tool.

I spent a significant amount of time wondering why adding users and changing the admin password does not work. Whenever there is an active django admin session, logging in fails with "Incorrect username or password." 

I'd suggest changing this, e.g., with a reference to the admin page and the suggestion to logout whenever there is an ongoing admin session in the background.

Tobias

**Comment by icoxfog417** [comment]
Thank you for reporting the difficulty you faced. Could you please tell us about the reproducing procedure? 

1. You use Django admin site to add users or change passwords.
2. After that. you can't log in doccano unless you close the session of the Django admin site (close page or tab).

Are the above procedures correct?

**Comment by mmisiewicz-yext** [comment]
I have been able to reproduce this behavior by logging into the admin, and then attempting to log into the site via the /auth page. It seems that simply being logged in as the admin causes the error `Forbidden: /v1/auth-token` to appear in the logs. A procedure I can use to reproduce is:

1. log in to /admin
2. go to home
3. press sign in button
4. attempt to log in as same user, will fail with auth-token error. 

Logging out of the admin interface resolves the issue.

**Comment by TobiasRoeddiger** [comment]
Yes, @icoxfog417 that's correct, sorry for being a bit unclear in my initial description. @mmisiewicz-yext thanks for the more detailed steps to reproduce the problem.

**Comment by icoxfog417** [comment]
Thank you for the detail procedure! It seems to be difficult to solve because this behavior is caused by Django authentication system.  At first I update FAQ.

**Comment by kuraga** [comment]
> At first I update FAQ

:+1: 

@TobiasRoeddiger , also related: #545, #613, #667.

**Comment by mlussati** [comment]
How to solved status 500
