### ISSUE TITLE
chakki works doccano

### ISSUE THREAD

**Issue by leventm** [doccano/doccano#724]
Not able to login into chakki works with credentials - admin & password. Throwing an error as username or password to be incorrect

**Comment by icoxfog417** [comment]
chakki-works's doccano is the outdated version. Please use doccano/doccano repository one.

**Comment by leventm** [comment]
I am not able to login, throwing incorrect username and password error


Sent from Outlook Mobile


From: Takahiro Kubo <notifications@github.com>Sent: Friday, May 1, 2020, 4:23 AMTo: doccano/doccanoCc: leventm; AuthorSubject: Re: [doccano/doccano] chakki works doccano (#724)
chakki-works's doccano is the outdated version. Please use doccano/doccano repository one.

**Comment by leventm** [comment]
Hi, 


What are the system requirements on ubuntu for installing the doccano text annotation tool?  Outdated chakki works one had python 2.7+, django...

Kindly respond and help out.


Thanks

Mudassir


Sent from Outlook Mobile


From:  <mudassir@leventm.com>Sent: Friday, May 1, 2020, 9:34 PMTo: doccano/doccano; doccano/doccanoCc: AuthorSubject: Re: [doccano/doccano] chakki works doccano (#724)I am not able to login, throwing incorrect username and password error


Sent from Outlook Mobile


From: Takahiro Kubo <notifications@github.com>Sent: Friday, May 1, 2020, 4:23 AMTo: doccano/doccanoCc: leventm; AuthorSubject: Re: [doccano/doccano] chakki works doccano (#724)
chakki-works's doccano is the outdated version. Please use doccano/doccano repository one.

**Comment by kuraga** [comment]
@leventm , suggest to you to open a new issue.
