### ISSUE TITLE
feature request: unapproved/approved queries in filter dropdown

### ISSUE THREAD

**Issue by mmisiewicz-yext** [doccano/doccano#725]
Feature description
---------
This feature would allow the user to filter for documents that have or do not have approvals, much like the done/undone options that are currently there. Would be happy to implement myself if there's a place to add it! 

![image](https://user-images.githubusercontent.com/48600678/80725511-2d3d2000-8ad1-11ea-9f8c-ad10151812d6.png)

**Comment by kuraga** [comment]
@tusharmakkar08 , could you, please, help with PR here? :)

**Comment by icoxfog417** [comment]
merge to #505
