### ISSUE TITLE
[Question] Docker deployment is obsolete in doccano 1.x.x?

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#731]
@Hironsan ,

you removed `README.md`'s `Docker` part [some time ago]( https://github.com/doccano/doccano/commit/1be0986c7a9faa5cf24d5d91900bb0d1058ba49f#diff-04c6e90faac2675aa89e2176d2eec7d8R64).

Is Docker-based start forbidden now?

**Comment by icoxfog417** [comment]
The 1 issue should be 1 topic. Please raise another issue if you need to clarify the question after that.

**Comment by kuraga** [comment]
Also to the context:
We have https://hub.docker.com/u/doccano docker hub repository. Without mention in docs.

**Comment by icoxfog417** [comment]
related: #743

**Comment by setu4993** [comment]
Information about Docker deployment is in the [Getting Started](https://github.com/doccano/doccano/blob/master/docs/getting-started.md#docker) doc.

**Comment by kuraga** [comment]
@setu4993 , yes and it differs from [README.md](https://github.com/doccano/doccano/blob/master/README.md). Tat's issue about.

**Comment by kuraga** [comment]
@Hironsan So what's the answer?
