### ISSUE TITLE
[Documentation enhancement request] Production and development differences

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#733]
Propose to document production and development differences.

**Comment by icoxfog417** [comment]
Could you please clarify what should be mentioned about the difference between production and development?

**Comment by kuraga** [comment]
@icoxfog417 , we have `/docker-compose.prod.yml` and `/docker-compose.dev.yml`.

As of `README.md`, they turn on different ip+ports. But what else?

**Comment by kuraga** [comment]
@Hironsan So, what's the answer?

**Comment by andreizolotarev** [comment]
@kuraga I agree with you that README just states about 2 options: prod and dev, and it is unclear for newcomers (especially, for some who are not so familiar with prod stuff) what option they should use. So, I think the main difference is that in /docker-compose.prod.yml NGINX is added, am I right, @Hironsan ?

**Comment by kuraga** [comment]
@andreizolotarev as open issues are monitored only, I've created a new one: #810.
