### ISSUE TITLE
[Question] About `--force-rm` option

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#735]
`docker compose build` has [`--force-rm`](https://docs.docker.com/compose/reference/build/) option:
```
    --force-rm              Always remove intermediate containers.
```
Am I right: we could suggest users to use it, amn't I? (To avoid `doccano_frontend` container storing.)

**Comment by icoxfog417** [comment]
`--force-rm ` A is the option that depends on user preference.

**Comment by kuraga** [comment]
P.S. Also `--abort-on-container-exit` could be a good choice of user preference.
