### ISSUE TITLE
How to download the mapping between label ids and label text

### ISSUE THREAD

**Issue by at-a-run** [doccano/doccano#737]
When I export the labeled data after labeling for sequence classification I only see integer ids for label column. As I didn’t create the ids I can’t tell the mapping between label ids and label text. There doesn’t seem to be a simple way to export it. The django admin page has this information but I need it programmatically. How do I do this?

**Comment by icoxfog417** [comment]
Please refer to #295 and you can export label by #443 .

**Comment by at-a-run** [comment]
Solutions in neither seem to work.

Using the sql query I get nothing #295.
```
$ docker exec -i doccano /bin/bash - << EOF
> python -c '
> import sqlite3
> conn = sqlite3.connect("app/db.sqlite3")
> # Must replace your project_id here (e.g. from url in web app)
> rows = conn.execute("SELECT id, text FROM api_label;").fetchall()
> print({k: v for k,v in rows})
> '
> EOF
{}
```
On printing the last modified date for db.sqlite3 it seems it hasn't been updated in a long time.

```
$ docker exec -i doccano /bin/bash - << EOF
ls -latrh "app"
EOF

total 436K
drwxr-xr-x  2 doccano doccano 4.0K Apr 10 06:14 tools
-rw-r--r--  1 doccano doccano  950 Apr 10 06:14 requirements.txt
-rwxr-xr-x  1 doccano doccano  535 Apr 10 06:14 manage.py
drwxr-xr-x  2 doccano doccano 4.0K Apr 10 06:14 classifier
-rw-r--r--  1 doccano doccano    0 Apr 10 06:14 __init__.py
-rw-r--r--  1 doccano doccano  463 Apr 10 06:14 Dockerfile
-rw-r--r--  1 doccano doccano  126 Apr 10 06:14 .dockerignore
drwxr-xr-x  1 doccano doccano 4.0K Apr 10 06:29 app
drwxr-xr-x  1 doccano doccano 4.0K Apr 10 06:29 server
drwxr-xr-x  5 doccano doccano 4.0K Apr 10 06:29 api
drwxr-xr-x  6 doccano doccano 4.0K Apr 10 06:29 authentification
-rw-r--r--  1 doccano doccano 364K Apr 10 06:29 db.sqlite3
drwxr-xr-x  1 doccano doccano 4.0K Apr 10 06:32 .
drwxr-xr-x  2 doccano doccano 4.0K Apr 10 06:32 junitxml
drwxr-xr-x 11 doccano doccano 4.0K Apr 10 06:37 staticfiles
drwxr-xr-x  1 root    root    4.0K Apr 10 06:39 ..
```

Using #443 
While I see a button to create a new label, I don't see any button to export labels anywhere. Specifically, I don't see any such button to export labels on the following URL:
http://XXXXXXXX:8888/projects/4/labels/

I'm working on Document Classification. The example in #443 is for Sequence Labeling. i don't see any such button for a test project for Sequence Labeling either.

I have admin permission to everything. I used `docker pull doccano/doccano` and here is the version:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
doccano/doccano     latest              4f018c685336        3 weeks ago         459MB
```

**Comment by at-a-run** [comment]
Discovered a url to download the label text and ids http://ip-100-110-144-190.us-west-2.compute.internal:8888/v1/projects/4/labels?format=json

Ref:
- #624
- https://github.com/doccano/doccano/blob/master/app/api/urls.py

**Comment by at-a-run** [comment]
Discovered a url to download the label text and ids http://***:8888/v1/projects/4/labels?format=json

Ref:

#624
https://github.com/doccano/doccano/blob/master/app/api/urls.py

**Comment by nicoleserafino** [comment]
Does anyone know how to do this when deployed to Azure? I've connected to the Azure Database for PostgreSQL server but it doesn't seem to have anything in it. Is the data stored somewhere else? If so, how can I connect to it? Or can I update to the latest UI without clearing my current projects?
