### ISSUE TITLE
[Enhancement request] Using more descriptive error messages in UI

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#739]
We have `Incorrect name or password` in UI on 502 Bad gateway HTTP error.

**Comment by kuraga** [comment]
Merged to #521.

**Comment by icoxfog417** [comment]
This issue is a little ambiguous about what kind of error should be fixed. Please clarify what error should be descriptive in the issue title.

**Comment by kuraga** [comment]
If we have 502 HTTP error we have to display 502 error (as we do for 403, etc.).

Note: you can simulate similar behavior by disconnecting Ethernent cable before clicking "Login".

**Comment by icoxfog417** [comment]
We reopen this issue if someone needs this enhancement.

**Comment by kuraga** [comment]
Sorry but this is  really a bug. We have an incorrect error on sign in!
