### ISSUE TITLE
[Question] Production deployment issue with docker-compose.prod.yml 

### ISSUE THREAD

**Issue by meetnileshhere** [doccano/doccano#740]
I didn't find any notes in FAQ regarding issue in docker compose deployment of docker-compose.prod.yml 

How to reproduce the problem
***********************************
The error is thrown while running docker-compose.prod.yml , part of the log is shown below. The container doccano_frontend_1 is not attached but no error shown.

Successfully built cb5e9d5b64b1
Successfully tagged doccano_nginx:latest
Recreating doccano_frontend_1 ... done
Recreating doccano_postgres_1 ... done
Recreating doccano_backend_1  ... done
Recreating doccano_nginx_1    ... done
Attaching to doccano_frontend_1, doccano_postgres_1, doccano_backend_1, doccano_nginx_1
backend_1   | Making staticfiles
postgres_1  | 2020-05-04 14:17:37.180 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
postgres_1  | 2020-05-04 14:17:37.190 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2020-05-04 14:17:37.196 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2020-05-04 14:17:37.209 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2020-05-04 14:17:37.292 UTC [18] LOG:  database system was shut down at 2020-05-03 11:05:49 UTC
postgres_1  | 2020-05-04 14:17:37.419 UTC [1] LOG:  database system is ready to accept connections
doccano_frontend_1 exited with code 0
*************************************************************************************
The frontend container is not running, it fails without showing any error.

Your Environment
---------
*   Operating System: mac os mojave 10.14.6
*   Python Version Used: 3.6.10
*   When you install doccano: 4th May 2020
*   How did you install doccano (Heroku button etc): Docker compose

**Comment by icoxfog417** [comment]
`exited with code 0` is normal termination. Please refer #471 .
