### ISSUE TITLE
Heroku and Localhost have different interface

### ISSUE THREAD

**Issue by yemregundogmus** [doccano/doccano#741]
Hello, 

I want to use doccano in my project, but there is a part I do not understand. When I put Doccano on production on my computer, a very different interface comes up. When I do this by clicking on the heroku button, a different interface comes up. What is the reason for this and how can I copy the new interface to the heroku :)
Thanks

Environment
---------

*   Operating System: Windows10
*   Python Version Used: 3.7.4
*   When you install doccano: 1-2 day ago
*   How did you install doccano (Heroku button etc): clone

**Comment by icoxfog417** [comment]
Heroku version is the old version (We now try to deploy the latest version to Heroku). Please use the docker-compose version.

**Comment by yemregundogmus** [comment]
> Heroku version is the old version (We now try to deploy the latest version to Heroku). Please use the docker-compose version.

Thank you for reply,

When I try to deploy the heroku with dockor-compose, I also get the old version. This my first working experience with Docker so i think the problem stems from me

I will be excitedly waiting for you to update the new version heroku :)

Have a nice day!
