### ISSUE TITLE
[Documentation enhancement request] docs/getting-started.md is old

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#743]
Feature description
---------

Seems like [docs/getting-started.md](https://github.com/doccano/doccano/blob/master/docs/getting-started.md) doesn't reflect recent documentation changes.

Propose: replace its content with [README.md's Usage](https://github.com/doccano/doccano/blob/master/README.md#usage) link.

**Comment by icoxfog417** [comment]
merged to #731
