### ISSUE TITLE
Simultaneous annotation by multiple users

### ISSUE THREAD

**Issue by manuelramirezv** [doccano/doccano#745]
Hello all!

I have a project with a dataset of about 12k phrases and about 20 different labels

This dataset was being annotated by 18 people at the same time. Well, when the people starts to label de phrases the annotations are being duplicated. We have tested all the configurations posibilities of the project, checking and unchecking the "Concurrence annotations" and "Randomize order" and in all cases the annotations are being duplicated. This means that in all cases the users are receiving like "Undone" phrases that are already annotated even if has the "Undone" filter selected

What is the right configuration for annotating a dataset concurrently between many users avoiding duplicities?
---------

Your Environment
---------

*   Operating System: Linux
*   Python Version Used: 3.6
*   When you install doccano: 2 months ago
*   How did you install doccano (Heroku button etc):  Docker compose from github source

**Comment by icoxfog417** [comment]
Thank you for using the doccano. I understand your request as following, do these suit your situation?

* You have multiple annotators (18 people)
* When annotation, you want to seal the annotations made by other annotators.

doccano [allows annotators to "watch" the other annotations](https://github.com/doccano/doccano/issues/531#issuecomment-574142901) (and approve it).

If you want to forbid to watch the other annotations, you have to divide the datasets for each user.

**Comment by manuelramirezv** [comment]
Thanks for your reply!

Our problem is that when 18 people starts to anotate the sentences, all receive the same sentences and are working in the same sentences, doing duplicated work. I think that could be related with the pagination of the sentences, of 10 in 10 . Each user receive in his navigator 10 sentences that could be the same (at least one part of them) than the others, because this sentences aren´t yet tagged

**Comment by icoxfog417** [comment]
* 18 people receive the same sentences and ..
  * you want to seal the annotations made by other annotators. => you have to divide the dataset for each annotator.
  * you allow annotators to watch other annotations => you can use colloborative annotation feature.

**Comment by Colanim** [comment]
@icoxfog417 How do you divide the dataset for each annotator ? I couldn't find any way to do this.

**Comment by Simaex** [comment]
@astariul  a separate project for each user containing just a part of your original dataset works for me.
