### ISSUE TITLE
Hi In the outdated version of chakkiworks (https://pythonawesome.com/open-source-text-annotation-tool-for-machine-learning-practitioner/) we had some requirements and installations like docker, python 3.6+, django 2.0.5+ and etc. But new updated one - https://github.com/doccano/doccano/ has no requirements and pre installations mentioned. Can you please guide me through the complete installations procedure to have the text tool running? Kindly help out. Its critical. Thanks

### ISSUE THREAD

**Issue by leventm** [doccano/doccano#746]
How to reproduce the problem
---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by icoxfog417** [comment]
Please don't use the title as description, follow the [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE/01-question.md).

**Comment by leventm** [comment]
Hi 
In the outdated version of chakkiworks (https://pythonawesome.com/open-source-text-annotation-tool-for-machine-learning-practitioner/) we had some requirements and installations like docker, python 3.6+, django 2.0.5+ and etc. But new updated one - https://github.com/doccano/doccano/ has no requirements and pre installations mentioned. Can you please guide me through the complete installations procedure to have the text tool running? Kindly help out. Its critical.
