### ISSUE TITLE
Doccano tool installation and requirements comparitive to the old outdated chakki works

### ISSUE THREAD

**Issue by leventm** [doccano/doccano#747]
Hi
In the outdated version of chakkiworks (https://pythonawesome.com/open-source-text-annotation-tool-for-machine-learning-practitioner/) we had some requirements and installations like docker, python 3.6+, django 2.0.5+ and etc. But new updated one - https://github.com/doccano/doccano/ has no requirements and pre installations mentioned. Can you please guide me through the complete installations procedure to have the text tool running? Kindly help out. It's critical. 

Following this installation -  https://github.com/doccano/doccano/, I'm facing login error.

Thanks

**Comment by icoxfog417** [comment]
Please use the latest doccano and [follow the usage instruction](https://github.com/doccano/doccano#usage).
