### ISSUE TITLE
Text Classification: Exporting the label instead of label id

### ISSUE THREAD

**Issue by WiraDKP** [doccano/doccano#749]
Thanks for the amazing product.

Can we have the de-referenced label exported instead of the id in **text classification**?
Current:
```
{"annotations": [{"label": 1, "user": 1}]}
```
Requested:
```
{"annotations": [{"label": "class_1", "user": 1}]}
```

As in sequence tagging we have
```
{"labels": [[26, 34, "PER"], [35, 56, "LOC"]]}
```

I do aware that we could export the label to get the ID mapping, but the problem is that we could only upload 1 MB at max so that we need to separate it into a few projects.
The ID mapping in the new project would be different and it is troublesome to keep track.
So I don't think ID mapping is the solution.

Thank you in advance.

**Comment by at-a-run** [comment]
I asked a similar question earlier #737. An option to switch between the labels and label-id at export time is desirable.

**Comment by icoxfog417** [comment]
Thank you for @at-a-run reply! @WiraDKP , please refer to the related issue that @at-a-run proposes.

**Comment by at-a-run** [comment]
@icoxfog417 I’m seconding @WiraDKP  request. It is preferable that at export time there be an option to choose between label id or label text.

**Comment by icoxfog417** [comment]
We are dealing with this feature at #295
