### ISSUE TITLE
Deploy the application using non dockerised database

### ISSUE THREAD

**Issue by meetnileshhere** [doccano/doccano#750]
I am installing the codebase using docker compose with the docker-compose.prod.yml on the following environment
macos 10.14.6
python 3.6.10
installation date 1st May 2020
installed doccano on docker.

I would like to know if this application can be customised to use externally hosted databases, not provided in the docker image. 

Regards,
Nilesh

**Comment by Hironsan** [comment]
Specify [extra_hosts](https://docs.docker.com/compose/compose-file/#extra_hosts) and set `DATABASE_URL` environmental variable.

- https://stackoverflow.com/questions/39101164/how-to-use-link-remote-postgres-db-with-django-docker-implementation
