### ISSUE TITLE
Doccano installation and login error

### ISSUE THREAD

**Issue by leventm** [doccano/doccano#751]
Hi 
In the outdated version of chakkiworks (https://pythonawesome.com/open-source-text-annotation-tool-for-machine-learning-practitioner/) we had some requirements and installations like docker, python 3.6+, django 2.0.5+ and etc. But new updated one - https://github.com/doccano/doccano/ has no requirements and pre installations mentioned. Can you please guide me through the complete installations procedure to have the text tool running? Kindly help out. Its critical. 
![Kazam_screenshot_00011](https://user-images.githubusercontent.com/56015210/81264563-3db84200-905f-11ea-88b7-7ab93c64a700.png)
Thanks

**Comment by icoxfog417** [comment]
Please use the latest doccano and [follow the usage instruction](https://github.com/doccano/doccano#usage).
