### ISSUE TITLE
How to add html button only for admin ?

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#753]
How to reproduce the behaviour
---------

Hi sir ,

I have one external API . I want to add my external API to doccano . For this i need to create a HTML button with form  . I want  this  button only visible for admin not for annotator  in projects page. 
Please suggest anyone for this task where exactly i have to  add my HTML and JavaScript code . 

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.6
*   When you install doccano: Feb , 2020
*   How did you install doccano (Heroku button etc): git clone + installed from source

**Comment by Hironsan** [comment]
Suppose that you are using Docker Compose version.

`TheSideBar.vue` will be helpful for you. It controls visibility by the user role.
https://github.com/doccano/doccano/blob/4378b878d38d990537b76e4d52998195afe9679d/frontend/components/organisms/layout/TheSideBar.vue#L69-L71
