### ISSUE TITLE
Choosing filter twice results in 404 error

### ISSUE THREAD

**Issue by cgill95** [doccano/doccano#754]
How to reproduce the behaviour
---------
After deploying Doccano and starting it up for the first time I added a plain text dataset consiting of the suggested text. When wanting to annotate it and click the "Select a Filter" button and choose the already activated filter again I get a redirect to a 404 page. It does not matter for what kind of project I do it or which of the three available filter I click on twice.

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: 3.7.5
*   When you install doccano: 07.05.2020
*   How did you install doccano (Heroku button etc): Docker Dev Environment

**Comment by icoxfog417** [comment]
Please tell us "When you install doccano?".
