### ISSUE TITLE
Service backend failed to complete build 

### ISSUE THREAD

**Issue by AsaKal** [doccano/doccano#755]
Error when installing requirements
---------
Hi
When building the backend, I ran into an error in step 8. The error is prompted when installing package psycopg2.
Here is the output when collecting the package
`

> Collecting psycopg2   
> 
>   Downloading psycopg2-2.8.5.tar.gz (380 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8gohkoqq/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8gohkoqq/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-u8_n7mgy
>          cwd: /tmp/pip-install-8gohkoqq/psycopg2/
>     Complete output (7 lines):
>     running egg_info
>     creating /tmp/pip-pip-egg-info-u8_n7mgy/psycopg2.egg-info
>     writing /tmp/pip-pip-egg-info-u8_n7mgy/psycopg2.egg-info/PKG-INFO
>     writing dependency_links to /tmp/pip-pip-egg-info-u8_n7mgy/psycopg2.egg-info/dependency_links.txt
>     writing top-level names to /tmp/pip-pip-egg-info-u8_n7mgy/psycopg2.egg-info/top_level.txt
>     writing manifest file '/tmp/pip-pip-egg-info-u8_n7mgy/psycopg2.egg-info/SOURCES.txt'
>     Error: b'strict.pm did not return a true value at /usr/bin/pg_config line 12.\n'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Service 'backend' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

`

How can i go around this?
Thanks in advance

Your Environment
---------
*   Operating System: macOS Catalina
*   Python Version Used: Python 3.7
*   When you install doccano: May 7 2020
*   How did you install doccano (Heroku button etc): git clone + installed from source

**Comment by icoxfog417** [comment]
It seems to be caused by installing `psycopg2` in your environment. Please confirm you can install `psycopg2` in your environment.

**Comment by AsaKal** [comment]
I am facing difficulties when trying to install it on the venv.  Correct me if I am wrong, the code is found in the dev-django.sh file  and I found  a possible solution on [https://github.com/psycopg/psycopg2/issues/997#issuecomment-545822141](url)  but how do i implement it in this case ? 
Is there any other possible solution ?

**Comment by AsaKal** [comment]
> It seems to be caused by installing `psycopg2` in your environment. Please confirm you can install `psycopg2` in your environment.

Thanks @icoxfog417 
I am facing difficulties when trying to install it on the venv.  Correct me if I am wrong, the code is found in the dev-django.sh file  and I found  a possible solution on [https://github.com/psycopg/psycopg2/issues/997#issuecomment-545822141](url)  but how do i implement it in this case ? 
Is there any other possible solution ?
