### ISSUE TITLE
Document Classifcation and Sequence Labeling at the same time

### ISSUE THREAD

**Issue by schafsam** [doccano/doccano#757]
Is it possible to do *Document Classification* and *Sequence Labeling* at the same time? 

Setting from where this question evolved: There are documents or rather records and in a first step they are classified into different categories and then depending on the class certain named entities are extracted. It would be greate if the labeller can set both the document class and mark the sequence labels at the same time. As I understood, with the current setting this means that one project for *Document Classification* and one for *Sequence Labeling* needs to be set up and the labeller needs to go over the data set twice.

Thanks a lot for any hint or help.

**Comment by at-a-run** [comment]
We are working on documents which fit this usage as well. I understand it will be possible to apply the text classification once and then rerun the named entity recognition in a second round but it would be nice to have have them in a single step.

**Comment by icoxfog417** [comment]
merge to #617
