### ISSUE TITLE
Checking the logged in user is superuser or not 

### ISSUE THREAD

**Issue by alokpredictly** [doccano/doccano#758]
I need to check whether the logged in user has superuser status or not. Actually I need to add something like this "You're a superuser or You're not a superuser" in the 'projects.html' page. 
This is to enhance the user experience for the team which is labelling the data using doccano. So is there any possible way I can check something like that the current user is superuser or not and return that to 'projects.html' page template.

Your Environment
---------

*   Operating System: Ubuntu 16.04
*   Python Version Used: Python 3.7
*   When you install doccano: 23rd April
*   How did you install doccano (Heroku button etc): Installed from source

**Comment by icoxfog417** [comment]
Thank you for your enchancement request. Could you please tell us why you want to notify the superuser role to the user? The number of superusers is little and they may know their own role.

**Comment by kuraga** [comment]
@icoxfog417 , let's say wider: display current role.

**Comment by alokpredictly** [comment]
> Thank you for your enchancement request. Could you please tell us why you want to notify the superuser role to the user? The number of superusers is little and they may know their own role.

It's to let the person who's annotating what's their role is.

**Comment by icoxfog417** [comment]
merge to #881
