### ISSUE TITLE
How can labeled data be persisted in cloud?

### ISSUE THREAD

**Issue by at-a-run** [doccano/doccano#760]
How to reproduce the behaviour
---------
Not applicable.

Your Environment
---------
*   Operating System: Ubuntu 18.04
*   Python Version Used: NA
*   When you install doccano: April 2020
*   How did you install doccano (Heroku button etc): docker pull

Question:

I want the labels to be backed up into s3 or dynamodb. How do I achieve this?

**Comment by harmw** [comment]
there is some work done around a client API [1] to help around these things, the idea would be to fetch the data using the API and store it as CSV. From there on you can store it in for example S3. You'd be able to fetch all labels using an API call.

```
    def fetch_labels(self, project_id):
        url = "{}/v1/projects/{}/labels".format(self.entrypoint, project_id)
        response = self.client.get(url, headers=self.client.headers)
        return response.json()
```

[1] https://github.com/doccano/doccano/issues/624
