### ISSUE TITLE
Button to clone a project with a single click

### ISSUE THREAD

**Issue by at-a-run** [doccano/doccano#762]
Feature description
---------
Ability to create a new project which is the same type (text classification) as an existing project form the UI.

Why is cloning necessary?

My existing project has many labels defined (20+) and with shortcuts for which the annotator is already trained. The new project needs these labels and it very cumbersome to manually recreate the label set in the new project.

Why can't you create a new project and copy labels using label download from old project and upload to new project? See #443 

1. I haven't seen the UI option in #443 to export / import labels. I'm using docker image version:
```
$ docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
doccano/doccano     latest              4f018c685336        4 weeks ago         459MB
```
2. I'm trying to figure out how to use the rest api to download labels and copy to another project. This may unblock me (when I figure out the authentication from python). However, we are trying to adopt this tool due to its UI benefits and this is impacting us.

**Comment by Hironsan** [comment]
If you want to copy labels from the UI, please use Docker Compose version.
If you want to copy labels by using API, please use some api client like [doccano_api_client](https://github.com/afparsons/doccano_api_client).
