### ISSUE TITLE
On first docker build: core-js not found

### ISSUE THREAD

**Issue by willywongi** [doccano/doccano#763]
I wanted to deploy Doccano on our own platform but I ran into an issue. Building doccano with docker-compose, both with .prod and .dev yaml files, fails on the frontend image. The issue here looks like there's a npm dependency missing.
Inspecting the logs from the dev compose file:
```
✔ Client: Compiled with some errors in 18.89s

 ERROR  Failed to compile with 145 errors

These dependencies were not found:
* core-js/modules/es6.array.find in ./.nuxt/client.js, ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js& and 2 others
[...long list of dependencies]
```

The containers starts but when accessing the frontend page at localhost:3000 I got a long list of errors:
```
ERROR in ./.nuxt/client.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.find' in '/src/frontend/.nuxt'
[...]
```

Running compose with prod.yaml stops with a long list of errors that look really the same issue:
```
ERROR in ./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--17-0!./node_modules/vue-loader/lib??vue-loader-options!./components/containers/annotation/TextClassification.vue?vue&type=script&lang=js&)
[...]
```

Manually installing core-js did not solved the problem.
```bash
cd frontend
npm install --save core-js
```

I noticed that the `package-lock.json` file is not commited: for what I know it should be committed to "pin" each package to an exact version, allowing reproducibile builds.

How to reproduce the problem
---------
```bash
docker-compose -f docker-compose.dev.yml up -d 
```

Your Environment
---------
*   Operating System: docker on macos
*   Python Version Used: 3.6
*   Doccano master@4378b87 (10th may 2020)
*   How did you install doccano (Heroku button etc): docker-compose (dev)

**Comment by Hironsan** [comment]
Hmm, I can't reproduce the error for both dev and prod with the latest doccano.

Does anyone have the same issue?

**Comment by willywongi** [comment]
Just to clarify: I encounter this problem with master (last commit: 4378b87). Trying the same thing with tag v1.0.4 works.

**Comment by willywongi** [comment]
I really haven't changed a thing but today it builds correctly. My suspects are still on that package.json file: dependencies could have changed while we spoke.
