### ISSUE TITLE
After filtering the dataset when clicking the annotation it is not shown the proper data (from the filter)

### ISSUE THREAD

**Issue by igormis** [doccano/doccano#765]
How to reproduce the behaviour
---------
I am doing filtering of the existing dataset, for instance I write Trump in the filter and the filter works fine. However, when clicking on the button Annotate on the first sentence it shows me all the sentences from the beginning (i.e. it does not redirect me to the wanted sentence, it just opens the first example from the dataset - I have no randomization selected for this project)

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.6
*   When you install doccano: 1 week ago
*   How did you install doccano (Heroku button etc): from git

**Comment by igormis** [comment]
The filter works
![Filter](https://user-images.githubusercontent.com/6599037/81695937-96267f80-9463-11ea-8bde-df972b6440b0.png)

**Comment by igormis** [comment]
When clicking Annotate it does not show the same data...
![Annotate](https://user-images.githubusercontent.com/6599037/81696035-b5251180-9463-11ea-86e0-f4a54308d4d4.png)

**Comment by igormis** [comment]
For instance if the filter filters 10 examples from 50, then by clicking on the 3 example it will show not the third from the filtered, but the 3rd from the whole dataset

**Comment by igormis** [comment]
@Hironsan any possible work-arounds or quick fixes on this issue? I tried also with 1.03 and 1.02 branches but no success...

**Comment by Hironsan** [comment]
Unfortunately, there is no quick fix. It takes some time to analyze the problem and fix it.
