### ISSUE TITLE
Add Image2sequence annotation feature

### ISSUE THREAD

**Issue by mathisdemos** [doccano/doccano#767]
Feature description
---------
Hey doccano team!

First of all thanks for your work on doccano! It's a pleasure to work with your tool and it helps us a lot in our daily work.

We have a proposal for a new feature that we would like to see in doccano because we'll need something like this very soon.

The feature is similar to the seq2seq annotation feature except that we would like to add a description to images instead. Our preliminary name for this feature would be 'img2seq'.

In img2seq projects the user can upload images with metadata and add a textual description as an annotation to each image. This is useful if you'd like to generate captions and some other use cases (OCR annotation in our case).

We are willing to provide a PR. This issue is mainly here to discuss if there are any objections to this feature and for people to give feedback and maybe to provide some useful hints on implementation details.

I'm looking forward to suggestions and feedback!

**Comment by Hironsan** [comment]
Is this understanding of mine correct?

![image](https://user-images.githubusercontent.com/6737785/81759532-f23ee180-94ff-11ea-8c89-d091ce2d89dc.png)

If so, I'm looking forward to a PR.

**Comment by mathisdemos** [comment]
yes, your understanding is correct. PR will follow soon.
