### ISSUE TITLE
Annotator not able to change label

### ISSUE THREAD

**Issue by sharmila-polamuri** [doccano/doccano#768]
How to reproduce the behaviour
---------

Project admin added labels to the document and assign annotator. I want the annotator to change the labels labeled by project admin. To achieve this in the django admin page i add the following permissions 
```
api | label | Can add label
api | label | Can change label
api | label | Can delete label
api | label | Can view label
api | document annotation | Can add document annotation
api | document annotation | Can change document annotation
api | document annotation | Can delete document annotation
api | document annotation | Can view document annotation
```
after this also annotator not able to change the label. In the backend i see the following error 
```
Forbidden: /v1/projects/82/docs/17425/annotations/1106
[13/May/2020 05:00:30] "DELETE /v1/projects/82/docs/17425/annotations/1106 HTTP/1.1" 403 63
```
Please suggest any idea about this problem to solve.

Your Environment
---------

*   Operating System:  Ubuntu 18.04
*   Python Version Used: 3.6
*   When you install doccano: Feb 2020
*   How did you install doccano (Heroku button etc): git+clone and installed from source

**Comment by cgill95** [comment]
The default process (as far as I understand) should be that the project admin just oversees and setups the project and approves the labels after they have been assigned by the annotators. Optional the annotator approver can change the labels chosen by the annotators and correct them (this was requested in #766 and added by myself but not yet added to master). Either way the annotator approver can approve the labels after they have been assigned.

**Comment by sharmila-polamuri** [comment]
Thank you.
