### ISSUE TITLE
Fail to add annotators. 404 error when trying to access django admin to add user.

### ISSUE THREAD

**Issue by arianpasquali** [doccano/doccano#770]
How to reproduce the behaviour
---------

1. clone repo
2. run docker-compose -f docker-compose.dev.yml up

Follow documentino on how to add annotators 
https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-add-annotators
 
3. Try to access django-admin at http://localhost:3000/admin

Get 404 error

**Comment by anurag-cser** [comment]
Same issue here. 

Using docker-compose.prod.yml

**Comment by Hironsan** [comment]
If you are using `docker-compose.dev.yml`, try to access django-admin at http://localhost:8000/admin.

**Comment by Hironsan** [comment]
If you are using `docker-compose.prod.yml`, try to access django-admin at http://0.0.0.0/admin.
