### ISSUE TITLE
Reverse Proxy doccano to a subdirectory

### ISSUE THREAD

**Issue by anurag-kx** [doccano/doccano#775]
I was trying to reverse proxy doccano installed in my local server to a subdirectory(apache webserver).

However, I got an error 404(in the console) as it was looking for _nuxt files in the root directory.
Also, the homepage was blank

Environment:

*   Operating System: ubuntu 16.04
*   Python Version Used: 3.6
*   When you install doccano: 12-05-2020
*   How did you install doccano (Heroku button etc): docker-compose.prod.yml file

**Comment by icoxfog417** [comment]
We can't figure our this is doccano issue or your environment issue. Please raise a new issue if you detect the problem of doccano.
