### ISSUE TITLE
Validation flow seems slow/tedious

### ISSUE THREAD

**Issue by harmw** [doccano/doccano#776]
How to reproduce the behaviour
---------
When selecting a _document_ from my _dataset_, and clicking *annotate*, I am shown a screen with the text and the labels already added (I've added these already, using the API).

Signing off on the entered labels, accepting them means clicking in the left side _checkbox-like icon_. The annoying part here is that, in order to go to the next document I need to go to the top right corner of my screen. This is tedious and slows down the manual validation of annotations. It's actually nicely visible when looking at the _Annotate the dataset_ video featured on the home-screen.

Question here would be if it's possible to have a mechanism that does the acknowledgment _and goes on to the next document_ all within a _single action_. For example using a hot-key and (for mouse-users) a button.

Hope this makes sense.

Your Environment
---------
A fresh clone and docker-compose using the `dev` configuration.

**Comment by icoxfog417** [comment]
You can move the documents by arrow key.

**Comment by kuraga** [comment]
> You can move the documents by arrow key.

It's not true: #635
