### ISSUE TITLE
Proper tagging of docker containers

### ISSUE THREAD

**Issue by harmw** [doccano/doccano#783]
Feature description
---------
Looking at using this in production, I came across https://hub.docker.com/r/doccano/doccano/tags which shows only a single tag getting pushed: `latest`
This makes deployment a bit tricky, as I cannot differentiate between different version of the project etc.

The idea here would be to introduce properly tagged containers, to reflect a specific point-in-time release of the project (as per https://github.com/doccano/doccano/projects ?). And keeping `latest` as it is being used today.

Thoughts? (let me see if I can help around with this)

**Comment by harmw** [comment]
actually, looking at https://github.com/doccano/doccano/blob/master/tools/cd.sh#L20 it should already be there 🤔

**Comment by kuraga** [comment]
Related: #786 .

**Comment by armandleopold** [comment]
Hello, Need proper tagging please.
One tag per/release.
We are using this image for production.

**Comment by kuraga** [comment]
Related: #971.
