### ISSUE TITLE
[Question] What `/docker-compose.yml` is for?

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#784]
What `/docker-compose.yml` is for? I don't see it in the documentation or in the code.

**Comment by willywongi** [comment]
For what I managed to understand, this same repo hosts two projects: a Django application (let's call it "old version"), with most of the pages built server side (with Django templates) and some frontend code built with webpack. This is what you see when you visit https://doccano.herokuapp.com/, and what you get if you user `docker-compose.yml`.
The second "soul" of this project is a two-tier application. Most of the backend is shared with the "old version", but is exposed through a REST API to a Vue frontend (built with nuxt). 

I feel this rather confusing: if I may, I would suggest the authors to use different branches to keep things clean: production (only tested and working code goes here), master (where most of the development is) and legacy (for the old Django app).

**Comment by kuraga** [comment]
@willywongi , thanks!

IMHO we should add this to [/docs/project_structure.md](https://github.com/doccano/doccano/blob/master/docs/project_structure.md). So, #780 is related.

If comment above is correct, feel free to close.
