### ISSUE TITLE
blocking : docker-compose -f docker-compose.prod.yml up

### ISSUE THREAD

**Issue by qqxhb** [doccano/doccano#788]
When I executed this command, I got stuck in step five.It's a long time since step five.....
`docker-compose -f docker-compose.prod.yml up`

``` Building frontend
Step 1/6 : FROM node:13.2.0
 ---> 760e12e87878
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> 82037efee00c
Step 3/6 : COPY . /app/
 ---> Using cache
 ---> 7d84ec4e3297
Step 4/6 : RUN npm install -g npm@latest
 ---> Using cache
 ---> 268a785825b5
Step 5/6 : RUN npm install
 ---> Running in 0544a16fc594
```

**Comment by icoxfog417** [comment]
* Please follow the [ISSUE_TEAMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE.md). We need your environment information to support you.
* We don't know your computer resource. Could you please show us supplemental information?

**Comment by qqxhb** [comment]
Thank you, but it's all right now.
