### ISSUE TITLE
Dummy data shown when API is unreachable

### ISSUE THREAD

**Issue by harmw** [doccano/doccano#789]
How to reproduce the behaviour
---------
Build the frontend: `docker build -t doccano-frontend frontend`

Launch: `docker run --rm -it -p 3000:3000 doccano-frontend`

Browsing to `http://localhost:3000` shows the frontend, everything fine there, trying to login with fake credentials (username: `123`, password: `123`) works instead of failing with auth errors. So somewhere in the frontend container dummy data is stored and now sent to the client.
The page at `http://localhost:3000/projects` shows a list of (dummy/testing) projects, where one would expect to see nothing (ie. auth errors)

As an example, this is the login call my browser tries:

```bash
curl 'http://localhost:3000/v1/auth-token' \
-XPOST \
-H 'Content-Type: application/json;charset=utf-8' \
--data-binary '{"username":"123","password":"123"}'
```
Which returns html...

When I point (hack) the `nuxt` code to some (dummy) url (`http://localhost:12345/v1`) to use as API, it does return _Incorrect username or password_ when trying to login. 

I haven't looked at the code yet, figured I'd get this reported first.

Your Environment
---------
*   Operating System: docker/mac
*   How did you install doccano (Heroku button etc): `docker build`

**Comment by icoxfog417** [comment]
Thank you for reporting the issue.

1.  Do you mean you can login doccano by fake credential as you said?
2. When you login by fake credential, can you get dummy data? If so, could you please show these to us?

**Comment by harmw** [comment]
After login (using `123/123` as credentials) I am greeted with the following projects overview:

<img width="1605" alt="Screenshot 2020-05-21 at 15 09 37" src="https://user-images.githubusercontent.com/5871646/82562301-3de33200-9b75-11ea-814f-f18684b0010d.png">

**Comment by Hironsan** [comment]
In early development, I have been developing frontend by using dummy API. It's accessible from localhost:3000/v1. I used Nuxt's serverMiddleware to implement the API. So If we remove the following lines, the API will be unreachable.

https://github.com/doccano/doccano/blob/a71fbd3e4ce576bfc08c0a5ca724388378200177/frontend/nuxt.config.js#L29-L31

Actually, it's legacy code. I'm currently using Python's backend API instead of the dummy API. It's deletable.

**Comment by harmw** [comment]
regarding the login without API, seems my `jwt` cookie is being set with value `undefined`. 

Let me dive a little deeper, I can image the API backend to return something meaningful here but the frontend on it's own being unable to workout what to do in this somewhat funky situation :)

**Comment by harmw** [comment]
the `tryLogin()` logic in `frontend/components/organisms/auth/LoginForm.vue`:

```javascript
tryLogin() {
      if (this.validate()) {
        this.login({
          username: this.username,
          password: this.password
        })
          .then((result) => {
              this.$router.push('/projects')
          })
          .catch(() => {
            this.showError = true
          })
[..]
```

hypothesis: when the backend API returns a `HTTP/400` _vue_ triggers the `catch()`. However, since we're talking to `/v1` we get html returned, ie. a `HTTP/200` which causes _vue_ to move along with `this.$router.push('/projects')`. Meaning, we're logged on and get to see the dummy data.

Would probably be sensible to just check if `result` is an object that holds a `token`-field, as that is how the API tells us everything is fine.
