### ISSUE TITLE
How do I install Doccano from source instead of docker?

### ISSUE THREAD

**Issue by yashsinghal** [doccano/doccano#793]
I want to install the new version of doccano from source instead of the docker file. Hw do I do it?

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used:3.7
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by icoxfog417** [comment]
You can watch the procedure to run the doccano inside [Dockerfile](https://github.com/doccano/doccano/blob/master/Dockerfile). But we don't recommend working by source if you are not familiar with Node.js and Django.
