### ISSUE TITLE
frontend_1  | npm ERR! exited with error code: 128

### ISSUE THREAD

**Issue by kartikpshah** [doccano/doccano#796]
when I am running 
docker-compose -f docker-compose.dev.yml up
I am getting below error.
error 
backend_1   | Watching for file changes with StatReloader

frontend_1  | npm ERR! Error while executing:
frontend_1  | npm ERR! /usr/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git
frontend_1  | npm ERR!
frontend_1  | npm ERR! fatal: unable to connect to github.com:
frontend_1  | npm ERR! github.com[0: 140.82.118.3]: errno=Connection timed out
frontend_1  | npm ERR!
frontend_1  | npm ERR!
frontend_1  | npm ERR! exited with error code: 128

frontend_1  |
frontend_1  | npm ERR! A complete log of this run can be found in:
frontend_1  | npm ERR!     /root/.npm/_logs/2020-05-26T20_26_04_942Z-debug.log
doccano_frontend_1 exited with code 1

---------

```bash
# copy-paste the error message here
```

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**How to reproduce the problem**

S46981@vc163:~$ /usr/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git                                                                                          
fatal: unable to connect to github.com:
github.com[0: 140.82.118.4]: errno=Connection timed out

S46981@vc163:~$
S46981@vc163:~$ sudo /usr/bin/git ls-remote -h -t git://github.com/adobe-webplatform/eve.git
fatal: unable to connect to github.com:
github.com[0: 140.82.118.4]: errno=Connection timed out

============================================

**Comment by icoxfog417** [comment]
The error message "Connection timed out" suggests you can't access the internet from your container. Please confirm the network connection.
