### ISSUE TITLE
Adding new role for a project does not give user permissions

### ISSUE THREAD

**Issue by yashsinghal** [doccano/doccano#797]
How to reproduce the behaviour
---------

I Wanted to make a new role of an anootator who can also change other annotations but not mark file as complete. I made a new role, but am I not given the option to give permissions to that role. How to Do the same?
Would be really thankful for the help.

Your Environment
---------

*   Operating System:
*   Python Version Used:
*   When you install doccano:
*   How did you install doccano (Heroku button etc):

**Comment by icoxfog417** [comment]
We are dealing with this feature at #531 .  Please up-vote the issue if you need this feature!
