### ISSUE TITLE
Mixed project

### ISSUE THREAD

**Issue by MikeVlad6** [doccano/doccano#799]
Hi,

First of all, great job, this project has helped me very much. 

Is it possible to create a new type of project which incorporates both SequenceLabeling and Text Classification without having to substantially change the entire architecture? For entity and sentiment analysis this would be great since the annotator won't have to read the same text twice. 
I've been trying to implement it myself but i've had alot of problems so far.

**Comment by icoxfog417** [comment]
We are considering this feature at #617. Please up-vote this issue if you want this feature!
