### ISSUE TITLE
Is there any way to assign a document to a specific annotator?

### ISSUE THREAD

**Issue by yashsinghal** [doccano/doccano#803]
How to reproduce the behaviour
---------

I wanted to assign newly uploaded documents to specific annotators on a project so one document is only visible to one annotator. Is there any way to do so or some quick code addition/fix?

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: 3.6
*   When you install doccano: 25rd May
*   How did you install doccano (Heroku button etc):From Source

**Comment by icoxfog417** [comment]
doccano does not have this feature. If you want to do it. you have to separate the dataset and make each project.
