### ISSUE TITLE
Execute refresh above the pagination-boundary example causes miss ordering

### ISSUE THREAD

**Issue by MikeVlad6** [doccano/doccano#804]
How to reproduce the issue:
Scroll on any project with more than 10 documents (pagination limit) and hit shift+refresh. Upon reloading, instead of getting document ID (24 for example) will get the corresponding document on the first page, in this case, 4. 
This can be assessed with a print in store/documents.js, in the getDocumentList action, line 102, (console.log(payload)). 
I've been able to fix this by adding this.updateSearchOptions before this.getDocumentList in the BottomNavigator.vue. 

I don't know if this is of any help to you but it might so i'll leave it here.

**Comment by icoxfog417** [comment]
What is the desirable specification you think? Please show us as-is and to-be.

**Comment by MikeVlad6** [comment]
I've uploaded a demo here. This is made on the master branch, i just cloned and ran it. There are multiple components which are calling getDocumentList and the bug occurs when hitting refresh on the (11th or greater document) - it will bring you the corresponding document from 1 to 10 (if u hit refresh on the 11th it will bring you the first document, 12th - second document etc). You can reproduce the issue with any document sample greater than the pagination size (10).
I haven't been able to fix it so far so i can't provide a to-be specification and i've also modified alot on my fork so it might not be that relevant. 
I'll come back with a solution if or when i find one.

Thanks for the good job!
https://imgur.com/a/H7qjw3t

**Comment by icoxfog417** [comment]
Thank you for providing the detail behavior. I understand this phenomenon as the following.

As-is

* When you execute refresh above the pagination-boundary example (11th or greater document), then the first example appears in front of the page. 

To-Be

* The example showed before the refresh and order of examples should be kept.

Or

* When executing refresh, back to top (1st) example.

**Comment by icoxfog417** [comment]
@MikeVlad6 Could you please confirm the behavior of the latest doccano? This bug will be fixed.
