### ISSUE TITLE
Downloading csv or json depends on Accept-header

### ISSUE THREAD

**Issue by harmw** [doccano/doccano#806]
How to reproduce the behaviour
---------
Observing some weird behaviour when trying to download my dataset.

Trying to get a `csv` file:
```
$ curl "https://doccano/v1/projects/6/docs/download?q=csv" -H 'accept: text/csv' -H "authorization: Token $TOKEN"
annotation_approver,id,label,text,user

$ curl "https://doccano/v1/projects/6/docs/download?q=csv" -H 'accept: */*' -H "authorization: Token $TOKEN"
annotation_approver,id,label,text,user

$ curl "https://doccano/v1/projects/6/docs/download?q=csv" -H 'accept: application/json'  -H "authorization: Token $TOKEN"
{"id": 21, "text": "hello world", "meta": {}, "annotation_approver": null, "label": 10, "user": 1}
```

Trying to get a `json` file:
```
$ curl "https://doccano/v1/projects/6/docs/download?q=json" -H 'accept: text/csv' -H "authorization: Token $TOKEN"
annotation_approver,annotations.0.label,annotations.0.user,annotations.1.label,annotations.1.user,id,text

$ curl "https://doccano/v1/projects/6/docs/download?q=json" -H 'accept: */*' -H "authorization: Token $TOKEN"
annotation_approver,annotations.0.label,annotations.0.user,annotations.1.label,annotations.1.user,id,text

$ curl "https://doccano/v1/projects/6/docs/download?q=json" -H 'accept: application/json' -H "authorization: Token $TOKEN"
{"id": 21, "text": "hello world", "annotations": [{"label": 10, "user": 1}, {"label": 12, "user": 1}], "meta": {}, "annotation_approver": null}
```

Hypothesis here would be Django taking into account what the `accept` header (coming from the client) specifies in order to `paint()` a proper return. Which ends up weird, as it creates a json structure from csv and vv.
 
Your Environment
---------
*   master branch in docker

**Comment by Hironsan** [comment]
Accept-header decides which [renderer](https://www.django-rest-framework.org/api-guide/renderers/) to use. On the other hand, the query parameter decides which painter to use. So the difference between the accept-header and the query parameter causes the weird behavior. The following is a weird combination.

| query | header|
|-------|--------|
|csv|application/json|
|json|text/csv|
|json|\*/\*|

**Comment by icoxfog417** [comment]
Please use the correct combination.
