### ISSUE TITLE
Done / Undone filter does not work correctly

### ISSUE THREAD

**Issue by meetnileshhere** [doccano/doccano#808]
I am using the codebase using docker compose with the docker-compose.prod.yml on the following environment
macos 10.14.6
python 3.6.10
installation date 1st May 2020
installed doccano on docker.

Your application is a real saviour for non-frontend person like me. Unfortunately I am facing an issue with the filtering of the annotated documents, it doesn't work for me. 

- I have set about 15 documents as Checked

- Then I am trying to use the filter to show only the done documents, it display nothing and shows 6 of 0 next to < > buttons. This should show me only 15. This looks to be an issue.

Then I am trying to use the filter as Undone but it shows me all the documents, this is also an issue, it should show me only Undone which is 15 less than the whole list.

I remember this has worked in the past when I initially used this application about a month back, but somehow it has gone wrong, is the code regressed?

Please help.

Regards,
Nilesh

**Comment by icoxfog417** [comment]
Thank you for using the doccano. In short, done/undone filter does not work correctly?

**Comment by meetnileshhere** [comment]
> Thank you for using the doccano. In short, done/undone filter does not work correctly?

That's correct. As specified above, I have seen this filter worked fine in the past. But it seems to have stopped in the latest release.

**Comment by Hironsan** [comment]
https://github.com/doccano/doccano/pull/897 solved this problem.
