### ISSUE TITLE
[Tiny enhancement request] Reflect opacity in Color column (on Labels page)

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#814]
Feature description
---------
Now, neither HEX code nor visual state reflect opacity in Color column (on Labels page).

Update 1: and opacity is not used on Annotation page.

Proposal:
- display A-component of RGBA code;
- use opacity on badge displaying.

Update 2: according to database, seems like opacity isn't stored at all. There are background and text colors, two RGB values.

**Comment by kuraga** [comment]
Update: according to database, seems like opacity isn't stored at all. There are background and text colors, two RGB values.

**Comment by icoxfog417** [comment]
We reopen this issue if someone needs this enhancement.

**Comment by kuraga** [comment]
If someone need, it won't see it.

**Comment by kuraga** [comment]
BTW, labels import format also doesn't suppose opacity.
