### ISSUE TITLE
Maintain all fields in the uploaded csv/json file in the downloaded file

### ISSUE THREAD

**Issue by yi-asapp** [doccano/doccano#819]
Feature description
---------
In my uploaded dataset file, each sentence was associated with an ID that I used to keep track of the instance. However, the ID info is lost in the downloaded output file, which is very inconvenient for me.

Proposal: keep all the fields in the uploaded dataset file, when we need to download the output file.

**Comment by Hironsan** [comment]
Did you include the ID in the meta field:

```javascript
{"text": "example", "labels": ["positive"], "meta": {"wikiPageID": 1}}
{"text": "example", "labels": ["positive", "negative"], "meta": {"wikiPageID": 2}}
{"text": "example", "labels": ["negative"], "meta": {"wikiPageID": 3}}
```

**Comment by icoxfog417** [comment]
You can use meta field.
