### ISSUE TITLE
[Bug report] Annotator doesn't see the project

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#822]
How to reproduce the behaviour
---------
I saw a situation: user `a_user` is an `annotator` at `a_project`'s Members page; but `a_user` doesn't see `a_project` at his Projects page.

At that moment I've removed `a_user`'s role and added it again (since situation has been seen during my job process so I had to solve it). It helped.

But I reproduced it synthetically:
1. Add `a_user` as an `annotator` of `a_project`.
2. Sign in to Django Admin.
3. Go to `Projects` page.
4. Go to `a_project`'s page.
5. On `Users` field, deselect `a_user` item.
6. Click `Save`.

Now:  _user `a_user` is an `annotator` at `a_project`'s Members page; but `a_user` doesn't see `a_project` at his Projects page_.

**Questions:**
1. Where and how is list from p.5 stored?
2. How does result of pp.1-6 could be reached by interaction with doccano, what do you think?

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: 4b5a3c34310f9c7e9d27163928073e74cc7bb226
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by Hironsan** [comment]
This may be due to the difference between RoleMapping and `users` field in the Project model.

**Comment by hushulong** [comment]
> This may be due to the difference between RoleMapping and `users` field in the Project model.

Yes. I've also found this problem where RoleMapping bulk create operations, because of [there isn’t a workaround when creating or updating objects in bulk, since none of save(), pre_save, and post_save are called.](https://docs.djangoproject.com/en/3.1/topics/db/models/)
### doccano/app/api/models.py
```
@receiver(post_save, sender=RoleMapping)
def add_linked_project(sender, instance, created, **kwargs):
    if not created:
        return
    userInstance = instance.user
    projectInstance = instance.project
    if userInstance and projectInstance:
        user = User.objects.get(pk=userInstance.pk)
        project = Project.objects.get(pk=projectInstance.pk)
        user.projects.add(project)
        user.save()


@receiver(post_save)
def add_superusers_to_project(sender, instance, created, **kwargs):
    if not created:
        return
    if sender not in Project.__subclasses__():
        return
    superusers = User.objects.filter(is_superuser=True)
    admin_role = Role.objects.filter(name=settings.ROLE_PROJECT_ADMIN).first()
    if superusers and admin_role:
        RoleMapping.objects.bulk_create(
            [RoleMapping(role_id=admin_role.id, user_id=superuser.id, project_id=instance.id)
             for superuser in superusers]
        )


@receiver(post_save, sender=User)
def add_new_superuser_to_projects(sender, instance, created, **kwargs):
    if created and instance.is_superuser:
        admin_role = Role.objects.filter(name=settings.ROLE_PROJECT_ADMIN).first()
        projects = Project.objects.all()
        if admin_role and projects:
            RoleMapping.objects.bulk_create(
                [RoleMapping(role_id=admin_role.id, user_id=instance.id, project_id=project.id)
                 for project in projects]
            )


@receiver(pre_delete, sender=RoleMapping)
def delete_linked_project(sender, instance, using, **kwargs):
    userInstance = instance.user
    projectInstance = instance.project
    if userInstance and projectInstance:
        user = User.objects.get(pk=userInstance.pk)
        project = Project.objects.get(pk=projectInstance.pk)
        user.projects.remove(project)
        user.save()
```
when creating superuser or project will lead to table **api_rolemapping** add record but table **api_project_users** not add 
corresponding record.

In my local, i custom **RoleMappingManager** to solve this problem.
```
class RoleMappingManager(Manager):
    """RoleMapping bulk_create send post_save signals"""

    def bulk_create(self, objs, **kwargs):
        for item in objs:
            post_save.send(item.__class__, instance=item, created=True)
        return super(RoleMappingManager, self).bulk_create(objs, **kwargs)

class RoleMapping(models.Model):
    user = models.ForeignKey(User, related_name='role_mappings', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name='role_mappings', on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = RoleMappingManager()

    def clean(self):
        other_rolemappings = self.project.role_mappings.exclude(id=self.id)

        if other_rolemappings.filter(user=self.user, project=self.project).exists():
            raise ValidationError('This user is already assigned to a role in this project.')

    class Meta:
        unique_together = ("user", "project", "role")
```
