### ISSUE TITLE
[Bug report] Labels deleting dialog: 'Cancel' doesn't work

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#824]
How to reproduce the behaviour
---------
1. Go to Labels page.
2. Select a label.
3. Click `Delete`.
4. A dialog is opened.
5. Click `Cancel`.

Expected: the dialog is closed.
Actual: nothing happened.

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: 4b5a3c34310f9c7e9d27163928073e74cc7bb226
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by Hironsan** [comment]
I forgot to add `@cancel="dialog=false"` line to `containers/labels/LabelDeletionButton.vue`:

https://github.com/doccano/doccano/blob/3577b0bcb6ae861b019295b3505babc7a4e6d120/frontend/components/containers/labels/LabelDeletionButton.vue#L12-L18
