### ISSUE TITLE
[Bug report] Click outside a dialog/press Esc and you'll break The World

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#825]
How to reproduce the behaviour
---------
1. Go to some page. Say Dataset page.
2. Open a dialog. Say "Actions -> Import Dataset" dialog.
3. Click outside of the dialog OR press Esc key.
4. Dialog is closed.

Now:
5. If you try to access _the same_ dialog, it won't be opened.
6. If you try to access another dialog, everything will be OK.
7. If we had clicked Cancel instead of p.3, everything would be OK even with the same dialog.

Expected: the dialog is closed.
Actual: nothing happened.

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: 4b5a3c34310f9c7e9d27163928073e74cc7bb226
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by Hironsan** [comment]
This is the problem of `BaseDialog` component. It seems that it doesn't propagate the state if Esc key is pressed or the outside of the dialog is clicked.

If we use `VDialog` component instead of `BaseDialog` component, the problem will be fixed:

```html
<!--
<base-dialog :dialog="importDialog">
-->
<v-dialog
  v-model="importDialog"
  width="800"
>
  <document-upload-form
    :upload-document="uploadDocument"
    :formats="getImportFormat"
    @close="importDialog=false"
  />
</v-dialog>
<!--
</base-dialog>
-->
```

**Comment by hugosoftdev** [comment]
Hey guys, i'd like to work in this issue! It can be a nice first issue and i think i can resolve it!
