### ISSUE TITLE
[Question] About conflicts on importing labels

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#826]
Importing labels to a project, we give a JSON file with labels information.
Each label consist of some properties. Consider three of them.
1. `id`. Is `id` saved? If so,
    1. What if importing label's `id` already exists in the system?
    2. Are `id`s "auto-incremented" identifiers? If current maximum `id` is `17` but importing label's `id` is `100`, what happens?
2. `label`. What if importing label's `label` already exists in the project?
3. `color`, etc. The same: what if importing value already exists in the project?

**Comment by Hironsan** [comment]
1. `id` is not saved.
2. If an importing label already exists in the project, it ignores.
3. Same as 2.

**Comment by kuraga** [comment]
@Hironsan , thanks!

> If an importing label already exists in the project, it ignores.

Who is _it_? :) So, is just old label untouched?

**Comment by Hironsan** [comment]
> is just old label untouched?

Yes, it expected to be untouched.
