### ISSUE TITLE
Problem in displaying HTML content

### ISSUE THREAD

**Issue by yashsinghal** [doccano/doccano#827]
How to reproduce the behaviour
---------

I have text that contains HTML tags and I want to annotate on the same. While annotating, I want to hide the HTML tags so it is clearer to see the actual content. Currently, I have done this by changing

`<span v-else :class="[newline ? 'newline' : '']">{{content}}</span>`
to
`<span v-else :class="[newline ? 'newline' : '']" v-html="content"></span>`

in the EntityItem.vue file of the frontend.

But due to this, I am not able to tag correctly. Is there a way to fix this?
Your Environment
---------

*   Operating System:Windows 10
*   Python Version Used:3.7
*   When you install doccano:Last Month
*   How did you install doccano (Heroku button etc): Source

**Comment by icoxfog417** [comment]
Your issue seems to Vue.js issue that not due to doccano.
