### ISSUE TITLE
[Enhancement request] Use color in labels selector (on Annotation page)

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#829]
Feature description
---------
On Annotation page, in labels selector color/background color/text color isn't used.

Proposal: use color in labels selector.

See also: #635 (IMHO it's better option).

**Comment by icoxfog417** [comment]
Please provide us (and other contributors) the evidence of the situation that you need this feature.

**Comment by kuraga** [comment]
@icoxfog417 , it's very important feature in light of #477.
