### ISSUE TITLE
[Feature request] Implement indicating number of annotated documents (by the user)

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#830]
Feature description
---------
Feature request: implement indicating number of annotated documents (by the user). Each annotator sees how many documents are being annotated in the project, by him.

**Comment by icoxfog417** [comment]
Please provide us (and other contributors) the evidence of the situation that you need this feature.

**Comment by kuraga** [comment]
@icoxfog417 , real situation: our annotators ask project administrator, more and more: how many documents are being annotated by me? How many more documents should I annotate?

**Comment by kuraga** [comment]
Related: #948.

**Comment by bahaodangpu** [comment]
Is this question solved？
