### ISSUE TITLE
[Feature request] Implement a control of annotation coverage per document

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#831]
Feature description
---------
For each project, propose to introduce a (assignable by project admin) property, N - minimal number of annotations (of a given document) to indicate the document as "done". (I.e. N = 1 now).

**Comment by icoxfog417** [comment]
Merge to Enhance Statistics: Compare Annotators #114

**Comment by ClementViricel** [comment]
Hello
i can't find this option anywhere in my sequence labelling annotation task
