### ISSUE TITLE
Admin account can not login on ip:3000/auth, only on Django ip:8000/admin

### ISSUE THREAD

**Issue by spacer730** [doccano/doccano#836]
How to reproduce the behaviour
---------
I have setup doccano on a remote station through ssh with docker-compose. When I go the ip:3000/auth I can not log in with the admin account it says username and password incorrect.

However when I log in to the ip:8000/admin page I CAN login using the same credentials for the admin account.

Anybody knows why this is and how I can solve it?

Interesting Note:
if I use ssh -fN <user_name>@<remote_station> -L 3000:127.0.0.1:3000 I can login on 127.0.0.1:3000 using my local station. But still not on my location station on ip:3000

Your Environment
---------
*   Operating System: Windows
*   Python Version Used: 3.6
*   When you install doccano: 11/06/2020
*   How did you install doccano (Heroku button etc): docker-compose

**Comment by Charlyo** [comment]
Same issue for me. Browser console output shows:

`Access to XMLHttpRequest at 'http://127.0.0.1:8000/v1/auth-token' from origin 'http://10.200.213.11:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Charlyo** [comment]
Same for me. Browser console shows: 
`Access to XMLHttpRequest at 'http://127.0.0.1:8000/v1/auth-token' from origin 'http://ip:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by spacer730** [comment]
Same my browser console shows:
![Reason Why logging in workstation kpnnl local-3000 Niet werkt2](https://user-images.githubusercontent.com/32341661/84519691-be0f3a00-acd2-11ea-9a57-e4891b844515.jpg)

If it instead would go to ip:8000/v1/auth-token rather than 127.0.0.1:8000/admin I think it would work logging from ip:3000/auth

**Comment by spacer730** [comment]
Found the solution. Find all files in doccano folder that contain 127.0.0.1 with grep -R "127.0.0.1" and then replace them with "<your_ip>"

**Comment by Charlyo** [comment]
This should not be needed. Ip should be changed automatically.

**Comment by spacer730** [comment]
I agree, however as a temporary solution you can use the method I posted above

**Comment by abarbosa94** [comment]
I did what is suggested by @spacer730 and it works :)

To be more specific, the files to be changed needs to be `frontend/nuxt.config.js` and `app/app/settings.py`

I do not have so much knowledge in Django/JS so if anyone gets why this happens I'd love to know :)

**Comment by sahinbatmaz** [comment]
Same problem. It is a huge problem for me. Please help as soon as possible.

**Comment by sahinbatmaz** [comment]
At the end of `app/app/settings.py`, adding the IP:PORT is enough.
```
if DEBUG:
    CORS_ORIGIN_WHITELIST = (
        'http://127.0.0.1:3000',
        'http://0.0.0.0:3000',
        'http://localhost:3000',
        'http://IP:PORT'
    )
```

In `frontend/nuxt.config.js`, 
```
baseUrl: process.env.NODE_ENV === 'production' ? '/v1' : 'http://127.0.0.1:8000/v1'
```
should be replaced to
```
baseUrl: process.env.NODE_ENV === 'production' ? '/v1' : 'http://IP:PORT/v1'
```

However, in this situation, I am unable to use local website.

**Comment by kuraga** [comment]
Confirm this issue on **development** 4927a01f090b91d8e14e467f2fd40d8301612e72's Docker Compose.

**Comment by Hironsan** [comment]
I can reproduce the problem. We need to dynamically set `baseUrl`.

**Comment by chriswweibo** [comment]
Same issue happens to me.
Appreciate improvment for this amazing tool.

**Comment by ofersabo** [comment]
Hi, 

Running Doccano locally on my Mac, can't log into the admin account. 
When the server comes up I get this error:
postgres_1  | 2020-11-26 13:39:09.091 UTC [1] FATAL:  database files are incompatible with server
postgres_1  | 2020-11-26 13:39:09.091 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.1.

I tried cloning this repo into another folder and to fire up the server from the new directory and it still doesn't work. 

I keep getting this error: 
![Screen Shot 2020-11-26 at 15 48 22](https://user-images.githubusercontent.com/31179968/100358474-eb407200-2ffe-11eb-9bdc-cc7f750dff65.png)


Any suggestions?

**Comment by pathaine** [comment]
I see this has been closed, but I am getting the same error while using the latest version of the repo

**Comment by shanewa** [comment]
I have the same error now. Can someone check it again?
