### ISSUE TITLE
Speech2Text not showing up as projectType

### ISSUE THREAD

**Issue by harmw** [doccano/doccano#845]
How to reproduce the behaviour
---------
Just launched the thing using compose (from scratch, no previous data) but couldn't find the new speech2text project when creating a new project in the `projectType` _selectbox_.

Launch:

`docker-compose -f docker-compose.dev.yml up`

I did notice the required database migration being applied:

```
backend_1   |   Applying api.0002_speech2text... OK
```

So, where is it :)

**Comment by Hironsan** [comment]
Currently, speech2text UI is available only in doccano v0.x(Docker version). Since the backend has been already implemented, we can use it by implementing the frontend.

**Comment by harmw** [comment]
But the PR from @c-w did include UI bits, right? So what do I need to do to see those :) As I'm building containers from scratch, from a recent `git pull`.

I've been trying from `master` btw: `6b176d41e134ca59c8d415c99f4f99edcf6908d6`

**Comment by Hironsan** [comment]
You can see speech2text UI by running doccano using Docker:

- [Installation Docker](https://github.com/doccano/doccano/blob/master/docs/getting-started.md#docker)

**Comment by Hironsan** [comment]
The new UI is not implemented yet.
