### ISSUE TITLE
How to upload a document with annotation from doccano API

### ISSUE THREAD

**Issue by br-dr3** [doccano/doccano#848]
Some context:
DoccanoDocumentDTO.py
```
from pydantic import BaseModel
class DoccanoAnnotationDTO(BaseModel):
    id: Optional[int]
    prob: int = 0
    label: int
    start_offset: int
    end_offset: int
    user: Optional[int]
    document: Optional[int]

class DoccanoDocumentDTO(BaseModel):
    id: Optional[int]
    text: str
    annotations: List[DoccanoAnnotationDTO]
    meta: str = "{}"
    annotation_approver: Optional[str]
```

DoccanoClient.py
```    
def insert_new_document(
    self, document: DoccanoDocumentDTO, project_id: int
) -> DoccanoDocumentDTO:
    url = self.doccano_url + f"/projects/{project_id}/docs"  
    posted_document = self._request_url(
        "POST", url, data=document.dict(), headers=self.headers
    ).json()

    return DoccanoDocumentDTO(**posted_document)
```

When building a DoccanoDocumentDTO and sending to API, it receives and uploads document, without any annotations. 

In doccano api, when using `<localhost>:<port>/v1/projects/{project_id}/docs/{doc_id}` endpoint, is possible to see that annotations is expected to be `string`, but when returning an annotated document, it comes a list as my dto suggests.

![Captura de Tela 2020-06-19 às 19 32 22](https://user-images.githubusercontent.com/42852567/85183862-c4b62800-b263-11ea-8144-0645411d5eab.png)

**Comment by sahinbatmaz** [comment]
When you download / fetch an existing document, it has 'annotations' attribute.

I think it is not possible with endpoint `<localhost>:<port>/v1/projects/{project_id}/docs/{doc_id}`, because this only update document table in the database and does not update annotations.

In the api, there is another endpoint, `<localhost>:<port>/v1/projects/{project_id}/docs/upload` . You can upload a document with annotations with this way. You can upload more than one document with this api. However, format is a little different.

```
docs_in_json = [
    {"text": "Peter Blackburn", "labels": [ [0, 15, "PERSON"] ]},
    {"text": "President Obama", "labels": [ [10, 15, "PERSON"] ]}
]
docs_data = '\n'.join(json.dumps(d) for d in docs_in_json)

data = {'file': ('doccano.jsonl', upload_dump,),'format': 'json'}
files = {'file': ('doccano.jsonl',upload_dump,)}

session.post('<localhost>:<port>/v1/projects/{project_id}/docs/upload', data=data, file=file)


```

**Comment by br-dr3** [comment]
@sahinbatmaz thank you, this may help to not access directly doccano database in order to upload documents. But what is the point to have an endpoint that receives annotations as parameter and it is ignored? Should this endpoint do annotation upload or should it doesn't have annotation as parameter?

This endpoint doesn't update documents, only upload.. If I have some new annotations to upload, should patch/put methods do annotation update as well?

Today I can't use them too..

**Comment by sahinbatmaz** [comment]
You are right. API is not good enough. These add / delete / update operations should be done easily by the official repository. 

I think these are in the to-do list of developers and will be added in later releases.

**Comment by br-dr3** [comment]
Thank you @sahinbatmaz.

@icoxfog417 @Hironsan This may be classified as bug, I guess.

**Comment by br-dr3** [comment]
By the way sahin, Did you try to upload documents with meta data using `<localhost>:<port>/v1/projects/{project_id}/docs/upload`? I could not upload due to object convert to string.. meta data comes with double quotes escaped

**Comment by Hironsan** [comment]
OK. Clear my mind:

- [API documentation](http://127.0.0.1:8000/swagger/) is strange(annotations is not a string).
- Clarify how to upload documents(`docs` / `docs/upload`?).
- Clarify how to add / delete / update annotations.
- Make API design better.

Is this right?

**Comment by br-dr3** [comment]
I would say something more technical:

- fix docs endpoints (put, patch, post)
- add new endpoints related to annotation (put, patch, post, get)
- design and documentation minor issues

**Comment by Hironsan** [comment]
> EDIT: I saw that annotations endpoints do exist, but they are not open to see in swagger.

Yes, actually annotation endpoints exist. But it's not able to show in swagger due to `drf_yasg` and API design.

**Comment by br-dr3** [comment]
When you say 

> Yes, actually annotation endpoints exist. But it's **not able to show** in swagger due to `drf_yasg` and API design.

You want to say that is not possible to do or you think Doccano should not do and because of this it is not able to show? 

Because I could make it appears by removing this line.. I don't know exactly the reason why it is here..

https://github.com/doccano/doccano/blob/eaa23b73e55992958bd4f47f3f9197c0e0483910/app/api/views.py#L195
