### ISSUE TITLE
Error : pyodbc : src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory

### ISSUE THREAD

**Issue by sahinbatmaz** [doccano/doccano#849]
OS : Windows 10

I cloned the repo and run docker-compose command.
When I debugged the code, I had the following error in the backend container;
```
pyodbc : src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
```
It happens in 'doccano/app/tools/dev-django.sh' script when installing requirements.

Solution : 

At the beginning of  'doccano/app/tools/dev-django.sh', I added

```
##############################
apt install -y gcc make # already installed actually
apt-get install -y build-essential libssl-dev libffi-dev python3-dev
apt-get install -y unixodbc-dev
##############################
```

**Comment by icoxfog417** [comment]
Could you please provide your environment information following to [ISSUE_TEMPLATE](https://github.com/doccano/doccano/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by sahinbatmaz** [comment]
```
OS: Windows 10
```
Installation :
```
git clone https://github.com/doccano/doccano.git
cd doccano
docker-compose -f docker-compose.dev.yml up -d
```
I was not able to login.

Then I looked at logs of containers.
```
docker logs doccano_backend_1
```
Logs:
```
...
> doccano/app/tools/dev-django.sh ...
...
> installing requirements ...
...
pyodbc : src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
....
```

I searched the error.
In the following link, I found the solution. It worked.
https://github.com/mkleehammer/pyodbc/issues/276#issuecomment-369809832

**Comment by sahinbatmaz** [comment]
https://github.com/doccano/doccano/blob/master/app/tools/dev-django.sh#L17

In this line, `apt-get update && apt-get install -y g++ unixodbc-dev # pyodbc build dependencies` is already added.
However, as stated in https://github.com/mkleehammer/pyodbc/issues/276#issuecomment-369809832, there are some other prerequisites; `apt-get install -y build-essential libssl-dev libffi-dev python3-dev`.

**Comment by Hironsan** [comment]
I tried to reproduce the error. But I couldn't do it.

My environment:
- Mac OS Mojave
  - docker-compose version 1.25.5, build 8a1c60f6
  - Docker version 19.03.8, build afacb8b
- Chromium OS 10.0_pre377782_p20200113-r10 clang version 10.0.0
  - docker-compose version 1.24.0, build 0aa59064
  - Docker version 19.03.11, build 42e35e61f3
- Ubuntu 18.04.3 LTS
  - docker-compose version 1.24.1, build 4667896b
  - Docker version 19.03.3, build a872fc2f86

**Comment by sahinbatmaz** [comment]
Thanks then. I don't know the reason of the problem. I did not change the doccano github code in my local.

So, there should be a difference in [ windows 10, docker, docker-compose, docker image ]. 

I am closing the issue since it could not be repeated.

If someone somehow encounters such problem, solution is to update the code in https://github.com/doccano/doccano/blob/master/app/tools/dev-django.sh#L17 
```
echo "Installing dependencies"
apt-get update && apt-get install -y g++ unixodbc-dev # pyodbc build dependencies
```
to

```
echo "Installing dependencies"
apt-get install -y build-essential libssl-dev libffi-dev python3-dev
apt-get update && apt-get install -y g++ unixodbc-dev # pyodbc build dependencies
```

**Comment by Hironsan** [comment]
Thank you for your contribution.
