### ISSUE TITLE
Annotate button lead to the different document after pagination

### ISSUE THREAD

**Issue by br-dr3** [doccano/doccano#850]
Video
---------
![Gravação-de-Tela-2020-06-23-às-12 32 31](https://user-images.githubusercontent.com/42852567/85424362-35a05d00-b54e-11ea-81c1-e704c2ff8f96.gif)

Your Environment
---------
*   Operating System: MacOS
*   When you install doccano: June 22
*   How did you install doccano: Customized installation

Comments
---------
It looks like it have been cached the first page and when pressing, it picks the first page doc on that position

**Comment by br-dr3** [comment]
May be somehow related to #804

**Comment by Hironsan** [comment]
Thanks for the GIF. It easy to understand the problem.

**Comment by br-dr3** [comment]
I was trying to fix this bug and I guess this should be made in order to fix.

DocumentsList.vue
`goToAnnotationPage(doc) {
      const index = this.items.findIndex(item => item.id === doc.id)
      const limit = this.options.itemsPerPage
      const offset = (this.options.page - 1) * limit
      const q = this.search
      this.updateSearchOptions({ limit, offset, q })
      this.$router.push('/projects/' + this.$route.params.id + '/' + this.getLink)
      **this.setCurrent(index)** // maybe it should be **index + limit**
      const checkpoint = {}
      **checkpoint[this.$route.params.id] = index + 1**  // maybe it should be **index + limit + 1**
      localStorage.setItem('checkpoint', JSON.stringify(checkpoint))
    }
`

 but after that I stuck into 2 endpoint calls that I can't find where they are being made. This calls are setted without

**Comment by Hironsan** [comment]
I found the calls are performed from `Paginator.vue` and `BottomNavigator.vue`

https://github.com/doccano/doccano/blob/dbbf6d65b064a09381c70915b1ca9533c472a063/frontend/components/containers/annotation/Paginator.vue#L108-L110

https://github.com/doccano/doccano/blob/dbbf6d65b064a09381c70915b1ca9533c472a063/frontend/components/containers/annotation/BottomNavigator.vue#L62-L64

**Comment by kuraga** [comment]
@Hironsan , @br-dr3 , as #868 has been reverted, reopen, please.

**Comment by br-dr3** [comment]
Any fix to that should test #887 #888 scenario.

**Comment by br-dr3** [comment]
Any update on that?

**Comment by Hironsan** [comment]
I made a PR #897 .

**Comment by br-dr3** [comment]
Wonderful! Thank you @Hironsan!

**Comment by yya518** [comment]
I pull the latest repo but find that the annotate button still leads to a different document, in my existing project. Am I missing anything? thanks.
