### ISSUE TITLE
unlock the limitation of uploading file size

### ISSUE THREAD

**Issue by Olivine-Ryo** [doccano/doccano#853]
Uploading file size is limited under 1MB as uploadFileRules, however doccano works well even for large files.
I think this file size limitation should be easily changeable for users.

[frontend/rules/index.js](https://github.com/doccano/doccano/blob/master/frontend/rules/index.js)
```{
export const uploadFileRules = [
  v => !!v || 'File is required',
  v => !v || v.size < 1000000 || 'File size should be less than 1 MB!'
]
```

**Comment by icoxfog417** [comment]
same as #708
