### ISSUE TITLE
projects pages is blank

### ISSUE THREAD

**Issue by liangxg787** [doccano/doccano#854]
How to reproduce the behaviour
---------

Your Environment
---------

*   Operating System:  ubuntu
*   Python Version Used: python3.7
*   When you install doccano: 2020.6.28
*   How did you install doccano (Heroku button etc): I have install requirement.txt, and run "python manage.py runserver"

I can open the main page, but prejects page is blank. And the server error information is like this: 
`[28/Jun/2020 11:30:26] "GET /static/assets/images/logo.png HTTP/1.1" 304 0
[28/Jun/2020 11:30:26] "GET /static/assets/css/forum.css HTTP/1.1" 304 0
`
So, how can I solve this problem?

**Comment by Hironsan** [comment]
If you want to install doccano from source, please see the following page:

- [For Developers](https://github.com/doccano/doccano/blob/master/docs/getting-started.md#for-developers)

**Comment by liangxg787** [comment]
Thanks, I have solved the problem. I did not deploied the server with Docker, thus getting in the trouble. The problem was caused by the error of compatibility of nodejs and npm.

**Comment by Hironsan** [comment]
Thanks for your comment. If you have further problems, feel free to submit an issue.
