### ISSUE TITLE
[Note] Backend's pip error in log

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#858]
How to reproduce the behaviour
---------
```
backend_1   | ERROR: django-pyodbc-azure 2.1.0.0 has requirement Django<2.2,>=2.1.0, but you'll have django 2.2.10 which is incompatible.
```

Your Environment
---------

*   Operating System: Calculate Linux 20.6
*   Python Version Used: system Python version is 3.7.7
*   When you install doccano: 4927a01f090b91d8e14e467f2fd40d8301612e72
*   How did you install doccano (Heroku button etc): Docker Compose

**Comment by fjen** [comment]
Why is this a wontfix?

It seems like the django-pyodbc-azure project is [inactive](https://github.com/michiya/django-pyodbc-azure/pull/204#issuecomment-563248221) and a switch to [ESSolutions/django-mssql-backend](https://github.com/ESSolutions/django-mssql-backend) is advised.
