### ISSUE TITLE
[Proposal] Set -x and -e, -u on each Bash script

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#860]
Feature description
---------
Proposal 1: `set -x` on each Bash script to see every command which run.

Proposal 2: `set -e` and `set -u` on each Bash script to fail script if some script's command failed.

**Comment by kuraga** [comment]
@Hironsan , did you have opinion here?

**Comment by Hironsan** [comment]
Candidates:
- [run.sh](https://github.com/doccano/doccano/blob/master/tools/run.sh)
- [prod-celery.sh](https://github.com/doccano/doccano/blob/master/tools/prod-celery.sh)
- [prod-django.sh](https://github.com/doccano/doccano/blob/master/tools/prod-django.sh)

**Comment by kuraga** [comment]
@Hironsan , well,

* `-e`/`errexit` has been set already,
* `-x`/`xtrace` is needless there,
* let's set `-u`/`nounset`?

https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html

**Comment by Hironsan** [comment]
> let's set -u/nounset?

Good idea.

**Comment by kuraga** [comment]
Trying to fix in #1760 in wider manner.

**Comment by kuraga** [comment]
BTW, @Hironsan , these files are not mentioned in the repository:

* [tools/create-admin.sh](https://github.com/doccano/doccano/blob/master/tools/create-admin.sh)
* [tools/dev-celery.sh](https://github.com/doccano/doccano/blob/master/tools/dev-celery.sh)
* [tools/dev-django.sh](https://github.com/doccano/doccano/blob/master/tools/dev-django.sh)
* [tools/dev-nuxt.sh](https://github.com/doccano/doccano/blob/master/tools/dev-nuxt.sh)
* [tools/install-mssql.sh](https://github.com/doccano/doccano/blob/master/tools/install-mssql.sh)

Thanks!

**Comment by Hironsan** [comment]
They are old files. We should be able to remove them.

**Comment by green5** [comment]
/etc/bash.bashrc

[[ "$PS1" =~ " "  ]] || PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
