### ISSUE TITLE
Nonworking delete button is shown for labels of other users

### ISSUE THREAD

**Issue by fjen** [doccano/doccano#866]
In projects with shared annotations, labels from other users are shown with a delete button next to them. However normal users (not annotation approvers) cannot delete labels of other users. Trying to delete one causes a 403 error.

It would be good to hide the delete button for these labels or at least have a visual aid to distinguish between own and foreign labels.

How to reproduce the behaviour
---------
* Create project with shared annotations (text classification in my case)
* Let one user annotate the dataset
* Second user sees labels of first user with a delete button
* Clicking delete causes a 403 error

Your Environment
---------

*   When you install doccano: eaa23b73e55992958bd4f47f3f9197c0e0483910
*   How did you install doccano (Heroku button etc): docker-compose -f docker-compose.prod.yml

**Comment by Hironsan** [comment]
Solved by #916
