### ISSUE TITLE
ERROR: no matching manifest for windows/amd64 10.0.19041 in the manifest list entries

### ISSUE THREAD

**Issue by DROMZEE** [doccano/doccano#867]
I've cloned the repo on Windows 10 with 
'''bash
git clone https://github.com/doccano/doccano.git --config core.autocrlf=input
'''

I've used this command to run

```bash
(base) PS C:\WORKSPACE\doccano> docker-compose -f docker-compose.dev.yml up
```
```bash
Pulling postgres (postgres:12.0-alpine)...
ERROR: no matching manifest for windows/amd64 10.0.19041 in the manifest list entries
```
Environment
---------
*   Operating System: Windows 10.0.19041
*   Python Version Used: 3.7.7

**Comment by icoxfog417** [comment]
This error is not related to doccano. Please refer the following link.
https://stackoverflow.com/questions/48066994/docker-no-matching-manifest-for-windows-amd64-in-the-manifest-list-entries
