### ISSUE TITLE
[Proposal] - Maybe annotation should save after press button

### ISSUE THREAD

**Issue by br-dr3** [doccano/doccano#869]
Feature description
---------
I guess when annotating, automatic save is confusing. If annotator explicit press a button after annotating, it should get better.

Additionally, maybe when pressed, the document annotations become unmodifiable and press some button to become editable again.

As part of the problem, maybe "done" documents (after approved) maybe be non-editable as well.

**Comment by kuraga** [comment]
...and this button may switch to the next document.

**Comment by icoxfog417** [comment]
We consider annotation should be automatically saved not to lost user's annotations.
