### ISSUE TITLE
Allow for partial export of dataset

### ISSUE THREAD

**Issue by cgill95** [doccano/doccano#871]
Feature description
---------
When exporting a annotated dataset it always exports the entire dataset. It would be a nice addition to limit this to only the selections if there are any. If nothing is selected it could always still export the entire dataset as a default.

**Comment by Hironsan** [comment]
To implement the feature, it may be necessary that the dataset is loaded by the client-side(browser). 

Legacy code:
https://github.com/doccano/doccano/tree/master/frontend/services/parsers

**Comment by icoxfog417** [comment]
We reopen this issue if someone needs this enhancement.
