### ISSUE TITLE
Newlines and formatting in text classification task

### ISSUE THREAD

**Issue by DavideAllavena** [doccano/doccano#874]
How to reproduce the behaviour
---------

In the text classification task I would like to do some simple text formatting (bold italics underline and more important newlines) in the shown documents. Is there a way to do this (maybe using html or another markup language. )
Is It already possible, is it a feature the you'll place on the docanno road-map? Thank you!

Your Environment
---------

*   Operating System:  Ubuntu 18:04
*   Python Version Used: 3.6.10
*   When you install doccano: June 8th
*   How did you install doccano (Heroku button etc): docker-compose

**Comment by DavideAllavena** [comment]
To increase the detail level: we are trying to use it on text coming from OCR  of documents made of 3-4 pages. Newlines are very important to understand document class.

**Comment by mtournier-apixio** [comment]
@Hironsan when you create a new `DocumentClassification` project and import a dataset in json or txt with something like:
`{"text": "this is line1\n this is line2\n this is line3\n"}`

You will get the text displayed as:
`this is line1 this is line2 this is line3`

Instead of the desired output:
```
this is line1
this is line2
this is line3
```

**Comment by DavideAllavena** [comment]
The bug can be fixed adding a `white-space: pre-line;` style to the `div` containing the text

**Comment by icoxfog417** [comment]
Erasing the new line is the specification of doccano. Simultaneously we understand keeping the new line is the required feature.

=> #879
