### ISSUE TITLE
Annotations out of order when exporting

### ISSUE THREAD

**Issue by agarcha1** [doccano/doccano#875]
How to reproduce the behaviour
I imported about 7000 sentences pre-annotated by spaCy's Named Enitity Recognizer model to doccano (Sequence Labelling) to make the annotation process easier. I have corrected the first 1700 sentences annotated by the model, and was hoping to filter them out after exporting the annotations to ensure I would only use the sentences I had corrected. However, in the json file the document id's do not correspond to how I annotated them, so it is impossible to tell which documents I corrected and which were only preannotated. Is there any way I could export the sentences to preserve the order I annotated them, or filter the annotations made by one user (me rather than the admin that imported the model's pre-annotations). I would appreciate any help!

Your Environment
---------

*   Operating System: Windows 10 
*   Python Version Used: Python 3.7.7
*   When you install doccano: A few weeks ago
*   How did you install doccano (Heroku button etc): Using browser access for my organization

**Comment by icoxfog417** [comment]
doccano import the data as you listed in the file. If you want to order the data, please change the order in the file.  If you faced the phenomenon that doccano does not keep the order in the file, please let us know.
