### ISSUE TITLE
Things seem to be running fine on the backend, but then I try to run 'http://0.0.0.0:8000', it says unable to connect

### ISSUE THREAD

**Issue by AanchalA** [doccano/doccano#876]
> How to reproduce the behaviour
![Screenshot (311)](https://user-images.githubusercontent.com/28100084/87068845-cf952480-c233-11ea-9902-e6fcbebfa4ec.png)

![Screenshot (310)](https://user-images.githubusercontent.com/28100084/87068870-da4fb980-c233-11ea-9659-83b876b223ac.png)

---------

Your Environment
---------

*   Operating System: Windows10
*   Python Version Used: 3.6
*   When you install doccano: git clone https://github.com/doccano/doccano.git --config core.autocrlf=input
*   How did you install doccano (Heroku button etc): docker-compose -f docker-compose.prod.yml up

**Comment by Hironsan** [comment]
The production environment doesn't provide a port 8000. It only provides a port 80. Please try to access http://0.0.0.0/

**Comment by AanchalA** [comment]
> 
> 
> The production environment doesn't provide a port 8000. It only provides a port 80. Please try to access http://0.0.0.0/

I tried this as well. It is still saying 'Unable to Connect'

**Comment by Hironsan** [comment]
Did you use http instead of https?

I want to know whether the Nginx container is running correctly. Could you please paste the result of `docker ps -a`?

```bash
❯ docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS                NAMES
e3061d726a24        doccano_nginx          "nginx -g 'daemon of…"   3 minutes ago       Up 3 minutes               0.0.0.0:80->80/tcp   doccano_nginx_1
c9126f54f10b        doccano_backend        "/app/tools/run.sh"      3 minutes ago       Up 3 minutes                                    doccano_backend_1
b95f20655c79        postgres:12.0-alpine   "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes               5432/tcp             doccano_postgres_1
d2d2775222f1        doccano_frontend       "docker-entrypoint.s…"   3 minutes ago       Exited (0) 3 minutes ago                        doccano_frontend_1
```

**Comment by AanchalA** [comment]
@Hironsan 

I am using http

This is the output for `> docker ps -a`:
`(nlp_bert) PS F:\Data Science\NLP\doccano> docker ps -a
CONTAINER ID        IMAGE                      COMMAND                   CREATED             STATUS                        PORTS
        NAMES
51017484b3a4        doccano_nginx              "nginx -g 'daemon of…"    17 hours ago        Exited (0) 28 seconds ago
        doccano_nginx_1
6f61f4413b76        doccano_backend            "/app/tools/run.sh"       17 hours ago        Exited (137) 18 seconds ago
        6f61f4413b76_doccano_backend_1
cfe49c743f0c        doccano_frontend           "docker-entrypoint.s…"    17 hours ago        Exited (0) 12 minutes ago
        doccano_frontend_1
91ea513e92b0        postgres:12.0-alpine       "docker-entrypoint.s…"    18 hours ago        Exited (0) 18 seconds ago
        doccano_postgres_1
8f90f0740d12        paschmann/rasa-ui:latest   "/bin/sh -c 'sh -c \"…"   4 months ago        Exited (255) 8 weeks ago      0.0.0.0:5001->5001/tcp   rasa_ui
6d09d8692348        rasa/rasa:latest-full      "rasa run --enable-a…"    4 months ago        Exited (255) 8 weeks ago      0.0.0.0:5005->5005/tcp   rasa`

**Comment by Hironsan** [comment]
After running `docker-compose -f docker-compose.prod.yml up`, could you please try to access localhost:80?

**Comment by AanchalA** [comment]
> 
> 
> After running `docker-compose -f docker-compose.prod.yml up`, could you please try to access localhost:80?
> 
> [#553 (comment)](https://github.com/doccano/doccano/issues/553#issuecomment-589908921)

It's still not working. I tried all the steps in the comment you referred, but it's saying Unable to Connect.

**Comment by devame** [comment]
I had the same problem. Using localhost:80 works

![image](https://user-images.githubusercontent.com/13633767/89129685-c2aade80-d51c-11ea-9018-fdbf4c333637.png)
