### ISSUE TITLE
[Feature request] Implement label groups

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#877]
Feature description
---------
Feature request:

1. Each label has a group:
2. Labels are visually grouped by their groups on Annotation page (also see #635).
3. There is a checkbox somewhere. If it is checked document: becomes annotated only when each group has a selected a label on Annotation page. Maybe, we could use #869 design here.

**Comment by icoxfog417** [comment]
duplicate to #477. We consider the simple feature to group labels at first.

**Comment by kuraga** [comment]
Related: #461.

**Comment by kuraga** [comment]
Duplicate of #5.
