### ISSUE TITLE
Feature Request: Keep and Display the new line in the Text Classification Task

### ISSUE THREAD

**Issue by icoxfog417** [doccano/doccano#879]
Enable to keep and display the new line in the text classification task as sequence labeling task (#654).

**Comment by icoxfog417** [comment]
related to #35

**Comment by jgieringer** [comment]
I'm uploading a json, that contains newlines in the text, with the latest master branch and I'm still not seeing newlines within the texts while annotating, but seeing newlines when I hover the text on the dataset page.
