### ISSUE TITLE
[Question] About projects without annotations share

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#883]
I don't see some information in docs. If a project **doesn't** have "Share annotations" turned on, how does it work exactly?

Are the end labels (which annotations approver sees) of the document a union of all annotations, or something else?

**Comment by kuraga** [comment]
Reply by myself;

* if sharing annotation is off, everybody sees own annotations, only.
* if sharing annotation is on, everybody sees union of all annotations of the document (and can remove some of them).

Annotation approvers don't have more rights here.

**Comment by Arziva** [comment]
has it changed now?
