### ISSUE TITLE
Use local CSS/JS

### ISSUE THREAD

**Issue by howiezhao** [doccano/doccano#886]
Feature description
---------

In some environments, such as intranet, some external CSS/JS may fail to load or the loading speed is too slow, resulting in a slow website response speed. Whether to consider using local CSS/JS?

----

Other questions:

Whether this document(https://doccano.github.io/doccano/) should be placed in the README and the `Documentation` link on the homepage of the website to **let more people know**?

In addition, the images in the section about "AWS HTTPS settings" in the documentation are not accessible.

And also, the last of the three images at the bottom of the homepage is no longer accessible.

It looks like the version deployed on Heroku is not updated, it still use the old repository link.

**Comment by icoxfog417** [comment]
We don't support using doccano without internet connection now. #23

**Comment by Spring-Chang** [comment]
I had the same situation!
