### ISSUE TITLE
Wrong document list in text classification with multiple projects

### ISSUE THREAD

**Issue by lasp73** [doccano/doccano#887]
How to reproduce the behaviour
---------
If you work with two text classification projects at the same time and switch between them, the wrong document list is presented. 

![doccano-wrong-docs4](https://user-images.githubusercontent.com/24196899/87226117-1a17bd80-c368-11ea-8f83-daf79ba0f8dd.gif)

Additionally, if you try to annotate the sentence, a wrong database record is inserted.

![wrong-docs](https://user-images.githubusercontent.com/24196899/87226122-2b60ca00-c368-11ea-85fc-d20073933f63.png)

Your Environment
---------
*   Using Docker with `docker-compose -f docker-compose.dev.yml up -d`
*   Original code from doccano/master on July 10, 2020, commit 690b688ded8775d079e44dee1f421ac4c36406fa

**I will submit a pull request the a proposed solution.**

**Comment by Hironsan** [comment]
I reverted https://github.com/doccano/doccano/pull/868.
