### ISSUE TITLE
Annotators should have permission to change/add/delete tags if given in Django

### ISSUE THREAD

**Issue by br-dr3** [doccano/doccano#895]
Feature description
---------
Approvers already have it, but annotators sometimes are asked to tag a pre-tagged (not reliable) document and propose a right tagged document.

This could be a Project constraint like "Can annotators remove other annotator tags?".

I guess annotators are same level, so they can edit other annotation and vice-versa. What they can't do is edit already approved docs.

**Comment by icoxfog417** [comment]
duplicate of #531
