### ISSUE TITLE
Why Does Doccano Deployed to Heroku Using Button Look Different From Git Clone?

### ISSUE THREAD

**Issue by pjchungmd** [doccano/doccano#906]
I deployed Doccano to Heroku using the button and the version I have looks exactly the same as what is found on https://doccano.herokuapp.com/. However when clone from git and run using Docker and Docker Compose, it looks totally different. Therefore what is the version of Doccano that is deployed to Heroku, and where can I find the code base?

**Comment by Hironsan** [comment]
> what is the version of Doccano that is deployed to Heroku
- v0.x

> where can I find the code base?
- [doccano/app/](https://github.com/doccano/doccano/tree/master/app)
