### ISSUE TITLE
[Bug report] Incorrect error about wrong login+password pair

### ISSUE THREAD

**Issue by kuraga** [doccano/doccano#910]
How to reproduce the behaviour
---------

1, Go to "Sign in" page.
2. Type a **correct** login+password pair.
3. Turn off your internet cable.
4. Press "Login" button.

You get:
![image](https://user-images.githubusercontent.com/1063219/87907999-5e911080-ca6e-11ea-9ebe-7b1658c5758a.png)

But the pair was **correct**!

Your Environment
---------

*   Operating System: Ubuntu 18.04.4 LTS
*   Python Version Used: system Python is 3.6.9
*   When you install doccano: 4b5a3c34310f9c7e9d27163928073e74cc7bb226
*   How did you install doccano (Heroku button etc): Docker Compose (production)

**Comment by icoxfog417** [comment]
We don't support offline usage. For that reason please don't turn off your internet cable.

https://github.com/doccano/doccano/issues/23
