### ISSUE TITLE
General question about shared hosting

### ISSUE THREAD

**Issue by pablodegrande** [doccano/doccano#914]
Hi,

I'd like to know if it is possible for my lab to deploy doccano in a hosting account, such as those provided by a2hostings. This account offer postgress, python, and ssh access.

Thanks a lot, Pablo.

**Comment by Hironsan** [comment]
I have no idea about A2 Hosting. But according to [the documentation](https://www.a2hosting.com/kb/developer-corner/application-deployment/installing-docker), it supports Docker. So you can deploy doccano.

**Comment by pablodegrande** [comment]
Sorry, I was trying to ask for shared hosting accounts (your link points to dedicated server accounts). I.e. do you app need a dedicated server, or can it be hosted in an apache virtual folder?

**Comment by Hironsan** [comment]
According to your information(This account offer postgress, python, and ssh access), you can deploy doccano because it uses Python, Postgres, Nginx, and Node.js. However, you have to set it up yourself.
