### ISSUE TITLE
Deploy to heroku fails because there are unapplied migrations

### ISSUE THREAD

**Issue by diwu1989** [doccano/doccano#917]
This is using the deploy to heroku button.
![image](https://user-images.githubusercontent.com/380950/88093515-f5310080-cb46-11ea-9c5e-00cca06ff580.png)

**Comment by diwu1989** [comment]
`heroku.sh` probably needs to run these:
```
python app/manage.py wait_for_db
python app/manage.py migrate
python app/manage.py create_roles
```
Very similar to `run.sh`

**Comment by icoxfog417** [comment]
Thank you for reporting the issue. We are dealing with this problem at #917.
