### ISSUE TITLE
Create a project button is visible despite of the user has no authority

### ISSUE THREAD

**Issue by pjchungmd** [doccano/doccano#920]
How to reproduce the behaviour
---------
Non-superuser (e.g. annotator) can see the "Create" project button when logged in.

![Screenshot from 2020-07-22 07-19-47](https://user-images.githubusercontent.com/64808267/88171080-ba81a380-cbec-11ea-9bff-24dcefa3ca84.png)

Clicking on the "Create" button brings up the appropriate modal:

![Screenshot from 2020-07-22 07-20-09](https://user-images.githubusercontent.com/64808267/88171112-ca998300-cbec-11ea-9c09-60717ef53192.png)

However submitting the form leads to:

![Screenshot from 2020-07-22 07-20-15](https://user-images.githubusercontent.com/64808267/88171132-d1c09100-cbec-11ea-82bc-d350e6ef45d1.png)

Expected behavior would be not to show the "Create" button in the first place for users without the privileges (as in 0.x version).

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.6.11
*   When you install doccano: 7/22/2020
*   How did you install doccano (Heroku button etc): git clone

**Comment by kuraga** [comment]
Related: #601 is a superset of this but has been closed.

**Comment by kuraga** [comment]
Related: #601.

**Comment by kuraga** [comment]
Let's merge to #922?
