### ISSUE TITLE
Django Stand-alone and AWS Deploy are different apps than prod

### ISSUE THREAD

**Issue by quinnpertuit1** [doccano/doccano#925]
How to reproduce the behaviour
---------
1) Starting the app by installing python and npm dependencies then:
cd app
python3 manage.py runserver

- this looks like an old version of doccano as a stand-alone Django app?

2) Starting the app by: 
aws deploy yml

- this looks like an old version of doccano 

3) Starting the app by heroku.yml

- is this the old app or the new app? Doesn't look like the wiki screenshots

What is going on here? It's like there's 5 ways to deploy this app and at least two are the wrong / old version.

**Comment by Hironsan** [comment]
1, 2, 3 -> Yes.

They are the old version. The new version is only available for `docker-compose.prod.yml`.
I have a plan to update AWS and GCP version to the new version.
- https://github.com/doccano/doccano/projects/17

**Comment by quinnpertuit1** [comment]
Hi Hiroki - what's the latest on this? Are the django, heroku, and aws deployments still the old version of the app?

**Comment by kuraga** [comment]
Related: #810
