### ISSUE TITLE
Show annotation status on the document list page

### ISSUE THREAD

**Issue by br-dr3** [doccano/doccano#928]
Feature description
---------
It would be awesome to have some info presented (like tagged and approved) in dataset view
![image](https://user-images.githubusercontent.com/42852567/88315187-5ba35380-ccec-11ea-96d4-f2b57cd503c4.png)

**Comment by Hironsan** [comment]
Design Idea:
![image](https://user-images.githubusercontent.com/6737785/88497958-cad6bb80-cffc-11ea-8519-6749adb34cb2.png)

**Comment by br-dr3** [comment]
Awesome @Hironsan! It looks perfect. Maybe you can put it inside document on doccano too, it would be great.

Just one question: How you gonna differentiate a `finished` from a `In progress`... Do you plan to put a `finish` button when tagging?

**Comment by Hironsan** [comment]
> Do you plan to put a finish button when tagging?

Yes. I think It's necessary to distinguish between `finished` and `in progress`. Especially for a sequence labeling task.

**Comment by br-dr3** [comment]
Maybe #869 should be re-open too?

**Comment by Hironsan** [comment]
Maybe a little different. I think annotations should be automatically saved.

Maybe `finished` is a little confusing word. I think it has two meanings: one is an annotator finished labeling a document and the other is an approver approved the document. It's necessary to design models carefully.

**Comment by leehanchung** [comment]
That looks awesome.

I do think there has to be a `submit` or `finished` button at the tagging page as not every piece of text will be tagged for sequence labeling task.

**Comment by lizfischer** [comment]
Any plans to implement this? Would be a major improvement for my workflow!
