### ISSUE TITLE
Duplicate Documents seen after setting "Randomize Document Order Per User"

### ISSUE THREAD

**Issue by aayushdua007** [doccano/doccano#933]
Hi,
While setting up a new project, I chose the option "Randomize Document Order Per User". Now when I import the dataset and every user started annotating, we are all seeing duplicate documents in the rows. This did not happen when we didnt select this setting. Even though duplicates are present the number of documents displayed on the page are same as the original no of documents(without duplicates). That means we are losing on some documents that are being replaced with these duplicate documents. 

Just to confirm we have checked and there are no duplicates in the file. So that means the issue is coming from Doccano and only when we are chosing the above mentioned setting.

We are currently using Doccano through deployment on Azure.

Any help is appreciated.
Thanks!

**Comment by kaushikepi** [comment]
Yes even I found this issue
