### ISSUE TITLE
/server/ app inside Django

### ISSUE THREAD

**Issue by leehanchung** [doccano/doccano#934]
Just curious, is the app/server/ app inside Django still in use at the current version? It appears to be legacy code that's now moved/implemented in frontend/ using nuxt.js.

Are there any plans to clean up the legacy code base?

**Comment by Hironsan** [comment]
The current version(v1.x) is not using `app/server`. It's for the previous version(v0.x).

There are no plans to clean up it for now. However, I would like to do it in the future.
