### ISSUE TITLE
Export to CONLL format

### ISSUE THREAD

**Issue by andrewlaikh** [doccano/doccano#936]
Is there a way to export NER annotations to CONLL format? 

I had a look at [doccano assistant](https://github.com/Andolab/doccano_assistant)  but do not understand how to obtain the 'dir_path_having_tokenized_sentences'. Is the feature available natively in doccano?

**Comment by Hironsan** [comment]
For now, I want you to use [doccano-transformer](https://github.com/doccano/doccano-transformer). It supports format transformation.
