### ISSUE TITLE
doccano image on Docker hub vs docanno version 1.0.4

### ISSUE THREAD

**Issue by leehanchung** [doccano/doccano#939]
Hi,

Just want to have a sanity check. I pulled doccano:doccano from Docker hub. It seems like the image uses the Django frontend and backend.

And here on Github, using docker-compose, the  version uses nuxt frontend w/ django backend and different UI/landing page.

Correct?

**Comment by Hironsan** [comment]
Yes. The docker version is the older version. I recommend you should use the docker-compose version.
