### ISSUE TITLE
[bug report] `annotation_approver` cannot see annotator's tags for sequence labeling

### ISSUE THREAD

**Issue by leehanchung** [doccano/doccano#946]
How to reproduce the behaviour
---------
Sign in as admin to `localhost/admin` Django backend
Create `user1`, `reviewer1`
Sign out.
Sign in as admin to `localhost` frontend
Add dataset
Add label
Add user1 as annotator
Add reviewer1 as `annotation_approver`
Sign out as admin
Sign in as user1
Annotate
Sign out
Sign in as reviewer1
Click on annotate
-> cannot see any annotations left by other users. toggle approve button on/off and still sees nothing.

Your Environment
---------

*   Operating System: Windows 10, Build 200725
*   Python Version Used:  python3 version defined in `app/Dockerfile`
*   When you install doccano:  fresh pull from 1.0.5 master branch
*   How did you install doccano (Heroku button etc):  `docker-compose -f docker-compose.prod.yml up --build`

**Comment by br-dr3** [comment]
Did you checked `share annotation across all users` when creating project?

![image](https://user-images.githubusercontent.com/42852567/89333390-4541b400-d66b-11ea-812b-539c735fa71c.png)

**Comment by icoxfog417** [comment]
Please check "share annotations" (Thank you for the correspondence of @br-dr3 !).
