### ISSUE TITLE
Chunk dataset between annotators

### ISSUE THREAD

**Issue by Colanim** [doccano/doccano#947]
**How can I chunk the dataset between annotators ?**

---

I have several annotators, but I want only 1 annotation per sample. Also I don't want annotators to modify another annotator's work.

---

If I check `share annotations`, people can view, edit, delete annotations. I don't mind they can view, but they can edit and delete annotations, which is a problem.

If I uncheck `share annotations`, people cannot view/edit/delete other's annotations, but they can annotate a sample that was already annotated.

---

Is there any way to chunk the dataset between annotators ? **Or show annotator only sample that were not annotated ?**

**Comment by Colanim** [comment]
As a temporary work-around, I added my own permission :

```python
class IsOwnAnnotationCanModify(ProjectMixin, BasePermission):

    def has_permission(self, request, view):
        if request.user.is_superuser:
            return True

        if request.method == 'GET':
            return True

        project_id = self.get_project_id(request, view)
        annotation_id = view.kwargs.get('annotation_id')
        project = get_object_or_404(Project, pk=project_id)
        model = project.get_annotation_class()
        annotation = model.objects.filter(id=annotation_id, user=request.user)

        return annotation.exists()
```

and modified this line : 

https://github.com/doccano/doccano/blob/4e25f169462a2d0413679beeb58c95b532616d14/app/api/views.py#L242-L243

to :

```python
self.permission_classes = [IsAuthenticated & IsInProjectOrAdmin & IsOwnAnnotationCanModify]
```

---

With this modification, when the project is set to `collaborative`, annotators can view other annotators' annotations, but they cannot modify it or delete it.

I wanted to make it impossible to annotate if there is an annotation from another annotator as well, but I couldn't find how to do this...

_Since this is only a work-around, I'm not closing the issue_

**Comment by icoxfog417** [comment]
Please uncheck share annotations if you want to forbid annotators to view/edit other annotator's annotations. If annotators can view/edit despite unchecking, please raise a new issue.

**Comment by kuraga** [comment]
Related: #831. See also: #114.
