### ISSUE TITLE
Assign different documents in one project to different users.

### ISSUE THREAD

**Issue by ShomyLiu** [doccano/doccano#948]
First thanks for your nice work.   I'm fresh to Doccano, and have a question about collaborative annotations.
Suppose there is a project, and I would like to know how to import and then assign different documents in one project to different users.
I have tried multiple documents in one project and find that the will be mixed together for all users.

**Comment by Hironsan** [comment]
Did you try `randomized document order` option? It may be helpful for users to assign different documents.

**Comment by ShomyLiu** [comment]
Hi, thanks for your reply.  I have tried `randomized document order`  and all the documents would also be mixed together.
I have to create different projects for different document and then assign to different users.

**Comment by Hironsan** [comment]
OK. I understood your request.

Current:
- User1: doc1, doc2, doc3
- User2: doc2, doc3, doc1
- User3: doc3, doc1, doc2

Your Request:
- User1: doc1
- User2: doc2
- User3: doc3

Right?

**Comment by ShomyLiu** [comment]
Hi,  my request is that different users can annotate different docs in **one project**.

- Project1:
    - user1: doc1, doc2, doc3
    - user2: doc4, doc5 .....
    - user3 .....

However, I have to do that in the following way:
- Project1: user1: doc1 + doc2 + doc3
- Project2: user2: doc4 + doc5.

In all,  is there any way to assign tasks in document-grained?

**Comment by liuhantang** [comment]
This is also the feature that I want.
As of my exploration from the doccano interface, currently you can only do this by manually creating different projects for each user. It would be great if doccano could auto dispatch tasks to each user in the same project.

**Comment by kuraga** [comment]
Related: #830.
