### ISSUE TITLE
WIP : Annotation of audios for Speech-to-Text parallel data set building 

### ISSUE THREAD

**Issue by tayciryahmed** [doccano/doccano#95]
### Describe the problem
Given the relative scarcity of tools for building a speech-to-text dataset (most standard tools are desktop-based now), it would be great if doccano could serve that purpose. At its core, I believe that would mean each audio is an input base64 string (displayed in the interface as an audio html5), then there would a form below (like in a Translation project) that allow you to enter annotations. 

The main functionality that would be tricky would likely be displaying the audios in the interface (easy using html5) and importing the audio data to doccano (we can represent audio files in Base64 encoding and load them as csv or json).

Does this sound doable?

**Comment by tayciryahmed** [comment]
If you think that is aligned with your vision of the project, I can work on it and submit an MR.

**Comment by Hironsan** [comment]
As I showed in [feature ideas](https://github.com/chakki-works/doccano/projects/2#card-16405643), I think it is important for users to increase the number of tasks they can annotate.

So, if you can work on the audio annotation feature and submit a PR, we are very happy!

**Comment by BrambleXu** [comment]
@tayciryahmed The model has changed a lot #110. If you are working on the audio annotation feature, please update to the latest version of doccano.
