### ISSUE TITLE
Does it support horizontal scaling (Multiple Heroku Dynos)

### ISSUE THREAD

**Issue by jcsoriano** [doccano/doccano#950]
Your Environment
---------

*   When you install doccano: August 12, 2020
*   How did you install doccano (Heroku button etc): Heroku button

Hi, thank you for the awesome app! I am trying it out if it can be used in our project. Does it support horizontal scaling (scaling to multiple Heroku Dynos)?

**Comment by icoxfog417** [comment]
We can't answer your question because we don't know the detail about the Heroku Dynos. 
We are very glad if you share the knowledge after your experience.
