### ISSUE TITLE
doccano start problem

### ISSUE THREAD

**Issue by huanshi2** [doccano/doccano#951]
when I start doccano in the Edge , it takes me for more than 10 seconds to come into the login interface , is there a solution to solve it?

I used docker to deploy it .

- win 10 2004
- docker desktop 2.2.0.0
- Microsoft Edge  84.0.522.52

**Comment by icoxfog417** [comment]
Thank you for using the doccano. Could you please show the log and your computer spec to solve the issue?

**Comment by icoxfog417** [comment]
I close this issue because of no response.
