### ISSUE TITLE
AWS deployment error: The image id '[ami-0873b46c45c11058d]' does not exist

### ISSUE THREAD

**Issue by diavy** [doccano/doccano#957]
I tried to use One-Click deployment for AWS. But I always came across the several erros: 

> 

The image id '[ami-0873b46c45c11058d]' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidAMIID.NotFound; Request ID: 4e79822a-f4d5-46b8-9132-bec99c3f25f8; Proxy: null)

> 

I also tried different regions: us-east-1, us-east-2, us-west-1, us-west-2 But none is working. I suspect the aws template contains incorrect ami ID.

**Comment by Juanvulcano** [comment]
It worked for me on us-west-2
