### ISSUE TITLE
Can I edit the text when annotating?

### ISSUE THREAD

**Issue by HelloDylan** [doccano/doccano#959]
Can I edit the text when annotating?

**Comment by mikemccawley** [comment]
That is never a good practice and the tool shouldn't allow it.  The subject
text should be extracted from real world and should be authentic and
representative of your intended production use case.  By all means, prep
the text in small ways (strip html, emojiis, tabs, etc) BEFORE the
annotating session begins. Not during.

**Comment by icoxfog417** [comment]
As @mikemccawley said, we don't support this feature now.
