### ISSUE TITLE
Keep label id when importing the dataset to enable re-labeling

### ISSUE THREAD

**Issue by mgrabmair-sinc** [doccano/doccano#961]
I have a sequence labeling project (training data) where I define a label set which I export and then re-import to another project (test data). It appears that, during the type system import, the types get reassigned new IDs. Once annotation is done the two exported datasets have the same type system, but different type IDs, and hence have to be joined over the label text string. In other words, the effective use of exported label sets is impaired, as it needs to be re-exported after import to allow for proper postprocessing.

I recommend that type IDs should become UUIDs that do not cause ID conflicts at import time and allow easier label set maintenance across projects.

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: default as per docker config
*   When you install doccano:
Early July 2020, update to latest release on July 23
*   How did you install doccano:
Local `docker-compose` deployment

**Comment by kuraga** [comment]
Related: #826.

**Comment by icoxfog417** [comment]
Merge to #482
