### ISSUE TITLE
Feature: flag button for erroneous examples

### ISSUE THREAD

**Issue by Collinbrown95** [doccano/doccano#966]
Feature description
---------
When an annotator encounters an erroneous example (e.g. null data, incorrect data, etc.), they should have the ability to indicate that something is wrong with the document.

I propose some kind of "flag" button on the annotation screen that the annotator can click if they encounter an incorrect example. Once clicked, this would update a new field for that document (e.g. "flagged"), and the change should persist in the back-end.

Perhaps there should also be a complimentary feature to this where, for example, admins or project managers can review flagged documents.

Thoughts?

**Comment by kuraga** [comment]
Or even more: an ability to lleft a comment on a document.

**Comment by MSLars** [comment]
I would add that it would be nice to have the ability to exclude such potentially erroneous documents from the exported dataset.

**Comment by icoxfog417** [comment]
Merge to #1050
