### ISSUE TITLE
Deploying Doccano in Production with a base URI

### ISSUE THREAD

**Issue by rolzy** [doccano/doccano#967]
Related Issues:
https://github.com/doccano/doccano/issues/380
https://github.com/doccano/doccano/issues/775

Hi, 

I am trying to deploy docker-compose.prod such that the frontend server has a new base URI. I have a reverse proxy setup with nginx such that access to XYZ.com/doccano/ gets redirected to localhost:[port for doccano]. 

A simple proxy_pass does not work because the relative URLs for nuxt.js files and image files remains to be set at the root URL. In development, I was able to fix this by setting the [router base property](https://nuxtjs.org/api/configuration-router/#base):
```
  2 export default {
  3   mode: 'spa',
  4   /*
  5   ** Headers of the page
  6   */
  7   router: {
  8     base: '/doccano/'
  9   }
```
```
sysadmin@XXX:~$ docker-compose -f docker-compose.dev.yml up
.
.
.
frontend_1  | ℹ Listening on: http://172.21.0.3:3000/doccano/
```
However, it seems that this setting does not work for the production environment. Any help regarding base URI setup and difference between deployment in development and production are greatly appreciated :)

Your Environment
---------

*   Operating System: Ubuntu 18.04
*   Python Version Used: 3.6
*   When you install doccano: August 24
*   How did you install doccano (Heroku button etc): git clone

**Comment by MKatereggaExigent** [comment]
Just change `8000:8000` or `3000:3000` in your `prod` or `dev` yml files to: `<your ipaddress>:8000:8000` or `<your ipaddress:3000:3000>`

**Comment by rolzy** [comment]
Thank you!

**Comment by kaushikepi** [comment]
@rolzy did it work?
