### ISSUE TITLE
Provide docker-compose.prod image to avoid build

### ISSUE THREAD

**Issue by waterponey** [doccano/doccano#971]
Feature description
---------
Would you be interested to make the docker-compose.prod.yml avoid any build on the deployment side ? 

This is to avoid having to deal with all the routing issues in secure environment (it's difficult to ask security IT teams to open access to *.debian.org or *.alpinelinux and *.npmjs but it's easyier to ask only for dockerhub with some tracability condition)

For instance we could modify the travis-ci job to make it push two docker images to dockerhub (one for the backend, and one for the frontend) build based on the source code on master ?

I can make a PR for that if you're interested.

**Comment by PATELS2R** [comment]
I am facing the same issue. Just not able to use it behind corporate proxy. #983 
Do you have any ideas or temporary workaround.

**Comment by kuraga** [comment]
:+1:

**Comment by PATELS2R** [comment]
@waterponey Do you have any temporary workaround to self-build and upload the `docker-compose.prod` image to Docker Hub??

**Comment by waterponey** [comment]
Hi, not right now but I plan to work on that at some point...

**Comment by kuraga** [comment]
Related: #783.
