### ISSUE TITLE
AWS CloudFormation Public DNS Not Working

### ISSUE THREAD

**Issue by katreparitosh** [doccano/doccano#975]
Hello, I used the One-Click Deployment method to deploy Doccano over the AWS EC2 instance. 

The stack creation in CloudFormation was successful. However, when I tried to access the app using the Public DNS of the EC2 instance, the webpage prompts "Site Not Reachable". 

I also used the port number(80) specified by Doccano, but it wouldn't work. 

Similar to #300 

Am I missing something? I would be grateful for any help provided.

**Comment by Juanvulcano** [comment]
What region are you using? I think the AMI only works on us-west-2 or something like that

**Comment by katreparitosh** [comment]
Thanks. 

I tried using the us-west-2 region, but now I am getting similar errors #957 and #190 which says AMI-ID does not exist. 

What could be the possible reason?

**Comment by zacharyblank** [comment]
I'm facing this same issue.

**Comment by Hironsan** [comment]
The problem `The image id does not exist` is solved in #978 .

If you cannot access the app, please wait for about 15 minutes after launching the stack because `docker-compose` is being executed in the instance.
