### ISSUE TITLE
Can't sign up on Doccano page?

### ISSUE THREAD

**Issue by stevesolun** [doccano/doccano#982]
I am going to doccano official page and can't sign up.
What I want to do is to annotate around 1000 lines of structured strings (NER) using predefined entities and export it to train SpaCy NER model.

Please advise how to do it.

**Comment by PATELS2R** [comment]
If by official page you mean [this](http://doccano.herokuapp.com/), its just a demo. There is no service available directly.
You need to setup doccano locally or on cloud using the installation instructions.

**Comment by Hironsan** [comment]
FYI:
- [I want to add annotators/annotation approvers](https://github.com/doccano/doccano/blob/master/docs/faq.md#i-want-to-add-annotators-annotatorsannotation-approvers)
