### ISSUE TITLE
How do I shift to the new user interface?

### ISSUE THREAD

**Issue by PATELS2R** [doccano/doccano#984]
I setup doccano with 
```
docker container create --name doccano \
 -e "ADMIN_USERNAME=admin" \
 -e "ADMIN_EMAIL=admin@example.com" \
 -e "ADMIN_PASSWORD=password" \
 -p 8000:8000 doccano/doccano

docker container start doccano
```

I noticed that the UI is quite different than the one we get while using `docker-compose -f docker-compose.dev.yml up`. The later one seems more modern with the ability to import labels configuration file.

How do I get the new UI with `docker container start` approach??

**Comment by Hironsan** [comment]
The docker version has not yet supported the new UI. If you want to use the new one, you need to use the docker-compose version.
