### ISSUE TITLE
Docker Compose error

### ISSUE THREAD

**Issue by RohanSaxena14** [doccano/doccano#985]
ERROR: Version in "./docker-compose.dev.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by Hironsan** [comment]
Please update your docker-compose version.

FYI:
- [how to fix "ERROR: Version in "./docker-compose.yml" is unsupported"](https://github.com/bigbluebutton/greenlight/issues/228)
