### ISSUE TITLE
New user not receiving email after signup ( deployed it on HEROKU)

### ISSUE THREAD

**Issue by yogesh1612** [doccano/doccano#988]
I deployed app on Heroku using one click deployment

**Comment by nbroad1881** [comment]
It probably has to do with the email settings not being set up correctly. 

[see here](https://github.com/doccano/doccano/blob/8b7dedca3991e0b253d949bc82409300380aa959/app/app/settings.py#L331)

**Comment by icoxfog417** [comment]
Heroku deploy is old version. So there is no feature to send email.
