### ISSUE TITLE
Azure AD Nuxt.js

### ISSUE THREAD

**Issue by joshurbain** [doccano/doccano#989]
Hello,

Is there a method to get the Nuxt.js version of Doccano (docker-compose.prod.yml) to work with the Social Auth logins? It looks like they only work with the old version of the software (docker-compose.yml), but I can't confirm.

How to reproduce the problem
---------
Build container using docker-compose.prod.yml with OAUTH_AAD_KEY, OAUTH_AAD_SECRET, and OAUTH_AAD_TENANT environment values filled in under the backend area in the docker-compose file.

Your Environment
---------
*   Operating System: MacOS
*   Python Version Used: 3.8 on host machine
*   When you install doccano: ?
*   How did you install doccano (Heroku button etc): docker-compose.prod.yml

**Comment by icoxfog417** [comment]
We try to implements OAuth at #676 . If you want this feature, please upvote PR.

**Comment by joshurbain** [comment]
> We try to implements OAuth at #676 . If you want this feature, please upvote PR.

That PR looks to implement Google's OAuth functionality, where I'm looking to implement Azure AD OAuth over Nuxt.js. Is that still supported? There is not a user-facing method to start the Active Directory login, like it was in the prior design.

**Comment by icoxfog417** [comment]
All of the OAuth that we support is summarized here. Would this be helpful for you?

https://github.com/doccano/doccano/blob/master/docs/advanced/oauth2_settings.md

**Comment by joshurbain** [comment]
> All of the OAuth that we support is summarized here. Would this be helpful for you?
> 
> https://github.com/doccano/doccano/blob/master/docs/advanced/oauth2_settings.md

I can get the Azure ActiveDirectory authentication working in the non-Nuxt.js interface, but not the latest UI (`docker-compose.prod.yml` with the proper environment variables set). Is there any documentation or guidance on getting OAuth/Azure ActiveDirectory authentication functioning in Nuxt.js?

**Comment by icoxfog417** [comment]
We don't have Azure environment to confirm it.
We are very glad if you share the knowledge after your experience.
