### ISSUE TITLE
Is there SSO support for Doccano to be used on systems like OKTA?

### ISSUE THREAD

**Issue by GullyBurns** [doccano/doccano#990]
Feature description
---------
Trying to use doccano in an enterprise setting but all systems must implement OKTA SSO security. Would it be possible to set up SSO or SAML support for doccano for use in a more robust / secure environment?

for example: https://github.com/zeekhoo-okta/okta-django-samples

Thanks! Great tool!

Gully

**Comment by icoxfog417** [comment]
Thank you for your interest for doccano. We already add OKTA support at #675.
