### ISSUE TITLE
labels disapearing in new UI ?

### ISSUE THREAD

**Issue by waterponey** [doccano/doccano#991]
How to reproduce the behaviour
---------

First of all thanks for all of your hard work ! 

I installed doccano using two methods :
 - the simple docker create / docker run 
 - the docker-compose using docker-compose.prod.yml

I'm interested in doing NER so I need to annotate my texts using a lot of labels.

As far as I understand, the docker-compose version is newer than the simple docker one (I haven't had time to look into that yet, could you tell me what triggers an update on the doccano/doccano image on docker hub ?)

The issue I have is that in the docker-compose version I need to select a sentence to see a list of all the annotation since they are not visible onscreen otherwise. But I absolutely need to have a list of annotation visible somewhere on screen for the annotator. Is it a new feature to have a "simpler" design that removes the list of annotation ? Is there a way to add an option to make it visible again ?

Also on the right of the screen there is a "key value" table and I'm not sure what's supposed to be printed here.

Your Environment
---------

*   Operating System: Linux (Centos 7)
*   Python Version Used: 3
*   When you install doccano: docker and docker-compose

**Comment by kuraga** [comment]
Related: #635 (merged in _non-equivalent_ #834), #627.

**Comment by icoxfog417** [comment]
Duplicate to #635
