### ISSUE TITLE
AWS CloudFormation Stack launched - Issues with 404 & ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by marmuel** [doccano/doccano#993]
### System information
- **OS Platform and Distribution**: AWS Amazon Linux t2.small
- **Python version**: 3.7

### Describe the problem

I've used your Stack to launch it via AWS CloudFormation. It was installed in the root of a newly created EC2. 
After that, I've changed the port in the docker-compose.dev.yml to 8002:8000 and in ...prod.yml to 80:80. 

I also changed the Inbound-Rules in the security group for my EC2. I can open the DEV with 8002 and also the PROD. 

But there is a problem with the URLs. For instance, if I open a demo, I get a 
**GET @http://127.0.0.1:8080/demo_text_classification.js net::ERR_CONNECTION_REFUSED** for the related JS-File. If I open the DEV with the Port 3000, everything works fine. Thank you for your hints!

**Comment by icoxfog417** [comment]
We can't figure out all of your AWS settings. If you confirm that the trouble depends on doccano but not AWS network setting, please raise a new issue.
