### ISSUE TITLE
Service Frontend failed to build non-zero code:128

### ISSUE THREAD

**Issue by copamundiale** [doccano/doccano#998]
How to reproduce the problem
---------
I tried to install doccano according to the provided installation guide:
$ git clone https://github.com/doccano/doccano.git
$ cd doccano
$ docker-compose -f docker-compose.prod.yml up

```bash
warning Pattern ["squire-rte@github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-squire-rte-1.9.0/node_modules/squire-rte" as pattern ["squire-rte@github:seonim-ryu/Squire#10a470c9dfd07cfb37b06dedc581526b061975e1"]. This could result in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/adobe-webplatform/eve.git
Directory: /app
Output:
fatal: the remote end hung up upon initial contact
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
Service 'frontend' failed to build : The command '/bin/sh -c apk add -U --no-cache git python3 make g++   && yarn install   && yarn build   && apk del --no-cache git make g++' returned a non-zero code: 128

```

Your Environment
---------

*   Operating System: Windows 10
*   Python Version Used: Python 3.7
*   When you install doccano: error during installation
*   How did you install doccano (Heroku button etc): clone git

**Comment by Hironsan** [comment]
Related issues:

- https://github.com/doccano/doccano/issues/796
- https://github.com/doccano/doccano/issues/500

The following may be helpful for you:

- https://github.com/doccano/doccano/pull/657/files

**Comment by copamundiale** [comment]
Thank you for you reply!
I read both issues and changed the dockerfile. Now I receive the following error:

Service 'frontend' failed to build : The command '/bin/sh -c git config --global url.https://github.com/' returned a non-zero code: 127

**Comment by lyl2854** [comment]
@copamundiale Same problem.

**Comment by Hironsan** [comment]
@copamundiale 
OK. Now you encountered status 127. Could you please try the following command?

```bash
$ git clone https://github.com/doccano/doccano.git --config core.autocrlf=input
$ cd doccano
$ Rewrite Dockerfile. See https://github.com/doccano/doccano/pull/657/files
$ docker-compose -f docker-compose.prod.yml up
```

Windows users need `--config core.autocrlf=input` option:

- [Getting started](https://github.com/doccano/doccano/blob/ec889bf43a4c83be455876d57b5ddeedd0bd6a07/docs/getting-started.md)

**Comment by copamundiale** [comment]
Thanks for the reply! I reinstalled doccano with --config core.autocrlf=input and changed the dockerfile. Yet I get the same error message non-zero code: 127
